### ISSUE TITLE
Build an alertmanager like Prometheus's

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#100]
- [x] Rules
- [ ] HA
- [x] Integrate with notification system like Slack and PagerDuty

**Comment by pranay01** [comment]
Alert rules is shipped with notification to Slack in [v0.5.0](https://github.com/SigNoz/signoz/releases/tag/v0.5.0)

Tracking Integration with PagerDuty in https://github.com/SigNoz/signoz/issues/463
Enabling HA setup for Alertmanager in https://github.com/SigNoz/signoz/issues/464
