### ISSUE TITLE
Bug: Time duration resets during naviation

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#1002]
https://user-images.githubusercontent.com/26831659/164205879-85004faa-03da-4f29-9072-61cade5d3c29.mov

Whenever we change the duration and then navigate, the duration value gets reset.

**Comment by nityanandagohain** [comment]
@pranay01  @ankit01-oss  please let us know if this is an expected behaviour, but ideally I think the range should be propagated from parent -> child

**Comment by nityanandagohain** [comment]
Bumping this, if we should solve this or not.

**Comment by YounixM** [comment]
@nityanandagohain: this is an expected behaviour. Every application has it's own time range set. 

Closing this. We can reopen if we want to have a same time range for all service based on user selection.
