### ISSUE TITLE
Plot K8S Infra metrics docs

### ISSUE THREAD

**Issue by thunko** [SigNoz/signoz#1010]
## Bug description

Hi, I'm trying to plot K8S Infra metrics to Signoz as indicated here:
https://signoz.io/docs/tutorial/kubernetes-infra-metrics/
but it takes me here:
https://signoz.io/docs/userguide/metrics-dashboard/
where it shows 'Not Found'

![image](https://user-images.githubusercontent.com/25479180/164650232-0b2d4fb3-4a3f-4a44-be18-522586780eee.png)

## Expected behavior

See instructions page

## How to reproduce

1. Visit link on step 3: https://signoz.io/docs/tutorial/kubernetes-infra-metrics/
2.
3.

## Version information 
* **Signoz version**:
* **Browser version**: Firefox 99.0.1
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel):

**Comment by pranay01** [comment]
@thunko The link is incorrect. Please use - https://signoz.io/docs/userguide/dashboards/

Will fix this

**Comment by pranay01** [comment]
Also, this might be helpful - https://signoz.io/docs/userguide/metrics/

**Comment by pranay01** [comment]
this is fixed now
