### ISSUE TITLE
Rows per page setting button does not work

### ISSUE THREAD

**Issue by hmazucato** [SigNoz/signoz#1024]
## Bug description
Hello team! Thank you for providing and supporting SigNoz! I am currently testing SigNoz application and found something that may be a bug in UI.

![image](https://user-images.githubusercontent.com/101214165/166247585-f20be838-a6af-468d-92c5-3fcf1ff27837.png)

## Expected behavior
Trace analyze page should show the quantity of rows that was selected on the setting button.

## How to reproduce
Select any trace to analyze
Go to the bottom of the page
Click on Rows per page setting button
Try to change the value from 10 to any available
The UI does not shows the selected rows quantity

## Version information 
* **Signoz version**: v0.7.5
* **Browser version**: Google Chrome 100.0.4896.127 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
* **Your OS and version**: Windows 11 Version 21H2 (Build 22000.652)
* **Your CPU Architecture**(ARM/Intel): Intel Core i7-11390H - AMD64

**Comment by pranay01** [comment]
thanks @hmazucato for raising the issue. We have raised a PR which should solved this issue. It would be availble in the next release
