### ISSUE TITLE
A glitch in service map before setting to default zoom value

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#103]
Steps to reproduce:

1. Go to Service Map 
2. Got to Metrics Tab
3. Come back to the Service Map tab, it jerks twice before going to final zoom

I created a loom video to explain the glitch.
https://www.loom.com/share/d32aa22838874827b63f661c62d7f789

**Comment by dhrubesh** [comment]
this issue is related to https://github.com/SigNoz/signoz/issues/110, 
@ankitnayan do you think we can close this?
