### ISSUE TITLE
Missing Service Name icons when grouping the tracing graph by service name.

### ISSUE THREAD

**Issue by malanvaneck** [SigNoz/signoz#1055]
## Bug description

*Not all services are shown on this graph when grouped by Service Name:*
![image](https://user-images.githubusercontent.com/52539494/166634789-f1b7ca37-e19a-42b6-b1c9-12bd8d99df87.png)

After forcing the browser height on the div to auto:
![image](https://user-images.githubusercontent.com/52539494/166635034-f6c7ab1c-8b2a-4d06-b97a-225a345880bf.png)

![image](https://user-images.githubusercontent.com/52539494/166635049-e56cb8b9-0685-42cf-bc38-e233e7d3ea90.png)

I could see the rest of the services:
![image](https://user-images.githubusercontent.com/52539494/166635571-5c9367f2-c56a-46bf-9a9a-7cc415030037.png)

## Expected behavior

The graph should autoscale to show all services selected.

## How to reproduce

1. Make sure there is more than 6 service reporting to SigNoz.
2. Go to the traces tab.
3. Change the "Group By" to Service Name.
4. Notice missing services at the bottom of the Graph. 

## Version information 
* **Signoz version**:  v0.7.5
* **Browser version**: 100.0.4896.127 (Official Build) (64-bit)
* **Your OS and version**: Ubuntu 20.04
* **Your CPU Architecture**(ARM/Intel): Intel

**Comment by pranay01** [comment]
@malanvaneck thanks for opening the issue

**Comment by makeavish** [comment]
Closed in latest release (v.0.15.0)
