### ISSUE TITLE
Service to database/queue communication on the Service Map

### ISSUE THREAD

**Issue by malanvaneck** [SigNoz/signoz#1061]
## Is your feature request related to a problem?

*Currently only Service to Service communication is shown on the Service Map*

## Describe the solution you'd like

*Request to add service to database/queue communication on the Service Map as shown in the HotR.O.D Demo*
![image](https://user-images.githubusercontent.com/52539494/166653861-0af17d3e-0065-47b5-9279-59357f6de9e9.png)

**Comment by makeavish** [comment]
We have shipped this already: https://github.com/SigNoz/signoz/pull/1455
