### ISSUE TITLE
Number of spans in each category should be same in `Traces` tab

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#1079]
<img width="275" alt="Screenshot 2022-05-04 at 8 52 23 PM" src="https://user-images.githubusercontent.com/83692067/166714738-ed6b20a3-fd04-45f7-a0b4-c3410426bebc.png">

The number of spans in `Status` and `Service Name` should be same.

**Comment by makeavish** [comment]
This has improved with new explorer page in latest version
