### ISSUE TITLE
Intermittent issue with services shown in aggregate chart when filtering services from left panel

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1087]
## Bug description

Intermittent issue with services shown in aggregate chart when filtering services from left panel. The services shown in aggregate chart are not same as those selected in left panel

*If this affects the front-end, screenshots would be of great help.*  

https://www.loom.com/share/45c74537dcc9421488c595ff29a40772

## Expected behavior

Aggregate chart should only show services which are selected in left panel

## How to reproduce

1. Open trace filter page
2. Select some services and do group by service name in aggregate chart
3. Deselect some services in left panel. The services selected and those in aggregate chart are not same.

## Version information 
* **Signoz version**: v0.7.5
* **Browser version**: Chrome https://www.loom.com/share/45c74537dcc9421488c595ff29a40772
* **Your OS and version**: macOS 12.3.1
* **Your CPU Architecture**(ARM/Intel):  ARM

**Comment by ksorv** [comment]
<img width="1642" alt="Screenshot 2023-05-09 at 10 36 01 PM" src="https://github.com/SigNoz/signoz/assets/34188267/7a559688-0dc9-486b-9609-fb0f0c302d7c">

@pranay01 seems like the tags part that you mentioned in the bug has been removed? I also checked the code, either I missed it in code or its been removed, Would you be able to confirm?

**Comment by makeavish** [comment]
Not reproducible in latest version
