### ISSUE TITLE
Inconsistent breadcrumb label for exceptions page

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1099]
## Bug description

On clicking a particular error type, the breadcrumb changes to `Error` and then changes back to `exceptions` on  clicking it again

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  
https://www.loom.com/share/0bc32477177f46ea96412aca71e6af12

## Expected behavior

The breadcrumb should have label `Exception` for all situations

## How to reproduce

1. Click Exceptiions tab from left panel
2. Click any exception type
3. Click Breadcrumb label

## Version information 
* **Signoz version**:
* **Browser version**:
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel):

**Comment by makeavish** [comment]
This was fixed in previous releases.
