### ISSUE TITLE
Error message is not informative when incorrect current password is entered

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1101]
## Bug description

Error message is not informative when incorrect current password is entered

*If this affects the front-end, screenshots would be of great help.*  

https://www.loom.com/share/7554baa8a38b4b3aac5c066f3985fe59

## Expected behavior

The error message should say something like `invalid current password` 

## How to reproduce

1. Go to my account from navbar pop up
2. Enter incorrect current password
3. Enter a different new password and try to change it. The error message displayed only says ` Something went wrong` which is not very informative

## Version information 
* **Signoz version**: v0.8.0-rc5
* **Browser version**: Chome
* **Your OS and version**: macOs 12.3
* **Your CPU Architecture**(ARM/Intel):  ARM

**Comment by palashgdev** [comment]
if the status code is 500 frontend will show Something went wrong

**Comment by gxwilkerson415** [comment]
@pranay01 can i be assigned to this issue?

**Comment by YounixM** [comment]
Fixed by https://github.com/SigNoz/signoz/pull/4733

Closing the issue.
