### ISSUE TITLE
Graphs getting slashed in `Usage Explorer` Tab

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#1108]
In the usage explorer tab, the first and the last bar graph are getting slashed. 

<img width="1126" alt="Screenshot 2022-05-06 at 12 55 11 PM" src="https://user-images.githubusercontent.com/83692067/167086352-76374912-74c0-4c50-a390-fd2ac129542a.png">

**Comment by makeavish** [comment]
Also the gaps in between them is too much.

<img width="1140" alt="Screenshot 2022-08-05 at 10 25 24" src="https://user-images.githubusercontent.com/9512100/183004514-616b60d4-f6d9-4af1-b430-9e0009410d6d.png">

**Comment by pranay01** [comment]
@ankit01-oss this is fixed as of v0.11.0
