### ISSUE TITLE
Unable to integrate Uvicorn (multiple workers) to SigNoz.

### ISSUE THREAD

**Issue by nitin1993915** [SigNoz/signoz#1113]
## Bug description

*Below mentioned Docker CMDs work with single uvicorn worker to get the app traces but does not work with multiple uvicorn workers 
 `["opentelemetry-instrument",` "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]  
 -- worked
 `["opentelemetry-instrument",` "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--workers", `"2"]
 -- did not work
*  

## Expected behavior
Should be able to check the traces on UI with multiple unicorn workers

**Comment by pranay01** [comment]
@srikanthccv do you have insights on this?

**Comment by srikanthccv** [comment]
@nitin1993915 Which version of SDK are you using? Unlike gunicorn, uvicorn doesn't have any hooks that can be used to instantiate new span processor for each worker https://github.com/open-telemetry/opentelemetry-python/tree/main/docs/examples/fork-process-model. The newer version of sdk attempt to fix this to certain extent but there might be some limitation with uvicorn.

**Comment by pranay01** [comment]
@nitin1993915 Just checking if you are still facing this issue or this is solved. Please update here accordngly

**Comment by srikanthccv** [comment]
You can get it to work using gunicorn + uvicorn.workers.UvicornWorker class but the uvicorn is directly not supported. Please follow up on the upstream repo for any updates https://github.com/open-telemetry/opentelemetry-python-contrib/issues/385.
