### ISSUE TITLE
`Save` button disabled with default values in Retention Settings

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#1117]
https://www.loom.com/share/ffcc2ed40a4c47cbb06658889ac1b319

**Comment by palash-signoz** [comment]
@Cruxashu this is expected right... as button will make a AJAX call which will update the default retention period if the value is equal to the default value which is received from the server... i don't think we should allow the user to update the same values

**Comment by pranshuchittora** [comment]
+1

**Comment by pranay01** [comment]
@ankit01-oss This is expected behavior, only if there is a change in value - the save button should be enabled. Closing the issue
