### ISSUE TITLE
Not all applications getting listed in application dashboard

### ISSUE THREAD

**Issue by AnirudhaGohokar** [SigNoz/signoz#1129]
In application dashboard i.e "Home / Application" , we are not able to see couple of applications that are sending metrics data to signoz.
But the same applications we are able to see in "Home / Traces" filter by Service Name section. Can we check why there's descripency here. Due to this we are unable to move forward with this monitoring tool.

**Comment by palash-signoz** [comment]
Hi @AnirudhaGohokar 
Can you please change the Global Time in the Header section ? would that solve your problem

**Comment by pranay01** [comment]
@AnirudhaGohokar The list of services shown are based on the time selected in the top right corner. Only the services which send data in the selected time are shown. 

As @palash-signoz suggested, can you try changing the time period and see if the issue still persists

**Comment by variable** [comment]
I am also having this problem, I have followed the [instructions](https://opentelemetry-python.readthedocs.io/en/latest/examples/django/README.html) to setup django side

```python
#!/usr/bin/env python
import os
import sys

from opentelemetry.instrumentation.django import DjangoInstrumentor

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.settings")
    os.environ.setdefault("OTEL_SERVICE_NAME", "MyApp")
    os.environ.setdefault("OTEL_EXPORTER_OTLP_ENDPOINT", "http://<our-signoz-ip>:4317")

    # This call is what makes the Django application be instrumented
    DjangoInstrumentor().instrument()

    try:
        from django.core.management import execute_from_command_line
    except ImportError:
        # The above import may fail for some other reason. Ensure that the
        # issue is really that Django is missing to avoid masking other
        # exceptions on Python 2.
        try:
            import django
        except ImportError:
            raise ImportError(
                "Couldn't import Django. Are you sure it's installed and "
                "available on your PYTHONPATH environment variable? Did you "
                "forget to activate a virtual environment?"
            )
        raise
    execute_from_command_line(sys.argv)
```

And has signoz running in a docker service, can't see `MyApp` showing in the dashboard

**Comment by variable** [comment]
> 

@srikanthccv thanks, I am completely new on this topic if I use auto instrumentation, do I still need to add my own tracers in each view? The docs are very fragmented. Also how do I define where the trace data should go? Again, the docs don't mention any of these.

**Comment by variable** [comment]
> 

Hi @pranay01 I am getting this error:
```
WARNING:opentelemetry.exporter.otlp.proto.grpc.exporter:Transient error StatusCode.UNAVAILABLE encountered while exporting metrics, retrying in Nones.
ERROR:opentelemetry.sdk.metrics._internal.export:Exception while exporting metrics an integer is required (got type NoneType)
Traceback (most recent call last):
  File "/Users/jlin/virtualenvs/tigerpaw_webui/lib/python3.7/site-packages/opentelemetry/exporter/otlp/proto/grpc/exporter.py", line 308, in _export
    timeout=self._timeout,
  File "/Users/jlin/virtualenvs/webui/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/jlin/virtualenvs/webui/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1661830548.932389000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3261,"referenced_errors":[{"created":"@1661830548.932389000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":167,"grpc_status":14}]}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jlin/virtualenvs/webui/lib/python3.7/site-packages/opentelemetry/sdk/metrics/_internal/export/__init__.py", line 482, in _receive_metrics
    self._exporter.export(metrics_data, timeout_millis=timeout_millis)
  File "/Users/jlin/virtualenvs/webui/lib/python3.7/site-packages/opentelemetry/exporter/otlp/proto/grpc/metric_exporter/__init__.py", line 248, in export
    return self._export(metrics_data)
  File "/Users/jlin/virtualenvs/webui/lib/python3.7/site-packages/opentelemetry/exporter/otlp/proto/grpc/exporter.py", line 345, in _export
    sleep(delay)
TypeError: an integer is required (got type NoneType)
```

**Comment by srikanthccv** [comment]
@variable try setting the --metrics_exporter to none. If you don't set anything it defaults to gRPC.

```
opentelemetry-instrument --traces_exporter otlp_proto_http --metrics_exporter none python manage.py runserver
```

**Comment by variable** [comment]
For the life of me I can't get the app to show up in signoz, it doesn't raise any errors, so I don't know if it's emitting data to it or not.

**Comment by tantobocah** [comment]
im also facing this issue, in /trace page i am able to see the service, but in /services page there is no service listed. I've tried to change the timestamp from the right top corner, still no change. Any solution regarding this?
I'm using signoz docker v0.20.0

**Comment by pranay01** [comment]
@variable Can you try this troubleshooting repo and share what do you see? Generally the services not appearing happens because of the incorrect URL being used for SigNoz collector (which depends a lot on the infra you are running SigNoz in and the network)

**Comment by sthitaprajnadas** [comment]
Tried troubleshooting guide and SigNoz OpenTelemetry endpoint working fine
<img width="866" alt="image" src="https://github.com/SigNoz/signoz/assets/17138164/2c641e1a-0b13-4444-8773-ea808acff14b">

But Flask Application not appearing in services section.

**Comment by pranay01** [comment]
@sthitaprajnadas Can you check the time period you have selected in the top write corner time selector? Ensure that the time period selected includes time when your application was sending data (or just try selecting a longer time period)

**Comment by sthitaprajnadas** [comment]
@pranay01 - I am giving 1 week time as shown below but still flask or FastAPI app not showing in services.

<img width="1404" alt="image" src="https://github.com/SigNoz/signoz/assets/17138164/6f379ecf-ed4c-4d08-b867-696da70003cd">

Command used to execute the Fast App is below:

OTEL_RESOURCE_ATTRIBUTES=service.name=SampleFastAPI \
OTEL_EXPORTER_OTLP_ENDPOINT="http://0.0.0.0:4317" \
OTEL_EXPORTER_OTLP_PROTOCOL=grpc opentelemetry-instrument  uvicorn main:app

For flask app just followed steps at :  https://signoz.io/opentelemetry/python/

Also used troubleshooting repo and got below as expected.

<img width="923" alt="image" src="https://github.com/SigNoz/signoz/assets/17138164/05e8a164-40f5-43e0-8a48-3a33ab2c4f27">

**Comment by srikanthccv** [comment]
@sthitaprajnadas 

1. Please make sure you always work in the virtual environments.
2. Install the libraries that your application uses, ex: Flask, FastAPI, SqlAlchemy.
3. And then ensure the necessary packages are **_installed in venv_** using `opentelemetry-bootstrap --action=install`.
4. Use `python -m pip freeze`, and it should output the several instrumentation packages such as `opentelemetry-instrumentation-{flask,sqlite,...}` i.e. all the instrumentation packages for web frameworks, database client libraries found in your environment.
5. Set the additional `OTEL_TRACES_EXPORTER=otlp,console` to debug if the instrumentation works. If the instrumentation works, you will see the JSON output of traces in the terminal.
6. Disable any hot reloading since it breaks the instrumentation

**Comment by ankit01-oss** [comment]
Also, check out troubleshooting docs in each language instrumentation.

[Python](https://signoz.io/docs/instrumentation/python/#troubleshooting-your-signoz-installation)
[Java](https://signoz.io/docs/instrumentation/java/#troubleshooting-your-installation)
[Javascript](https://signoz.io/docs/instrumentation/javascript/#troubleshooting-your-installation)

**Comment by makeavish** [comment]
I think the issue is instrumentation related. Please follow troubleshooting docs for each language as shared above.

**Comment by dafu-wu** [comment]
same issue, use triton server metric, not show my app in services
