### ISSUE TITLE
Enable support for Logs 

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1139]
This feature should enable users to send logs to SigNoz and visualise it in SigNoz UI

- [ ] https://github.com/SigNoz/signoz/issues/1140
- [ ] https://github.com/SigNoz/signoz/issues/1141

**Comment by pranay01** [comment]
Initial logs design. Would love any feedback. Any thing which you find missing
![variant2](https://user-images.githubusercontent.com/504541/176823688-67c0080d-872e-4255-ad2d-5192af7c390c.png)

**Comment by alexanderadam** [comment]
It looks great. Any plans to [render the shell colour codes in HTML/CSS](https://unix.stackexchange.com/questions/44956/converting-colored-output-into-html)?

**Comment by pranay01** [comment]
hey @alexanderadam thanks for the feedback. Is the use case for having different colors based on stderr or stdout  - to identify logs from stderr more easily? Would you not just want to filter based on that?

**Comment by alexanderadam** [comment]
It was just an idea. A filter is sure necessary but I often like visual hints. It's also fine for me if there isn't any visual hint.

**Comment by blakeromano** [comment]
It'd be awesome if the syntax was similar to Kibana Query Language (KQL). Also if we could select a specific time frame to look at. For example I may want to look from 10:30AM-11:30AM even though it is 10PM now.

**Comment by pranay01** [comment]
@blakeromano You would be able to select custom time frame. This is supported even today in SigNoz. We will leverage the same component

![Screenshot 2022-07-04 at 1 16 01 PM](https://user-images.githubusercontent.com/504541/177106935-ff992861-a2b6-4452-a09e-a379a853aba0.png)

Regarding KQL, is the primary reason for the suggestion is that you are currently familiar with KQL and would want to see something similar in terms of supported patterns? Or there are any other specific reasons?

**Comment by blakeromano** [comment]
I think that the query mechanism in Kibana is smart and easy, and I think using similar syntax will make transition over for teams easier. Or I would be okay with something similar to the new query builder where you have the option to use KQL or Signoz's own query language. I think that might also be a smart way to go.

**Comment by chrisstetter** [comment]
I have seen that log management will be released with https://github.com/SigNoz/signoz/milestone/12. But as far as I can see, you plan not to release the corresponding frontend in that release?

**Comment by pranay01** [comment]
We have released logs in [v0.11.0](https://github.com/SigNoz/signoz/releases/tag/v0.11.0)
@chrisstetter @alexanderadam would be great if you can check out any share any feedback
