### ISSUE TITLE
Service Map takes 15-20s to load when loading for the first time

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#114]
## In what situation are you experiencing subpar performance?

Service Map takes 15-20s to load when loading for the first time (Attached loom video link)

## How to reproduce

1. Go from metrics tab to Service map tab for the first time after starting SigNoz
2. It takes 15-20s to load for the first time
3. Second time loading is much faster

## Expected behavior
Service Map should load first time also in sub 1s time

## Your Environment

- Self Hosted SigNoz

## Additional context
Loom Video
https://www.loom.com/share/5323b33de4714b04bf2d6c4f6c9146f9?from_recorder=1&focus_title=1

**Comment by ankitnayan** [comment]
fixed in release https://github.com/SigNoz/signoz/releases/tag/v0.3.1

**Comment by ankitnayan** [comment]
#131 #132
