### ISSUE TITLE
[Epic] Enable Support for Logs (Backend)

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1141]

**Comment by bhaswanth88** [comment]
would love to see this feature soon.  This is very much the need of hour to do a simple way of integrating logs for distributed microservice based envs

**Comment by nityanandagohain** [comment]
- [ ] https://github.com/SigNoz/signoz/issues/1260

**Comment by nityanandagohain** [comment]
- [ ] #1271
