### ISSUE TITLE
Add support for monitoring Traefik

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1160]
## Is your feature request related to a problem?

Many users have asked for a way to support Traefik with SigNoz - so that users can also understand time spent in the API gateway or get metrics from it

## Describe the solution you'd like
SigNoz should be able to get get trace / metrics data in Traefik

## Additional context
Reddit Discussion - https://www.reddit.com/r/selfhosted/comments/usfkgk/comment/i93fmd1/

#### *Thank you* for your feature request – we love each and every one!

**Comment by pranay01** [comment]
Wait for opentelemetry support

**Comment by prashant-shahi** [comment]
Tracking issue: https://github.com/traefik/traefik/issues/6374

**Comment by rwjack** [comment]
I'm compelled to give SigNoz a chance opposed to DataDog, and it seems that opentelemetry has been implemented in traefik (https://github.com/traefik/traefik/pull/8999)

Any updates on this?

**Comment by prashant-shahi** [comment]
@rwjack We will be initiating Traefik support work and docs in couple of days.

**Comment by prashant-shahi** [comment]
@rwjack Here is the PR that you can track for this in SigNoz: https://github.com/SigNoz/signoz.io/pull/903

**Comment by rwjack** [comment]
@prashant-shahi Thanks!

**Comment by prashant-shahi** [comment]
Traefik v3 is yet to be officially out.
However, there are v3 release candidates that can be used for time-being.

https://github.com/traefik/traefik/releases/tag/v3.0.0-rc3

We have included the beta version of v3 in our Traefik tutorial.
