### ISSUE TITLE
Add LDAP Authentication

### ISSUE THREAD

**Issue by mxlxm** [SigNoz/signoz#1162]
## Is your feature request related to a problem?

Allow user to login with their LDAP credentials.

## Describe the solution you'd like

Integrate LDAP support with https://github.com/go-ldap/ldap, and also allow user to specify mappings between LDAP group memberships and signoz user role.

**Comment by pranay01** [comment]
thanks for opening this issue @mxlxm We will look into it

**Comment by iamkhalidbashir** [comment]
This would be cool if implemented

**Comment by tominglis** [comment]
I would love to see this feature, so that we can login to the app using FreeIPA.

**Comment by robertcoltheart** [comment]
Yep, one of the lacking features that will stop us using SigNoz I'm afraid.

**Comment by ankitnayan** [comment]
It will be available in the enterprise plan
