### ISSUE TITLE
Add sample apps reference in docs

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#117]
We have sample apps for languages like Python, NodeJS, etc. which users can start with to try instrumentation with SigNoz.

Add the reference of the sample apps in the docs and steps for using then in the [docs](https://signoz.io/docs/instrumentation/overview).

Sample app repos
- Flask (Python) - https://github.com/SigNoz/sample-flask-app
- Golang - https://github.com/SigNoz/sample-golang-app
- NodeJS - https://github.com/SigNoz/sample-nodejs-app

**Comment by saideepesh000** [comment]
@pranay01  I think this issue can be closed

[Flask](https://signoz.io/docs/instrumentation/python#instrumentation-of-a-sample-flask-application)
[Nodejs](https://signoz.io/docs/instrumentation/python#instrumentation-of-a-sample-flask-application)
[Golang](https://signoz.io/docs/instrumentation/golang#instrumentation-of-a-sample-golang-application)

But we still need `java` implementation

**Comment by pranay01** [comment]
Ok. closing this issue and creating new one for Java
