### ISSUE TITLE
update Makefile build- target

### ISSUE THREAD

**Issue by mugr1x** [SigNoz/signoz#1172]
trying to build with deploy/install.sh as advised in docs builds fine,
however make build-frontend-amd64 shows an error about node version
so this is mostly dev/pipeline due to an outdated docker repo ?

in clean arch chroot: https://bin.disroot.org/?bf9d0899220b375b#6Ewxhb3mXmiqcJfJJ6zwchhp4k8vL8mMCTkmAkW4V3Tn

**Comment by pranay01** [comment]
@prashant-shahi do you have any more insights on this?

**Comment by prashant-shahi** [comment]
Hey @mugr1x! That looks like node version mismatch issue.

We had updated frontend Dockerfile few days back.
Can you pull latest changes from `develop` branch? It should be fixed there.

Closing this issue for now, feel free to re-open if this issue still persists for you.
