### ISSUE TITLE
coldStorage s3 issue 

### ISSUE THREAD

**Issue by medicharlachiranjeevi** [SigNoz/signoz#1175]
## Bug description
config about Move to S3  is reverting back to none values in logs we got the exception. 
```
2022-05-20T05:28:43.172Z	INFO	app/server.go:157	/api/v1/settings/ttl	timeTaken: 6.452474382s
2022/05/20 05:28:43 http: URL query contains semicolon, which is no longer a supported separator; parts of the query may be stripped when parsed; see golang.org/issue/25192
```
this is working as at version 0.7.5 in 0.8.0 it's not working as expected.

## How to reproduce

1. install latest SigNoz in k8s using helm
2. enable coldStorage 
3. try change Move to S3 period.

![Screenshot from 2022-05-20 12-26-11](https://user-images.githubusercontent.com/17638736/169471148-8e5cfce0-d076-4930-8de9-f33bf4e1b2f9.png)
![Screenshot from 2022-05-20 12-26-16](https://user-images.githubusercontent.com/17638736/169471157-02248774-e575-464a-b30c-4fb4612b0f31.png)

## Version information 
* **Signoz version**: 0.8.0

**Comment by palash-signoz** [comment]
Fixed by https://github.com/SigNoz/signoz/pull/1177

**Comment by prashant-shahi** [comment]
@medicharlachiranjeevi The above PR should resolve this issue.

**Comment by prashant-shahi** [comment]
@medicharlachiranjeevi The above PR should resolve this issue.

**Comment by medicharlachiranjeevi** [comment]
when it is going to be realised ?

**Comment by prashant-shahi** [comment]
@medicharlachiranjeevi Today :)

**Comment by medicharlachiranjeevi** [comment]
hey @prashant-shahi ,
seem's it's not deployed yet.

**Comment by prashant-shahi** [comment]
@medicharlachiranjeevi we are currently working on couple of things that would be out in the new release..
it should be out in few days.
