### ISSUE TITLE
Docker fills up disk even though data stored is only 4.5GB

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#121]
## Steps to reproduce
Install SigNoz and keep it running for a few days. The disk space seems to deplete continuously even though the retention policy is set and Druid shows only 4.6 GB of data stored.

## Your Environment

- [x] Linux
- [ ] Mac
- [ ] Windows

**Comment by sourabhtk37** [comment]
@ankitnayan any more information available in this? Logs?

Steps to reproduce:
- Have signoz running for few days? How many days?
- Can you see the storage filling up instantly? 
- Watch disk space?

**Comment by ankitnayan** [comment]
@sourabhtk37 I am not able to free up time to investigate this issue. Please feel free to pick this up, if you get some time.

## Sharing the context
> Have signoz running for few days? How many days?

The demo services take up around 1.5GB per day. The default retention policy set at Druid is 3 days and hence the size of the volume should be maintained at 4.5GB. This is verified by `docker system df`. The volume size is consistent at 4.5GB but the overall disk space of the machine keeps increasing.

> Can you see the storage filling up instantly?

No, it increases uniformly

> Watch disk space?

As I vaguely remember, I tried to dig deeper using `docker ps --size` and  `du -sh /var/lib/docker/overlay2` and I think, Kafka size was increasing, maybe due to logs. So, I tried adding  below config at [file](https://github.com/SigNoz/signoz/blob/main/deploy/docker/druid-kafka-setup/docker-compose.yaml#L36) but I don't remember the results. That was more than a month back.
```
KAFKA_LOG_RETENTION_HOURS: 1
KAFKA_LOG_RETENTION_BYTES: 10737418240
KAFKA_LOG_SEGMENT_BYTES: 1073741824
KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
KAFKA_LOG_SEGMENT_DELETE_DELAY_MS: 60000
```

Running Kafka + Druid for a few days can be huge for resources. It takes 5GB to get started. We can assign you an ec2 instance to experiment with. Let me know over slack.

**Comment by makeavish** [comment]
Stale issue. Closing it.
