### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by JamieSlome** [SigNoz/signoz#1210]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@cokebeer) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by pranay01** [comment]
thanks @JamieSlome for opening the issue. Let me check the GitHub link you have shared

**Comment by JamieSlome** [comment]
Thanks, @pranay01 🤝 

Just for reference, the report we received can be found directly here:
https://huntr.dev/bounties/f2181d40-407d-4ce3-b137-8fb3af66cad0/

It is currently private and only accessible to maintainers with repository write permissions that sign up to the platform. However, we understand that you may not want to sign-up, so can provide you with a magic URL once we have an e-mail that we can use to send the details to :)

**Comment by pranay01** [comment]
Hey @JamieSlome 
Have added an email for reporting vulnerabilities here
https://github.com/SigNoz/signoz/blob/develop/SECURITY.md
