### ISSUE TITLE
@opentelemetry/exporter-otlp-grpc is deprecated

### ISSUE THREAD

**Issue by Zoharos** [SigNoz/signoz#1212]
Hi,
I noticed that in the documentation it is recommend to use @opentelemetry/exporter-otlp-grpc although it is deprecated.

Maybe update the documentation @opentelemetry/exporter-trace-otlp-grpc and @opentelemetry/exporter-metrics-otlp-grpc and that it is supported.

Thanks

**Comment by srikanthccv** [comment]
@Zoharos feel free to send a pull request updating the docs if you are interested. Otherwise, one of us will review the post content again and update all the relevant deps.

**Comment by pranay01** [comment]
@Zoharos here's the repo for the website - https://github.com/SigNoz/signoz.io/

**Comment by Zoharos** [comment]
Hi,
Before I leave a PR I checked if the new recommended libraries are supported by signoz and it made me some problems.
In http I get 400 bad request because of unknownfield scopeSpans ERROR.
In grpc I get http2Server.HandleStreams received bogus greeting from client ERROR.

**Comment by srikanthccv** [comment]
@Zoharos thanks for taking a stab at it. There was a change in proto since 0.15.0 because of renaming `InstrumentationLibrarySpans` to `ScopeSpans` https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v0.15.0. Which version of `@opentelemetry/exporter-trace-otlp-*` are you using?

**Comment by Zoharos** [comment]
@srikanthccv with both grpc and http packages I tried with the latest version as of now (0.29.0)

**Comment by HyunGook-Kim** [comment]
@opentelemetry/exporter-trace-otlp-http with version 0.28.0 works fine. But 0.29.0 above requires collector version 0.48 and up(https://github.com/open-telemetry/opentelemetry-js#upgrade-guidelines).

So, i tried to upgrade my signoz/otelcontribcol version from 0.45.1-1.0 to 0.5.0 and the docker image throws an error `cannot unmarshal the configuration: unknown exporters type "clickhousetraces" for "clickhousetraces" (valid values: [sapm sentry awsemf kafka azuremonitor datadog file influxdb jaeger_thrift logzio alibabacloud_logservice awsprometheusremotewrite stackdriver awsxray loadbalancing sumologic awskinesis jaeger opencensus otlphttp splunk_hec tanzuobservability zipkin clickhousemetricswrite newrelic loki prometheusremotewrite elasticsearch googlecloud otlp prometheus signalfx tencentcloud_logservice carbon humio elastic f5cloud honeycomb logging parquet skywalking clickhouse dynatrace]`

After i changed the `clickhousetraces` to `clickhouse` in otel-collector-config.yml, it cause error on migration.

It seems signoz/release/v0.9.1 branch still use `signoz/otelcontribcol:0.45.1-1.0`. Is there a plan for upgrade version of otelcontribcol in the future?

**Comment by srikanthccv** [comment]
We will probably upgrade in next major release

**Comment by ankitnayan** [comment]
https://github.com/open-telemetry/opentelemetry-js/issues/2943#issuecomment-1114265125

**Comment by srikanthccv** [comment]
With our distribution signoz-otel-collector, this is not an issue anymore.
