### ISSUE TITLE
Enable searching of services and operation names in trace filter page

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1224]
## Is your feature request related to a problem?

When there are lots of services and operations in the trace filter page ( say 20+) then finding the exact service/operation to filter on becomes extremely cumbersome in current UX. 

## Describe the solution you'd like

Users should be able to filter services and operations name through a search like interface, so that they can find the required service name much more easily, rather than scrolling through a long list

## Describe alternatives you've considered

Currently you can scroll the list, but it is not very efficient

## Additional context
Current SigNoz UX
![Screenshot 2022-06-02 at 7 33 08 PM](https://user-images.githubusercontent.com/504541/171647229-f07ba655-be48-4b23-860b-a98633e9516d.png)

Datadog UX where you can search with initial letters and it suggests matching entries
![Screenshot 2022-06-02 at 7 34 45 PM](https://user-images.githubusercontent.com/504541/171647526-635a5eda-69fe-4a8e-b283-8f6765e34855.png)

#### *Thank you* for your feature request – we love each and every one!

**Comment by ankitnayan** [comment]
Fixed by https://github.com/SigNoz/signoz/pull/1304
