### ISSUE TITLE
More intuitive custom time filter selection

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1225]
## Is your feature request related to a problem?

To select a custom time filter in SigNoz UI, users need to go the time filter in top right corner and select a time frame. Though users are generally not very sure on what time filter they should  select and which has the issues they are trying to investigate.

![Screenshot 2022-06-02 at 7 39 39 PM](https://user-images.githubusercontent.com/504541/171648567-4f5f8a32-3cf3-4339-9384-9be9b74cd3ec.png)

## Describe the solution you'd like
Other tools like Kibana allow you to visually select a custom time period from a bar chart. So, if you want to explore cases like times in which RPS was very high, you can just select that region from the chart itself.

**Comment by makeavish** [comment]
This is supported in latest version
