### ISSUE TITLE
Enable status code filtering in left panel in trace filter page for grpc codes also

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1226]
## Is your feature request related to a problem?

Currently, left panel in trace filter page is shows only HTTP code as filters. Though users can filter based on GRPC code using tag filters, it would be good idea to enable status code based filtering in trace filter left panel also

![Screenshot 2022-06-02 at 8 19 30 PM](https://user-images.githubusercontent.com/504541/171657054-6e781beb-315b-4e25-a269-15054eae2246.png)

## Describe the solution you'd like

Show GRPC code also along with HTTP Codes in left panel filter

## Describe alternatives you've considered

Using GRPC code filters from tag filters. This works, but including this in left panel would make the user experience much more seamless.

![Screenshot 2022-06-02 at 8 22 13 PM](https://user-images.githubusercontent.com/504541/171657652-85b6494a-51e9-49b4-9629-95782615066a.png)

**Comment by ankitnayan** [comment]
This is fixed now
