### ISSUE TITLE
Querying traces

### ISSUE THREAD

**Issue by Zoharos** [SigNoz/signoz#1237]
## Is your feature request related to a problem?
No

## Describe the solution you'd like
I want to make a query on traces and create a dashboard panel of it, is it possible right now in Signoz?

**Comment by pranay01** [comment]
@Zoharos Can you share more details on which specific queries you want to run ?

**Comment by pranay01** [comment]
You can filter traces based on tags today - https://signoz.io/docs/userguide/traces/#filter-spans-by-tagsattributes
![Screenshot 2022-06-06 at 2 29 41 PM](https://user-images.githubusercontent.com/504541/172130106-607d9698-ca97-4c6d-bcbf-9200363af5bf.png)

**Comment by Zoharos** [comment]
I want to compare the number of traces with errors in the last two weeks compare to the two weeks before them

**Comment by ankitnayan** [comment]
@srikanthccv doing this should be possible with the CH query builder, right? I tried running below query but it return 0 values in the chart but works fine when I connect to clickhouse from a terminal client.

```
select toStartOfHour(timestamp) AS hour, count() as errorCount from signoz_traces.signoz_index_v2 where statusCode=2 and timestamp > toDateTime64(now() - INTERVAL 1 WEEK, 0, 'UTC') group by hour;
```

**Comment by srikanthccv** [comment]
@ankitnayan make sure resulting time column is `time.Time` and value is `float64` from the query result. Let me know if it still doesn't work.

**Comment by ankitnayan** [comment]
@srikanthccv it worked with above changes
```
select toDateTime(toStartOfHour(timestamp)) AS hour, toFloat64(count()) as errorCount from signoz_traces.signoz_index_v2 where statusCode=2 and timestamp > toDateTime64(now() - INTERVAL 1 WEEK, 0, 'UTC') group by hour order by hour asc;
```

cc: @pranay01

**Comment by ankitnayan** [comment]
@Zoharos the above query should yield what you want to plot. Can you check if this works for you?
