### ISSUE TITLE
Rename `Metrics` tab to `Services`

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1249]
Currently the default selected tab in SigNoz is `Metrics` tab which actually shows the list of services and datapoints on them which are obtained from traces.

This name could be a bit misleading as SigNoz also supports [sending many types of metric ](https://signoz.io/docs/userguide/send-metrics/) which can be plotted in the `Dashboards` tab. 

Hence, using `Services` for the default tab might be a more suitable naming.

![Screenshot 2022-06-13 at 4 52 33 PM](https://user-images.githubusercontent.com/504541/173343286-25513c58-f7a4-4ae8-92c2-16d0daba1025.png)

Recently, there was a conversation in our slack community regarding this also 
https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1654766368613349

**Comment by pranay01** [comment]
@ankitnayan What do you think?

**Comment by ankitnayan** [comment]
@pranay01 yes, we can do that. It makes sense.

**Comment by pranshuchittora** [comment]
@pranay01 Palash has raised a fix for the same and renamed the specific Tab name per the requirements.
And here's the PR for the same https://github.com/SigNoz/signoz/pull/1250

Ideally, the name of the route (in the URL) and the breadcrumb should change as well but it is now mentioned in the scope of this issue, 

Refer this for the detailed explanation of what exactly is missing https://github.com/SigNoz/signoz/pull/1250#pullrequestreview-1014626726
