### ISSUE TITLE
Make SigNoz more GRPC aware

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1252]
## Is your feature request related to a problem?

Currently, SigNoz assumes the request type being HTTP requests. This leads to suboptimal experience for users using SigNoz for GRPC services.

e.g. 
1. To be considered for External calls tab, only call with `http.url`. as non empty are plotted
2. HTTP code facet in trace filter page shows only HTTP status codes

## Describe the solution you'd like
We should relook if there are are inherent assumptions for HTTP at certain places and removes such assumptions wherever possible.

**Comment by ankitnayan** [comment]
@srikanthccv please check `spanmetricsprocessor` for missing data in application detail charts at https://github.com/SigNoz/engineering-pod/issues/405

- [ ] RPS
- [ ] Error
- [ ] External Calls
- [ ] DB Calls

**Comment by ankitnayan** [comment]
@pranay01 How to change below fields in making signoz `grpc` aware?
-  the `method` table column in the span list component
-  LHS filters starting with `HTTP `

![Screenshot 2022-06-28 at 7 14 13 PM](https://user-images.githubusercontent.com/12460410/176194232-7a25828e-9db0-4496-a74e-94101fccda39.png)

**Comment by srikanthccv** [comment]
@pranay01 the below two charts in the external page are by http address. Should we create two new panels with address=`rps service`+`rpc method`? Or should we combine all of them on into same two panels with new name like `remote resource` i.e HTTP endpoint for HTTP calls and `rps service`+`rpc method` for gRPC and similar. 
![Uploading Screenshot 2022-06-28 at 7.15.22 PM.png…]()

**Comment by srikanthccv** [comment]
@pranay01 We plan to address this in current sprint and make it part of next release. Please share a PRD doc and we will discuss and iterate on it. 

Some things to note:

Usually systems are mostly either gRPC/protobuf (microservices-demo) or HTTP/JSON(hotrod). So by dividing and adding separate panels and filters for each protocol we make UI little complicated. This will create empty HTTP panels when services are mostly gRPC based and vice versa. If we have to combine them we will need to coin new term which accommodates both protocols.

Alternatively we can let the users to customize/hide components but this will require some work on frontend. However, if we agree on to something, the data can modeled on the backend and any UI related work can be done later.

**Comment by pranay01** [comment]
> @pranay01 How to change below fields in making signoz `grpc` aware?
> 
> * the `method` table column in the span list component
> * LHS filters starting with `HTTP `
> 
> ![Screenshot 2022-06-28 at 7 14 13 PM](https://user-images.githubusercontent.com/12460410/176194232-7a25828e-9db0-4496-a74e-94101fccda39.png)

I think in the LHS filters we can change fields to 

`Status Code`
`Method`
`HTTP Host`
`HTTP Route`
`HTTP URL`

@srikanthccv does GRPC also have Host, Route and URL? In that case we would need to change the above fields as well

**Comment by pranay01** [comment]
> @pranay01 the below two charts in the external page are by http address. Should we create two new panels with address=`rps service`+`rpc method`? Or should we combine all of them on into same two panels with new name like `remote resource` i.e HTTP endpoint for HTTP calls and `rps service`+`rpc method` for gRPC and similar. <img alt="Screenshot 2022-06-28 at 7 15 22 PM" width="1201" src="https://user-images.githubusercontent.com/22846633/176195225-3f7b16ac-149e-420a-9f60-ae2a7437b1f8.png">

I would prefer to go with 2nd approach. A question here: Can a service have both HTTP and GRPC calls? In that case I think there should be an indication on which calls or HTTP calls and which are GRPC

**Comment by pranay01** [comment]
Discussed with @ankitnayan We will go with HTTP and GRPC in the same graph

**Comment by srikanthccv** [comment]
>does GRPC also have Host, Route and URL?

Not in the same sense as HTTP but there are similar attributes, closest thing to route is `{rpc.serivce}`+`rpc.method` and URL = Host + Route.

>Status Code
RPC Method
HTTP Method
HTTP Host
HTTP Route
HTTP URL

I think one more detail we can include in the left is `rpc.service` (not same service name; a process can expose multiple rpc services but the resource `service.name` is same for both) because user will have number of services each with many methods, sometimes even common name is possible. So user would first filter by rpc.service and then method in that service.

>We will go with HTTP and GRPC in the same graph

@ankitnayan we will have address tag which is either http host:port or rpc serive:method? or idea is to run two queries different for HTTP and RPC and show the data in the same graph?

**Comment by ankitnayan** [comment]
> we will have address tag which is either http host:port or rpc serive:method?
@srikanthccv this seems cleaner to me. What do you say?

**Comment by srikanthccv** [comment]
@ankitnayan Yes, I think that would also be more appropriate because in general [`http.url`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#common-attributes) can be anything.
