### ISSUE TITLE
Show Loading icon for cases when API response is taking more time for trace filter page

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1257]
Sometimes, trace filter page takes time in loading. In these scenario a loading gif should be shown to indicate to users that this page will take some time to load

**Comment by ankitnayan** [comment]
@pranay01 please add more details

**Comment by YounixM** [comment]
@pranay01:  Did we encounter this issue in recent times? We can close this if not.

**Comment by makeavish** [comment]
This has been fixed at multiple places with new designs.
Still at some older pages the issue exists which are expected to be resolved after those pages are migrated to new design.

**Comment by makeavish** [comment]
Closing this as it's fixed in recent versions
