### ISSUE TITLE
Trace tag details in traces section overflowing in UI

### ISSUE THREAD

**Issue by muddlebee** [SigNoz/signoz#126]
## Bug description

Trace tag details in traces section is overflowing. 
e.g. http://localhost:3000/traces/bcb0bc7006d635327a6a6580bb1dad8f

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

![Screenshot 2021-05-29 at 10 15 40 AM](https://user-images.githubusercontent.com/8139783/120058252-42370a80-c067-11eb-9eef-d9ce8de07f0e.png)

## Expected behavior
Trace tag details should be contained within the div

## How to reproduce

1. Setup https://signoz.io/docs/instrumentation/nodejs (export OTEL_LOG_LEVEL=debug option should be enabled)
2. Hit /hello endpoint. Go to Metrics -> Click Node-Telemetry -> Check **Top Endpoints** section/box
3. Navigate to GET /hello and then choose any traceID
4. Click on the highlighted yellow section below.

![Screenshot 2021-05-29 at 10 26 12 AM](https://user-images.githubusercontent.com/8139783/120058420-5a5b5980-c068-11eb-81a4-e4fbbe646141.png)

or

Navigate directly to the traces section if you have the traceID .
e.g http://localhost:3000/traces/bcb0bc7006d635327a6a6580bb1dad8f

**Comment by anweshknayak** [comment]
I can take this up 👀

**Comment by LEO1612D** [comment]
I can help in this one

**Comment by anweshknayak** [comment]
sure @LEO1612D Go ahead 👍  assigning to you

**Comment by pranay01** [comment]
Closing this issue as we have updated how tags are shown in trace details page
