### ISSUE TITLE
Sign Up Button Not Working

### ISSUE THREAD

**Issue by moronmon** [SigNoz/signoz#1282]
## Bug description
Hi,
I do try to run the Signoz 0.8.2 version, deployed using the docker-compose.
The deployment is working fine, but when I try to log in, I don't know the administrator credentials. After looking at the documentation (https://signoz.io/docs/userguide/authentication/), it said:
"
The person who installs SigNoz and registers for the first time is by default assigned the role of an admin.
If you are logging in SigNoz for the first time, just create an account. This will make you an admin.
"
But when I tried to SignUp, the "Get Started" button is grey-out (as Attached image).

Do I miss something?
## Expected behavior
The Get Started will be clickable after the all information filled in.

## How to reproduce

1.
2.
3.

## Version information 
* **Signoz version**: 0.8.2
* **Browser version**: Brave [Version 1.39.122 Chromium: 102.0.5005.115 (Official Build) (64-bit)](https://brave.com/latest/) & Firefox 101.0.1
* **Your OS and version**: Client Pop OS! 22.04, Server: Ubuntu Server 20.04
* **Your CPU Architecture**(ARM/Intel): Intel

#### *Thank you* for your bug report – we love squashing them!
![Signoz-SignUp](https://user-images.githubusercontent.com/59859392/174525651-9c00c561-6cc7-48cc-b0ad-61e0ef1905e9.png)

**Comment by ankitnayan** [comment]
@moronmon I think you did not meet the requirement checks of a strong password as can be inferred from the screenshot attached

![Screenshot 2022-06-20 at 10 25 13 AM](https://user-images.githubusercontent.com/12460410/174527875-259ee21e-9622-49d6-885d-6a628f574883.png)

**Comment by moronmon** [comment]
Hi @ankitnayan ,
Thank you ... thank you. I missed the special character.
