### ISSUE TITLE
Allow Y-Axis minimum value to be zero

### ISSUE THREAD

**Issue by drjasonharrison** [SigNoz/signoz#1290]
## Is your feature request related to a problem?

For some graphs, a Y-axis of 0 (zero) is expected rather than a Y-axis min/max interval that adjusts with the data in the current time period. For example, CPU load, latency, response time...It's fine to scale Y-axis max sometimes, but other times it should be set to a fixed value. This allows for quicker interpretation as the user does not need to read the Y-axis graph and the data point values to determine if something has changed in the behaviour.

## Describe the solution you'd like

For Y-axis min: auto, and fixed values
For Y-axis max: auto, and fixed values

## Describe alternatives you've considered

These are the only options. Currently there is only auto.

## Additional context

Here are some examples of graphs that lie, including ones where the Y-axis intercept is not 0: https://heap.io/blog/how-to-lie-with-data-visualization

#### *Thank you* for your feature request – we love each and every one!

**Comment by ksorv** [comment]
@pranay01 We can give a right click context menu on the charts where this is to be allowed, Later if more options are needed they can also be added there.

Here's a rough kind of behaviour without the context menu:
https://github.com/SigNoz/signoz/assets/34188267/ff2f44f4-1e93-4d41-a8b2-a9758e1875d7

Let me know If I should go ahead with something like this, or if you'd like me to change something up..

**Comment by srikanthccv** [comment]
This is now supported with the soft min/max options in panel settings https://signoz.io/docs/dashboards/panel-types/timeseries/#soft-min-max
