### ISSUE TITLE
Create a repo for community members to share pre made SigNoz dashboards

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1298]
## Is your feature request related to a problem?

SigNoz currently supports ability to import and export dashboard JSON. Currently every SigNoz user needs to create his own dashboard from scratch. This is time consuming.

## Describe the solution you'd like

We can allow SigNoz users to share dashboards they have created with the community. This would help new users get started with a good base point rather than writing everything from scratch. The dashboard repos can potentially be organized under common types like dashboards for Hostmetrics, K8s metrics, JVM metrics, Kafka metrics, etc.

## Describe alternatives you've considered

There can be multiple ways to enable this - either Github repos, or a place where json files are hosted.

## Additional context

Considerations
- [ ] how to make this work for different versions of SigNoz dashboards so that users can seamlessly upgrade dashboards

#### *Thank you* for your feature request – we love each and every one!

**Comment by zriyansh** [comment]
<img width="1258" alt="Screenshot 2022-06-22 at 13 10 46" src="https://user-images.githubusercontent.com/52788043/174972291-df95ebf7-fa3e-4e7d-9433-43f214e943ec.png">

Is the JSON for these dashboards available in the docs? 
If some dev has it, would be good to initiate the community repo with these pre-made examples.

**Comment by pranay01** [comment]
Currently, this has dashboards for hostmetrics and k8s metrics.

https://github.com/SigNoz/benchmark/tree/main/dashboards

@prashant-shahi do confirm if this can be added in the docs?

**Comment by prashant-shahi** [comment]
@pranay01  We are already using that dashboard JSON in docs. https://signoz.io/docs/tutorial/kubernetes-infra-metrics/

But a new repository for dashboards would make more sense.

**Comment by makeavish** [comment]
Repo exists now: https://github.com/SigNoz/dashboards
