### ISSUE TITLE
Too long time range passed from metrics to traces page

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#13]
Keeping the startTime and endTime as the same would be more beneficial to debug issues. As there can be 100s of spans in a sec and thus a time range of 15 mins does not make much sense in debugging in the trace page.

@pranay01 what do you think?

**Comment by pranay01** [comment]
Yeah, makes sense. Let's reduce the time range for going from metrics to traces page. We would need to introduce separate interval selection for custom aggregate panel then
