### ISSUE TITLE
Create chart for the alert rule to verify the alert rule

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#1350]
Currently, when writing an alert rule a user is not sure whether the rule is correct and it creates confusion if an alert is not firing. Today, we have to go to the `dashboards` page and create a temporary panel and plot the alert rule to verify that it works and then copy that to the alerts page. 

What can be done?
1. Show a chart for the alert rule when creating an alert on the same page
2. Allow creating alerts from dashboard

**Comment by pranay01** [comment]
@ankitnayan Is this for the new alerts builder UI or for existing promql page?

**Comment by srikanthccv** [comment]
Both of the mentioned points ways of helping users exist today
