### ISSUE TITLE
No reset password option in login screen

### ISSUE THREAD

**Issue by AnirudhaGohokar** [SigNoz/signoz#1358]
Not sure how we can reset password. There's no option available on login screen.

**Comment by pranay01** [comment]
@AnirudhaGohokar Users can't reset their password from login screen. 

You can ask your admins to generate a link to reset password (as shown in the screenshot below). You can use this link to reset your password

![Screenshot 2022-07-05 at 1 34 13 PM](https://user-images.githubusercontent.com/504541/177280331-cf69a305-b3e2-4955-bc4a-21671f01f85b.png)
