### ISSUE TITLE
Move `externalCall` APIs to query-builder from promql

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#1363]
The current `externalCall` page has 4 charts which needs to move from promQl to query-builder APIs. Below are the charts in that page

1. External Call Error Percentage
2. External Call duration
3. External Call RPS(by Address)
4. External Call duration(by Address)

**Comment by sf-pchakraborty** [comment]
I will take it up.

**Comment by ankitnayan** [comment]
> I will take it up.

Okay @sf-pchakraborty. I have assigned the issue to you.
