### ISSUE TITLE
Move the `overview` section apis at application detail page to query-builder from promql

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#1375]
The current overview section in the application detail page has 4 charts which need to move from promQL to query-builder APIs. Below are the charts on that page:

1. Application latency
2. Requests
3. Error Percentage
4. Top Endpoints

**Comment by sf-pchakraborty** [comment]
@ankitnayan Please assign this to me.

In the above Tab only 2 charts are coming from PromQl - Rate (ops/s) and Error Percentage.  The other two charts are from different apis. They needn't be changed.
@srikanthccv confirmed the same.

**Comment by ankitnayan** [comment]
@sf-pchakraborty we will change the other 2 APIs also. Move them from traces to metrics API. But to scope it down we can start with metrics API.

**Comment by sf-pchakraborty** [comment]
@ankitnayan Can you please create a separate issue for the rest of the 2 APIs and let's start a discussion reg that.

**Comment by ankitnayan** [comment]
@sf-pchakraborty I am thinking to modify it from the backend itself. This is the issue referring that https://github.com/SigNoz/signoz/issues/1793
