### ISSUE TITLE
Dashboard charts keep changing colors between refresh

### ISSUE THREAD

**Issue by RemyRanger** [SigNoz/signoz#1380]
## Bug description

Chart's colors keep changing between refreshes in my dashboard:
Refresh 1 : 
![image](https://user-images.githubusercontent.com/27485192/178508220-fa071e32-abc3-487d-a07a-8388deed2f3f.png)

Refresh 2 : 
![image](https://user-images.githubusercontent.com/27485192/178508330-0d78c8dd-c280-46a7-b3fa-509d19f71e39.png)

## Expected behavior

It would be better if colors and services order stop changing and follow a fixed order.
Better for looking at trends between 2 refresh.

## How to reproduce

1. Refresh any graph in dashboard page (refresh page or click on refresh button).

## Version information 
* **Signoz version**: v0.9.2
* **Browser version**: Chrome Version 103.0.5060.114 (Official Build) (64-bit)
* **Your OS and version**: Ubuntu 20.04.4 LTS
* **Your CPU Architecture**(ARM/Intel): Intel 64-bit

**Comment by pranay01** [comment]
thanks for opening the issue @RemyRanger

**Comment by makeavish** [comment]
This is fixed in latest version
