### ISSUE TITLE
Support legend in formulas 

### ISSUE THREAD

**Issue by pranshuchittora** [SigNoz/signoz#1383]
## Is your feature request related to a problem?
Currently, the formula field doesn't support the legend. 

## Describe the solution you'd like
Add support for legend in formula

**Comment by ankitnayan** [comment]
@pranshuchittora this would be needed to move the application overview metrics to query-builder from promql?

**Comment by pranshuchittora** [comment]
https://github.com/SigNoz/signoz/pull/1530
