### ISSUE TITLE
Show Timestamp from Events

### ISSUE THREAD

**Issue by Natrinicle** [SigNoz/signoz#1407]
## Is your feature request related to a problem?

Events show up in the correct order but don't display the timestamp when they occurred in the Tags/Events right side panel when a span is selected. I used Jaeger before and it was incredibly helpful to see the timestamp so you could add events without starting a whole new span and still get an idea of where your code is running slowly.

## Describe the solution you'd like

Add the event timestamp to the UI, perhaps opposite the event name in the same bar?

## Describe alternatives you've considered

Hovering over the event to see the timestamp would also work but would be less efficient to see at a glance. Could also add the timestamp as a footer if that looks better and to ensure it wouldn't interfere with the name if it's long.

## Additional context
[Span.add_event](https://opentelemetry-python.readthedocs.io/en/latest/_modules/opentelemetry/trace/span.html#Span.add_event)

#### *Thank you* for your feature request – we love each and every one!

**Comment by ankitnayan** [comment]
@Natrinicle that is true. 
@pranay01 we already have timestamp coming from the backend. We should include timestamp in the design and frontend should be able to display it.

**Comment by pranay01** [comment]
I think something like this would be useful

[Figma link](https://www.figma.com/file/lE5BDDuulXuGnqvB5GRk1V/SigNoz-OSS---v2-Designs?node-id=2274%3A35793&t=4qFMJYPkfSv04Noe-1)

![gantt-expanded-multiple-events](https://user-images.githubusercontent.com/504541/204463121-87c47b13-a8fb-446f-8bdd-17f783860f1e.png)

**Comment by palashgdev** [comment]
@ankitnayan in attributeMap we don't have multiple timestamp only one timestamp is available for one event probably design need to updated accordingly

**Comment by palashgdev** [comment]
@pranay01 i guess timestamp is not the right keyword maybe (time)?

also can we display the rest of the details in the info icon hover? seems details are going to the next line if we don't want ellipses of the text

<img width="316" alt="Screenshot 2022-12-01 at 3 57 23 PM" src="https://user-images.githubusercontent.com/88981777/205029284-12c71baf-b59f-4e0e-b7ac-0b74f27317a6.png">
