### ISSUE TITLE
Allow Tag/Event Panel to Be Resized

### ISSUE THREAD

**Issue by Natrinicle** [SigNoz/signoz#1408]
## Is your feature request related to a problem?

The Tag/Event panel is difficult to see the field values at times and requires copying the value out to something else in order to see.

## Describe the solution you'd like

It would be nice if the Tag/Event panel could be resized so slightly longer fields could be viewed directly in the window.

## Describe alternatives you've considered

Perhaps a popup window when the fields are clicked on similar to how the exception window can be popped up.

**Comment by palashgdev** [comment]
@pranay01 Can you please help me with the design here

**Comment by ankitnayan** [comment]
@Natrinicle Is this fixed with `v0.10.0` release? I think we open a modal to show the complete value of a tag if the size does not fit the current allocation. Can you please check?

**Comment by Natrinicle** [comment]
Yes, it looks like I can see the data. Nice solution, thanks!
