### ISSUE TITLE
Allow Horizontal Scrolling for Long Traces

### ISSUE THREAD

**Issue by Natrinicle** [SigNoz/signoz#1409]
## Is your feature request related to a problem?

Traces longer than ~20 seconds can run under the Tags/Events pane making them difficult to see where they fall in the waterfall view. The top flamegraph shows all the traces but if they're 20ms in a 20s trace you can't make them out up there. Scrolling down they end up running off the viewable window.

## Describe the solution you'd like

Allow for horizontal scrolling in the waterfall view in the center of the page for longer traces.

## Describe alternatives you've considered

Could potentially support resizing the trace spans to fit the width of the window but this could result in the same problem as with the flamegraph being too small?

**Comment by pranshuchittora** [comment]
@pranay01 can you pls initiate a PRD for the same and the design process too.

**Comment by makeavish** [comment]
This is available in latest SigNoz versions
