### ISSUE TITLE
Check for max value in latency to be greater than min value 

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#141]
## Is your feature request related to a problem?

Currently, trace filter page allows latency filter have max value to lower than min value. This will always give 0 traces as results

## Describe the solution you'd like
Give a warning when max value is less than min value, and don't allow latency filter to be applied. May be keep apply button in latency filter in disabled state

## Additional context
Attaching screenshot
![photo_2021-05-31 23 32 14](https://user-images.githubusercontent.com/504541/120228297-775e7b00-c268-11eb-9bc5-950966cae706.jpeg)

#### *Thank you* for your feature request – we love each and every one!

**Additional context**

**Comment by saideepesh000** [comment]
Hey @pranay01, can I take this up

**Comment by pranay01** [comment]
Awesome @saideepesh000 Let me know if you need any help. 

If the Max value is more than min value, the Appy button should be disabled and there should be a warning message above the line over cancel and apply buttons. This should say 'max value should be greater than min value' in warn colors. Will share a design if you need exact fonts etc.

**Comment by saideepesh000** [comment]
@pranay01 you can close this issue
