### ISSUE TITLE
Allow wrap limit of 2/3 lines in tags value in trace detail page

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1412]
## Is your feature request related to a problem?

Currently tag value fields starts showing `View full value` link if the value exceeds a single line. 

![Screenshot 2022-07-16 at 10 27 04 AM](https://user-images.githubusercontent.com/504541/179340128-c82421b2-8c14-4d1e-b89b-3ed225f5c42a.png)

## Describe the solution you'd like

Ideally it should show up to 2/3 lines as wrapped text before starting to show `View full value` link

**Comment by palashgdev** [comment]
fixed by #2035
