### ISSUE TITLE
Disable Registration

### ISSUE THREAD

**Issue by warent** [SigNoz/signoz#1417]
Is it possible to disable registration in the login page? If the page is exposed to the public web, it would be nice to deny people the ability to arbitrarily create accounts.

**Comment by pranay01** [comment]
@warent Only the admin who register for the first time can create an account. Other users need to get an invite from admin to create an account. For more details check here - https://signoz.io/docs/userguide/authentication/#roles

**Comment by pranay01** [comment]
hey @warent let me know if this issue is good to be closed or you have any questions on this

**Comment by warent** [comment]
It makes sense, thank you for your quick response! Just a gentle suggestion that the UX for this gets looked at again so it's clearer that it is secure. At minimum possibly just adding a setting in the admin panel to remove/hide "Create an account"

Anyway, loving Signoz for my business [fontpeek.com](https://fontpeek.com/). Thanks for your hard work!
