### ISSUE TITLE
In service map, speed of packet changes when changing from 1min time range to 5 min time range

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#142]
## Bug description

*Please describe.*  
If packet speed between nodes depends on RPS,  why does the speed of packet change when changing from 1min tim range to 5 min time range

## Expected behavior
The packed speed between nodes shouldn't depend on the time range chosen

## How to reproduce

1. Open SigNoz dashboard. Instrument a few services or run sample HotRod application
2. Go to service map tab. Default period is 1 min. Note packet speed
3. Change time period to 5 min from top right time range selector. The packet speed between nodes changes

## Additional context
Attaching loom video.
 https://www.loom.com/share/b01f0e8ed3624529ae93e86f55381d16

**Comment by makeavish** [comment]
This is fixed in latest version.
@pranay01 closing it.
