### ISSUE TITLE
Unable to Migrate v0.9.2 to v0.10.0

### ISSUE THREAD

**Issue by Natrinicle** [SigNoz/signoz#1424]
## Bug description

Getting the following segmentation violation when attempting to run Signoz upgrade

```
kubectl --namespace observability run -i -t signoz-migrate --image=signoz/migrate:0.10 -- -host=dev-clickhouse -port=9000 -userName=admin -password=27ff0399-0d3a-4bd8-919d-17c2181e6fb9
```

```
No TTL found, skipping TTL migration
There are total 343055873 rows, starting migration...

Processing 343055873 rows of serviceName bbhoarde-staging
Writing 88177 rows
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5e6fdd]

goroutine 1 [running]:
github.com/ClickHouse/clickhouse-go/v2.(*batch).Append(0xc000d0a1e0, {0xc00009a280, 0xc000098000, 0xc0000209c0})
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.12/conn_batch.go:90 +0x1d
main.writeErrorIndexV2({0x6e17a8, 0xc0000c66c0}, {0xc005e38000, 0x15871, 0xc000cefca8})
	/go/src/github.com/signoz/migrate/main.go:156 +0x39f
main.write({0x6e17a8, 0xc0000c66c0}, {0xc005e38000, 0x10, 0x15b00})
	/go/src/github.com/signoz/migrate/main.go:148 +0xa6
main.main()
	/go/src/github.com/signoz/migrate/main.go:309 +0xd35
```

Not sure if this is related to the number of rows in my database? Migrate appears to have worked on another cluster configured the same way but with no data in it.

## Expected behavior

Upgrade to complete successfully

## How to reproduce

1. Run command as specified in upgrade document as well as above.

## Version information 
* **Signoz version**: v0.9.2 -> v0.10.0
* **Browser version**: N/A
* **Your OS and version**: Debian Linux Bookworm (Local), Amazon Linux (Kubernetes Node)
* **Your CPU Architecture**(ARM/Intel):  x86_64

**Comment by pranay01** [comment]
@Natrinicle Just checking if this issue was solved or you are still facing this issue
 cc: @makeavish

**Comment by Natrinicle** [comment]
> @Natrinicle Just checking if this issue was solved or you are still facing this issue cc: @makeavish

This is still running the debug version of the migration script that @makeavish provided me. We managed to get a single error message from it that indicated Clickhouse required more RAM.

```
_________**********************************_________
2022-07-21T14:29:54.920Z	FATAL	migrate/main.go:314	code: 241, message: Memory limit (total) exceeded: would use 6.30 GiB (attempt to allocate chunk of 4509085 bytes), maximum: 6.30 GiB: (while reading column traceID): (while reading from part /var/lib/clickhouse/disks/s3/data/signoz_traces/signoz_error_index/20220719_150922_161956_13_153896/ from mark 329 with max_rows_to_read = 8192): While executing MergeTreeInOrdererror while reading spans
main.main
	/go/src/github.com/signoz/migrate/main.go:314
runtime.main
	/usr/local/go/src/runtime/proc.go:255
Session ended, resume using 'kubectl attach signoz-migrate -c signoz-migrate -i -t' command when the pod is running
```

After increasing the RAM and restarting Clickhouse, the migration script started again and ran Clickhouse out of HDD space after a couple of days. I increased the HDD space and am running the migration script again but I had to start from the beginning as I wasn't sure where it left off when the space issue occurred.

**Comment by Natrinicle** [comment]
@makeavish provided the new migration script image but upon running it, it appears that the retention period was hit and the exceptions expired so this is no longer an issue. It appears that I was likely unable to run the migration because of limited resources on the Clickhouse database pod just in case anyone else hits similar things in the future. Thanks for adding that batchSize argument to the migration script though just in case it's necessary in the future!
