### ISSUE TITLE
Create alerts for `value` type queries

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#1449]
Currently, a user cannot create alerts on `value` type queries. This issue is to enable creating such alerts.

**Comment by mindhash** [comment]
@pranay01 This refers to comparing the threshold with the value from the latest sample in the selected timeframe.  Something similar to what we have in REDUCE TO option of metrics builder. 

I am thinking we can include this verbiage `in the last sample` in the rule condition (below).  but there may be a better way to handle this. 

![image](https://user-images.githubusercontent.com/10277894/181487157-6de888bd-76d3-475c-93a7-02169ac9d580.png)

**Comment by pranay01** [comment]
- How will user select that they are trying to create alert for a time series or value type. In dashboard there is a way to select timeseries or value first before using query builder

**Comment by mindhash** [comment]
Discussion between Pranay and Amol:

- Alerts on `Value` type may not be the right way to go as they would result in occasion spikes and  reduce quality of alerting.  Unless a specific use case shows up in the future, we can recommend users to go with `at least once` in 5 mins (timeframe) option which gets closer to value type. 
- This issue will not go into Thursday Release cycle 
- Amol to explore Panel - Alert integration in grafana

@pranay01 please share if I missed anything

**Comment by mindhash** [comment]
Closing this issue for now, as we will not support this immediately unless a good use case comes up
