### ISSUE TITLE
Provide helm chart used to install SigNoz in the repo

### ISSUE THREAD

**Issue by samnano** [SigNoz/signoz#1452]
## Is your feature request related to a problem?

we have a k8 cluster and we would like to be able to edit the templates/manifests files easily to suit our needs

## Describe the solution you'd like

it will be better if you can provide us manifest files for the helm chart or a kustomization manifest file in deploy directory in the Repo

**Comment by prashant-shahi** [comment]
@samnano we have our helm charts in `signoz/charts` repository: https://github.com/SigNoz/charts

**Comment by samnano** [comment]
Thank you @prashant-shahi
