### ISSUE TITLE
Add to Service Map via Span Tags

### ISSUE THREAD

**Issue by Natrinicle** [SigNoz/signoz#1454]
## Is your feature request related to a problem?

The service map feature currently requires that every system shown talking to each other must be sending in traces/spans to the OpenTelemetry collector but some systems either don't have an integration or would take time and effort to integrate.

## Describe the solution you'd like

Use the db.system and net.peer.name to identify system communication and map it in the service map. Similarly, this could be used with http.url and http.method for mapping HTTP requests to remote systems that might not be under the control of the user running SigNoz.

## Describe alternatives you've considered

N/A

## Additional context

The docker-compose example uses Jaeger's Hotrod which appears to create a fake Redis & MySQL that send in traces/spans which causes them to show up when using the example stack and app in the service map. It appears that real Redis, MySQL, and PostgreSQL only have the capability to have metrics collected but not traces/spans. All these services are unable to send in traces/spans unless their source code is changed at some point in the future making the service map only show connections between traced services and the fake Redis/MySQL in Hotrod.

https://github.com/jaegertracing/jaeger/blob/a5974e10da0901ceddb882b1bb65bd5e92d41bf0/examples/hotrod/services/driver/redis.go#L38
https://github.com/jaegertracing/jaeger/blob/a5974e10da0901ceddb882b1bb65bd5e92d41bf0/examples/hotrod/services/customer/database.go#L34

#### *Thank you* for your feature request – we love each and every one!

**Comment by ankitnayan** [comment]
@Natrinicle many users have requested this feature and we have decided to work on this. Not just dbs but also messaging systems could be part of the service map in upcoming releases of SigNoz. We will keep you posted.

**Comment by makeavish** [comment]
Closing this as it was shipped as part of [v0.10.1](https://github.com/SigNoz/signoz/releases/tag/v0.10.1)
