### ISSUE TITLE
Typo In Docs

### ISSUE THREAD

**Issue by saideepesh000** [SigNoz/signoz#146]
## Bug description

Typo in docs:
![image](https://user-images.githubusercontent.com/43727167/120493559-b01d6200-c3d8-11eb-83fa-893a4accd8c0.png)
 

## Expected behavior
I think it should be `OpenTelemetry`

Where is the repo for docs ?

**Comment by pranay01** [comment]
Hey @saideepesh000 Docs repo is not yet public. We plan to make it public soon.

Meanwhile I will fix this type

**Comment by pranay01** [comment]
this is fixed now
