### ISSUE TITLE
Alerts query-builder support for `absent`

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/signoz#1463]
Not able to replicate equivalent of the following:

```
absent(up{host_name="my-machine-hostname",job="otel-collector"})
```

The above query helps to figure out if any of the agents are down:
- `1` when the agent is up
- no values are returned when the agent is down

cc @mindhash

**Comment by srikanthccv** [comment]
@pranay01 One way we could do this is to give a checkbox option to select whether to send an absent alert when data is missing. Please let us know what you think.

**Comment by pranay01** [comment]
@srikanthccv How do products like Grafana handle this issue
