### ISSUE TITLE
Use prepared statement for DB calls that use args.

### ISSUE THREAD

**Issue by jshiwam** [SigNoz/signoz#1464]
(conitnuation of Issue #[1353](https://github.com/SigNoz/signoz/issues/1353))
Use Prepared Statements in [GetService ](https://github.com/SigNoz/signoz/blob/develop/pkg/query-service/app/clickhouseReader/reader.go#L660)

**Comment by srikanthccv** [comment]
@jshiwam that will be addressed as a part of https://github.com/SigNoz/signoz/pull/1455. So, I am going to close this issue and re-open the original issue. Please a new comment with sub-items in #1353 and when you open a PR, use the description `Part of #Issue` instead of `Fixes #Issue` or link it.
