### ISSUE TITLE
Add tags to trace filter page on click on any tag in trace detail page

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#1476]
SigNoz shows a list of tags in the trace detail page. It would be useful to give an option to add a tag to search filter for spans in trace filter page. This would help users in investigating a tag and see latencies and errors of the spans with that tag in trace filter page

**Comment by makeavish** [comment]
Closing in favor of https://github.com/SigNoz/signoz/issues/2172 (2nd point in above issue's description)
