### ISSUE TITLE
APDEX score support 

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1477]
## Is your feature request related to a problem?

Many New Relic users are used to seeing an APDEX score for the health of their services. We have had feedback from some users asking for supporting it

## Describe the solution you'd like

Support APDEX scores in SigNoz or some similar measure. We have to understand what extra information does an APDEX score provide which is not included in current SigNoz dashboards.

https://docs.newrelic.com/docs/apm/new-relic-apm/apdex/apdex-measure-user-satisfaction/

Also, not sure if the word 'APDEX' can be used as this may be a NewRelic trademark word

**Comment by srikanthccv** [comment]
We have chosen 500ms as a default threshold. A user with editor/admin access can update it to a sensible value for each service, which will persist in DB. An endpoint will be added to fetch and set the setting for the threshold.

Following the same approach as other graphs, the implementation will allow users to switch between traces or span metrics for the score calculation and uses the `v3/query_range`. The content of the payload is dependent on the data source and settings. It is certainly possible that the user sets a threshold `t`, which doesn't have the exact bucket boundary `le` for the satisfied count or the bucket boundary `le` = `4t` for tolerating count. We will use the nearest upper boundary `le` in such cases.

**Comment by srikanthccv** [comment]
Postman collection here https://signoz.postman.co/workspace/Team-Workspace~cfa5c7b5-124f-4bbc-88d9-2351af8dd95b/collection/21397560-42ea3640-244b-4399-93d7-ba2933c290eb?action=share&creator=21397560

**Comment by srikanthccv** [comment]
@Rajat-Dabade, This is very unlikely but when the upper bound for the threshold doesn't exist in the `le` array, use `+Inf`.
