### ISSUE TITLE
Design for filtering traces by `traceID`

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#1490]

**Comment by pranay01** [comment]
@ankitnayan  Is there any more details on this issue? 
I was checking jaeger UI for this and it had just one box to add trace id, after which it opens the trace detail page.
Can't users do the same thing today by going to trace detail page and changing the traceid?
Should we add this capability in filtering page or traceID page? Is there a use case for seeing all spans in a trace ( for a given traceID)?
