### ISSUE TITLE
Frontend Perf Improvement for trace detail page to load > 10K spans

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#1493]
Currently, the trace detail page loads somewhere between 5K to 10K spans and the browser tab OOMs for more spans. The frontend handles creating multiple trees and subtrees from the backend response. This issue is to optimise the performance of the trace detail page and test how many spans can be loaded on the trace detail page after improvisations.

**Comment by makeavish** [comment]
@ankitnayan Closing it as we are shipping hierarchical view for large traces in the enterprise version (v0.11.4), which handles large traces.
