### ISSUE TITLE
Support for ARM machines

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1498]
Currently SigNoz doesn't run on ARM machines provided by cloud providers like AWS, Azure, etc. It does run on M1 ARM machines  provided by Apple though.

Some users are interested in using ARM machines as they are 30-35% cheaper than AMD/Intel machines for the same specs.

It would be great if SigNoz can run on ARM machines. It will be more cost effective for users

e.g. 
a1.4xlarge    is 0.408  USD/hr for 16 vCPU| 32 GB RAM
c7g.4xlarge is 0.5781 USD/hr for 16 vCPU| 32 GB RAM

which is ~30% more cost effective

![Screenshot 2022-08-10 at 3 48 36 PM](https://user-images.githubusercontent.com/504541/183877734-45ddbc44-bbdf-4323-b779-3bd97dbc9d21.png)

**Comment by zidhuss** [comment]
Does the arm docker compose file still exist?

https://github.com/SigNoz/signoz/blob/46e131698eb8f49b41a172573a3e29854604617d/deploy/README.md?plain=1#L30-L34

https://github.com/SigNoz/signoz/blob/46e131698eb8f49b41a172573a3e29854604617d/CONTRIBUTING.md?plain=1#L247-L249

**Comment by pranay01** [comment]
Thanks for pointing @zidhuss I think we moved away from arch based docker files

@prashant-shahi can you updated the README and contributing.md?

**Comment by prashant-shahi** [comment]
ARM is already supported by SigNoz.

**Comment by anthonypillot** [comment]
Hello @prashant-shahi ,
According to what I read in the [self-hosted Kubernetes documentation](https://signoz.io/docs/install/kubernetes/others/#prerequisites), it states that “x86-64/amd64 workloads are currently supported, as the arm64 architecture is not”. Are these details up-to-date?

**Comment by prashant-shahi** [comment]
> Hello [@prashant-shahi](https://github.com/prashant-shahi) , According to what I read in the [self-hosted Kubernetes documentation](https://signoz.io/docs/install/kubernetes/others/#prerequisites), it states that “x86-64/amd64 workloads are currently supported, as the arm64 architecture is not”. Are these details up-to-date?

Oh, nice catch! Looks like they are not up-to-date.

Thank you for reporting this. We will get this resolved ASAP.

**Comment by prashant-shahi** [comment]
@anthonypillot Thank you for your PR contribution 🎉
