### ISSUE TITLE
Service map zooms out on selecting specific service

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#151]
## Bug description

On Macbook Air 13", connected to Dell Monitor in mirror mode, service maps zooms out to a point on selecting a specific service

*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior
The selected service node should come to the center on selecting a service, the whole service map shouldn't zoom out

## How to reproduce

1. Open SigNoz dashboard
2. Instrument with few services or run the default hot rod application
3. Go to Service map tab
4. Select a particular service from dropdown
5. The whole service map zooms out to a point

## Additional context
Attached video

https://user-images.githubusercontent.com/504541/120809925-3320f280-c568-11eb-95ea-c999612c4173.mp4

**Comment by ankitnayan** [comment]
@nidhi-tandon @jyash97 @anweshknayak @saideepesh000 Do you guys see any issues there? I have pro and I cannot replicate. Also, I guess the zoom level is set based on screen size. This part can be improved I hope https://github.com/SigNoz/signoz/blob/main/frontend/src/modules/Servicemap/utils.ts#L77

**Comment by anweshknayak** [comment]
@ankitnayan @pranay01 tested with the latest pull. not able to replicate.

Device/OS : `Macbook Air 13" macOS Mojave v10.14`

But at times I have faced the zoom out issue. I don't remember the exact steps which led to it.

**Comment by jyash97** [comment]
I am able to replicate this issue, it happens because of the screen size. Try updating the resolution maybe. The linked PR seems to fix the issue.

**Comment by nidhi-tandon** [comment]
Tracking it here as well https://github.com/vasturiano/react-force-graph/issues/296

**Comment by nidhi-tandon** [comment]
@jyash97 [This](https://github.com/SigNoz/signoz/pull/154) PR didn't work out on @ankitnayan laptop. Ankit and I have the same laptop and it's not working for him. 
Created an issue on the [react-force-graph](https://github.com/vasturiano/react-force-graph/issues/296)  github.

**Comment by jyash97** [comment]
I am on macOS Big Sur and the chrome version is `91.0.4472.77` and after trying the PR with `320px` and `330px` it works for me.

**Comment by ankitnayan** [comment]
I think we should merge the PR if it's only specific to my laptop and close the issue. If anybody finds the same problem, we can re-open this issue.

**Comment by pranay01** [comment]
@ankitnayan Shall we close this issue as the fix is merged in the latest release? https://github.com/SigNoz/signoz/pull/170
