### ISSUE TITLE
Need an option to save charts

### ISSUE THREAD

**Issue by upeshphable** [SigNoz/signoz#1510]
## Is your feature request related to a problem?

As a user, I have to come back to dashboard to look at data periodically but I lose the charts with filtered operations.

## Describe the solution you'd like

Ability to save the filter/charts so that I can come back later and just open them up.

## Describe alternatives you've considered

None

#### *Thank you* for your feature request – we love each and every one!

**Comment by makeavish** [comment]
This is available with new trace explorer page in v0.23.0 release.
