### ISSUE TITLE
Hot ROD application services not getting removed my list of services

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#1522]
Hey Folks 👋

I have removed the hot rod application containers from the `docker-compose` file but it's not getting removed from my dashboard in the list of applications. The containers were removed a day before, but even when selecting the time filter for `last 5 mins` it shows up.

<img width="1246" alt="Screenshot 2022-08-17 at 11 28 36 AM" src="https://user-images.githubusercontent.com/83692067/185046006-bbe45a41-479c-43b8-baf1-4a7a646b1776.png">

Screenshot of my docker-compose file

<img width="966" alt="Screenshot 2022-08-17 at 11 32 59 AM" src="https://user-images.githubusercontent.com/83692067/185045928-038765fa-5b6e-436b-a766-12d78f7a8939.png">
778-4a08-96b1-5e19072940e2.png">

**Comment by pranay01** [comment]
@ankit01-oss can you share what does your `docker ps` show?

**Comment by prashant-shahi** [comment]
@ankit01-oss it is likely that hotrod containers are still running. You could either manually delete them or run docker-compose command with `--remove-orphans` flag.

**Comment by ankit01-oss** [comment]
@pranay01 here. The hotrod containers are not running.

<img width="1439" alt="Screenshot 2022-08-17 at 1 25 28 PM" src="https://user-images.githubusercontent.com/83692067/185065292-b1a57ca6-8b19-4af1-948a-96faf3eb773c.png">

@prashant-shahi I used `--remove-orphans` to run the docker compose command. Sharing a screenshot for reference 👇

<img width="865" alt="Screenshot 2022-08-17 at 1 25 54 PM" src="https://user-images.githubusercontent.com/83692067/185065684-1c82357f-231d-446b-bca2-ff111bf77578.png">

**Comment by ankit01-oss** [comment]
I just instrumented a sample nestjs application. I think ideally services not reporting data in a time range should not appear in the `application` list, right @pranay01 ? But other services are still showing in the list, including a nodejs app that I instrumented hours ago. Though, all the data shown is `0`.

<img width="1236" alt="Screenshot 2022-08-17 at 1 28 30 PM" src="https://user-images.githubusercontent.com/83692067/185066110-f643ce07-e534-41a6-9ad8-2795d2a2f56d.png">

**Comment by ankit01-oss** [comment]
@ankitnayan the below PR should fix this, right? If yes, feel free to close this issue.

 https://github.com/SigNoz/signoz/pull/1521

**Comment by ankitnayan** [comment]
yes...though @srikanthccv would be the right person to answer that

**Comment by srikanthccv** [comment]
@ankit01-oss yes, this is fixed by #1521
