### ISSUE TITLE
Not able to set traces retention when s3 cold storage is enabled

### ISSUE THREAD

**Issue by vkperumal** [SigNoz/signoz#1523]
## Bug description

When traces retention is set on the application it gets reverted back to 3 days.

![image](https://user-images.githubusercontent.com/35548944/185053420-bcbbd8b3-8583-432d-92b9-df15eca59032.png)

## Expected behavior
Traces Retention period should be set

## How to reproduce

1.set traces retention to 7 days and move to s3 to 4 days
2. Go to another section like usage explorer
3. go to settings page and you can see settings reverted

## Version information 
* **Signoz version**: 0.10.2
* **Your OS and version**: Amazon Linux 2
* **Your CPU Architecture**(ARM/Intel): Intel

**Comment by makeavish** [comment]
Closing as the issue was not reproducible and was resolved after clickhouse container resources were increased.
