### ISSUE TITLE
Refresh Button disappears for when custom filter is applied

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#1524]
Please refer to the video for the issue

https://www.loom.com/share/e317482111eb44d5b3b6cb267b2ed50f

**Comment by pranshuchittora** [comment]
https://user-images.githubusercontent.com/32242596/186618203-ac6cbf21-7111-480a-81aa-fa5d6867e075.mov

**Comment by fahad-frontend** [comment]
Working on this

**Comment by sf-pchakraborty** [comment]
Had a look into this issue, looks like the moment we select custom  from date range, the refresh button is disabled.

**Comment by ankitnayan** [comment]
@pranay01 is this supposed to be like this as choosing a custom time range will not change past data and hence hitting refresh won't pull the latest data and hence the chart remains the same?

**Comment by vg18gupta** [comment]
@pranay01 have the team started working on this?
If no, I you can assign this to me

**Comment by ankit01-oss** [comment]
@ankitnayan yes, that is applicable for just custom time range. But if we go back to `Last 5 min`, the `refresh` button should come up.

And as @pranshuchittora mentioned, the refresh button also reappears when the page is refreshed.

**Comment by pranay01** [comment]
Not showing Refresh button when custom data range is selected is correct. But when the time is changed to `Last 5 min` or something like that, then refresh button should appear

> @pranay01 is this supposed to be like this as choosing a custom time range will not change past data and hence hitting refresh won't pull the latest data and hence the chart remains the same?

**Comment by ankitnayan** [comment]
@fahad-frontend are you working on this or @vg18gupta can pick this up

**Comment by pranay01** [comment]
related https://github.com/SigNoz/signoz/issues/664

**Comment by pranay01** [comment]
@vg18gupta assigning to you since we have not received any response form @fahad-frontend

**Comment by vg18gupta** [comment]
@ankit01-oss @pranay01  looks like the refresh button is intentionally hidden for the custom date range.
Also not able to raise PR, can someone help me here?

**Comment by sf-pchakraborty** [comment]
@vg18gupta What you said is correct. But when you try to flip back to 'Last 5 min' or something like that the 'Refresh' button should re-appear right? that's not happening right now.

For this to replicated you need to select custom date range first and then flip back to pre-defined ranges.

**Comment by vg18gupta** [comment]
@sf-pchakraborty I have raised a [PR](https://github.com/SigNoz/signoz/pull/1582), seems like there is another issue in here. Once a custom date is selected and then if we refresh the page the hidden state of the refresh button is not persisted

**Comment by palashgdev** [comment]
Closed via: https://github.com/SigNoz/signoz/pull/1582
