### ISSUE TITLE
Suggest users about missing spans when spans are missing in trace detail

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#1526]

**Comment by pts95** [comment]
Is this about detecting breaks in context propagation (i.e. when child contexts are not created properly / there is a mismatch between different components)? If not, what are some of the other ways in which you are detecting missing spans?

**Comment by LasseRafn** [comment]
I think this can be closed 😅

**Comment by makeavish** [comment]
Can be closed as we are detecting missing spans now

**Comment by ManzerHa-Kore** [comment]
Hi, @makeavish is the problem solved? Can you suggest me some solution for missing spans in trace detail for AWS lambda in express app

**Comment by makeavish** [comment]
> Hi, @makeavish is the problem solved? Can you suggest me some solution for missing spans in trace detail for AWS lambda in express app

You might need to follow this: https://dalejsalter.com/post/8afd46ad-7da2-4b2a-9cb5-9e5ae4fe6cc2/cdk-lambda-otel-honeycomb

`AWS has native XRay integration with Lambda. This means that when your function gets invoked, it has X-Ray information from the Lambda service that is passed into it. This means that when we work with OTEL, it will already have a parent span (the lambda service). The problem is that span will not go to SigNoz, and SigNoz will think there is a missing span. To fix this issue we just say that our first span is our root span.

To fix this we need both of these options:

File: lib/hello-world.ts

tracing: lambda.Tracing.PASS_THROUGH
File: lib/hello-world.function.ts

tracer.startActiveSpan('handler', { root: true }, async (span: any) => {
   // your code here
}
`
