### ISSUE TITLE
Improve experience of running SigNoz from source for contributors

### ISSUE THREAD

**Issue by pts95** [SigNoz/signoz#1529]
I tried to setup SigNoz for the first time following CONTRIBUTING.md - and it took me 30 minutes to get it running end-to-end. For context, I am developing on a Mac M1. Most of these changes are done to existing files in master - which are not supposed to be committed. I think we can reduce the time to run SigNoz from source.

## Describe the solution you'd like

We can either write a script for local start from source or can split the existing docker-compose file into separate pieces according to envs - so we can just start the same file accordingly. That way we can just use one makefile step, and get SigNoz running from source easily.

**Comment by pranay01** [comment]
Closing issue as #1528 was merged
