### ISSUE TITLE
Retain Filter Traces values after checking out TraceID and coming back to Traces section

### ISSUE THREAD

**Issue by muddlebee** [SigNoz/signoz#153]
## Bug description

Retain Filter Traces values in dropdown after checking out TraceID and coming back to Traces section

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  
![chrome-capture](https://user-images.githubusercontent.com/8139783/120881677-7aeb5c80-c5f0-11eb-8ddb-5773465b9e9b.gif)

## Expected behavior
Last filled values should be there after coming back to traces section

![Screenshot 2021-06-05 at 11 24 52 AM](https://user-images.githubusercontent.com/8139783/120881714-d3baf500-c5f0-11eb-8b36-ec3d3d408ee6.png)

## How to reproduce

1. Select two options in Filter Traces section. 
2. Goto `List of traces with spanID` and click on any TraceID. It will lead to a new screen for span details.
3. Navigate back to Traces section 

![Screenshot 2021-06-05 at 11 29 25 AM](https://user-images.githubusercontent.com/8139783/120881806-5d6ac280-c5f1-11eb-865b-368f01d8ff72.png)

## Version information 
* **Signoz version**: v0.2.2
* **Browser version**: Chrome v90
* **Your OS and version**: MacOS Mojave v10

**Comment by anweshknayak** [comment]
@ankitnayan @pranay01 I hope this is a valid scenario.

**Comment by pranay01** [comment]
@anweshknayak Yes this is a valid scenario.  The filter values should be preserved in going to trace detail page and back

**Comment by pranay01** [comment]
This is fixed not with new trace filter design in https://github.com/SigNoz/signoz/releases/tag/v0.6.0
