### ISSUE TITLE
Create docs on how to run otel collectors in VMs and send data from them to SigNoz otel collector

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1531]
Based on a conversation in slack community

https://signoz-community.slack.com/archives/C01HWUTP4HH/p1661239521408789

![Screenshot 2022-08-23 at 1 21 26 PM](https://user-images.githubusercontent.com/504541/186103113-431fd8ad-57f9-406a-97e2-194616e93ab2.png)

**Comment by ankitnayan** [comment]
https://signoz.io/docs/tutorial/opentelemetry-binary-usage-in-virtual-machine/
