### ISSUE TITLE
Logs filtering custom fields 

### ISSUE THREAD

**Issue by rrangerCDV** [SigNoz/signoz#1547]
## Bug description

I can't filter my logs by custom traceId field. My logs can contains traceId / spanId and some times not, so the parsing step to copy fields is not working properly. I'm using filelogs on 2 VMs with otel-collector docker.

ex 1:
`"{\"level\":\"info\",\"service\":\"Router\",\"time\":1662023186,\"message\":\"[back-front-2] \\\"GET https://web.fr/realestate/v2/developers HTTP/2.0\\\" from XXX - 200 26482B in 40.529079ms\"}"`

ex 2:
`"{\"level\":\"info\",\"service\":\"developers\",\"traceId\":\"ff4c9698b1fb1ac2eb590ac8cb3a7f9b\",\"spanId\":\"f57445fc97c67fb7\",\"time\":1662023186,\"message\":\"Developers list fetched.\"}"`

## Expected behavior

![image](https://user-images.githubusercontent.com/95221433/187913257-1f042fe0-8f07-47d7-8ba5-6878d25a5ddd.png)

## How to reproduce

1. produce logs with traceId and without
2. parse only body logs
3. see (front) traceId custom field and try to filter on

## Version information 
* **Signoz version**: v011.0
* **Browser version**: chrome Version 104.0.5112.101 (Official Build) (64-bit)
* **Your OS and version**: ubuntu
* **Your CPU Architecture**(ARM/Intel): 64amd

**Comment by nityanandagohain** [comment]
Can you please share the logs of query-service when you run this query. Will help us debug the issue.

**Comment by rrangerCDV** [comment]
`2022-09-02T08:06:42.297Z	INFO	app/server.go:312	Starting HTTP server{port 11 8080  <nil>} {addr 15 0 0.0.0.0:8080 <nil>}
2022-09-02T08:06:42.297Z	INFO	app/server.go:324	Starting pprof server{addr 15 0 0.0.0.0:6060 <nil>}
2022-09-02T08:06:42.297Z	INFO	app/server.go:338	Starting Private HTTP server{port 11 8085  <nil>} {addr 15 0 0.0.0.0:8085 <nil>}
starting private http
2022-09-02T08:06:46.558Z	INFO	rules/promRuleTask.go:314	promql rule task:5-groupname	 eval started at:2022-09-02 08:06:46.558424655 +0000 UTC
2022-09-02T08:06:46.558Z	INFO	rules/promRule.go:308	rule:PROGRAM Latency > 1s for 2m	 evaluating promql query: sum(rate(signoz_latency_sum{service_name="service-program"}[2m]))/sum(rate(signoz_latency_count{service_name="service-program"}[2m])) > 1000
time="2022-09-02T08:06:46Z" level=warning msg="Ignoring hint {StepMs:0 Func:rate StartMs:1662105886558 EndMs:1662106006558} for query [1662105886558,1662106006558,{service_name=\"service-program\",__name__=\"signoz_latency_sum\"}]." component=clickhouse
time="2022-09-02T08:06:46Z" level=warning msg="Ignoring hint {StepMs:0 Func:rate StartMs:1662105886558 EndMs:1662106006558} for query [1662105886558,1662106006558,{service_name=\"service-program\",__name__=\"signoz_latency_count\"}]." component=clickhouse
2022-09-02T08:06:54.925Z	INFO	rules/promRuleTask.go:314	promql rule task:2-groupname	 eval started at:2022-09-02 08:06:54.925229434 +0000 UTC
2022-09-02T08:06:54.925Z	INFO	rules/promRule.go:308	rule:ESTIMATE Latency > 5s for 2m	 evaluating promql query: sum(rate(signoz_latency_sum{service_name="service-estimate"}[2m]))/sum(rate(signoz_latency_count{service_name="service-estimate"}[2m])) > 5000
time="2022-09-02T08:06:54Z" level=warning msg="Ignoring hint {StepMs:0 Func:rate StartMs:1662105894925 EndMs:1662106014925} for query [1662105894925,1662106014925,{service_name=\"service-estimate\",__name__=\"signoz_latency_sum\"}]." component=clickhouse
time="2022-09-02T08:06:54Z" level=warning msg="Ignoring hint {StepMs:0 Func:rate StartMs:1662105894925 EndMs:1662106014925} for query [1662105894925,1662106014925,{service_name=\"service-estimate\",__name__=\"signoz_latency_count\"}]." component=clickhouse
2022-09-02T08:06:55.390Z	INFO	app/server.go:189	/api/v1/logs/aggregate	timeTaken: 15.164603ms
2022-09-02T08:06:55.390Z	INFO	app/server.go:189	/api/v1/logs	timeTaken: 11.705714ms
`

**Comment by rrangerCDV** [comment]
I hope it will help you :)

> 2022-09-02T08:06:42.297Z	INFO	app/server.go:312	Starting HTTP server{port 11 8080  <nil>} {addr 15 0 0.0.0.0:8080 <nil>}
> 2022-09-02T08:06:42.297Z	INFO	app/server.go:324	Starting pprof server{addr 15 0 0.0.0.0:6060 <nil>}
> 2022-09-02T08:06:42.297Z	INFO	app/server.go:338	Starting Private HTTP server{port 11 8085  <nil>} {addr 15 0 0.0.0.0:8085 <nil>}
> starting private http
> 2022-09-02T08:06:46.558Z	INFO	rules/promRuleTask.go:314	promql rule task:5-groupname	 eval started at:2022-09-02 08:06:46.558424655 +0000 UTC
> 2022-09-02T08:06:46.558Z	INFO	rules/promRule.go:308	rule:PROGRAM Latency > 1s for 2m	 evaluating promql query: sum(rate(signoz_latency_sum{service_name="service-program"}[2m]))/sum(rate(signoz_latency_count{service_name="service-program"}[2m])) > 1000
> time="2022-09-02T08:06:46Z" level=warning msg="Ignoring hint {StepMs:0 Func:rate StartMs:1662105886558 EndMs:1662106006558} for query [1662105886558,1662106006558,{service_name=\"service-program\",__name__=\"signoz_latency_sum\"}]." component=clickhouse
> time="2022-09-02T08:06:46Z" level=warning msg="Ignoring hint {StepMs:0 Func:rate StartMs:1662105886558 EndMs:1662106006558} for query [1662105886558,1662106006558,{service_name=\"service-program\",__name__=\"signoz_latency_count\"}]." component=clickhouse
> 2022-09-02T08:06:54.925Z	INFO	rules/promRuleTask.go:314	promql rule task:2-groupname	 eval started at:2022-09-02 08:06:54.925229434 +0000 UTC
> 2022-09-02T08:06:54.925Z	INFO	rules/promRule.go:308	rule:ESTIMATE Latency > 5s for 2m	 evaluating promql query: sum(rate(signoz_latency_sum{service_name="service-estimate"}[2m]))/sum(rate(signoz_latency_count{service_name="service-estimate"}[2m])) > 5000
> time="2022-09-02T08:06:54Z" level=warning msg="Ignoring hint {StepMs:0 Func:rate StartMs:1662105894925 EndMs:1662106014925} for query [1662105894925,1662106014925,{service_name=\"service-estimate\",__name__=\"signoz_latency_sum\"}]." component=clickhouse
> time="2022-09-02T08:06:54Z" level=warning msg="Ignoring hint {StepMs:0 Func:rate StartMs:1662105894925 EndMs:1662106014925} for query [1662105894925,1662106014925,{service_name=\"service-estimate\",__name__=\"signoz_latency_count\"}]." component=clickhouse
> 2022-09-02T08:06:55.390Z	INFO	app/server.go:189	/api/v1/logs/aggregate	timeTaken: 15.164603ms
> 2022-09-02T08:06:55.390Z	INFO	app/server.go:189	/api/v1/logs	timeTaken: 11.705714ms

**Comment by nityanandagohain** [comment]
You should get a debug statement like this when you run the query on the UI.


![image](https://user-images.githubusercontent.com/26831659/188097844-cb26fc92-d46f-41e8-97d9-ee206a00db64.png)

Can you share that.


Also can you exec into your clickhouse container and run the following commands and share the output.

```
show create table signoz_logs.logs;
```

**Comment by rrangerCDV** [comment]
![image](https://user-images.githubusercontent.com/95221433/188101232-38e7eead-9f45-4710-beaa-c1e7898c9374.png)

**Comment by nityanandagohain** [comment]
Will it be possible for you to share the source logs that you are ingesting along with the otel-collector-config as it will be easier to replicate on my side?

**Comment by gzsombor** [comment]
I think, I have the same problem. For me, filtering for `logback_mdc_uri IN ('/api/parts') ` works, I get correct result - and in the logs, I can see:

```
2022-10-27T18:06:13.917Z        DEBUG   clickhouseReader/reader.go:3140 SELECT timestamp, id, trace_id, span_id, trace_flags, severity_text, severity_number, body,CAST((attributes_string_key, attributes_string_value), 'Map(String, String)') as  attributes_string,CAST((attributes_int64_key, attributes_int64_value), 'Map(String, Int64)') as  attributes_int64,CAST((attributes_float64_key, attributes_float64_value), 'Map(String, Float64)') as  attributes_float64,CAST((resources_string_key, resources_string_value), 'Map(String, String)') as resources_string  from signoz_logs.logs where timestamp >= '1667045173734000000' and timestamp <= '1667066773734000000' and attributes_string_value[indexOf(attributes_string_key, 'logback_mdc_uri')] IN ('/api/parts')  order by timestamp desc limit 25
```

However, when I try to use `logback_mdc_uri IN ('/api/parts')  AND logback_mdc_userId IN ('5')`, I dont get anything back, in the docker logs, there is nothing shown up, and in the browser's network tab I can see that I get a 400 for this request:
```http://localhost:3301/api/v1/logs?q=logback_mdc_uri IN ('/api/parts) AND logback_mdc_userId IN ('5')&limit=25&orderBy=timestamp&order=desc&timestampStart=1667045173734000000&timestampEnd=1667066773734000000 ```

with:
```{"status":"error","data":"Failed to fetch logs from the DB","errorType":"bad_data","error":"field not found for filtering"}```

Does it help?

**Comment by nityanandagohain** [comment]
Thanks @gzsombor will get back to you on this.

**Comment by gzsombor** [comment]
After digging deeper, it seems that the problem came from the fact, that there are attributes, which contains upper case characters, which confuses the parser, because sometimes it inconsistently converts the fields to lower case, in #1670 I could fix my problem.

**Comment by nityanandagohain** [comment]
Thanks for the PR, I have added my thoughts on it.
