### ISSUE TITLE
Return to Metrics Page should be renamed to Return to Services Page

### ISSUE THREAD

**Issue by sf-pchakraborty** [SigNoz/signoz#1565]
Currently if page isn't found , we are showing "Return to Metrics Page" as in the attached screenshot. Since we have renamed it to Services, it should show  "Return to Services Page".

![Screenshot 2022-09-14 at 8 05 37 AM](https://user-images.githubusercontent.com/30225487/190056319-e4e16340-aba3-4d25-8e29-8979ba3631c5.png)

**Comment by pranay01** [comment]
Yes, we should rename to `Return to Services page` 

Can you raise a PR for this?

**Comment by sf-pchakraborty** [comment]
This should be fixed with this PR - https://github.com/SigNoz/signoz/pull/1566

**Comment by sf-pchakraborty** [comment]
This is fixed with https://github.com/SigNoz/signoz/pull/1566
