### ISSUE TITLE
Grouping spans by custom tags (and table of results)

### ISSUE THREAD

**Issue by pete-woods** [SigNoz/signoz#1571]
## Is your feature request related to a problem?

Coming from Honeycomb, some equivalent to the span query page is something I'm looking for.

The key thing that's missing is being able to group by multiple, standard and custom tags. See the top of the screenshots below for comparison to the Honeycomb feature set.

## Describe the solution you'd like

Additionally (I realise this would be further work) the table in the current query view is not especially useful.

In Honeycomb (again, see attached screenshots), the results of the grouped query are shown in the table underneath the chart. This allows you to see the attributes you've specifically grouped by.

Instead of what looks like the most recent spans in Signoz, they also offer a "slowest spans" tab.

Finally a "raw data" tab, that lets you see all the tags of your spans. It's a big table, but it's very helpful when bulding up your query, as you can see what tags are on your data, and click them to "group by" or "filter by".

### Table showing grouped attributes
![Screenshot 2022-09-15 at 10 28 43](https://user-images.githubusercontent.com/152569/190369047-e5cb456f-c4fe-4c2d-8ca1-77cee609d508.png)

### Slowest traces
![Screenshot 2022-09-15 at 10 29 04](https://user-images.githubusercontent.com/152569/190369043-873bd31b-6915-4e6f-ad05-78622acddf5a.png)

### Raw data
![Screenshot 2022-09-15 at 10 29 54](https://user-images.githubusercontent.com/152569/190369040-18de4e77-606e-4b3c-b9d6-72ea2cb28a48.png)

**Comment by ankitnayan** [comment]
@pete-woods the group by `tags` is already enabled using `clickhouse query` builder in the dashboard. An example would be 
```
SELECT
    toDateTime(toStartOfMinute(timestamp)) AS minute,
    tagMap['http.method'] AS op_name,
    toFloat64(quantile(0.99)(durationNano)) AS value
FROM signoz_traces.signoz_index_v2
WHERE timestamp > toDateTime64(now() - toIntervalMinute(30), 0, 'UTC') AND tagMap['http.method'] != ''
GROUP BY
    op_name,
    minute
ORDER BY op_name, minute ASC
```

**Comment by makeavish** [comment]
GroupBy custom tags support is added with #2116 #2115
