### ISSUE TITLE
Dashboards for span queries

### ISSUE THREAD

**Issue by pete-woods** [SigNoz/signoz#1572]
## Is your feature request related to a problem?

Once you can create the sorts of queries that we would find useful (#1571), the next thing is to be able to dashboard them.

## Describe the solution you'd like

Similar to the metric dashboards, being able to collect and arrange useful span queries together (including their tables) is very important to us.

**Comment by ankitnayan** [comment]
@pete-woods this is already possible today. An example query is mentioned at https://github.com/SigNoz/signoz/issues/1571#issuecomment-1277922563

**Comment by makeavish** [comment]
It's available in SigNoz already so closing this
