### ISSUE TITLE
signoz-otel-collector as deployment 

### ISSUE THREAD

**Issue by adecchi-2inno** [SigNoz/signoz#1577]
## Bug description

Unable to run **signoz-otel-collector** as **deployment**, it only runs as **daemonset**. 
On the other hand, there is a bug that Signoz try to use replicacount inside a daemonset.

## Expected behavior

Run **signoz-otel-collector** as **deployment** and fix the issue in case of to run it as **daemonset**.

## How to reproduce

1. Trying to install it with helm.

## Version information 
* **Signoz version**: v0.11.1
* **Chart Signoz version**: 0.3.3

## Additional context
 Probably **signoz-otel-collector** needs to run as **daemonset** when it requires to send Logs, so probably update the Helm Chart Template could fix both errors reported.
For the First error, remove the replicacount from the template when runs as **daemonset**, and for the second add some extra values to specified if Logs is required/enables if it is, so the **signoz-otel-collector** should be deploy as **daemontset** in other case as deployment.

**Comment by prashant-shahi** [comment]
@adecchi-2inno  We have already moved back OtelCollector to Deployment but the release PR is pending.

You can track it here: https://github.com/SigNoz/charts/pull/82

**Comment by prashant-shahi** [comment]
@adecchi-2inno The PR has been merged. You should have SigNoz otelCollector reverted back to deployment.
While `k8s-infra` chart is introduced to handle the same.
