### ISSUE TITLE
Feature: Enhance flamegraph visualization

### ISSUE THREAD

**Issue by muddlebee** [SigNoz/signoz#159]
## Is your feature request related to a problem?
Yes. Issues with current implementation of flamegraph visualization.

-  Spans are little confusing, as it is stacking up from left to right. So some spans are getting tightly accumulated towards the end, some not coming in screen either.

![Screenshot 2021-06-05 at 12 21 15 PM](https://user-images.githubusercontent.com/8139783/120896386-e8be7500-c63e-11eb-81e4-750f25608c84.png)

- When you click a span event in flamegraph, it zooms to make the selected event as parent span.

## Describe the solution you'd like
Stacking the spans with top down/bottom up approach for Signoz traces. something like below

![image](https://user-images.githubusercontent.com/8139783/120897153-61730080-c642-11eb-8542-beb0a8e0d3bf.png)

Link : https://files.speakerdeck.com/presentations/05d336f06c10013249425a603f66d397/slide_2.jpg

**Comment by suvojit-0x55aa** [comment]
[Pyroscope](https://github.com/pyroscope-io/pyroscope) has a great flame graph visualization, just putting it here for reference.

**Comment by pranay01** [comment]
Yeah, know folks at pyroscope. They use flamebearer library. We are exploring that also - if it would support our use cases. Thanks for pointing @suvojit-0x55aa

**Comment by MoroIddrisu** [comment]
Hello

**Comment by pranay01** [comment]
fixed by https://github.com/SigNoz/signoz/pull/764 - Updated trace detail page design
