### ISSUE TITLE
[feat]: Create template for documentation issues

### ISSUE THREAD

**Issue by publikphigor** [SigNoz/signoz#1591]
## Is your feature request related to a problem?
I was going to open an issue to contribute to the docs but I couldn't find in the list a template for docs contributions.

## Describe the solution you'd like
Add a docs contribution to the template available for selection when opening a new issue.
Also, a pretended prefix that describes the issue being opened instead of a blank one. Examples:
[docs]: Contributing to docs
[feat]: Suggesting new features

## Additional context
![Screenshot_20220924-010610_Chrome](https://user-images.githubusercontent.com/35191595/192071261-004232a8-3bd4-48bf-ab79-cfeef54d420f.png)

**Comment by pranay01** [comment]
Hey - you can create issues for documentation in https://github.com/SigNoz/signoz
