### ISSUE TITLE
signoz-otel-collector:0.55.1 Image Not found 

### ISSUE THREAD

**Issue by KR-Ravindra** [SigNoz/signoz#1598]
While using docker stack deploy example from - https://signoz.io/docs/install/docker-swarm/
The latest git pull has an image "signoz-otel-collector:0.55.1" which is not found. I had also tried pulling this manually. No luck!

**Comment by prashant-shahi** [comment]
@KR-Ravindra could you please update the images of `otel-collector` and `otel-collector-metrics` to `signoz/signoz-otel-collector:0.55.1`?
You could either manually update it or `git checkout` to `develop` branch and re-deploy.

We have already fixed this in `develop` and it would be part of the next release.

**Comment by KR-Ravindra** [comment]
Ok Thanks for the quick reply! @prashant-shahi I guess this solves my problem!
