### ISSUE TITLE
Alert Threshold value 0 is not allowed

### ISSUE THREAD

**Issue by DamZiobro** [SigNoz/signoz#1599]
## Bug description

When I create new alert in SigNoz UI and try to set 'Alert Threshold == 0' I get the following error.
![image](https://user-images.githubusercontent.com/4758489/192551587-b7355041-1d4d-4164-9d3f-b72f982f5377.png)

As a workaround I can use very low fraction value ex. 0.0000001, but it is not very intuitive.
Alert Threshold 0 should be valid. 

## Expected behavior

Setting of Alert Threshold 0 should be allowed in Alert manager. 

## How to reproduce

1. Install SigNoz using default setting of standalone Docker. 
2. Try to create some Alert in SigNoz UI and set 'Alert Threshold' value to 0.
3. You should see the error as reported above.

**Comment by srikanthccv** [comment]
Fixed in e21f23874da4b390836f0fc9bb9ad72e3479b185. Also, see v0.19 upgrade path https://github.com/SigNoz/signoz/releases/tag/v0.19.0
