### ISSUE TITLE
Feature: Explore Gantt chart for trace/span visualization

### ISSUE THREAD

**Issue by anweshknayak** [SigNoz/signoz#160]
## Is your feature request related to a problem?
Yes. As an enhancement for Traces/Span graphs. More #159

## Describe the solution you'd like

- [Zipkin](https://zipkin.io/pages/data_model.html ) does provide a nice Gantt chart of individual traces, and you can view a tree of dependencies, but it’s essentially only a context calling tree with no information as to latencies, status codes, or anything else.

![image](https://user-images.githubusercontent.com/8139783/120896782-97af8080-c640-11eb-86fc-57a8497d31bc.png)

---

- [Jaeger](https://www.jaegertracing.io/docs/1.22/architecture/) is another self-hosted tracing system that supports the OpenTracing specification.

 UI is very similar to Zipkin with pretty waterfall graphs and a dependency tree, but again, nothing that can easily help aggregate performance information

![image](https://user-images.githubusercontent.com/8139783/120897056-06410e00-c642-11eb-8ac9-bdad366f6dc1.png)

## Additional context

Tracing graphs overview/history: https://www.roguelynn.com/words/tracing-fast-and-slow/

**Comment by pranay01** [comment]
We will be working on improving the trace visualization. Will track this as part of this enhancement

**Comment by ankitnayan** [comment]
#184
