### ISSUE TITLE
Conditional color codes for number(Value) widgets in dashboard

### ISSUE THREAD

**Issue by bhaswanth88** [SigNoz/signoz#1600]
## Is your feature request related to a problem?

As the value widgets are pure textual, easy / quick glance will be hard if there are multiple value widget, so conditional visual representation will be easy to look.

## Describe the solution you'd like
In the scenario I am using, I have created one dashboard which shows expiry of SSL certificates issued for domains we are maintaining. As there are multiple domains, multiple value widgets are created, but the content inside is very textual, so if there a way to display color based on conditions such as 

1. green if ssl expiry date is above a month 
2. yellow if ssl expiry is between month and 10 days.
3. red if ssl expires in less than 10 days. 

as it is just value, just like alert thresholds, multiple conditions with color code can be mapped  and visually shown. 

## Describe alternatives you've considered

None.

**Comment by bhaswanth88** [comment]
similar kind can also be introduced for Services section-> columns: P99, Error Rate & OPS

**Comment by fakoredeDamilola** [comment]
Hello, I would love to work on this also. Thanks

**Comment by palashgdev** [comment]
> Hello, I would love to work on this also. Thanks

please go ahead

**Comment by AbelHristodor** [comment]
Any updates on this?

**Comment by ankitnayan** [comment]
part of the latest release https://github.com/SigNoz/signoz/releases/tag/v0.34.0
