### ISSUE TITLE
Support Microsoft Teams as an alert channel

### ISSUE THREAD

**Issue by thelazyoxymoron** [SigNoz/signoz#1601]
## Is your feature request related to a problem?

I'm not able to send alert notifications via webhook to Microsoft Teams. The alert manager logs says `unexpected status code 400`

## Describe the solution you'd like

Microsoft Teams requires that a JSON body be sent with a mandatory parameter named `text` which has all the content. Whatever is being sent over normal webhook calls can be wrapped inside `text` field and sent to support Teams.

## Describe alternatives you've considered

None

**Comment by dallasbeek** [comment]
Up vote!

**Comment by haicheviet** [comment]
Same for google chat webhook Url

**Comment by IlyaTeplitski** [comment]
Bump

**Comment by VishnuTeja27** [comment]
++
