### ISSUE TITLE
signup fails

### ISSUE THREAD

**Issue by tomquas** [SigNoz/signoz#1606]
## Bug description
<img width="388" alt="Screen Shot 2022-10-03 at 10 05 47" src="https://user-images.githubusercontent.com/564311/193530009-dec4224b-a382-4457-b91c-17fc42c8b6b9.png">

http://localhost:3301/signup

According to screenshot, password policies are a) a pain b) useless if not implemented correctly c) not worth a dime - as many studies and reports found out before. why not drop them?

## Expected behavior

i can sign up / log in.

## How to reproduce

1. $ cd deploy/docker/clickhouse-setup
2. $ docker compose up 
3. $ open http://localhost:3301/signup 
4. see screenshot

## Version information 
* **Signoz version**: 0.11.1 (docker > create 
* **Browser version**: chrome 10x.y

**Comment by LasseRafn** [comment]
submit a PR to change it

**Comment by pranay01** [comment]
@palashgdev can you check what's the issue here?

**Comment by pranay01** [comment]
Thanks for reporting the issue. This is not expected. Is there a particular type of passwords you see this repeating on ? Cause this works well for some passwords I tried @tomquas

**Comment by palashgdev** [comment]
it is due to regex is failing at https://github.com/SigNoz/signoz/blob/develop/frontend/src/pages/SignUp/utils.ts#L10

we can add `:`

**Comment by lakshya-dhariwal** [comment]
Hey @pranay01 would love to take a stab at this. So what are we going with - adding : to regex or removing the special character constraint.

**Comment by mariuskimmina** [comment]
Hey, I would like to pick this up if no one else is working on it. 
I would simplify the check to just look for 8 characters, as those other constrains do not significantly improve security but negatively impact user experience and are generally considered outdated.
Feel free to assign me.

**Comment by pranay01** [comment]
@mariuskimmina Sure, please just reduce check to 8 chars. Assigned it to you

Feel free to join our s[lack community](https://signoz.io/slack) as well if you need any help

**Comment by JakkuSakura** [comment]
It appears again. v0.110

<img width="1204" height="850" alt="Image" src="https://github.com/user-attachments/assets/ea8ab218-8ae5-45ee-8d76-551123329b8f" />
