### ISSUE TITLE
Compliance issues with Signoz

### ISSUE THREAD

**Issue by AnirudhaGohokar** [SigNoz/signoz#1607]
Hi Signoz Team,

The privacy policy of signoz is clearly stating that it collects personal information like user details,usage,location and cookies. Some clients specially big enterprise customers won't be comfortable in sharing any of these data points. So is there any documentation around turning off these data points collection? If not can you please mention which of those data point collections cannot be turned off?

Please note this would be standalone installation on a private server.

**Comment by pranay01** [comment]
@AnirudhaGohokar Please check details on telemetry data collected and way to disable - https://signoz.io/docs/telemetry/
