### ISSUE TITLE
Enhance span visualization for traces

### ISSUE THREAD

**Issue by muddlebee** [SigNoz/signoz#161]
### Goal

Enhance [Span](https://opentelemetry.lightstep.com/spans/) visualization for traces section @Signoz.

---

| Title  | Assignees | Milestone | State |
| :---         |     :---:        |  :---:          |         ---: | 
| [Explore Gantt chart for trace/span visualization](https://github.com/SigNoz/signoz/issues/160)  | N/A     |  N/A    | Open   |
| [Enhance flamegraph visualization](https://github.com/SigNoz/signoz/issues/159)    | N/A       |  N/A       | Open   |

---

![Screenshot 2021-06-05 at 12 21 15 PM](https://user-images.githubusercontent.com/8139783/120897504-2c67ad80-c644-11eb-8297-3083c615b194.png)

**Comment by pranay01** [comment]
fixed by https://github.com/SigNoz/signoz/pull/764 - Updated trace detail page design
