### ISSUE TITLE
The Service Name should not be capitalized

### ISSUE THREAD

**Issue by sf-pchakraborty** [SigNoz/signoz#1610]
## Bug description

Currently the list of services in Services tab show in Capital Case. But when we click on a particular service, and go to the details,
the breadcrumbs show the service name in lower case.

## Expected behaviour
The breadcrumbs should also show the service name in the small case, same as reported by backend.

## How to reproduce

1. Go to Services Tab

<img width="1434" alt="Screenshot 2022-10-05 at 8 21 55 AM" src="https://user-images.githubusercontent.com/30225487/193971275-94f98614-dbf0-4f20-96b9-cb02552a4587.png">

2. Click on any Service

<img width="1429" alt="Screenshot 2022-10-05 at 8 22 08 AM" src="https://user-images.githubusercontent.com/30225487/193971360-efc962fe-f74b-436a-ab96-3bbe3543adef.png">

**Comment by pranay01** [comment]
I think the breadcrumbs should also be in Capital case. can you take this up @sf-pchakraborty

**Comment by ankitnayan** [comment]
> I think the breadcrumbs should also be in Capital case. can you take this up @sf-pchakraborty

I recommend we do not change the case of service name anywhere. We should display what we receive in the telemetry data. If in the service list page, we are capitalizing the first char, we should not do that.

**Comment by KongrooParadox** [comment]
I am looking to contribute to an opensource project for the first time and think this issue would do nicely :)
@pranay01 @ankitnayan  @sf-pchakraborty  Could one of you assign this issue to me ?

> > I think the breadcrumbs should also be in Capital case. can you take this up @sf-pchakraborty
> 
> I recommend we do not change the case of service name anywhere. The name is also propagated to the traces page which can cause confusion. We should display what we receive in the telemetry data. If in the service list page, we are capitalizing the first char, we should not do that.
I also think that the **original** case for service name should be preserved, and would remove the capital added to the service list page.
This would be coherent with the breadcrumbs and url of each service.

**Comment by makeavish** [comment]
The service name should not be altered anywhere in the app.
@palashgdev Please take it up.
