### ISSUE TITLE
Add padding to cells in Flamegraph

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#162]
![Screenshot 2021-06-06 at 10 39 40 AM](https://user-images.githubusercontent.com/12460410/120913270-82c00500-c6b3-11eb-904d-29b25196009d.png)
Currently, the text seems cluttered. Can we add some padding in a cell so that text inside the cell has some distance from the edge?

**Comment by pranay01** [comment]
@pranshuchittora Pointers to keep in mind for flamegraph design

**Comment by pranay01** [comment]
fixed by https://github.com/SigNoz/signoz/pull/764 - Updated trace detail page design
