### ISSUE TITLE
clickhousetraces table not create after drop

### ISSUE THREAD

**Issue by YoKv** [SigNoz/signoz#1624]
## Bug description

signoz_traces have no tables created after drop datebase 

## How to reproduce

1. docker-compose up -d 
2. connect to  clickhouse and drop  datebases signoz_logs,signoz_metrics,signoz_traces
3. update signoz-otel-collector  in docker-compose.yaml to recreate container 
4.  docker-compose up -d 
5. signoz_logs,signoz_metrics works, signoz_traces only create datebase and no tables/views created

## Version information 
* **Signoz version**: 0.11.1

**Comment by makeavish** [comment]
@YoKv We are using [golang-migrate](https://github.com/golang-migrate/migrate) to maintain database migrations. If you are dropping any tables manually, then you also need to force start migrations again by dropping `schema_migrations` table.

**Comment by YoKv** [comment]
> @YoKv We are using [golang-migrate](https://github.com/golang-migrate/migrate) to maintain database migrations. If you are dropping any tables manually, then you also need to force start migrations again by dropping `schema_migrations` table.

it works.Thanks!
