### ISSUE TITLE
4318 port pointing to 4317

### ISSUE THREAD

**Issue by AshnaSabu123** [SigNoz/signoz#1626]
The port 4318 of OTLP HTTP receiver is pointing to 4317 of  OTLP gRPC receiver.
 
signoz/signoz-otel-collector:0.55.1  --- 4317-4318/tcp

In the docker-compose file the ports are given like below

   - "4317:4317"     # OTLP gRPC receiver
   - "4318:4318"     # OTLP HTTP receiver

## How to reproduce
 docker-compose up -d

Please have a check on this issue

**Comment by prashant-shahi** [comment]
@AshnaSabu123 I don't think that should be the case.
Upon running `docker ps` command, you should output with the following:

```
930e84208309   signoz/signoz-otel-collector:0.55.1            "/signoz-collector -…"   3 weeks ago    Up 3 weeks             4317-4318/tcp                                                                                                  clickhouse-setup_otel-collector-metrics_1
12c8cd3aacd1   signoz/signoz-otel-collector:0.55.1            "/signoz-collector -…"   3 weeks ago    Up 3 weeks             0.0.0.0:4317-4318->4317-4318/tcp, :::4317-4318->4317-4318/tcp, 0.0.0.0:14268->14268/tcp, :::14268->14268/tcp   clickhouse-setup_otel-collector_1
```

-  `4317-4318/tcp` should be shown for `otel-collector-metrics` which is derived from OtelCollector Dockerfile that states port of range from `4317` to `4318` are available. None of the ports are exposed for that service in `docker-compose` YAML.
- You should be see ports mapping next to `otel-collector` correctly.

Closing the issue, but feel free to open it if you think the issue still persists.
