### ISSUE TITLE
Enter key doesn't work correctly in login page

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#1627]
## Bug description

In the login page when I enter my email and press enter it throws invalid credentials error, it only works when I click on the next button instead of pressing enter

![image](https://user-images.githubusercontent.com/26831659/194856288-4e0c38b5-0c4c-485f-b077-f7381743ba6a.png)

## Expected behavior
It should not throw the error.

**Comment by ankitnayan** [comment]
@palashgdev this is still not fixed IMO

**Comment by palashgdev** [comment]
@ankitnayan issue is with different use case let me check

**Comment by palashgdev** [comment]
@ankitnayan issue is with a different use case let me check
