### ISSUE TITLE
How does golang use http to send data

### ISSUE THREAD

**Issue by yxiaoy6** [SigNoz/signoz#1629]
My signoz is deployed in kubernetes using the helm method, and the ingress proxy cannot be used on port 4317. I would like to know how to use the http method of 4318 to send golang data to signoz.

thank you for your reply！

**Comment by prashant-shahi** [comment]
@yxiaoy6 You can find complete example of OpenTelemetry Golang using HTTP protocol here: https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp

**Comment by prashant-shahi** [comment]
@yxiaoy6 Closing the issue since it is answered in previous comment.

Feel free to open it again, if you have face any issues regarding the same.
