### ISSUE TITLE
Latest Helm Chart Installation Error

### ISSUE THREAD

**Issue by WilSimpson** [SigNoz/signoz#1630]
## Bug description
Unable to deploy to local k8s cluster (microk8s) with helm. Running the install returns:
```
Error: template: signoz/charts/k8s-infra/templates/otel-deployment/deployment.yaml:64:24: executing "signoz/charts/k8s-infra/templates/otel-deployment/deployment.yaml" at <include "otel.endpoint" .>: error calling include: template: signoz/charts/k8s-infra/templates/_helpers.tpl:246:22: executing "otel.endpoint" at <.Chart.IsRoot>: can't evaluate field IsRoot in type interface {}
```

## Expected behavior
`helm install ...` does not throw any errors

## How to reproduce
1. Add chart to helm `helm repo add signoz https://charts.signoz.io`
2. Update helm chart `helm repo update`
3. Install with all defaults to an empty namespace `helm --namespace platform install signoz signoz/signoz`

## Version information 
* **Signoz version**: Helm latest
* **Kubernetes server version**: v1.24.6
* **Helm vereseion**: v3.6.2
* **Microk8s version**: v1.25.3
* **Architecture**: x86_64

**Comment by prashant-shahi** [comment]
@WilSimpson Thanks for reporting this issue.

I will be working on the fix ASAP.

**Comment by prashant-shahi** [comment]
@WilSimpson It looks like this is caused by unavailability of `Chart.IsRoot` in the Helm version used.

Could you please upgrade your Helm version?
I have tested it with Helm `v3.9.3`.

Do let us know if it works for you after upgrading.

**Comment by prashant-shahi** [comment]
It looks like the `Chart.IsRoot` function is available from `v3.7.0` onwards.

![image](https://user-images.githubusercontent.com/11138844/195184155-3f4e8219-85db-4e67-97dd-35b0d735e9b8.png)

**Comment by WilSimpson** [comment]
I upgraded to helm `3.10.0` and it fixed the issue. Thanks for the information! I tried to look for a version requirement of helm in the docs but all I remember seeing was 3.6.

**Comment by pranay01** [comment]
@prashant-shahi might be good to add the version requirements in docs as well
