### ISSUE TITLE
Allow user to automatically select date range from graph itself

### ISSUE THREAD

**Issue by ishan123456789** [SigNoz/signoz#1632]
## Is your feature request related to a problem?
Ease of setting custom date range

## Describe the solution you'd like
Currently to select a particular date range we need to manually add/update values in the dropdown which can be moved to graph itself, so selecting a particular range in graph should reflect in the selected range.

## Describe alternatives you've considered
N/A

## Additional context
We've used ELK + Datadog that had this feature so would be great to have it here as well

#### *Thank you* for your feature request – we love each and every one!

**Comment by makeavish** [comment]
Drag to select time range is a feature in SigNoz now.
