### ISSUE TITLE
In case of no data the chart goes blank, it should show proper message.

### ISSUE THREAD

**Issue by sf-pchakraborty** [SigNoz/signoz#1640]
For External Calls, when there's no data, the chart goes blank. It's hard for the user to know if the chart is loading or there's nothing to show. 

![Screenshot 2022-10-16 at 8 37 27 PM](https://user-images.githubusercontent.com/30225487/196043059-43e14f8e-7046-454c-9465-490c8f37a9fc.png)

## Expected behavior

It should atleast show some message to inform the user.

![Screenshot 2022-10-16 at 8 38 38 PM](https://user-images.githubusercontent.com/30225487/196043102-d28874ad-f5c0-4653-a4b2-4686d7f181db.png)

## How to reproduce

Please find the attached screenshot

**Comment by pranay01** [comment]
thanks for opening the issue @sf-pchakraborty Would you like to take this up?

**Comment by sf-pchakraborty** [comment]
Looks like this issue has already been fixed as part of this merge - https://github.com/SigNoz/signoz/pull/2003

Will close it for now
