### ISSUE TITLE
Two backslashes are shown in Event view instead of one (in value)

### ISSUE THREAD

**Issue by lukaszherman** [SigNoz/signoz#1653]
Backslashes are escaped correctly in JSON view, but two backlashes are shown in Event view (should be just one '\').

{
"timestamp": 1666272185422752800,
"id": "2FlLy8mdGBzFof0oKEZy4x4YREm",
"trace_id": "",
"span_id": "",
"trace_flags": 0,
"severity_text": "",
"severity_number": 0,
"body": "",
"resources_string": {},
"attributes_string": {
"Body": "",
"vSqlServer": "SQL111B\SQL2019B",
"vUserName": "abcd"
},
"attributes_int": {},
"attributes_float": {}
}

![image](https://user-images.githubusercontent.com/11869360/196963527-63e35e96-1477-4515-93a1-ae4a1a2a1f9c.png)

**Comment by pranay01** [comment]
@lukaszherman Is it in the logs detail view?

**Comment by nityanandagohain** [comment]
@lukaszherman what is the actual value. I guess it's `SQL111B\\SQL2019B` right ?

**Comment by lukaszherman** [comment]
Actual value should be with single backslash:
SQL111B\SQL2019B

**Comment by nityanandagohain** [comment]
Interesting, I tried replicating but not able to achieve this I am getting a single backslash.


can you share a sample log line along with the different operators you are using to parse the log. That will help.

**Comment by nityanandagohain** [comment]
closing this as no sample data received, feel free to reopen with sample raw data that can be ingested to replicate this issue
