### ISSUE TITLE
signoz-otel-collector: panic on histogram creation without a bucket.

### ISSUE THREAD

**Issue by marianomirabelli** [SigNoz/signoz#1658]
## Panic error on signoz-otel-collector creating a histogram without buckets.

We use SigNoz as APM to monitor the metrics and traces generated by OpenTelemetry. Our stack is based on Kotlin and we are saving custom metrics to Clickhouse using the [Micrometer](https://micrometer.io/) library with the [OTLP Meter](https://github.com/micrometer-metrics/micrometer/tree/main/implementations/micrometer-registry-otlp)(version 1.9.4).

When it came to creating custom counters, we had no problem. However, if we want to generate a timer (behind the scenes, the Micrometer timer creates a HistogramTimer), we get the following error:

`goroutine 151 [running]:
go.opentelemetry.io/collector/pdata/internal.ImmutableUInt64Slice.At(...)
	/go/pkg/mod/go.opentelemetry.io/collector/pdata@v0.55.0/internal/generated_immutable_slice.go:125
github.com/SigNoz/signoz-otel-collector/exporter/clickhousemetricsexporter.addSingleHistogramDataPoint({0x4004718000}, {0x400503d620}, {0x4003afd800}, {0x0, 0x0}, 0x40006e94c8, 0x4000d5a330)
	/src/exporter/clickhousemetricsexporter/helper.go:404 +0x804
github.com/SigNoz/signoz-otel-collector/exporter/clickhousemetricsexporter.(*PrwExporter).PushMetrics(0x4000d22280, {0x47e9e40, 0x400503d860}, {0x4000be6be8})
	/src/exporter/clickhousemetricsexporter/exporter.go:190 +0xe08
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsRequest).export(0x40048c5b00, {0x47e9e40, 0x400503d860})
	/go/pkg/mod/go.opentelemetry.io/collector@v0.55.0/exporter/exporterhelper/metrics.go:65 +0x44
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send(0x40006c41c8, {0x484ea60, 0x40048c5b00})
	/go/pkg/mod/go.opentelemetry.io/collector@v0.55.0/exporter/exporterhelper/common.go:225 +0xc0
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send(0x40002538c0, {0x484ea60, 0x40048c5b00})
	/go/pkg/mod/go.opentelemetry.io/collector@v0.55.0/exporter/exporterhelper/queued_retry.go:176 +0x4f0
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send(0x4000cec5a0, {0x484ea60, 0x40048c5b00})
	/go/pkg/mod/go.opentelemetry.io/collector@v0.55.0/exporter/exporterhelper/metrics.go:132 +0x90
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1({0x3a836a0, 0x40048c5b00})
	/go/pkg/mod/go.opentelemetry.io/collector@v0.55.0/exporter/exporterhelper/queued_retry_inmemory.go:119 +0x68
go.opentelemetry.io/collector/exporter/exporterhelper/internal.consumerFunc.consume(0x4000d02620, {0x3a836a0, 0x40048c5b00})
	/go/pkg/mod/go.opentelemetry.io/collector@v0.55.0/exporter/exporterhelper/internal/bounded_memory_queue.go:82 +0x38
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func2(0x40006c5610, 0x40007f1c40)
	/go/pkg/mod/go.opentelemetry.io/collector@v0.55.0/exporter/exporterhelper/internal/bounded_memory_queue.go:69 +0xac
created by go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers
	/go/pkg/mod/go.opentelemetry.io/collector@v0.55.0/exporter/exporterhelper/internal/bounded_memory_queue.go:63 +0x108`

As a result of this, our custom metrics are not saved to Clickhouse. Therefore, these metrics are not available to be queried by dashboards and alerts. On top of that, if we continue to send this kind of metric, the signoz-otel-collector pods fail and go into a reboot loop.

## Expected behaviour

The expected behaviour is to allow creating and saving of custom metrics into Clickhouse through the signoz-otel-collector deployment.

## How to reproduce

1. Creates a timer using Micrometer with OTLP Meter as the following code shows:
```
    val config =  object : OtlpConfig{
            private val configuration = mapOf(
                "otlp.url" to otlpProvider.host
            )

            override fun get(key: String): String? {
                return configuration[key]
            }
        }
        return OtlpMeterRegistry(config, Clock.SYSTEM)
```
2. Address the otlp.url to the following endpoint: `http://${SIGNOZ_OTEL_COLLECTOR_SVC}:4318/v1/metrics`
3. Create a timer as the following code suggests:
`this.meterRegistry.timer(metric.name, buildTags(tags)).record(duration)`
4. Deploy your app and try to generate your custom metrics.

## Version information 
* **Signoz version**: signoz-otel-collector:0.55.3
* **Browser version**: N/A
* **Your OS and version**: Amazon Linux 2
* **Your CPU Architecture**(ARM/Intel): AMD64

## Additional context
Our applications are deployed on top of Kubernetes 1.22 with Amazon EKS. We are instrumenting our applications using [OpenTelemetry Operator](https://github.com/open-telemetry/opentelemetry-operator).

## Suggested Solution
Taking into account that I've found the following [issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12854/files) in the prometheusremotewriteexporter component from the opentelemetry-collector-contrib project. I think that it is possible to replicate the same solution in the clickhousemetricsexporter.

Therefore I've created this [PR](https://github.com/SigNoz/signoz-otel-collector/pull/23) applying the solution cited above. I've generated a custom image of the signoz-otel-collector in our local environment and I've deployed it. This has solved the issue for us

**Comment by srikanthccv** [comment]
This is fixed
