### ISSUE TITLE
Support custom port if default ports are not available

### ISSUE THREAD

**Issue by suvojit-0x55aa** [SigNoz/signoz#166]
## Is your feature request related to a problem?

Yes it is, I'm unable to run it with other services running on default ports of signoz.

## Describe the solution you'd like

Ability to change the default ports of signoz, either through some config files or env.

From what I understood the following line hardcodes the ports:
https://github.com/SigNoz/signoz/blob/34e33af290f85ec2fbc1fbc710844f9f62b327e1/deploy/install.sh#L101

It is also hardcoded throughout [install.sh](https://github.com/SigNoz/signoz/blob/main/deploy/install.sh)

**Comment by pranay01** [comment]
@suvojit-0x55aa are there specific ports which are preventing you from deploying SigNoz?

**Comment by suvojit-0x55aa** [comment]
@pranay01 mostly port 80 taken by nginx and 8080 for another service.
One way custom port can be implemented is mapping the default docker port to a different host port.

**Comment by ankitnayan** [comment]
@suvojit-0x55aa This is already an option in respective docker-compose files. Let's say, for clickhouse setup:
1. Port of `frontend` can be changed [here](https://github.com/SigNoz/signoz/blob/main/deploy/docker/clickhouse-setup/docker-compose.yaml#L47)
2. Port of `query-service` can be changed [here](https://github.com/SigNoz/signoz/blob/main/deploy/docker/clickhouse-setup/docker-compose.yaml#L27)

**Comment by suvojit-0x55aa** [comment]
@ankitnayan thanks I'll test it out and get back, if it's not used I I think it should be removed.

**Comment by suvojit-0x55aa** [comment]
@ankitnayan If I use the druid-kafka option i guess I'll have to make change here ?
https://github.com/SigNoz/signoz/blob/34e33af290f85ec2fbc1fbc710844f9f62b327e1/deploy/docker/druid-kafka-setup/docker-compose-tiny.yaml#L172

**Comment by ankitnayan** [comment]
@suvojit-0x55aa Correct! Let me know if you face any issues

**Comment by pranay01** [comment]
@prashant-shahi Is this issue fixed now?

**Comment by prashant-shahi** [comment]
@pranay01yes  it is resolved.

We don't expose `8080` port of query-service anymore.

We only expose two ports by default in docker-compose YAML:
- `3301`  frontend port
- `4317` otel collector port
