### ISSUE TITLE
container directory mounted in otel collector

### ISSUE THREAD

**Issue by rinshadka** [SigNoz/signoz#1665]
HI,
I have found the docker container directory is bind mounted to otel collector service. Is this mandatory since I am running signoz in a server having many other parallel projects as docker containers. Actually whats the purpose of that volume mount?

https://github.com/SigNoz/signoz/blob/develop/deploy/docker/clickhouse-setup/docker-compose.yaml#L89

Thanks,
Rinshad.

**Comment by prashant-shahi** [comment]
Hi @rinshadka :wave: 

It is not mandatory for running SigNoz.
We mainly use it to tail and parse logs from all containers and send it to SigNoz OtelCollector running locally.

Feel free to comment out that section if you do not need logs collection.

**Comment by prashant-shahi** [comment]
Feel free to re-open the issue, if any issue related to the same persists.
