### ISSUE TITLE
Names of apps at Service Map is not display completly

### ISSUE THREAD

**Issue by njuarezgt** [SigNoz/signoz#1666]
## Is your feature request related to a problem?

*Please describe.*

Names of apps at Map Services is not display completly
![image](https://user-images.githubusercontent.com/11880420/198355438-6987b9bb-9556-4ba0-b486-6323c16427b6.png)
## Describe the solution you'd like
Showing full service name onHover over the circle.
Thanks, regards.

**Comment by pranay01** [comment]
@palashgdev Can you check what could be a good solution for this. Would showing full service name onhover work

**Comment by tuxitop** [comment]
Is there any plan to fix this issue? many of our service names start with the same characters and this map is completely unreadable for us, because we don't have any way to know which is which.

**Comment by prashanth-nani** [comment]
@pranay01 Any update on this? We are facing the same issue. This issue makes the entire service map unusable. All our service names start with the same prefix and SigNoz only shows the prefix.  Also a legend explaining the different colours being used in the map would be helpful. 

This is how it looks like right now. 

![image](https://github.com/SigNoz/signoz/assets/8893755/d7b737ef-e30e-415b-b053-65f1fb5c6369)
