### ISSUE TITLE
Old data not reflecting in UI after upgradation

### ISSUE THREAD

**Issue by AshnaSabu123** [SigNoz/signoz#1673]
After upgrading the signoz to the latest version with the old volumes, the old data is not reflecting in UI.

## Expected behavior

Old data should be displayed in the UI

## How to reproduce

1. Change the docker images in the compose file to the latest version
2. docker-compose up -d

## Version information 
* **Signoz version**: 0.11.2

**Comment by pranay01** [comment]
@AshnaSabu123 Any specific reason why you didn't follow the [steps](https://signoz.io/docs/operate/docker-standalone/#upgrade) mentioned here to upgrade?

Can you share more details on what data you had in the system? Was it primarily traces data? Or you ahd logs and metrics as welk? 

Were all the data missing?
