### ISSUE TITLE
Time macros not found in dashboard clickhouse query

### ISSUE THREAD

**Issue by allanli524** [SigNoz/signoz#1675]
## Bug description
Dashboard - Panels: fresh after installation and setup, if no variable has been configured by the user, then the date range macros {{.SIGNOZ_START_TIME}} and {{.SIGNOZ_END_TIME}} are not included in the network request payload. This issue fixes itself after the user creates any sort of variable.

## Expected behavior
The macros should be included in the request payload

## How to reproduce

1. Install/reinstall a fresh instance of SigNoz with Docker standalone
2. create a dashboard and timeseries panel, select clickhouse query
3. run a sample query with the macros

## Version information 
* **Signoz version**: 0.11.2
* **Browser version**: 106.0.5249.119 Chrome
* **Your OS and version**: macOS Monterey 12.6
* **Your CPU Architecture**(ARM/Intel): ARM

**Comment by ankitnayan** [comment]
https://github.com/SigNoz/signoz/issues/2742
