### ISSUE TITLE
Dashboard: new variable, no form completion check

### ISSUE THREAD

**Issue by allanli524** [SigNoz/signoz#1676]
## Bug description
 When we create a new variable in the dashboard and click the `save` button while not filling in the `name` field, the other fields that the user fills out gets erased and the reset without any warning.

## Expected behavior
The UI should warn the user to fill in the name field, at least it shouldn't reset all the other fields without any warning. 

## How to reproduce

1. Create new variable
2. Don't fill the name field but fill other fields such as query
3. Click save

## Version information 
* **Signoz version**: 0.11.2
* **Browser version**:
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel):

**Comment by pranay01** [comment]
@palashgdev can you take a look at this issue. seems like a simple bug

@srikanthccv should have more context on how the feature works

**Comment by makeavish** [comment]
Fixed in latest version
