### ISSUE TITLE
Feat(FE): Add compact table format to log viewer with scrolling / lazy loading

### ISSUE THREAD

**Issue by ppenguin** [SigNoz/signoz#1678]
## Is your feature request related to a problem?

When using the log viewer, one can only see an (arbitrary?) representation of log events, which is unsuitable to have a good overview of larger numbers of log messages.

## Describe the solution you'd like

A compact, table format log viewer (in the event pane) that can stream logs (in live tail mode) .
The columns would be selected from 2 sources:
- fields (like currently the case)
- `json` keys from the event body (possibly these would need to defined by their names while defining the view) and left empty if the key doesn't exist)

When scrolling in the table, auto scrolling (due to live tailing) would be suspended, and one could scroll down to older entries; when scrolling further back additional , older entries would be shown (probably these would need to be fetched from the DB, i.e. lazy loadad). A kind of "to-top" button would continue live tailing (newest entries on top).

The event pane itself would be scrollable, so that scrolling through log messages keeps the field headers and other page elements in sight.

Filters would be set on a per-column basis, this has two advantages:
- it takes much less space than the current filter selection pane
- it has better UX: one would define the apprpriate filter directly on the fieldsone wants to filter.

## Describe alternatives you've considered

- use a `grafana` table view that uses the `SigNoz` `clickhouse` DB as a data source. Since querying the DB is done periodically, this does not give "real realtime" log tailing (but merely refresh e.g. every 5s).

## Additional context

Usability bonus would probably be to allow for defining and saving filter presets. One could select certain groups of services to examine (e.g. based on a `serviceName` field in the `json` body) and would then live-stream the logs.

**Comment by pranay01** [comment]
Thanks for opening the issue @ppenguin 

Would a log line view be more interesting to you, like some other products do - or a compact table format ( with columns for interesting fields) In our initial user research we found that table views are able to show less data in a single page and in log lines view there is not much structure info.

For reference, this is what I mean by log line view
![log-line-view](https://user-images.githubusercontent.com/504541/209558068-57802bef-91cd-4927-9630-2af1821f87ce.png)

**Comment by nityanandagohain** [comment]
@ppenguin with respect to this 

> json keys from the event body (possibly these would need to defined by their names while defining the view) and left empty if the key doesn't exist)


Why would you want to do this, can you share a concrete usecase ? Ideally, if you are interested in some fields from the body, they should be parsed at the config level and converted to fields.

**Comment by ankitnayan** [comment]
different view of logs are released
