### ISSUE TITLE
Signoz Frontend Logs Query builder doesn't show all fields

### ISSUE THREAD

**Issue by abhinavramana** [SigNoz/signoz#1686]
Some improvements:
1. It currently only shows interesting fields and selected fields. So no one knows that `body` exists and this makes it difficult to search
2. Query builder using AND etc. is only supported when we enter the entire text like: https://signoz/logs?q=service_name%20IN%20(%27paint-service-backend-prod%27)%20AND%20body%20CONTAINS%20%27LKEyS9zvyAggmOeIp0Hzu0bpGoX2%27 . 
![image](https://user-images.githubusercontent.com/4195703/200042337-58ff6560-f809-42f7-80b0-3d487d6df84a.png)
Unless we type the text like 
![image](https://user-images.githubusercontent.com/4195703/200042415-bc0d50c1-6d5f-4e90-bd31-5049d37db999.png)
it won't show in the log query builder. It should be supportive even without text

**SUGGESTION** 
We should be able to see all fields that are supported for searching

**Comment by abhinavramana** [comment]
Currently INTERESTING FIELDS doesn't contain body 
![image](https://user-images.githubusercontent.com/4195703/200053198-89cd6474-7a67-4aeb-8cac-c5bb26bf72aa.png)

**Comment by nityanandagohain** [comment]
Hi @abhinavramana .

* So whenever you write any query, if it's a random string then it is searched against the `body`. Thats the reason we don't show body  in selected and interesting field. You can find some examples here https://signoz.io/docs/userguide/logs_query_builder/

* Regarding the second point, you are right. The when you click on the field for the second time it doesn't work in the query builder. We have an issue for that which is to be picked up https://github.com/orgs/SigNoz/projects/10/views/30
