### ISSUE TITLE
Add Filters to "Exceptions" View

### ISSUE THREAD

**Issue by AlexeiZenin** [SigNoz/signoz#1687]
## Is your feature request related to a problem?

Couldn't find exceptions for a certain service or environment easily

## Describe the solution you'd like

Add filters based on tags like how it is implemented in the "Services" page currently.

## Describe alternatives you've considered

Setting to show 100 per page and then using Ctrl + F in my browser to find the service(s) I need to look for exceptions in. Repeat this per every page of 100 services (linear search).

## Additional context

Filters on Service page:

![Screen Shot 2022-11-04 at 2 31 02 PM](https://user-images.githubusercontent.com/12644364/200049532-7f8b48c8-0fe6-40bf-847e-d9e3f16afb0a.png)

**Comment by makeavish** [comment]
It's available in latest version of SigNoz.
