### ISSUE TITLE
Starlette logging middleware extensions lose the trace and span context in FastAPI

### ISSUE THREAD

**Issue by abhinavramana** [SigNoz/signoz#1692]
**Describe your environment** 
Happens in AWS docker containers as well as local box
Signoz running in Kubernetes but reproducible in local box as well

**Steps to reproduce**
Code: https://github.com/abhinavramana/trimmed-wombo-fastapi-signoz/blob/main/wombo/fastapi.py#L50 and https://github.com/abhinavramana/trimmed-wombo-fastapi-signoz/blob/main/wombo/logging_middleware.py
Video explaination: https://drive.google.com/file/d/1tsbh54DiZANQfEOK_637sPLrvuTzNUaR/view?usp=share_link

1. Deploy the app
2. Hit "/log" endpoint
3. Find the trace 
4. Go to the logs and search for that trace
5. You won't find the stats blob ```stats_json = {
        "user_id": user_id,
        "path": f"{request.method}-{request.url.path}",
        "response_status_code": response_status_code,
        "run_time": run_time,
        "headers": request.headers.items(),  # Starlette Header is not serializable
    }```
6. Go to the logs and look for any log with user_id
7. See that the stats json blob exists but doesn't have traceId

**What is the expected behavior?**

Stats_json should have traceId and spanId as well since they are still in the request lifecycle

**What is the actual behavior?**
Stats_json don't have traceId and spanId

**Comment by srikanthccv** [comment]
See https://github.com/abhinavramana/trimmed-wombo-fastapi-signoz/commit/1dde3ddfe9a05efc1144468263ab756a720affcc#commitcomment-89123531

**Comment by abhinavramana** [comment]
I had to do something similar to CORSMiddleware as well but yes this works!

**Comment by srikanthccv** [comment]
The OpenTelemetry integration should be first, but the rest of your custom middleware can be in any order. Closing this since the original issue of lost trace context is fixed.
