### ISSUE TITLE
Support for Clickhouse queries in alert builder

### ISSUE THREAD

**Issue by mindhash** [SigNoz/signoz#1699]
## Is your feature request related to a problem?

*The alert builder currently does not support native clickhouse queries. This limits use of alert builder to metrics only. Adding support for clickhouse queries would be a good start in supporting alerts on logs and other components (in addition to metrics)*

## Describe the solution you'd like
- Add a new tab **clickhouse query** in alert builder 

## Describe alternatives you've considered
None.

**Comment by mindhash** [comment]
The primary design concern in this solution would be handling of timeframe and threshold conditions. 

In the current version, we support promql expression and query builder (form based) queries. Both these option go through a query construction phase, which appends the WHERE conditions on the query - threshold condition (like result > 10) and timeframe condition (timestamp between current - 15 and current). 

In both these cases, the clickhouse queries are generated by alerting engine based on the parameters selected by user. The alert queries run every minute and the above conditions are applied at the time of every execution.

Coming back to clickhouse query case -  Since  user is going to write the native query and it wont be generated by alerting engine, we will need a common ground to interpret the bind variables (threshold, timestamp).  This can get increasingly complex with use of subqueries,  joins etc. 

To illustrate this further, lets look at the example below:
`Select t1.value, t2.value from Samples s1, Samples s2, timeseries t1, timeseries t2 where ....   `

In this case, both the timestamp condition and selection of result become ambiguous.  The question becomes which timeseries table should we apply the timeframe condition on? and which of the values will count as result to be evalauted against the threshold.

To resolve such ambiguity, we need a common understanding on bind parameters. I think we can settle with these 3:

- target_val (must be present in select either as column or column alias)
- ${from_ts} (must be present in at least one where condition)
- ${to_ts} (must be present in at least one where condition)

These parameters will be reserved and must be present in each ch query (in alert builder). 

At the time of execution of the rule, the alerting engine will replace ${from_ts} and ${to_ts} in the query with actual timestamp values. And use the target_val column (or alias) of the result to apply threshold condition.

@makeavish @nityanandagohain  @pranay01 @ankitnayan @srikanthccv  please review and share thoughts.

**Comment by srikanthccv** [comment]
> To illustrate this further, lets look at the example below:
Select t1.value, t2.value from Samples s1, Samples s2, timeseries t1, timeseries t2 where ....

>In this case, both the timestamp condition and selection of result become ambiguous.

I don't think we should allow this. Here is what I think. We can assume that they query any source, and the final result must be of `Vector` form (throw invalid otherwise) with one `time.Time` column and one number column, and an optional n number of string columns with label pairs (this can be any number resulting time series). This is what we do for dashboards and query-builder based alerts if I am not mistaken. What changes here is that the user writes the query instead of us writing the conditional statements etc...

**Comment by ankitnayan** [comment]
@makeavish please share a few queries on the traces data that should be supported. Eg, group by an attribute key, count of errors with a set of filters, number of events with a given name in a service.

@nityanandagohain please share a few queries on logs data that should be supported.

**Comment by mindhash** [comment]
> I don't think we should allow this. Here is what I think

@srikanthccv please share your reason for reservation against the proposed approach with an example. It helps in understanding an argument. 

The alert queries are slightly different than dashboard since there is a need to pick target column.  The thought here is to ensure user always has a target column and identifies it.  The select can have multiple columns and choosing one column is necessary to compare the threshold.

I am open to other ideas. I understand their may be a better way around this
