### ISSUE TITLE
Can't find counter metrics in dashboard

### ISSUE THREAD

**Issue by nappa85** [SigNoz/signoz#1707]
I'm testing SigNoz 0.11.2 using docker-compose clickhouse environment (minus hotrod containers), along with other products, firing metrics to a single otel-collector instance with different exporters.

In my Rust code I've got those metrics:
```rust
static HTTP_COUNTER: Lazy<Counter<u64>> = Lazy::new(|| {
    get_meter()// retrieve common meter
        .u64_counter("http.hits")
        .with_description("Request hit counter")
        .with_unit(Unit::new("r"))
        .init()
});
static HTTP_REQ_HISTOGRAM: Lazy<ValueRecorder<f64>> = Lazy::new(|| {
    get_meter()// retrieve common meter
        .f64_value_recorder("service.duration")
        .with_description("Service request latencies")
        .with_unit(Unit::new("s"))
        .init()
});
static MYSQL_QUERY_HISTOGRAM: Lazy<ValueRecorder<f64>> = Lazy::new(|| {
    get_meter()// retrieve common meter
        .f64_value_recorder("mysql.duration")
        .with_description("MySQL query latencies")
        .with_unit(Unit::new("s"))
        .init()
});

fn metric_web(info: warp::log::Info<'_>) {
    debug!("served {} {} {:?}", info.method(), info.path(), info.status());

    let attributes = &[
        KeyValue::new("method", info.method().to_string()),
        KeyValue::new("path", info.path().to_owned()),
        KeyValue::new("status", info.status().as_u16() as i64),
        KeyValue::new("failed", !info.status().is_success()),
    ];

    HTTP_COUNTER.add(1, attributes);
    HTTP_REQ_HISTOGRAM.record(info.elapsed().as_secs_f64(), attributes);
}

fn metric_mysql(info: &sea_orm::metric::Info<'_>, pool: &'static str) {
    debug!(
        "mysql query{} on {} took {}s: {}",
        if info.failed { " failed" } else { "" },
        pool,
        info.elapsed.as_secs_f64(),
        info.statement.sql
    );

    MYSQL_QUERY_HISTOGRAM.record(
        info.elapsed.as_secs_f64(),
        &[
            KeyValue::new("query", info.statement.sql.clone()),
            KeyValue::new("pool", pool),
            KeyValue::new("failed", info.failed),
        ],
    );
}
```

On SigNoz I can find `mysql.duration` (called `mysql_duration`) and `service.duration` (called `service_duration`) metrics, but I can't find `http.hits` metrics, while on other products I can find all of them.

Is there some kind of filter on metric names? Am I doing something wrong?

**Comment by pranay01** [comment]
@srikanthccv Would you have any insights on this?

**Comment by srikanthccv** [comment]
@nappa85 Please provide a fully reproducible example. I tried a basic OTLP example with an HTTP counter and could see the metric name `http_hits`. 
<img width="836" alt="Screenshot 2022-11-12 at 4 23 42 AM" src="https://user-images.githubusercontent.com/22846633/201441660-13920301-9df0-4426-99bc-9c7cb692903e.png">

**Comment by ankitnayan** [comment]
@nappa85 the 2nd image is not from SigNoz's UI? How are you visualizing the data?

**Comment by nappa85** [comment]
> @nappa85 the 2nd image is not from SigNoz's UI? How are you visualizing the data?

Second image is from another product ingesting the very same OTLP data (I've an otlp-collector exporting to different products to make a comparison)

**Comment by srikanthccv** [comment]
Ah, I see you are using delta temporality in the code. We currently support the cumulative to remain compatible with Prometheus, its query language and ecosystem. So if it's possible, I would suggest you use cumulative (which is also default in OTEL). Otherwise, there needs to be another intermediate step which converts delta points to cumulative making it stateful, which makes it difficult to scale horizontally.

**Comment by nappa85** [comment]
I've ended up using Delta after this issue https://github.com/open-telemetry/opentelemetry-rust/issues/677
I'll try with other configs and let you know

**Comment by nappa85** [comment]
I went with default values, so aggregator selector exact and export kind stateless, and I have the same behavior
![image](https://user-images.githubusercontent.com/7566389/202131168-24d2868a-d00d-40a8-8c01-eacba3a671a4.png)
![image](https://user-images.githubusercontent.com/7566389/202130654-278e2017-d2a4-453e-9070-115a4abceaf7.png)

**Comment by srikanthccv** [comment]
> In this dashboard we can see http.hits going up in time, but the request rate was constant

Is it constant? or is it not big enough to tell the difference in the same chart because y axis is skewed by noop line? 

> At half chart I switched back to export_kind stateless and the value disappeared

What is export kind stateless?

**Comment by nappa85** [comment]
> > In this dashboard we can see http.hits going up in time, but the request rate was constant
> 
> Is it constant? or is it not big enough to tell the difference in the same chart because y axis is skewed by noop line?

I'm sending a request every 2 seconds, so it's constant

> > At half chart I switched back to export_kind stateless and the value disappeared
> 
> What is export kind stateless?

It's an opentelemetry crate concept, I thought it was standard also outside rust

**Comment by nappa85** [comment]
Just to be fully transparent: I've made an MVP with opentelemetry 0.18.0, latest version, I wasn't using it because it's a big breaking change from 0.17.0 and it lacks documentation about metrics. You can find the code here https://github.com/nappa85/otlp-test/tree/v0.18.0
It fires every possible metric type (u64/f64)_((observable_)counter|histogram|observable_gauge|(observable_)up_down_counter), and for every metric type it aggregates 3 different ways: sum, last_value and histogram
In total are 30 different metrics sent, all the integer metrics sends a constant 1 value, all the float metrics sends the same random value between 0 an 1 for every call
The export kind is stateless, the default, so I'm no more using delta that you don't support (it was a limitation of 0.17.0)

I've configured SigNoz and another product doing a graph for every metric, grouping the 3 different aggregations.
Data generation is made calling my program with `curl` using `watch`, that makes a call every 2 seconds.
```bash
watch curl 127.0.0.1:3000/a
```

In signoz I find histogram metrics split in 3 voices: _bucket, _count and _sum, so there are 5 lines per graph
All metrics in SigNoz appears monotonic growing, even if I specified NOOP for all values, except for the observable_up_down_counter, here I really can't say what's going on.
![Screenshot_20221116_172810](https://user-images.githubusercontent.com/7566389/202255860-3ac9c9b1-f4f2-4fc7-842b-6798c131422c.png)
![image](https://user-images.githubusercontent.com/7566389/202256842-6e5e3644-5a53-4c3d-b211-c259b9365b83.png)


With the exact same data, the other product gives a correct output
![Screenshot_20221116_172841](https://user-images.githubusercontent.com/7566389/202257523-399241e4-2f46-4d6f-b5a3-d8e92063547c.png)
![Screenshot_20221116_172859](https://user-images.githubusercontent.com/7566389/202257535-53e1108b-c96b-4c8b-9a3d-2a4424516c22.png)


I don't know if I'm doing something wrong with SigNoz, let me know

**Comment by nappa85** [comment]
Just to be clear, someone pointed out it seems I'm telling that SigNoz doesn't works.
No, I'm just pointing there are unclear/unfriendly things, I wrote this report at the end of my work day and I'm quite exhausted, so maybe I haven't choosen the best words...
As a developer, I think this kind of feedback are really helpful.

**Comment by srikanthccv** [comment]
@nappa85 I am not sure I really understand what you are trying to convey. We appreciate any and all feedback. Our underlying data model closely follows OpenMetrics (~Prometheus) exposition format. So just using NOOP gives you the raw data, which is not very helpful. You need to change the aggregate operator depending on the metric type (usually RATE or SUM_RATE for counters, combined with histogram_quantile for histogram types etc.). Please go through these docs https://signoz.io/docs/userguide/create-a-custom-query/ and try to use the appropriate operator to plot the graphs. You also mentioned some rust SDK-specific things I am not fully aware of. If you are unsure about something and need help, please join our Slack channel and ask questions https://signoz.io/docs/community/#slack.

**Comment by nappa85** [comment]
An example of what I'm trying to express:

From my application I produce this histogram, it's variable data, response timing, I need to see something like the average time, not only the last value for the time frame.
I'm producing a random float value between 0 and 1, so, with standard distribution, the average will be near 0.5, and sending the exact same data to both products.

With the other product, I simply put the histogram data in the graph, it forces me to use an aggregation and by default uses p50, the result is already acceptable
![image](https://user-images.githubusercontent.com/7566389/202653875-2910e5d2-16af-4c60-9bef-ddb37e45636d.png)

With SigNoz I find 3 different possible metrics: histogram_bucket, histogram_count and histogram_sum. I'm discarding count and sum becaure they aren't what I want, so, NOOP is obviously wrong, but if I plot it it's already a warning, why all values are growing like it's a count?
![image](https://user-images.githubusercontent.com/7566389/202654694-cd074fd7-624c-4776-ae2a-e065fa73bfef.png)
Even with P50 I have a growind graph
![image](https://user-images.githubusercontent.com/7566389/202654962-166e24f4-7423-4479-82f0-dbb78e2029ab.png)
With RATE I have all the single values distinct
![image](https://user-images.githubusercontent.com/7566389/202655198-33462c0f-5d3e-4163-99de-3624caf2c8e9.png)
Strangely they are all under 0.5, but if I take a look to histogram_last, I see I have many values over 0.5
![image](https://user-images.githubusercontent.com/7566389/202657175-f5b0ca99-8896-42ee-90d5-4ac3c2066473.png)
Maybe I'm using the wrong aggregator?
SUM_RATE goes too high
![image](https://user-images.githubusercontent.com/7566389/202657451-99dcb5c4-3cfd-4a58-8658-e4fc4711716d.png)
RATE_SUM even higher
![image](https://user-images.githubusercontent.com/7566389/202657596-365b7629-cc0c-4e47-91a6-5b9cbb43fb76.png)
RATE_AVG suspiciously always under 0.5
![image](https://user-images.githubusercontent.com/7566389/202657882-dcde4ed9-d353-43b1-b338-62084284945f.png)

I can accept I'm using SigNoz the wrong way, I'm testing it since few days and I'm neither an expert in metrics, but it doesn't seem to be user friendly

**Comment by srikanthccv** [comment]
I think I understand the challenge you are facing, especially since you don't have prior experience prometheus or primal. You were expecting the aggregation can be directly based on the metric type instead of you trying to figure out what to do with the underlying raw data.

**Comment by nappa85** [comment]
> I think I understand the challenge you are facing, especially since you don't have prior experience prometheus or primal. You were expecting the aggregation can be directly based on the metric type instead of you trying to figure out what to do with the underlying raw data.

Can you elaborate more? Being the data the same, how can I reach the same result i get with the other product using SigNoz?
