### ISSUE TITLE
Signoz Frontend  logs doesn't respect the URL

### ISSUE THREAD

**Issue by abhinavramana** [SigNoz/signoz#1713]
## Bug description

Video description: https://drive.google.com/file/d/1ASViNttxOfA1vbPie9KrsmVYQSh02aF7/view?usp=share_link

**Comment by nityanandagohain** [comment]
Thanks for reporting the issue @abhinavramana .


@palashgdev two request are getting created when query is present in the url. when the the page loads data w.r.t to the query is loaded but a new request is triggered with doesn't contain any query and it overrides the previous data.
![image](https://user-images.githubusercontent.com/26831659/201825575-e80d8dfc-095c-4436-92fd-7f5ce931583a.png)

![image](https://user-images.githubusercontent.com/26831659/201825619-88a17e22-89a5-4a5c-b813-06c988e41039.png)

**Comment by pranay01** [comment]
@palashgdev it seems even now in #1727 there are 2 queries being created, but both have query params. 

API call 1
![Screenshot 2022-11-21 at 2 49 17 PM](https://user-images.githubusercontent.com/504541/203012568-da9c566d-
150f-4cea-865a-a78bee0ecc1f.png)

API call 2
![Screenshot 2022-11-21 at 2 49 30 PM](https://user-images.githubusercontent.com/504541/203012649-8c7ef6a4-afd7-48d8-abf3-2c7f8eb2ef88.png)

**Comment by palashgdev** [comment]
> #1727



> @palashgdev it seems even now in #1727 there are 2 queries being created, but both have query params.
> 
> My guess was it should just be making 1 query
> 
> API call 1 ![Screenshot 2022-11-21 at 2 49 17 PM](https://user-images.githubusercontent.com/504541/203012568-da9c566d-150f-4cea-865a-a78bee0ecc1f.png)
> 
> API call 2 ![Screenshot 2022-11-21 at 2 49 30 PM](https://user-images.githubusercontent.com/504541/203012649-8c7ef6a4-afd7-48d8-abf3-2c7f8eb2ef88.png)

yeah ideally it should be one only but this would require major refactoring
