### ISSUE TITLE
Issues observed while importing dashboards through the "Import Grafana Json"

### ISSUE THREAD

**Issue by kaoutherab** [SigNoz/signoz#1714]
## Bug description
I am trying to leverage the out of the box node exporter grafana dashboards by importing the file https://github.com/rfmoz/grafana-dashboards/blob/master/prometheus/node-exporter-full.json into Signoz through the "Import Grafana Json" feature. But noticed the following behavior:
1- For some panels, I see in logs the error: "Max query size exceeded"
2- Signoz shows some panels, but the queries in the panels are empty. After doing some comparison with expected dashboards, those empty panels are related to "rows" in Grafana, ie sections that would contain a collection of panels. So, Signoz dashboard render those "rows" as empty panels. and does not render the actual panels of those sections. Only panels of the first section "row" are rendered in Signoz dashboard.
3- The tooltip on the Signoz Dashboard panel UI gets truncated and cannot see or drag to see the whole attributes in the tooltip, ie, the tooltip is truncated horizontally and vertically.

**Comment by pranay01** [comment]
@srikanthccv are the issues mentioned here fixed now?

**Comment by srikanthccv** [comment]
The first two points are addressed in the linked PRs, and the last point is related to UI, which is yet to be addressed.

**Comment by pranay01** [comment]
Okay, creating a new issue for point 3. https://github.com/SigNoz/signoz/issues/1960

Closing this issue
