### ISSUE TITLE
Ability to select time range in charts manually and populate global time range based on that

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#1716]
## Is your feature request related to a problem?
when I click on the bars (in the chart), I was expected to see logs associated with that timestamp

## Describe the solution you'd like
We should be able to select a time range from the counts chart.

![image](https://user-images.githubusercontent.com/26831659/201862614-6323476e-b1c0-47c9-9834-c831b09650ae.png)

**Comment by pranay01** [comment]
This may be a general feature in charts, not necessarily only for logs. So this should be built in a more generic way for chart components

**Comment by nityanandagohain** [comment]
Bumping this.

**Comment by YounixM** [comment]
This is addressed. Closing the issue.
