### ISSUE TITLE
Filter on application in exceptions page

### ISSUE THREAD

**Issue by hardik-epifi** [SigNoz/signoz#1725]
## Is your feature request related to a problem?
We have lot of applications in production and it is becoming very difficult for us to view exceptions for a particular service.

## Describe the solution you'd like
Allow filtering on application name so that one can view exceptions happening in a particular service

## Describe alternatives you've considered
Sentry

**Comment by ankitnayan** [comment]
We can build a search like the one in the serviceList page. The image is attached for reference.

![image](https://user-images.githubusercontent.com/12460410/202409462-008ccc7a-cf54-4dd1-8bd4-8ce48e3be666.png)
