### ISSUE TITLE
Create alerts on exceptions count/velocity

### ISSUE THREAD

**Issue by hardik-epifi** [SigNoz/signoz#1726]
## Is your feature request related to a problem?
We want to create alerts whenever we see increase in number of exceptions occuring in particular services. The alert should be configurable on per error basis for example we do not want alerts on "not found" errors or certain other known business errors.

## Describe the solution you'd like
Should be able to set alerting rules on exceptions

## Describe alternatives you've considered
Sentry

**Comment by iamkhalidbashir** [comment]
We need this urgently

**Comment by makeavish** [comment]
We have merged a PR to introduce alerts based on exceptions count.
https://github.com/SigNoz/signoz/pull/1752

Feature will be released in v0.11.4
