### ISSUE TITLE
[EPIC] Add Table and Top List as visualization type for panels

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1738]
A typical use case for this would be to show top 10 APIs for a service or set of filters on services based on latency.

Currently, service pages show this, but it should be possible to add panels in dashboards as well which show lists or tables

[PRD link](https://www.notion.so/signoz/PRD-Add-Table-and-Top-List-as-visualization-type-for-panels-44c0d62147754160bdde509bd94dce40z) (internal link)

**Comment by makeavish** [comment]
Table view is available so I think this issue can be closed.
Reopen if needed.
