### ISSUE TITLE
Find Trace Link in sample Hot R.O.D application not working

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#174]
## Bug description

'Find trace' link which comes when we click on customer's name does not work. You can find the 'find trace' link from the image below.

![Screenshot 2021-06-11 at 7 42 45 PM](https://user-images.githubusercontent.com/83692067/121700163-421a1e80-caed-11eb-9e26-115fe13f96ab.png)

## How to reproduce

1. Open localhost:9000 to run the sample HotR.O.D application
2. Click on a customer's name to order a car
3. Click on 'find trace' which comes with the car dispatch messages. For e.g.,
HotROD T750571C arriving in 2min [req: 6364-8, latency: 697ms] [find trace]

**Comment by pranay01** [comment]
@ankit01-oss Are you running this with SigNoz? The default links in HOTROD are designed for Jaegar. I am  assuming you are not running Jaeger
