### ISSUE TITLE
unescape the logs body and make the json prettier.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#1746]
## Bug description

Right now escaped characters are not handled properly in the UI. We can escape them and parse it if it is a JSON

**Comment by pranay01** [comment]
@nityanandagohain Can you add more details to the issues? Are you referring to the `body` field in logs detail view?

**Comment by nityanandagohain** [comment]
Right the escape characters should not be displayed.

Also if we can identify the data as json then we can prettify it .

**Comment by nityanandagohain** [comment]
Done
