### ISSUE TITLE
Traces page crashes on Signoz Frontend due to incompatible json parsing

### ISSUE THREAD

**Issue by abhinavramana** [SigNoz/signoz#1747]
## Bug description
Some traces pages crash and show black screen even though the relevant logs page works. See images below:
![trace page backend no errors](https://user-images.githubusercontent.com/4195703/203614784-dd63a649-6442-4c25-b909-87143751c7d1.png)
![trace page frontend crashes](https://user-images.githubusercontent.com/4195703/203614789-1e1aa311-23b2-4ce7-aeda-0052c9c9265d.png)
![logs work](https://user-images.githubusercontent.com/4195703/203614794-f9b5e248-95d7-4a85-b8e4-d86c376a3434.png)

## Expected behavior

Traces page shouldn't crash especially if the backend response is correct (the logs page works perfectly for the same trace)

## How to reproduce

1. Open a traces page
2. Some of them just show black screen

To properly reproduce, you may have to somehow INJECT the jsons that are failing that are coming as part of traces:
```
[{"columns":["__time","SpanId","TraceId","ServiceName","Name","Kind","DurationNano","TagsKeys","TagsValues","References","Events","HasError"],"events":[[1668536065656,"b6b1291680e5a409","992f27c1def0fd57b4bf4cd0a21cdfd1","paint-service-backend-prod","/api/exports/ http receive","1","41937",["service.name","telemetry.auto.version","telemetry.sdk.language","telemetry.sdk.name","telemetry.sdk.version","type"],["paint-service-backend-prod","0.34b0","python","opentelemetry","1.13.0","http.request"],["{TraceId=992f27c1def0fd57b4bf4cd0a21cdfd1, SpanId=402e8572029e0540, RefType=CHILD_OF}"],[],false],[1668536065681,"dfd01cc76e76aa02","992f27c1def0fd57b4bf4cd0a21cdfd1","paint-service-backend-prod","/api/exports/ http send","1","323803",["http.status_code","service.name","telemetry.auto.version","telemetry.sdk.language","telemetry.sdk.name","telemetry.sdk.version","type"],["500","paint-service-backend-prod","0.34b0","python","opentelemetry","1.13.0","http.response.start"],["{TraceId=992f27c1def0fd57b4bf4cd0a21cdfd1, SpanId=402e8572029e0540, RefType=CHILD_OF}"],[],true],[1668536065681,"9b47310dd265e594","992f27c1def0fd57b4bf4cd0a21cdfd1","paint-service-backend-prod","/api/exports/ http send","1","227992",["service.name","telemetry.auto.version","telemetry.sdk.language","telemetry.sdk.name","telemetry.sdk.version","type"],["paint-service-backend-prod","0.34b0","python","opentelemetry","1.13.0","http.response.body"],["{TraceId=992f27c1def0fd57b4bf4cd0a21cdfd1, SpanId=402e8572029e0540, RefType=CHILD_OF}"],[],false],[1668536065656,"402e8572029e0540","992f27c1def0fd57b4bf4cd0a21cdfd1","paint-service-backend-prod","/api/exports/","2","26023535",["telemetry.sdk.version","http.host","http.status_code","net.peer.ip","http.url","telemetry.auto.version","telemetry.sdk.language","http.route","http.scheme","http.target","net.peer.port","http.flavor","http.method","net.host.port","telemetry.sdk.name","http.server_name","http.user_agent","service.name"],["1.13.0","172.31.51.42:8000","500","172.31.33.28","http://172.31.51.42:8000/api/exports/","0.34b0","python","/api/exports/","http","/api/exports/","63788","1.1","POST","8000","opentelemetry","paint.api.wombo.ai","Dream/1 CFNetwork/1335.0.3 Darwin/21.6.0","paint-service-backend-prod"],["{TraceId=992f27c1def0fd57b4bf4cd0a21cdfd1, SpanId=, RefType=CHILD_OF}"],[],true],[1668536065659,"5acd78441d8d4d64","992f27c1def0fd57b4bf4cd0a21cdfd1","paint-service-backend-prod","HTTP GET","3","20528351",["telemetry.sdk.version","http.method","http.url","service.name","telemetry.auto.version","telemetry.sdk.language","telemetry.sdk.name"],["1.13.0","GET","https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com","paint-service-backend-prod","0.34b0","python","opentelemetry"],["{TraceId=992f27c1def0fd57b4bf4cd0a21cdfd1, SpanId=402e8572029e0540, RefType=CHILD_OF}"],["{\"name\":\"exception\",\"timeUnixNano\":1668536065679561528,\"attributeMap\":{\"exception.escaped\":\"False\",\"exception.message\":\"(\\\"Connection broken: OSError(28, 'No space left on device')\\\", OSError(28, 'No space left on device'))\",\"exception.stacktrace\":\"Traceback (most recent call last):\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/response.py\\\", line 443, in _error_catcher\\n    yield\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/response.py\\\", line 566, in read\\n    data = self._fp_read(amt) if not fp_closed else b\\\"\\\"\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/response.py\\\", line 532, in _fp_read\\n    return self._fp.read(amt) if amt is not None else self._fp.read()\\n  File \\\"/opt/venv/lib/python3.9/site-packages/cachecontrol/filewrapper.py\\\", line 96, in read\\n    self._close()\\n  File \\\"/opt/venv/lib/python3.9/site-packages/cachecontrol/filewrapper.py\\\", line 72, in _close\\n    self.__buf.seek(0, 0)\\n  File \\\"/usr/local/lib/python3.9/tempfile.py\\\", line 474, in func_wrapper\\n    return func(*args, **kwargs)\\nOSError: [Errno 28] No space left on device\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/models.py\\\", line 760, in generate\\n    for chunk in self.raw.stream(chunk_size, decode_content=True):\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/response.py\\\", line 627, in stream\\n    data = self.read(amt=amt, decode_content=decode_content)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/response.py\\\", line 592, in read\\n    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)\\n  File \\\"/usr/local/lib/python3.9/contextlib.py\\\", line 135, in __exit__\\n    self.gen.throw(type, value, traceback)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/response.py\\\", line 460, in _error_catcher\\n    raise ProtocolError(\\\"Connection broken: %r\\\" % e, e)\\nurllib3.exceptions.ProtocolError: (\\\"Connection broken: OSError(28, 'No space left on device')\\\", OSError(28, 'No space left on device'))\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"/opt/venv/lib/python3.9/site-packages/opentelemetry/trace/__init__.py\\\", line 573, in use_span\\n    yield span\\n  File \\\"/opt/venv/lib/python3.9/site-packages/opentelemetry/sdk/trace/__init__.py\\\", line 1033, in start_as_current_span\\n    yield span_context\\n  File \\\"/opt/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/requests/__init__.py\\\", line 244, in _instrumented_requests_call\\n    raise exception.with_traceback(exception.__traceback__)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/requests/__init__.py\\\", line 208, in _instrumented_requests_call\\n    result = call_wrapped()  # *** PROCEED\\n  File \\\"/opt/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/requests/__init__.py\\\", line 125, in call_wrapped\\n    return wrapped_request(self, method, url, *args, **kwargs)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/sessions.py\\\", line 529, in request\\n    resp = self.send(prep, **send_kwargs)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/requests/__init__.py\\\", line 147, in instrumented_send\\n    return _instrumented_requests_call(\\n  File \\\"/opt/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/requests/__init__.py\\\", line 158, in _instrumented_requests_call\\n    return call_wrapped()\\n  File \\\"/opt/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/requests/__init__.py\\\", line 145, in call_wrapped\\n    return wrapped_send(self, request, **kwargs)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/sessions.py\\\", line 687, in send\\n    r.content\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/models.py\\\", line 838, in content\\n    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/models.py\\\", line 763, in generate\\n    raise ChunkedEncodingError(e)\\nrequests.exceptions.ChunkedEncodingError: (\\\"Connection broken: OSError(28, 'No space left on device')\\\", OSError(28, 'No space left on device'))\\n\",\"exception.type\":\"ChunkedEncodingError\"},\"isError\":true}"],true]]}]
```

## Version information 
* **Signoz version**: v0.11.3
* **Browser version**: Mozilla Firefox (But affects all)
* **Your OS and version**: Ubuntu 22.04, MAC OS  (But affects all)
* **Your CPU Architecture**(ARM/Intel): Intel, ARM

**Comment by abhinavramana** [comment]
Another one:
```"{\"name\":\"exception\",\"timeUnixNano\":1668536065679561528,\"attributeMap\":{\"exception.escaped\":\"False\",\"exception.message\":\"(\\\"Connection broken: OSError(28, 'No space left on device')\\\", OSError(28, 'No space left on device'))\",\"exception.stacktrace\":\"Traceback (most recent call last):\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/response.py\\\", line 443, in _error_catcher\\n    yield\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/response.py\\\", line 566, in read\\n    data = self._fp_read(amt) if not fp_closed else b\\\"\\\"\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/response.py\\\", line 532, in _fp_read\\n    return self._fp.read(amt) if amt is not None else self._fp.read()\\n  File \\\"/opt/venv/lib/python3.9/site-packages/cachecontrol/filewrapper.py\\\", line 96, in read\\n    self._close()\\n  File \\\"/opt/venv/lib/python3.9/site-packages/cachecontrol/filewrapper.py\\\", line 72, in _close\\n    self.__buf.seek(0, 0)\\n  File \\\"/usr/local/lib/python3.9/tempfile.py\\\", line 474, in func_wrapper\\n    return func(*args, **kwargs)\\nOSError: [Errno 28] No space left on device\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/models.py\\\", line 760, in generate\\n    for chunk in self.raw.stream(chunk_size, decode_content=True):\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/response.py\\\", line 627, in stream\\n    data = self.read(amt=amt, decode_content=decode_content)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/response.py\\\", line 592, in read\\n    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)\\n  File \\\"/usr/local/lib/python3.9/contextlib.py\\\", line 135, in __exit__\\n    self.gen.throw(type, value, traceback)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/response.py\\\", line 460, in _error_catcher\\n    raise ProtocolError(\\\"Connection broken: %r\\\" % e, e)\\nurllib3.exceptions.ProtocolError: (\\\"Connection broken: OSError(28, 'No space left on device')\\\", OSError(28, 'No space left on device'))\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"/opt/venv/lib/python3.9/site-packages/opentelemetry/trace/__init__.py\\\", line 573, in use_span\\n    yield span\\n  File \\\"/opt/venv/lib/python3.9/site-packages/opentelemetry/sdk/trace/__init__.py\\\", line 1033, in start_as_current_span\\n    yield span_context\\n  File \\\"/opt/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/requests/__init__.py\\\", line 244, in _instrumented_requests_call\\n    raise exception.with_traceback(exception.__traceback__)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/requests/__init__.py\\\", line 208, in _instrumented_requests_call\\n    result = call_wrapped()  # *** PROCEED\\n  File \\\"/opt/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/requests/__init__.py\\\", line 125, in call_wrapped\\n    return wrapped_request(self, method, url, *args, **kwargs)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/sessions.py\\\", line 529, in request\\n    resp = self.send(prep, **send_kwargs)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/requests/__init__.py\\\", line 147, in instrumented_send\\n    return _instrumented_requests_call(\\n  File \\\"/opt/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/requests/__init__.py\\\", line 158, in _instrumented_requests_call\\n    return call_wrapped()\\n  File \\\"/opt/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/requests/__init__.py\\\", line 145, in call_wrapped\\n    return wrapped_send(self, request, **kwargs)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/sessions.py\\\", line 687, in send\\n    r.content\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/models.py\\\", line 838, in content\\n    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/models.py\\\", line 763, in generate\\n    raise ChunkedEncodingError(e)\\nrequests.exceptions.ChunkedEncodingError: (\\\"Connection broken: OSError(28, 'No space left on device')\\\", OSError(28, 'No space left on device'))\\n\",\"exception.type\":\"ChunkedEncodingError\"},\"isError\":true}"```

**Comment by learning-dev** [comment]
Hi @ankitnayan @palashgdev  can you please assign this to me?

**Comment by palashgdev** [comment]
> Hi @ankitnayan @palashgdev can you please assign this to me?

Hi @learning-dev you can look into other issues you can always get started just by picking good-first-issues
