### ISSUE TITLE
How to delete the Resource Attribute Value from Signoz Dropdown

### ISSUE THREAD

**Issue by ankitasalunkhe** [SigNoz/signoz#1750]
Hii,

I have Signoz the show the matrices for my application on that. So I have created Resource attribute like service.namespace and deployment.environments and added the value over there.
I have replaced the old value with new one.
So on signoz its showing both the values.
So can you please help me to remove the old value from dropdown on signoz.

Thanks,

**Comment by ankitnayan** [comment]
Connect to the clickhouse instance using the below docs:
https://signoz.io/docs/operate/clickhouse/connect-to-clickhouse/#docker


Replace *xxxxx* in the below query with the timeseries you want to remove:

```
alter table  signoz_metrics.time_series_v2 delete where metric_name='signoz_calls_total' and JSONExtractString(labels, 'resource_deployment_environment')='XXXXXXX';
```
