### ISSUE TITLE
Evaluate Apache Iceberg for long term storage of logs

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1753]
Iceberg project seems to be getting increasing interest

Provides some nice features like 
- Full Schema Evolution
- Advanced partitioning

Project page - https://iceberg.apache.org/

References
----

Introductory post which is showing cost benefits
https://medium.com/insiderengineering/apache-iceberg-reduced-our-amazon-s3-cost-by-90-997cde5ce931

Post from Uber on big data file format - https://www.uber.com/en-IE/blog/cost-efficiency-big-data/

**Comment by ankitnayan** [comment]
clickhouse looks good for now
