### ISSUE TITLE
Log view to Trace view

### ISSUE THREAD

**Issue by ishworg** [SigNoz/signoz#1755]
## Is your feature request related to a problem?

If I am currently in the logs view, after getting trace id log lines to match, is there a way to click and land in the trace view? it might be a UI related.

## Describe the solution you'd like

In the log view, if I click a trace ID or span ID, I would like to land on the trace view. A plus would be being able to land back from trace view to log view.

## Additional context

When we use log lines with trace and span IDs in it, we would like them to go at the least unidirectional from Log view to Trace view.

eg.
```
{"level":"info","msg":"test","key":"val","timestamp":"2022-11-25T12:34:58.523+1100","trace_id":"63801bc21c9a3cc4b55e2c8d2d2a2c58","span_id":"a022cfbfcd5dd1d9"}
```

#### *Thank you* for your feature request – we love each and every one!

Thank you for signoz.

**Comment by ishworg** [comment]
Hey @Xonman here is the MR. Thanks mate.

**Comment by YounixM** [comment]
This is done ✅. Closing the issue.
