### ISSUE TITLE
Log count graph jumps twice when changing filter

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1769]
## Bug description

Log count graph jumps twice when changing filter

## Expected behavior

The log count graph shouldn't have a jumpy behavior

## How to reproduce

1. Go to Logs page
2. Add filters by clicking selected fields in log lines
3. Check the count graph

## Version information 
* **Signoz version**: v0.11.4-rc3
* **Browser version**:  Chrome Version 107.0.5304.110 (Official Build) (arm64)
* **Your OS and version**: macOS 13.0 (22A380)
* **Your CPU Architecture**(ARM/Intel): ARM

## Additional context

Loom Video - https://www.loom.com/share/ea53f972863d4f64be0e827f8eb57e3f

**Comment by ankitnayan** [comment]
fixed
