### ISSUE TITLE
Over flowing fields in logs query builder when fields with long text is selected

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1770]
## Bug description

Over flowing fields in logs query builder when fields with long text is selected

## Expected behavior

The long field text should be wrapped in the logs query builder 

## How to reproduce

1. Go to Logs page
2. Add filters by clicking selected fields in log lines. select a field which has long text value
3. Check the query builder
4. The long field text overflows the query builder

## Version information 
* **Signoz version**: v0.11.4-rc3
* **Browser version**:  Chrome Version 107.0.5304.110 (Official Build) (arm64)
* **Your OS and version**: macOS 13.0 (22A380)
* **Your CPU Architecture**(ARM/Intel): ARM

## Additional context

Loom Video - https://www.loom.com/share/c80d4cf696d34a07b1335572909c9124

**Comment by ankitnayan** [comment]
new explorer page released
