### ISSUE TITLE
Kubernetes installation fails

### ISSUE THREAD

**Issue by sjcotto** [SigNoz/signoz#1773]
## Bug description

Kubernetse instalation fails

Following the docs

https://signoz.io/docs/install/kubernetes/others/

after execution the helm install

```
helm --namespace platform install my-release signoz/signoz
```

returns an error

```
Error: template: signoz/charts/k8s-infra/templates/otel-deployment/deployment.yaml:64:24: executing "signoz/charts/k8s-infra/templates/otel-deployment/deployment.yaml" at <include "otel.endpoint" .>: error calling include: template: signoz/charts/k8s-infra/templates/_helpers.tpl:249:22: executing "otel.endpoint" at <.Chart.IsRoot>: can't evaluate field IsRoot in type interface {}
```

**Comment by prashant-shahi** [comment]
@sjcotto Helm version >= 3.8 is prerequisite for the Helm chart.

You could upgrade your helm version to resolve this issue.
Do let us know if the issue persists.
