### ISSUE TITLE
Enable search of tags in trace detail page

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#1777]
In the waterfall view, when we click on a span, a list of attributes is shown in the right panel. If the number of attributes is high, it becomes difficult to find an attribute as there is no ordering of attributes.

As a solution, we can create a search box which can be used to filter the attributes by keys.

**Comment by ankitnayan** [comment]
@pranay01 should we hide the search box if the number of attributes is less than 5?

**Comment by pranay01** [comment]
Yeah, would make sense
