### ISSUE TITLE
Flamegraph - sort children by startTime

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#178]
## Current Behaviour
The flamegraph sorts the siblings in ascending order by frame's name. 
The reference to code is [here](https://github.com/SigNoz/signoz/blob/main/frontend/src/modules/Traces/TraceGraph.tsx#L64)

## Expected Behaviour
The siblings should appear in order of their start time. 
This can be achieved according to library docs mentioned [here](https://github.com/spiermar/d3-flame-graph/blob/d23276005fa253a9d67e002833d8286e728ceebb/README.md#sort)

**Comment by ankitnayan** [comment]
@nidhi-tandon can you please detail out the issue faced here. We can check with fellow contributors

**Comment by MoroIddrisu** [comment]
Hello

**Comment by pranay01** [comment]
fixed by https://github.com/SigNoz/signoz/pull/764 - Updated trace detail page design
