### ISSUE TITLE
Enable pre-built dashboards for opentelemetry collectors

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#1780]
Below charts for metrics, logs and traces would give a lot of visibility into opentelemetry collectors deployed at SigNoz.

- [x] Receiver Acceptance Rate
- [x] Receiver Rejection Rate
- [x] Exporter Sending Rate
- [x] Exporter Failing Rate
- [x] Dropping Rate
- [ ] Export new metrics on avg export latency

**Comment by prashant-shahi** [comment]
Resolved by https://github.com/SigNoz/engineering-pod/pull/936
