### ISSUE TITLE
Evaluate query performance in distributed setup

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#1781]
Evaluate query performance and data correctness based on sharding by traceID (in spans), fingerprint (in metrics) and id (in logs). Altogether we are using some sort of random loadbalancing in the end.

Does a query with some filters perform better when data is fetched from multiple shards or is limited to the processing speed of a single shard?

**Comment by makeavish** [comment]
Answered here:
https://github.com/SigNoz/signoz/issues/1783#issuecomment-1337612608
