### ISSUE TITLE
Enable communication between opentelemetry collector and query-service

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#1786]
Usecases when the otel-collector config needs to be updated from UI:
- burst protection
- auth for ingestion using api_key
- logs to metrics processor
- logs parsing from the UI
- sampling
- drop rules

**Comment by ankitnayan** [comment]
https://github.com/SigNoz/engineering-pod/issues/853

**Comment by srikanthccv** [comment]
I will be sending a series of small PRs for the collector repo first. Here is the rough plan

- Add wrapper signoz collector that runs the otelcol.Collector
- Add a simple Client that runs Collector without any OpAMP capabilities (as it is today)
- Add a config manager implementation that is responsible for running/restarting/rollbacking
- Add a server Client that works with the config manager to add OpAMP capabilities
- Add a service interface that runs the one of Client implementation
- Wire it all up.

**Comment by srikanthccv** [comment]
We have OpAMP running pretty well for quite some time now. This is completed.
