### ISSUE TITLE
Set anti-affinity for distributed setup

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#1790]
- [x] setup clickhouse anti-affinity for hostname topology
- [x] setup otel-collectors anti-affinity for pods in the same hostname

**Comment by prashant-shahi** [comment]
- Not setting any default value for `podDistribution` of ClickHouse but only in the comment
- Using `topologySpreadConstraints` instead of anti-affinity to spread `otel-collector` pods across all nodes irrespective of replica count.
