### ISSUE TITLE
Logs to traces correlation - Going from Logs details  to traces filter page if logs have traceid/spanid

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1799]
If a logs item has traceID/spanID it should also have a hyperlink which users can click and directly go to that traceID/spanID in the trace detail view

**Comment by nityanandagohain** [comment]
related to https://github.com/SigNoz/signoz/issues/2230

**Comment by nityanandagohain** [comment]
Released in v0.19.0
