### ISSUE TITLE
Better docs for getting logs from files

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1804]
Current [docs](https://signoz.io/docs/userguide/collect_logs_from_file/) for ingesting logs from a file to SigNoz leaves lot to be desired. The current example takes a particular example, but users may be sending logs in many possible formats and the docs doesn't explain clearly how does parsing and mapping of attributes works in otel collector.

It would be great if we can add more examples with files having different type of logs

**Comment by pranay01** [comment]
For example what should be the parsing and attribute mapping entries be on otel-collector-config when a log file has log lines like this
`{"level":"info","message":"message was served","service":"node-service"}
`

**Comment by ankitnayan** [comment]
docs released
