### ISSUE TITLE
Default current timestamp if timestamp not present or timestamp parsing fails.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#1806]
## Is your feature request related to a problem?

As of now if there is no timestamp present in logs it is set to epoch 0, which makes it difficult to debug.

## Describe the solution you'd like

We can set it to current time when the log is received by the collector.

**Comment by pranay01** [comment]
I think otel collector has something called [observed timestamp](https://opentelemetry.io/docs/reference/specification/logs/data-model/#log-and-event-record-definition) can we use this?

**Comment by nityanandagohain** [comment]
yes, we do have to observed timestamp, but I think we shouldn't use it for timerange filtering and should rely on only one field. It should be kept as a reference to check when the log was received.
