### ISSUE TITLE
Logs not showing up in the UI. 

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#1809]
There are a few instances where logs might not show up in the UI.
This issue will have all the cases because of which the issue might occur and the solutions related to it.

**Comment by pranay01** [comment]
Logs doesn't show up in SigNoz UI when timestamo is not present in log line. e.g.
`{"level":"info","message":"message was served","service":"node-service"}
`

**Comment by nityanandagohain** [comment]
Few scenarios that we have seen.
* Timestamp is not present in logs generated by service - Each log line should have a corresponding timestamp attached to it.
   eg:- `{"time": "2022-09-01T11:12:36.901569069+1100", "level":"info","message":"message was served","service":"node-service"}`
* Timestamp is not parsed correctly in otel collector- Timestamp present in logs should be parsed by using the [time_parser](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/time_parser.md) provided by opentelemetry.
* [Timezone discrepencies](https://github.com/SigNoz/signoz/issues/1774) - Issues might occur when you change timezone in your machine. In the issue linked user changed the timezone but missed restarting rsyslog

**Comment by nityanandagohain** [comment]
Closing this, now by default timestamp is added by Otel-collector if it is not parsed by the user.

Timezone discrepancy will still remain, but the user can fix that on their machine.
