### ISSUE TITLE
Not suggesting another port if same port is used on localhost

### ISSUE THREAD

**Issue by rahulrana95** [SigNoz/signoz#181]
## Bug description

*Please describe.*  
When we run 'yarn dev' on localhost it try to open localhost on port 3000, while if the port is being used it not suggesting to open another port or randomly opening any new port.
*If this affects the front-end, screenshots would be of great help.*  
If same port is being used then localhost:3000 will keep loading, no errors
Confusing for people.

## Expected behavior

Should show that this port is used and open on any new port available

## How to reproduce

1. open any other project on same port
2. run yarn dev
3. see it will  not work on localhost:3000

## Version information 
* **Signoz version**:
* **Browser version**:
* **Your OS and version**:

**Comment by makeavish** [comment]
Port has been moved to `3301` which is not used by other apps/services thus avoiding conflicts.
Closing it. Reopen if required.
