### ISSUE TITLE
Need docs on how to configure SAML and SSO

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1811]
We currently don't have generic docs apart from the [keycloak tutorial](https://signoz.io/docs/tutorial/setting-up-sso-saml-with-keycloak/#steps-to-set-up-saml)

We should have docs on how to configure this for LDAP, Active Directory etc.

**Comment by makeavish** [comment]
We have a generic doc now: https://signoz.io/docs/userguide/sso-authentication/
