### ISSUE TITLE
Trace Detail Page is blank when trace detail of a span is not found

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#1815]
We should show 404 with error Trace not found when trace id is not found.

https://www.loom.com/share/8f33d770a9434127879685af512f5024

**Comment by palashgdev** [comment]
@pranay01 need a design in this one where events are empty 

possible reason 

1. latency
1. not found

**Comment by pranay01** [comment]
@palashgdev we can use existing 404 page

We can show the error message where we are displaying `Not Found` in the attached screenshot

![404-page](https://user-images.githubusercontent.com/504541/208414368-def2381b-0f53-4b3d-acb9-8628ac740089.png)
