### ISSUE TITLE
Clickhouse container not coming up on M1 chip macbook Pro

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#182]
## Bug description

On trying to install clickhouse setup in M1 Chip Macbook pro via docker, Clickhouse container doesn't come up

## Expected behavior
SigNoz should be installed successfully even on M1 chip Macbook

## How to reproduce

1. `git clone https://github.com/SigNoz/signoz.git && cd signoz/deploy/`
2. `./install.sh`
3. Choose clickhouse as the option

Clickhouse container fails to get started. Attaching logs for the container

## Version information 
* **Signoz version**:
* **Browser version**:
* **Your OS and version**: Macbook Pro 2020 model

## Additional context

![photo_2021-06-22 01 21 39](https://user-images.githubusercontent.com/504541/122819536-381bcb00-d2f8-11eb-8633-b2e8e37e4326.jpeg)

**Comment by MoroIddrisu** [comment]
Hello
