### ISSUE TITLE
Auto Refresh on dashboards

### ISSUE THREAD

**Issue by sbusetty-rythmos** [SigNoz/signoz#183]
## Is your feature request related to a problem?

*Currently we dont have auto refresh feature. We need to click refresh button to get the dashboards refreshed*

## Describe the solution you'd like

We need to have auto refresh feature so the dashboards get refreshed and we can see the stats without refreshing everytime.

#### *Thank you* for your feature request – we love each and every one!

**Comment by makeavish** [comment]
Added in https://github.com/SigNoz/signoz/pull/1712
