### ISSUE TITLE
Filter for only showing top-level spans

### ISSUE THREAD

**Issue by elbaro** [SigNoz/signoz#1834]
## Is your feature request related to a problem?

My page "Traces" is filled with subspans. Sub-spans names are sometimes not meaningful without the root span name.

## Describe the solution you'd like

Option1. Add a checkbox, when clicked it only shows the top-level spans (spans without the parent).
Option2. Add a span-depth (0, 1, ..) filter, so it only shows the spans less than or equal to the given depth.

**Comment by pranay01** [comment]
@elbaro Can you share an example where
> Sub-spans names are sometimes not meaningful without the root span name.

**Comment by elbaro** [comment]
```py
with span("job A"):
    for i in range(10):
        with span(f"Trial {i}"):
            try:
              run_a()
              break
           except:
              pass
```

```py
with span("Training a ML model"):
  for epoch in range(100):
    with span(f"Epoch {epoch}"):
        for batch in ..:
           ..
```

```py
with span("Long running task"):
   with span("Data Preparation"):
     ..
   with span("Preproessing"):
     ..
   with span("Upload"):
     ..
```

I want to monitor them in units of "Long running task" or "Training a ML model", not "Epoch 93" or "Trial 3".
Also "Trial 3" could be a part of the job A or job B.

**Comment by djMax** [comment]
This is a basic piece of functionality for a distributed tracing system of any volume. I am kind of surprised this issue has been around for a year.

**Comment by ankitnayan** [comment]
cc @makeavish

**Comment by makeavish** [comment]
> This is a basic piece of functionality for a distributed tracing system of any volume. I am kind of surprised this issue has been around for a year.

@djMax This is available on new trace explorer page:

<img width="1226" alt="Screenshot 2023-11-28 at 10 43 26" src="https://github.com/SigNoz/signoz/assets/9512100/a095793b-764e-4cf0-915c-b60c1eb2556e">
