### ISSUE TITLE
Inconsistencies in Signoz front-end regarding logs that exist

### ISSUE THREAD

**Issue by navyamehta** [SigNoz/signoz#1842]
## Bug description
Front-end issue, attached video: 

https://user-images.githubusercontent.com/45111560/206733328-fc6e7d9e-4e7b-4663-9389-ff24ad26b39f.mov

Please watch the attached video. For a certain trace_id, it is known (and can be seen) that logs do exist. However, the first time we search for the logs, they don't appear (and they appear briefly while scrolling and then vanish). On a second search, the logs appear correctly. 

## Expected behavior
The logs should appear correctly on the first search.

## How to reproduce
Have multiple services in Signoz (our system processes >90k logs an hour). Search seems to show inconsistencies.

## Version information 
* **Signoz version**: 0.11.4
* **Browser version**: Chrome 107.0.5304.87
* **Your OS and version**: Signoz cluster runs on m6a.16xlarge in AWS

**Comment by pranay01** [comment]
@navyamehta Thanks for sharing the issue. Are you seeing this behavior only for a specific attribute (`trace_id`) or you noticed this for any other attributes as well.

**Comment by abhinavramana** [comment]
Trace is  the most common form we search for logs. So definitely it happens for that. But I do believe it happens for other indirect attributes like body as well

**Comment by navyamehta** [comment]
Yupp we've seen this for other attributes too, it seems even more pronounced sometimes when searching via 'body contains ...'.

**Comment by ankitnayan** [comment]
@navyamehta do you still see such an issue with `v0.12.0`?

**Comment by pranay01** [comment]
@navyamehta This issue should be solved with https://github.com/SigNoz/signoz/releases/tag/v0.13.0

Feel free to re-open if you see the issue persisting
