### ISSUE TITLE
Compact and/or customisable log view layout

### ISSUE THREAD

**Issue by wfhartford** [SigNoz/signoz#1848]
## Is your feature request related to a problem?

I would like to be able to read application log messages in a format similar to a typical log file.

## Describe the solution you'd like

An option on the view log events screen which displays one log event per line showing just the most vital information, such as timestamp, log level, logger name, and message text. Ideally there should be a way to customize the fields shown; for example, there may be cases where host name is important, but logger name is not.

## Describe alternatives you've considered

The current log view, which shows the message and timestamp in a JSON format is usable, but each log message takes up a lot of screen space, making it harder on the eyes to scan log messages.

## Additional context
Attached image shows the current log view, this large image shows only three log entries.
![image](https://user-images.githubusercontent.com/717585/206861647-ce2743dc-43fe-4462-8687-58376d39a2f2.png)

Compare the above to a comparable screen in Elastic Kibana, where a much smaller area displays far more information:
![image](https://user-images.githubusercontent.com/717585/206861942-e3f2bb44-23c5-46a4-93ae-28d21f877561.png)

**Comment by pranay01** [comment]
thanks for opening the issue @wfhartford
