### ISSUE TITLE
FE: invite token error message for 2nd sign up

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/signoz#1860]
First signup being admin user, after that if anyone tries to signup, we throw the error message saying  invalid invite token but it should be something like “root admin user already exists, ask admin to invite”
[Slack Message](https://signoz-community.slack.com/archives/C01HWUTP4HH/p1671120745525799?thread_ts=1671120745.525799&cid=C01HWUTP4HH)

**Comment by prashant-shahi** [comment]
We should be able to create an admin account, which is the first account after an installation.
Only for 2nd or later account we need an invite link, which can be issued by the Admin account(s).

**Comment by pranay01** [comment]
`If you want to Sign Up, please ask your admin to send an invite`

**Comment by pranay01** [comment]
If no user exists, directly open signup page on on visiting login page

If a user exists, please remove the following message from the login page
`If you are setting up SigNoz for the first time, Create an account`

**Comment by makeavish** [comment]
This should be already fixed.
