### ISSUE TITLE
FE: Dashboard plotting all charts with new data when only one widget is modified

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/signoz#1865]
## In what situation are you experiencing subpar performance?

When multiple widgets present in a single dashboard, modifying one widget causes all widgets to be plotted again with new data.

## How to reproduce

1. Load Hostmetrics Dashboard or any other dashboard with many widgets
2. Modify one of the widgets
3. Save the widget which returns you back to the dashboard page loading all widgets

/cc @ankitnayan @palashgdev

**Comment by ankitnayan** [comment]
I think it is reloaded because the time interval `now - X minutes` changed. I can see the same behaviour for grafana too. Have a look at https://play.grafana.org/d/000000029/prometheus-demo-dashboard?orgId=1&from=now-24h&to=now&refresh=5m

@pranay01 @srikanthccv @prashant-shahi what do you think?

**Comment by srikanthccv** [comment]
We could also put the loader very small in the corner when one of the widgets gets modified. 

>I think it is reloaded because the time interval now - X minutes changed

Since the time difference won't be much, there won't be a major change in the time series plot. It makes sense to put a small loader in the corner to indicate this plot might show little old data but update when the new data arrives.

**Comment by ankitnayan** [comment]
created another issue based on above interaction

**Comment by pranay01** [comment]
@ankitnayan This UX seems fine

> Since the time difference won't be much, there won't be a major change in the time series plot. It makes sense to put a small loader in the corner to indicate this plot might show little old data but update when the new data arrives.
