### ISSUE TITLE
Ability to filter by service name in Exceptions page

### ISSUE THREAD

**Issue by abhinavramana** [SigNoz/signoz#1882]
## Is your feature request related to a problem?
The problem is that we just want to look at the exceptions of a newly deployed service usually. However, when we have lots of services, it is very difficult to see all major exceptions in 1 go

## Describe the solution you'd like
There is a time filter already, would like to see a filter for service name

**Comment by ankitnayan** [comment]
This still exists today as part of filtering from frontend

<img width="417" alt="Screenshot 2022-12-20 at 11 02 37 PM" src="https://user-images.githubusercontent.com/12460410/208729749-937cc7b4-ea55-4403-b8a3-eef316884b03.png">

**Comment by abhinavramana** [comment]
I see, it was really not very visible, but you can close the issue
