### ISSUE TITLE
Grouping ability in Exceptions page

### ISSUE THREAD

**Issue by abhinavramana** [SigNoz/signoz#1883]
## Is your feature request related to a problem?

The main use-case for exceptions page is that whenever new deploy happens, I should be able to see most common exceptions that happened. However, signoz groups everything by ExceptionType+ExceptionMessage, and we usually have same exception message except some values:
![image](https://user-images.githubusercontent.com/4195703/208722265-3a0ad14b-bf5f-4f57-aa08-55af34e6726d.png)
This results in pages of useless exceptions since they are all the same

## Describe the solution you'd like

Now its good to have exception_type+exception_message grouping, but it would be beneficial if users are given a choice to group by exception_type only just to see all different exceptions

**Comment by ankitnayan** [comment]
@makeavish can we enable this as part of user defined config or env?

**Comment by makeavish** [comment]
@ankitnayan Yes, it's possible to allow users to group exceptions based on provided config but the grouping will be only done for newer data.

**Comment by ankitnayan** [comment]
> 

That should be fine IMO

**Comment by abhinavramana** [comment]
The main thing is an option to ignore grouping by exception message.

My suggestion: Have a checkbox to do the same

So group by then becomes just by exception type and application name. NOTE: The service name filter should still work!

**Comment by makeavish** [comment]
@abhinavramana We can enable a config that will allow you to ignore grouping by exception message. But you will need to restart otel collector to apply the config and the config will be applied only to new data. So, old data will be grouped by previous config.

Let us know if that works for you.

**Comment by abhinavramana** [comment]
Yes that works.
