### ISSUE TITLE
TraceDetail page has error and no content is rendered: Cannot read properties of undefined (reading 'startTime')

### ISSUE THREAD

**Issue by MikhailNazarov** [SigNoz/signoz#1898]
## Bug description
TraceDetail page has error and no content is rendered:

main.455cd5ddbc1d313a1149.js:2 TypeError: Cannot read properties of undefined (reading 'startTime')
    at A (TraceDetail Page.f417213c047acd24647e.js:formatted:2531:35)
    at za (main.455cd5ddbc1d313a1149.js:2:2126978)
    at xc (main.455cd5ddbc1d313a1149.js:2:2179095)
    at iu (main.455cd5ddbc1d313a1149.js:2:2166332)
    at ru (main.455cd5ddbc1d313a1149.js:2:2166260)
    at nu (main.455cd5ddbc1d313a1149.js:2:2166123)
    at Xc (main.455cd5ddbc1d313a1149.js:2:2163110)
    at main.455cd5ddbc1d313a1149.js:2:2112897
    at t.unstable_runWithPriority (main.455cd5ddbc1d313a1149.js:2:2520854)
    at wi (main.455cd5ddbc1d313a1149.js:2:2112674)

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  
![image](https://user-images.githubusercontent.com/1934951/209098778-4da1671a-21a9-4cfe-98ae-6fc9d5f1f25f.png)

## How to reproduce

Open trace details page

## Version information 
* **Signoz version**: 0.12.0
* **Browser version**:  Yandex Browser 22.11.0.2484
 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 YaBrowser/22.11.0.2484 Yowser/2.5 Safari/537.36
* **Your OS and version**:  ArchLinux Gnome 43.2
* **Your CPU Architecture**(ARM/Intel): Intel Core i7-10700K

**Comment by pranay01** [comment]
@MikhailNazarov This is a bug which was introduced in v0.12.0. We will ship a fix for this in the next release. 

How often are you seeing this?
This should appear only when the trace is missing root span

**Comment by pranay01** [comment]
>I'll try to add root span, now I have it every time

Weird, so none of your traces have a root span?

**Comment by MikhailNazarov** [comment]
Could you please tell me how to create a root span in an asynchronous application on rust tokio. I did it by analogy with your example for rust, but for some reason it doesn't work out for me.

**Comment by pranay01** [comment]
@srikanthccv Would you have any insights on this?

**Comment by srikanthccv** [comment]
@MikhailNazarov can you share the example where the root span doesn't exist? FYI here is another example with the tokio https://github.com/open-telemetry/opentelemetry-rust/blob/780dfb1e515e4fd3382e9458043612c5e8c96d88/examples/external-otlp-tonic-tokio/src/main.rs.
