### ISSUE TITLE
Integration with vector.dev

### ISSUE THREAD

**Issue by shrbb** [SigNoz/signoz#1905]
## Is your feature request related to a problem?

We are not facing any probem, requesting a feature

## Describe the solution you'd like

We would like to use vector.dev as OTEL collector

## Additional context

We have deployments of our product on different cloud environments, we need observability to all of them in a centralized Signoz

**Comment by pranay01** [comment]
@shrbb Would love to understand why would you like to use vector as a logs collector instead of native otel collector.

**Comment by shrbb** [comment]
@pranay01  Just for its performance https://medium.com/ibm-cloud/log-collectors-performance-benchmarking-8c5218a08fea

**Comment by ankitnayan** [comment]
Their support to all the three signals is slow https://github.com/vectordotdev/vector/issues/1444

**Comment by ankitnayan** [comment]
Issue tracing perf comparison - https://github.com/vectordotdev/vector/issues/13132

**Comment by shrbb** [comment]
@ankitnayan we have heavy volume of logs and multiple deployments, what is your recommendation, fluentbit or default OTEL collector 
here is our usecase https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1671171975183959

**Comment by ankitnayan** [comment]
Otel-Collector should be good. We will add more parsing support from SigNoz's UI going forward using otel-collector. You can still use [fluentbit](https://signoz.io/docs/userguide/fluentbit_to_signoz/), [fluentd](https://signoz.io/docs/userguide/fluentd_to_signoz/), [logstash](https://signoz.io/docs/userguide/logstash_to_signoz/) to forward logs to signoz

**Comment by ankitnayan** [comment]
>@ankitnayan we have heavy volume of logs and multiple deployments

How much volume are you expecting?

**Comment by shrbb** [comment]
**How much volume are you expecting?**
@ankitnayan we have data coming from thousands of IOT devices every second

**Otel-Collector should be good.** 
We are starting with logs now, later we will integrate opentelemetry for apps
Is OTEL collector enough for logs or we should use fluent bit

**Comment by nityanandagohain** [comment]
Hi @shrbb , FluentBit is something very lightweight and has less plugins as described in this blog https://logz.io/blog/fluentd-vs-fluent-bit/ . So if you are constrained on memory and cpu and you don't have complex parsing requirements  for n number of collectors/agents that you are going to use to forward your logs then you can go ahead with fluentBit.


If you don't have any memory constrains, you can go ahead with otel collector, as there is not much difference between otel and fluentD. Though with Fluentd there are a few more options for parsing logs but otel collector is catching up.

**Comment by Uburro** [comment]
hello guys
the problem with the fluent bit is that it is single-threaded and on large volumes it simply cannot cope with editing data
The problem with flunetd and logstesh is that they consume a lot of resources, while in performance they are much inferior to the same vector and even filebit

**Comment by nityanandagohain** [comment]
Interesting, thanks for sharing @Uburro

**Comment by Syn3rman** [comment]
Btw @Uburro, Fluent Bit did introduce multi-threading in the latest version: https://fluentbit.io/announcements/v1.7.0/ :)

**Comment by Uburro** [comment]
> Btw @Uburro, Fluent Bit did introduce multi-threading a while back: https://fluentbit.io/announcements/v1.7.0/ :)

Cool:)) i didn't know it.

**Comment by nityanandagohain** [comment]
SigNoz now supports receiving data from Vector in SigNoz cloud doc: https://signoz.io/docs/logs-management/send-logs/vector-logs-to-signoz/

it will be open sourced soon.
