### ISSUE TITLE
Show 'No Data' text on charts/graphs

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#1908]
On default dashboards when data is not available the graphs are blank without any message. They should show 'No Data' text.

<img width="1248" alt="Screenshot 2022-12-26 at 10 29 51" src="https://user-images.githubusercontent.com/9512100/209503384-7a917dea-854a-4b5c-9325-17c112eb72d3.png">

**Comment by mariuskimmina** [comment]
Hey,

I'd like to pick this up, if no one else is already working on this please feel free to assign me.

**Comment by makeavish** [comment]
Assigned to you @mariuskimmina 
Let us know if you need any help.
You can also join slack community: https://signoz.io/slack

**Comment by mariuskimmina** [comment]
Hey, 

I started looking into this. From what I can see, there should actually be data, the dataset is not empty.

![image](https://user-images.githubusercontent.com/38843153/211183516-ab349cc3-6d75-486f-b1fe-5b38c32b47ef.png)

If the dataset were empty, I believe that 'No data to display' would be shown (which I could change to 'No Data' to match the usual grafana look that everyone is used to) but I believe there might be a deeper Issue here where the graph should be displaying data but it doesn't.

Frontend is not my area of expertise tho, so I might also be totally wrong - please let me know what you think.

**Comment by mariuskimmina** [comment]
Going further, in the `Graph` component `chartHasData` evaluates to true, so I am almost certain we should actually be seeing data here.

**Comment by mariuskimmina** [comment]
Okay, I might have been wrong about there being data, the data I saw apparently stems came from the another chart on the Overview metrics page, my bad.
