### ISSUE TITLE
The search results do no clear when adding filter in live mode on logs

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#1911]
https://www.loom.com/share/b7a44d542dd040a4a9711fb0b5ad79ba

**Comment by ankitnayan** [comment]
It is a bug introduced in develop branch. It does not exist in current release https://www.loom.com/share/6ed493f6a51247db91a821439531f7fd

**Comment by palashgdev** [comment]
@ankitnayan if you notice that the api response is in a pending state after successfully fetching it, can you help what exactly is the bug here? it will only reflect from there only.
