### ISSUE TITLE
Flickering of chart in the logs page

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#1932]
https://www.loom.com/share/7c28b1d1cfd64be0b310470ef89d2f81

**Comment by pranay01** [comment]
- Apply a filter in logs filter page
- Go to Services page
- Come back to logs page

The chart flickers 2-3 times

https://www.loom.com/share/e6e0160fd7244696a613d046dd6a80d1

**Comment by palashgdev** [comment]
fixed by 
1. https://github.com/SigNoz/signoz/pull/1934
1. https://github.com/SigNoz/signoz/pull/1947

**Comment by pranay01** [comment]
Issue seems to be solved with above PRs. Closing the issue
