### ISSUE TITLE
Request for multi-architecture images of signoz components (ARM support) 

### ISSUE THREAD

**Issue by rajdas98** [SigNoz/signoz#194]
**Is your feature request related to a problem? Please describe.**

Currently, signoz docker images are not built for multi-arch support(ARM)
Required arch support- arm64/amd64

**Describe the solution you'd like**
Add arch support of arm64 and amd64 for the following signoz components
- signoz frontend
- query-service
- flattener 

Using `docker buildx`, we can build for multi-arch images.

**Comment by rajdas98** [comment]
cc: @ankitnayan  @pranay01  Please feel free to assign this issue to me

**Comment by MoroIddrisu** [comment]
Hello
