### ISSUE TITLE
External call error percentage panel should show overall error percentage

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#1941]
This panel has always been an overall error percentage. The builder query added groupby address. We should remove groupbya address.

**Comment by sf-pchakraborty** [comment]
The equivalent promql query expression also had groupby and it wasn't added separately only for querybuilder -

below was the promql query -

query: `max((sum(rate(signoz_external_call_latency_count{service_name="${servicename}", status_code="STATUS_CODE_ERROR"${resourceAttributePromQLQuery}}[5m]) OR vector(0)) by (address))*100/sum(rate(signoz_external_call_latency_count{service_name="${servicename}"${resourceAttributePromQLQuery}}[5m])) by (address)) < 1000 OR vector(0)`,
