### ISSUE TITLE
Kubernetes pods logs are not being parsed

### ISSUE THREAD

**Issue by pantoninho** [SigNoz/signoz#1942]
## Bug description

Kubernetes pods logs are not being parsed. Their content is included in the `body` property instead of being parsed. In the screenshot we can see `span_id` and `trace_id` are not being extracted from the log message.

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/14220276/209936034-7877dd35-0d9b-49e7-85d1-5e3861c472ca.png">

## Expected behavior

Logs content should be parsed and values like `trace_id` and `span_id` should not be empty.

## How to reproduce

1. Deploy Signoz helm chart into a kubernetes cluster
2. Deploy a fastify (nodejs webserver) application, which uses pino as its logger, with opentelemetry auto-instrumentation
3. See logs in the frontend

## Version information 
* **Signoz version**: 0.12.0
* **Browser version**: Safari and latest Chrome
* **Your OS and version**: MacOS Monterey (12.5.1)
* **Your CPU Architecture**(ARM/Intel):

**Comment by nityanandagohain** [comment]
You will have to parse them using different operators that are available https://signoz.io/docs/userguide/logs/#operators-for-parsing-and-manipulating-logs

Here is an example https://github.com/SigNoz/logs-benchmark/blob/5c1990d8637beee6326dbcb6f376ed268f540246/signoz/signoz-client/otel-collector-config.yaml#L22

**Comment by pranay01** [comment]
@pantoninho Can you check and confirm if above instructions are able to solve your issue?

**Comment by pantoninho** [comment]
I'm sorry for the late response but I can confirm the above instructions solve my issue.

Closing the issue. Thank you!
