### ISSUE TITLE
Dependent variables in Dashboard

### ISSUE THREAD

**Issue by wiradikusuma** [SigNoz/signoz#1973]
## Describe the solution you'd like

In a multi-region serverless microservice, a "server instance" has at least 3 attributes: name, region, and instance id. Let's say you use Fly.io ( https://fly.io/docs/reference/regions ) and have the following setup:

`payment-system` in region `den` (instances: `A`, `B`) and `dfw2` (instances: `C`).
`email-system` in region `dfw2` (instances: `D`) and `ams` (instances: `E`, `F`).

In the Dashboard, if I put those as variables (`App Name`, `Region` and `Instance`), I want e.g. `Region` to be filtered by `App Name`. In other words, if I select `payment-system` for `App Name`, I want to see only `den` and `dfw2` in the `Region` dropdown. And when I select `dfw2` for the `Region`, I will only see instance `C` in the `Instance` dropdown.

## Describe alternatives you've considered

To combine all attributes as one, e.g. `payment-system-den-A`.

**Comment by pranay01** [comment]
@wiradikusuma Thanks for opening the issue. We will take a look into it

**Comment by srikanthccv** [comment]
@pranay01 can you share what the user interaction would be like and how the selected value change in one variable affects its dependent and independent variables? this is just to ensure we are all on the same page about the expected behaviour.

**Comment by pranay01** [comment]
I think the issue itself has decent amount of detail. For example, if there are 3 variables A, B & C.

If user selects value A1 for variable A, then only those options for variable B & C should be shown which can go with A1 - only show those label values of B & C which occur with variable A1

Let me know if there are any scenarios where this may get computationally intensive, and we can discuss more about it.

**Comment by srikanthccv** [comment]
I understood the issue details. I meant to ask about the state transitions. Should changing a variable instantly update the dashboard, or should there be a button where they select filters individually and then click on the button to apply filters? When variable A changes and dependent variable B is a multi-select, what should be the default value? Should they all be selected, or only the first one be selected or none? An independent variable C, does it remain selected with the previously selected value or gets reset when there is a change in variable A? etc.

**Comment by pranay01** [comment]
- _Should changing a variable instantly update the dashboard, or should there be a button where they select filters individually and then click on the button to apply filters?_

I think it should apply directly without need to click another button. This is the current experience in our dashboards.

- _When variable A changes and dependent variable B is a multi-select, what should be the default value?_

We should add an option (* or `all`) selecting which means that all the options in B are selected. This should also be the default value. This is the approach which some other products take

- _An independent variable C, does it remain selected with the previously selected value or gets reset when there is a change in variable A_

I think for an independent variable, we can keep it the same. What do you mean by `reset` in this case? Select the default option? (like `*` aka `all`)

**Comment by srikanthccv** [comment]
>What do you mean by reset in this case? Do you selecting the default option? (like * aka all)

Yes, it could remain the same or reset to a default value. 

The first two points were brought up since they are similar to the trace filter page, and we discussed some reconsideration after user feedback. It would be good to have a consistent experience across the product. There will be an option ALL, and it will be the default value for multi-select. The first value will be the default value for a single select.

**Comment by srikanthccv** [comment]
This is done
