### ISSUE TITLE
Caching the results of `query_range` apis for overlapping period

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#1988]
We can speed up loading of dashboards when there is an overlap of time period of `query_range` APIs querying the same data.

**Comment by ankitnayan** [comment]
We should log how much of cache is hit for a query.

I am guessing there will be some randomness in query response time depending on which hit the cache. The above will help us debug better

**Comment by srikanthccv** [comment]
Yes, we log the cache retrieve status https://github.com/SigNoz/signoz/blob/9826ab04b3faa5d991e46be8e9ea8630f48f68ed/pkg/query-service/app/querier/helper.go#L163C18-L163C33. The log level should be changed.
