### ISSUE TITLE
Threshold bars for the timeseries charts

### ISSUE THREAD

**Issue by himanshuinvideo** [SigNoz/signoz#1989]
## Is your feature request related to a problem?

*To detect anomalies on the timeseries, the threshold is going to be helpful *

## Describe the solution you'd like

Along side query, formula, the dashboard panels should show option to add multiple thresholds

**Comment by pranay01** [comment]
@himanshuinvideo can you share more details on how multiple thresholds would be useful? May be an example would be great 

Currently we allow single threshold to be set and it is also shown in the graph while setting alert

**Comment by srikanthccv** [comment]
I think the author is referring to dashboards only, not alerts. Consider a CPU usage chart; the multiple threshold bars in the question could be <= 50% green, 50 - 75% - yellow, and > 75% red.

**Comment by pranay01** [comment]
https://signoz.io/blog/community-update-31/#add-thresholds-in-time-series-table-and-value-view

Thresholds on values, tables and timeseries charts are now available
