### ISSUE TITLE
Irregular box sizes 

### ISSUE THREAD

**Issue by UtkarshMishra12** [SigNoz/signoz#1997]
## Bug description
Irregular box sizes 

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  
![image](https://user-images.githubusercontent.com/67385503/211165714-9f2c38a2-6f67-42e4-9801-e81cd752cb0e.png)

## Expected behavior
It should be equal in height

## How to reproduce

1.
2.
3.

## Version information 
* **Signoz version**:
* **Browser version**:
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel):

**Comment by pranay01** [comment]
@UtkarshMishra12 Thanks for the issue. Do you have a proposal on how to solve this?

Here's our website repo where you can raise a PR on how to fix it - https://github.com/SigNoz/signoz.io

**Comment by UtkarshMishra12** [comment]
@pranay01 Yes, we can define the height of the 2nd & 3rd boxes as equal to the 1st one, it'll be solving this issue.

**Comment by YounixM** [comment]
We have moved to new website now. Closing this PR as it's stale and not applicable anymore.
