### ISSUE TITLE
Move Signoz packages utilized by flattener processor from gitlab to github repo

### ISSUE THREAD

**Issue by lalitkale** [SigNoz/signoz#200]
## Bug description
Flattener processor uses packages that are referred from GitLab. However, it would be easier to read and package them as part of the main repo at Github. It also helps to manage dependencies for SigNoz.

Reference: https://github.com/SigNoz/signoz/blob/ea93b65ab7c0be2c89f62dde20fbbd9b7843d4f9/pkg/processors/flattener/main.go#L11-L13 

While moving please unify the license from the packages on GitLab to Github.

## Expected behavior
GitLab Packages ported and included in main GitHub repo

## How to reproduce
NA

## Version information 
* **Signoz version**: v0.3.2

## Additional context
This bug is filed as per discussion with @pranay01 on SigNoz slack. 
reference: https://signoz-community.slack.com/archives/C01LWQ8KS7M/p1624903179025900

**Comment by MoroIddrisu** [comment]
Hello

**Comment by MoroIddrisu** [comment]
Hello

**Comment by pranay01** [comment]
flattener processor was only there for druid datastore setup. Support for druid as datastore is deprecated now
