### ISSUE TITLE
Don't show big loading icons in the panels when a dashboard reloads

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#2004]
- [x] #2073
- [x] #2074
- [ ] #2075

**Comment by ankitnayan** [comment]
https://github.com/SigNoz/signoz/issues/1865

**Comment by csudani7** [comment]
@ankitnayan @palashgdev PR is merged with smoother transition so can you guys confirm #2075 issue? is it resolved or still anything pending?

**Comment by palashgdev** [comment]
I don't think it is actionable right now ... will revisit if any more insights is needed for now we close
