### ISSUE TITLE
Add lazy loading when showing all the panels in a dashboard

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#2005]
If a dashboard has 20 panels, we load (and hence the API calls) all the panels in one go. It fires 20 concurrent requests to clickhouse. We should add lazy loading here. We should only load the panels when a user scrolls down.

**Comment by jyash97** [comment]
Hey @ankitnayan 

Can I take a look at this? I always wanted to give it a try on `IntersectionObserver` and this seems to be a good use case

**Comment by ankitnayan** [comment]
sure...assigning this to you @jyash97

**Comment by ankitnayan** [comment]
@jyash97 I hope you are looking into this. Let us know if you need more context or won't be able to make time

**Comment by jyash97** [comment]
Hey @ankitnayan if you need this urgently, you can assign this issue to someone else or the team

**Comment by ankitnayan** [comment]
we were looking to make it to the next release on wed, 25th Jan. Let us know if possible

**Comment by jyash97** [comment]
I dont think I would be able to pull this off before 25 Jan. You might assign this to someone else

Thanks

**Comment by ankitnayan** [comment]
> I dont think I would be able to pull this off before 25 Jan. You might assign this to someone else
> 
> Thanks

no worries..
