### ISSUE TITLE
Unable to view Services after installation of signoz

### ISSUE THREAD

**Issue by coding-dong** [SigNoz/signoz#2007]
## Bug description

Unable to view application after installation of signoz in the services section.

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  
![image](https://user-images.githubusercontent.com/107399101/211263544-8e46fc7d-fb9c-4e06-b89e-99e65df149da.png)

## Expected behavior

According to documentation once the installation is done... Applications would be shown in the services tab.

## How to reproduce

1. install signoz
2.open localhost:3301
3. check the services section

## Version information 
* **Signoz version**: 0.13.1
* **Browser version**:
* **Your OS and version**:  Linux localhost.localdomain 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

* **Your CPU Architecture**(ARM/Intel):

**Comment by pranay01** [comment]
@coding-dong Can you share what output you get on running the troubleshooting tool - run the binary in the same location where you are running the application - https://signoz.io/docs/install/troubleshooting/

**Comment by coding-dong** [comment]
thanks for the response @pranay01 . Looks like the test machine which we are working with doesnt have enough memory. After that every thing is working good.
