### ISSUE TITLE
Invite links do not work if name is not given when creating the invite

### ISSUE THREAD

**Issue by patrijua** [SigNoz/signoz#2008]
## Bug description

Invite links do not work if name is not given when admin creates the invite. When invite link is created and name is NOT given, when the user uses the link to create an account "Get Started" button is remains disabled and user can not create an account.

## Expected behavior

User should be able to create an account  via invite link even thought admin did not provide name when creating the invite link

## How to reproduce

1. When admin creates an invite link from Organization Settings view, the UI says that name is optional. Admin creates the invite without giving the name 
![image](https://user-images.githubusercontent.com/57624530/211331833-e9ab9820-36fc-4bbb-9df8-1ed288c04e4b.png)

2.When invite link is created without name, when the user uses the link to create an account, "Get Started" button is disabled and user can not create an account 
![image](https://user-images.githubusercontent.com/57624530/211331945-48268183-66a9-4887-b0d7-5ce9cc5f3cd3.png)

## Version information 
v.0.12.0
v0.13.0

**Comment by patrijua** [comment]
According to your video, you have resolved the problem. Thank you!

**Comment by pranay01** [comment]
@patrijua @palashgdev is this issue fixed? Can we close this issue?

**Comment by makeavish** [comment]
Fixed in https://github.com/SigNoz/signoz/pull/2026
