### ISSUE TITLE
Add logs parser tests to build process

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#2019]
The logs parser tests don't run as a part of the build process. Include them in the `test` target so that PR that doesn't pass tests won't get merged.

https://github.com/SigNoz/signoz/blob/b87f3bdb50e468dd2698ba456f17f230f9b7d4ce/Makefile#L139-L140

https://github.com/SigNoz/signoz/blob/b87f3bdb50e468dd2698ba456f17f230f9b7d4ce/.github/workflows/build.yaml#L35-L38

**Comment by nityanandagohain** [comment]
Tests are run with https://github.com/SigNoz/signoz/blob/c0d10f0d88992bf18afb4e5d48fd1d73128d5bd1/Makefile#L150C2-L150C34
