### ISSUE TITLE
Support for reading raw encoding in kafka receiver in logs

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#2047]
The `kafka` receiver docs state below for raw encoding:
``` 
raw: (logs only) the payload's bytes are inserted as the body of a log record.
```
For above usecase, we need the body to be parsed as `string(r.Body().Bytes().AsRaw())` when storing to clickhouse rather than `r.Body().AsString()`. 

Also, ingesting raw data from kafka may not have timestamp. How to accomodate for that?

**Comment by ankitnayan** [comment]
there is a `group_id` field in `kafkareceiver` which will handle data from different partitions. If there are more consumers in a consumer group, the consumers will remain idle. I see a problem of rebalancing when the number of consumers change which can be caused by changing the pod count of otel-collectors, otel-collectors being down or restarting. Sharing some resources which might be useful to understand this 
https://medium.com/javarevisited/kafka-partitions-and-consumer-groups-in-6-mins-9e0e336c6c00
https://medium.com/bakdata/solving-my-weird-kafka-rebalancing-problems-c05e99535435

There is an open issue with opentelemetry-collector-config to take rebalancing into consideration https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17312. The above mentioned issues will still be valid if kafka takes long time in rebalancing.

**Comment by srikanthccv** [comment]
The body field is AnyValue type on the LogRecord https://github.com/open-telemetry/opentelemetry-proto/blob/d8729d40f629dba12694b44c4c32c1eab109b00a/opentelemetry/proto/common/v1/common.proto#L25-L40

So irrespective of the upstream encoding, we should be able to inspect the `Type()` of the Value and prepare its human-readable string representation.


Something I spent some time playing yesterday
```
// See https://cs.opensource.google/go/go/+/refs/tags/go1.17.7:src/encoding/json/encode.go;l=585.
// This allows us to avoid using reflection.
func float64AsString(f float64) string {
	if math.IsInf(f, 0) || math.IsNaN(f) {
		return fmt.Sprintf("json: unsupported value: %s", strconv.FormatFloat(f, 'g', -1, 64))
	}

	// Convert as if by ES6 number to string conversion.
	// This matches most other JSON generators.
	// See golang.org/issue/6384 and golang.org/issue/14135.
	// Like fmt %g, but the exponent cutoffs are different
	// and exponents themselves are not padded to two digits.
	scratch := [64]byte{}
	b := scratch[:0]
	abs := math.Abs(f)
	fmt := byte('f')
	if abs != 0 && (abs < 1e-6 || abs >= 1e21) {
		fmt = 'e'
	}
	b = strconv.AppendFloat(b, f, fmt, -1, 64)
	if fmt == 'e' {
		// clean up e-09 to e-9
		n := len(b)
		if n >= 4 && b[n-4] == 'e' && b[n-3] == '-' && b[n-2] == '0' {
			b[n-2] = b[n-1]
			b = b[:n-1]
		}
	}
	return string(b)
}

func bodyNormalized(l plog.Logs) string {
	v := l.ResourceLogs().At(0).ScopeLogs().At(0).LogRecords().At(0).Body()
	fmt.Println("type", v.Type())
	switch v.Type() {
	case pcommon.ValueTypeStr:
		return v.Str()

	case pcommon.ValueTypeBool:
		return strconv.FormatBool(v.Bool())

	case pcommon.ValueTypeDouble:
		return float64AsString(v.Double())

	case pcommon.ValueTypeInt:
		return strconv.FormatInt(v.Int(), 10)

	case pcommon.ValueTypeMap:
		jsonStr, _ := json.Marshal(v.Map().AsRaw())
		return string(jsonStr)

	case pcommon.ValueTypeBytes:
		return string(v.Bytes().AsRaw())

	case pcommon.ValueTypeSlice:
		jsonStr, _ := json.Marshal(v.Slice().AsRaw())
		return string(jsonStr)
	}
	return "<invalid>"
}

func TestLogs(t *testing.T) {
	l1 := plog.NewLogs()
	l1.ResourceLogs().AppendEmpty().ScopeLogs().AppendEmpty().LogRecords().AppendEmpty().Body().SetEmptyBytes().FromRaw([]byte{104, 101, 108, 108, 111})
	fmt.Println(bodyNormalized(l1))

	l2 := plog.NewLogs()
	l2.ResourceLogs().AppendEmpty().ScopeLogs().AppendEmpty().LogRecords().AppendEmpty().Body().SetStr("hello")
	fmt.Println(bodyNormalized(l2))

	l3 := plog.NewLogs()
	l3.ResourceLogs().AppendEmpty().ScopeLogs().AppendEmpty().LogRecords().AppendEmpty().Body().SetDouble(1.23)
	fmt.Println(bodyNormalized(l3))

	m := make(map[string]interface{})
	m["message"] = "hello"
	l4 := plog.NewLogs()
	l4.ResourceLogs().AppendEmpty().ScopeLogs().AppendEmpty().LogRecords().AppendEmpty().Body().SetEmptyMap().FromRaw(m)
	fmt.Println(bodyNormalized(l4))

	t.Fatal("boom!")
}

```

**Comment by ankitnayan** [comment]
**DataDog exporter:**
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datadogexporter/internal/logs/translator.go#L156

**Clickhouse exporter:**
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/exporter_logs.go#L103

**Logzio exporter**
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/logzioexporter/jsonlog.go#L87

**Loki exporter**
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/legacy_exporter.go#L396


I don't see any of them handling this

**Comment by srikanthccv** [comment]
The "raw" signal encoding support is pretty recent (~4 months ago). You could see that the `Logzio` exporter is handling the map type, so I assume they know the possible types and eventually want to support all types.

**Comment by srikanthccv** [comment]
Also, one thing to highlight with this receiver in its current shape, it only consumes messages one-by-one which could be inefficient for large volumes of messages.

**Comment by ankitnayan** [comment]
> Also, one thing to highlight with this receiver in its current shape, it only consumes messages one-by-one which could be inefficient for large volumes of messages.

that's purpose of event driven systems like consumers, right? Should we be worried if we have a batch processor at the end?

**Comment by ankitnayan** [comment]
>inefficient for large volumes of messages.

You meant inefficient for otel-collector or clickhouse?

**Comment by srikanthccv** [comment]
>that's purpose of event driven systems like consumers, right?

Is this use case event driven or more of an async mode? Should receiver consumes the messages in batches? 

>Should we be worried if we have a batch processor at the end?

We may not be effectively using the batch processor. Say the batch trigger timeout is set to 1s, then the amount of records written to ClickHouse depends on the consumption rate of the receiver which we know is consuming one by one. I would like to see what would be maximum consumption throughput.
