### ISSUE TITLE
Rearranging layout of a dashboard causes all APIs to be fired again and all panels reload

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#2062]
https://www.loom.com/share/0801a7afd8184f719b64647c5f70f7c5

**Comment by ankitnayan** [comment]
@palashgdev can you verify if this is fixed? I can see multiple api calls being done when the layout is rearranged

**Comment by csudani7** [comment]
> @palashgdev can you verify if this is fixed? I can see multiple api calls being done when the layout is rearranged

@ankitnayan This issue was fixed atm. But Lazy loading code is violating this issue's solution.
For that i raised PR: https://github.com/SigNoz/signoz/pull/2164
Once this PR merge it will resolve this issue.
