### ISSUE TITLE
Support shareable filters in `/logs` page URLs 

### ISSUE THREAD

**Issue by inbrewj-udc** [SigNoz/signoz#2066]
## Is your feature request related to a problem?

Yes and no - I don't think this is a bug per se, just a feature that hasn't been fleshed out yet.

## Describe the solution you'd like

Whenever I type a query into the field in the `Logs` module, I see the query being added to the query parameters in the URL:

![image](https://user-images.githubusercontent.com/104355301/212953643-7bb93080-1a6d-40e9-9f82-5b08fcafc05c.png)

However, if I were to share this link with colleagues, or add it to a tag on an alert, the query params would be lost as soon as the page loads.

It would be brilliant if the `/logs` page would read the query parameters and populate the query field after the page loads (whilst still keeping the query params visible in the address bar!)

## Describe alternatives you've considered

- Saving queries in text files and other manual copy / paste solutions

**Comment by pranay01** [comment]
Potentially related - https://github.com/SigNoz/signoz/issues/444
