### ISSUE TITLE
Fixing tooltip position

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#2077]
https://www.loom.com/share/cf502c9329f54e8e9381f2456385ecbb

**Comment by ankitnayan** [comment]
> Hi @ankitnayan. How can i generate real data to test this issue?

It should be there if you have env `FRONTEND_API_ENDPOINT` provided by the maintainers 
cc: @palashgdev

**Comment by maryojo** [comment]
Hi @palashgdev, I would like to work on this

**Comment by palashgdev** [comment]
> Hi @palashgdev, I would like to work on this

Please go ahead
