### ISSUE TITLE
Signoz to interpret colors

### ISSUE THREAD

**Issue by shrbb** [SigNoz/signoz#2082]
Some loggers are colored and this is causing junk characters in signoz
Need a way to make signoz interpret colors.

**Comment by pranay01** [comment]
hey @shrbb Can you share some examples of what you are seeing in SigNoz logs page and what was the log sent from the logger

**Comment by shrbb** [comment]
https://docs.rs/simplelog/0.12.0/simplelog/enum.ColorChoice.html

**Comment by nityanandagohain** [comment]
Thanks for creating the issue,

There seems to be two ways to handle this issue, 
1) On clickbouselogsexporter, we can clean the log body by removing the characters.
or
2) Frontend can render/ ignore these characters.


I would go with the first solution as the second solution might cause issues with full-text search. cc @ankitnayan

**Comment by pranay01** [comment]
@nityanandagohain Can we check how other open source tools like Grafana and Elastic solve this today?

**Comment by nityanandagohain** [comment]
Coloured logs are supported now.
