### ISSUE TITLE
signoz-otel-collector-metrics pod CrashLoopBackOff

### ISSUE THREAD

**Issue by Vhartmannfigaro** [SigNoz/signoz#2084]
## Bug description

In my values.yaml i put
```
  # -- Name of the external cluster to run DDL queries on.
  cluster: replicated
```
I use an external clickhouse database,

And  both otel collectors pods are crashloopbackoff and in metrics pod logs i have :

`2023-01-20T19:39:47.696Z        info    components/components.go:30     Stability level of component is undefined       {"kind": "exporter", "data_type": "metrics", "name": "clickhousemetricswrite", "sta
bility": "Undefined"}                                                                                                                                                                                      
time="2023-01-20T19:39:47Z" level=info msg="Executing:\nCREATE DATABASE IF NOT EXISTS signoz_metrics ON CLUSTER cluster\n" component=clickhouse                                                            
panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                    
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x3865bb9]`

I see that this pod try to create on cluster "cluster" and not "replicated" cluster, 

Thanks in advance for your help,

## Version information 
* **Signoz version**: v0.14.0
* **Browser version**:
* **Your OS and version**: Debian
* **Your CPU Architecture**(ARM/Intel): 
* Running on Kubernetes : 1.25.1-00

**Comment by pranay01** [comment]
@Vhartmannfigaro What's the version of the external ClickHouse you are using?

**Comment by Vhartmannfigaro** [comment]
Hi @pranay01,

External Clickhouse version: 22.12.1.1752

**Comment by prashant-shahi** [comment]
@Vhartmannfigaro Unfortunately, we do not support dynamic values for cluster and databases, but have a static one.
Mainly due to limitations of go-migrate migration files.

Following values will have to remain the same:
```
externalClickhouse:
  cluster: cluster
  database: signoz_metrics
  traceDatabase: signoz_traces

```

**Comment by Vhartmannfigaro** [comment]
Thanks @prashant-shahi  for your help, after renamming cluster it works

**Comment by prashant-shahi** [comment]
@Vhartmannfigaro That's great to hear that your issue is resolved.
