### ISSUE TITLE
Option to go from Trace and Exceptions to Logs

### ISSUE THREAD

**Issue by vasicvuk** [SigNoz/signoz#2085]
## Is your feature request related to a problem?

No

## Describe the solution you'd like

Since Logs can also have Span and Trace Ids it would be a good option to be able to navigate from Traces and Exceptions directly to logs.

## Describe alternatives you've considered

Copying the TraceId and manually searching

**Comment by vasicvuk** [comment]
Ideally maybe there should be a single screen Trace Overview showing traces, logs and exceptions

**Comment by makeavish** [comment]
It's available now
