### ISSUE TITLE
FE: fix cyclic dependency 

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#2088]
## Bug description

*Please describe.*  
There are cyclic imports in the FE code base 

## Expected behavior
remove import/no-cycle rule in the eslint

## How to reproduce

1. remove import/no-cycle
1. yarn lint

**Comment by prakha** [comment]
i want to fix this issue. could you please assign this issue to me

**Comment by pranay01** [comment]
Sure @prakha Assigned this to you! Let us know if you need any help getting started

**Comment by roopeshsn** [comment]
Hi, @pranay01 @palashgdev! Whether this issue is still open. If yes, I would like to work on this!

**Comment by besalraj30** [comment]
Hi, is this still open? @pranay01

**Comment by srikanthccv** [comment]
Not relevant anymore.
