### ISSUE TITLE
FE: remove `no-shadow:off` `'@typescript-eslint/no-shadow': 'off'` and  rules from eslint rule list

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#2089]
## Bug description

*Please describe.*  

remove this rule from eslint

**Comment by palashgdev** [comment]
Currently there are 86 issues regarding this rule

**Comment by Aakarshan-369** [comment]
Hi! I'm a new comer here and saw this good-first-issue. I was interested to know how I should go about solving it. I see the `no-shadow:off` rule in the `signoz/frontend/.eslintrc.js` 
Thanks!

**Comment by palashgdev** [comment]
@Aakarshan-369 there are two rules for same 

1. `no-shadow:off`
1. '@typescript-eslint/no-shadow': 'off'


we need to remove both of them i guess remove the first one https://github.com/SigNoz/signoz/pull/2093 can you take yup the second one ?

**Comment by Aakarshan-369** [comment]
should I go on and remove the `no-shadow:off` and let #2093  remove the second one ?
thanks for the quick follow-up :)

**Comment by palashgdev** [comment]
> should I go on and remove the `no-shadow:off` and let #2093 remove the second one ? thanks for the quick follow-up :)

shared the context in the PR if you have any doubt

**Comment by saadahmadhere** [comment]
is this issue resolved?

**Comment by ksorv** [comment]
@palashgdev #2670 closes this issue.

Please check and let me know

**Comment by mehra-sourav** [comment]
@ksorv , I think this is still pending. As far as I know, #2670  was closed abruptly.

**Comment by ksorv** [comment]
> @ksorv , I think this is still pending. As far as I know, #2670  was closed abruptly.

U can check the comment @mehra-sourav, in my PR.

Some code was to be fixed... but Im not sure where the problem was originating.
