### ISSUE TITLE
Issues in login screen -  even when passwords match, `Get Started` is disabled

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#2092]
### Discussed in https://github.com/SigNoz/signoz/discussions/2091

<div type='discussions-op-text'>

<sup>Originally posted by **monirerahmani-devops** January 22, 2023</sup>
Hi

Does signoz support add users?
</div>

**Comment by pranay01** [comment]
@FellipeMTX Check the attached discussion thread -  https://github.com/SigNoz/signoz/discussions/2091

**Comment by makeavish** [comment]
@pranay01  This bug was fixed in this PR: https://github.com/SigNoz/signoz/pull/2026
Will be shipped in coming release (v0.15.0)
