### ISSUE TITLE
delete logs

### ISSUE THREAD

**Issue by manang** [SigNoz/signoz#2095]
Is there a command to delete all the logs from clickhouse? NOt the traces, just the logs.
Thanks a lot
Angelo

**Comment by palashgdev** [comment]
@nityanandagohain @prashant-shahi do we have anything for same ?

**Comment by prashant-shahi** [comment]
@manang You could disable log collection first, followed by setting TTL to logs from SigNoz UI to few hours.
You should eventually have no logs data.

**Comment by prashant-shahi** [comment]
If you want to delete at source, @nityanandagohain/@srikanthccv should be able to provide with raw ClickHouse query for the same.

But recommended way is to use TTL and disable log collection.

**Comment by manang** [comment]
thanks a lot for your help
I used the retention time to free the db.
Thanks a lot again

**Comment by prashant-shahi** [comment]
@manang okay.

Also, follow the respective docs below for disabling log collections:
- [Docker](https://signoz.io/docs/userguide/collect_docker_logs/#disable-automatic-container-log-collection)
- [Kubernetes](https://signoz.io/docs/userguide/collect_kubernetes_pod_logs/#steps-to-disable-automatic-pod-logs-collection)
