### ISSUE TITLE
FE: Some UI Sorting improvements

### ISSUE THREAD

**Issue by vasicvuk** [SigNoz/signoz#2100]
## Is your feature request related to a problem?

No

*Please describe.*

## Describe the solution you'd like

It would be nice to have fields always sorted in the same way when looking at traces. Currently, it is randomly sorting so sometimes **db.statement** field is at the beginning and sometimes at the end.

Also, by default on the Trace list, traces should be sorted by Date Descending to see the newest ones first.

**Comment by makeavish** [comment]
Hey @vasicvuk 
Are you talking about tags on trace detail page?
<img width="332" alt="Screenshot 2023-01-23 at 19 05 45" src="https://user-images.githubusercontent.com/9512100/214052901-7a41065c-fa1d-49b4-8ca0-2b94013c393d.png">

**Comment by vasicvuk** [comment]
@makeavish Sure, yes

**Comment by makeavish** [comment]
> Also, by default on the Trace list, traces should be sorted by Date Descending to see the newest ones first.

We are not sorting by default due to some performance concerns, you can always sort by clicking on Date column for trace table.

<img width="1223" alt="Screenshot 2023-01-23 at 19 07 40" src="https://user-images.githubusercontent.com/9512100/214053281-892edc02-2e76-4b01-b71e-1b109ca6cf05.png">

**Comment by makeavish** [comment]
@palashgdev We should sort tags and events on trace detail page

**Comment by vasicvuk** [comment]
> > Also, by default on the Trace list, traces should be sorted by Date Descending to see the newest ones first.
> 
> We are not sorting by default due to some performance concerns, you can always sort by clicking on Date column for trace table.
> 
> <img alt="Screenshot 2023-01-23 at 19 07 40" width="1223" src="https://user-images.githubusercontent.com/9512100/214053281-892edc02-2e76-4b01-b71e-1b109ca6cf05.png">

Maybe if there is a selected smaller amount of time (1 hour) or some subquery it can be default to resolve this potential perf issue :). Currently, it is always an extra click which is annoying.

**Comment by makeavish** [comment]
> > > Also, by default on the Trace list, traces should be sorted by Date Descending to see the newest ones first.
> > 
> > 
> > We are not sorting by default due to some performance concerns, you can always sort by clicking on Date column for trace table.
> > <img alt="Screenshot 2023-01-23 at 19 07 40" width="1223" src="https://user-images.githubusercontent.com/9512100/214053281-892edc02-2e76-4b01-b71e-1b109ca6cf05.png">
> 
> Maybe if there is a selected smaller amount of time (1 hour) or some subquery it can be default to resolve this potential perf issue :). Currently, it is always an extra click which is annoying.

We will be working on improving performance and UX of trace filter page in coming months. Will keep your feedback in mind.
cc: @pranay01

**Comment by makeavish** [comment]
In new trace explorer page the table is sorted by default.
