### ISSUE TITLE
(traces): tag filtering doesn't change the left side filters values

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#2105]
## Bug description

Applying to filter custom attributes using the top bar doesn't update the pagination values and left side filter

<img width="1227" alt="Screenshot 2023-01-24 at 1 43 16 PM" src="https://user-images.githubusercontent.com/22846633/214241888-932497bd-7678-4f5c-a4db-0241761373c1.png">

## Expected behavior

It shouldn't show the pagination and left side filter with count when there is no data

## How to reproduce

1. Apply any filtering that results in no data

## Version information 
* **Signoz version**: All version

**Comment by makeavish** [comment]
This has irrelavant with new explorer page
