### ISSUE TITLE
Exception tab resource filter

### ISSUE THREAD

**Issue by fabioboterolyons** [SigNoz/signoz#2108]
## Is your feature request related to a problem? yes

We are using Otel as distributed tracing tool we use use resource tags to filters our applications, in the code below:
```
const provider = new NodeTracerProvider({
    sampler: new AlwaysOnSampler(),
    resource: Resource.default().merge(
      new Resource({
        [SemanticResourceAttributes.SERVICE_NAME]: SERVICE_NAME,
        [SemanticResourceAttributes.SERVICE_VERSION]: serviceVersion,
        [SemanticResourceAttributes.DEPLOYMENT_ENVIRONMENT]:
          DEPLOYMENT_ENVIRONMENT,
      }),
    ),
  });
```

we can see how we init the application exporter, this is the way that Otel recommends, one of those fields are the DEPLOYMENT_ENVIRONMENT that field we are using to filter applications by environments as [prd, dev, stg ] in the service tag in otel we can see a text input to use those filters and is very useful. But we have the exception section where we can not use those filters and is difficult to us to track in which environment the exceptions occur.

## Describe the solution you'd like

Have the resource filters in exceptions tab

## Describe alternatives you've considered

Add the same text input that exists in services tab in the exceptions tab

## Additional context
<img width="709" alt="Screen Shot 2023-01-19 at 3 56 40 PM" src="https://user-images.githubusercontent.com/7157055/214319197-cf440bcb-9586-4b22-a376-652d96a7f2c0.png">
<img width="1521" alt="Screen Shot 2023-01-19 at 3 56 50 PM" src="https://user-images.githubusercontent.com/7157055/214319201-eaacac36-f31e-499b-868a-ceb2a894f498.png">

**Comment by pranay01** [comment]
@fabioboterolyons Thanks for opening the issue. 

From a visualisation perspective, consider the following flow:
1. add the resource attribute filter (similar to services page) 
2. the list of applications in the exceptions table gets filtered based on resource attribute filter

Does this approach work?

**Comment by makeavish** [comment]
This exists in latest version of SigNoz
