### ISSUE TITLE
Tag filter modal closes randomly

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#2109]
Tag filter modal closes randomly while adding new filters.
Loom video: https://www.loom.com/share/5fd742a6a5d64251af3b593e61289f88

**Comment by srikanthccv** [comment]
Wasn't this fixed in https://github.com/SigNoz/signoz/pull/2106? @palashgdev

**Comment by makeavish** [comment]
No this fixed the random behavior of tag filters when adding new tag filters. 
Random behavior was that when changing the operator of newly added filter the old filters would be removed randomly. Only that was fixed in https://github.com/SigNoz/signoz/pull/2106
