### ISSUE TITLE
High CPU usage by ClickHouse

### ISSUE THREAD

**Issue by vasicvuk** [SigNoz/signoz#2112]
## In what situation are you experiencing subpar performance?

I have installed the SigNoz using the official charts. Currently, it processes 17k spans per hour, and I would like to get it to process nearly 500k per hour.

The main issue I have is the high CPU usage on the click house pod. It constantly is using 430% CPU (4.3 cpus). 

The only thing that I see in logs of click house is repeating:

```
2023.01.24 21:39:40.466440 [ 25 ] {ddd16d9e-c070-4213-b281-62a2f1985bc0::20221002_4478_4478_0_7094} <Error> virtual bool DB::MutatePlainMergeTreeTask::executeStep(): Code: 10. DB::Exception: Not found column MethodInfo in block. There are only columns: timestamp, id, trace_id, span_id, severity_text, body, observed_timestamp, trace_flags, severity_number, resources_string_key, resources_string_value, attributes_string_key, attributes_string_value, attributes_int64_key, attributes_int64_value, attributes_float64_key, attributes_float64_value, k8s_pod_name, k8s_container_name. (NOT_FOUND_COLUMN_IN_BLOCK), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3ef75a in /usr/bin/clickhouse
1. DB::Block::getByName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) const @ 0x13ef0872 in /usr/bin/clickhouse
2. DB::getBlockAndPermute(DB::Block const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const*) @ 0x158db96f in /usr/bin/clickhouse
3. DB::MergeTreeDataPartWriterCompact::writeDataBlockPrimaryIndexAndSkipIndices(DB::Block const&, std::__1::vector<DB::Granule, std::__1::allocator<DB::Granule> > const&) @ 0x158d682e in /usr/bin/clickhouse
4. DB::MergeTreeDataPartWriterCompact::fillDataChecksums(DB::MergeTreeDataPartChecksums&) @ 0x158d7bc2 in /usr/bin/clickhouse
5. DB::MergeTreeDataPartWriterCompact::fillChecksums(DB::MergeTreeDataPartChecksums&) @ 0x158d847c in /usr/bin/clickhouse
6. DB::MergedBlockOutputStream::finalizePartAsync(std::__1::shared_ptr<DB::IMergeTreeDataPart>&, bool, DB::NamesAndTypesList const*, DB::MergeTreeDataPartChecksums*) @ 0x159c9396 in /usr/bin/clickhouse
7. DB::MutateAllPartColumnsTask::finalize() @ 0x159ee9c5 in /usr/bin/clickhouse
8. ? @ 0x159ecfec in /usr/bin/clickhouse
9. DB::MutatePlainMergeTreeTask::executeStep() @ 0x159d562e in /usr/bin/clickhouse
10. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0xa3b9f1b in /usr/bin/clickhouse
11. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0xa3b9950 in /usr/bin/clickhouse
12. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xa4b38a6 in /usr/bin/clickhouse
13. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0xa4b51f7 in /usr/bin/clickhouse
14. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa4b11c8 in /usr/bin/clickhouse
15. ? @ 0xa4b43dd in /usr/bin/clickhouse
16. ? @ 0x7fdc728ef609 in ?
17. __clone @ 0x7fdc72814133 in ?
 (version 22.8.8.3 (official build))
```

This CPU load is present even if the SigNoz frontend is not used by anybody.

## How to reproduce

I am really not sure what is specific to the environment in order to create a reproduction. But I will try to give as much information as you request from me.

## Your Environment

- [X] Linux
- [ ] Mac
- [ ] Windows

Please provide details of OS version etc.

 Ubuntu 22.04.1

**Comment by pranay01** [comment]
@vasicvuk Thanks for the issue.

Few quick questions:
- What machine are you using for running this ( no. of CPU cores, RAM)? 
- Are you on  AWS, GCP or Azure or any other provider?
- What disk are you using? (gp2?)

**Comment by srikanthccv** [comment]
Did you try changing the TTL? If so, how much data existed prior? Can you share the output for
```SQL
SHOW CREATE TABLE signoz_logs.distributed_logs;
```

In our experience, the more number Merge mutation that ClickHouse does in the background leads to more CPU it util. Does it remain consistently high? If you can share more information, that would help us if it is by the design of ClickHouse or some unusual activity. 

Can you share the output for 
```
SELECT * from system.merge
```

And if you can share the output of the Linux perf tool with top entries, that will also help. It will look like the following.

<img width="756" alt="191133570-da319873-506e-494a-81e9-b9b8f9e74254" src="https://user-images.githubusercontent.com/22846633/214450645-f97bd98b-57b9-4b47-b91f-392de87b8ba6.png">

**Comment by vasicvuk** [comment]
> @vasicvuk Thanks for the issue.
> 
> Few quick questions:
> 
> * Which version of SigNoz are you running?
> * What machine are you using for running this ( no. of CPU cores, RAM)?
> * Are you on  AWS, GCP or Azure or any other provider?
> * What disk are you using? (gp2?)

Version is: v0.14.0
VM with 8vCPU and 32 GB ram. Ram is DDR3 1866mhz ECC.  CPU is  Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz

**Comment by vasicvuk** [comment]
> 

Seems to me that the issue is somehow correlated with the fact that it expects this column `MethodInfo` and it does not exist, I reinstalled SigNoz removing all the data and now the CPU of clock house is at 30% with no errors in the log.

I will check if the CPU goes high again and let you know.

**Comment by srikanthccv** [comment]
How frequently does this show up? Can you check the operator user entry and see if it has a password? You will get the user info from this config file `/etc/clickhouse-server/users.d/chop-generated-users.xml` from the ClickHouse pod.

**Comment by srikanthccv** [comment]
I would open a separate issue for things unrelated to the original issue request.

**Comment by vasicvuk** [comment]
Hi @srikanthccv 

I opened a new issue here

**Comment by srikanthccv** [comment]
We have encountered another instance of high CPU usage because of failed merge mutation. @vasicvuk Did you try creating the materialized column `MethodInfo`? It looks like that failed. There was bug related but It was fixed already.

**Comment by vasicvuk** [comment]
Probably that was the case. Closing it now.
