### ISSUE TITLE
FE: Changing the global time hangs the UI for some amount of time 

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#2122]
@csudani7 Can you please check this behaviour?
https://www.loom.com/share/c990f425c1a049539d2a473b5ec98b41

_Originally posted by @makeavish in https://github.com/SigNoz/signoz/issues/2068#issuecomment-1403372065_

**Comment by csudani7** [comment]
@makeavish & @srikanthccv Not able to reproduce in latest develop branch. I tried with below custom parameters.
Please visit: https://www.loom.com/share/724102a8671b488d85f74aa0b8ea1ee3
Can you confirm this?

CC: @palashgdev

**Comment by MastersAbh** [comment]
Can you assign this to me ?

**Comment by palashgdev** [comment]
Sure @MastersAbh

**Comment by makeavish** [comment]
@csudani7 Not able to reproduce this issue.
@MastersAbh Were you able to reproduce?

**Comment by MastersAbh** [comment]
Hey, No. This seems to be working properly now. 
@palashgdev can you check again ?

**Comment by makeavish** [comment]
Closing the issue as it's not reproducible
