### ISSUE TITLE
FE:  Remove deprecation warning from Antd

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#2148]
## Is your feature request related to a problem?

*Please describe.*

this [warning occurred](https://ant.design/docs/react/migration-v5#component-api-adjustment) when we migrate antd version from [v4 to v5](https://github.com/SigNoz/signoz/pull/2012) as there are a few components which are listed below that need to update 

Resolution to solve the issue 

- some props by which the warning should be gone

Components:

- [x] #2360
- [x] #2362
- [x] #2423
- [x] #2447
- [x] #2448

**Comment by niteshsingh1357** [comment]
Hi @palashgdev, is this issue available? Can we split this ticket based on the components deprecation warning is for?
For example, "remove the deprecation warning for `Menu`" could be one sub-issue. Similarly, for `Dropdown` and `Tabs`

What do you think?

**Comment by palashgdev** [comment]
Yeah this issue is still there let me break it down
