### ISSUE TITLE
Sort logs in ascending or descending order

### ISSUE THREAD

**Issue by abhinavramana** [SigNoz/signoz#2176]
## Is your feature request related to a problem?
Its difficult to see the logs since intutively we want to see from the start.

## Describe the solution you'd like
Give ascending / descending sort by timestamp for logs

## Additional context
![image](https://user-images.githubusercontent.com/4195703/216652249-8a8fb490-3ea7-491d-af1f-adddd3f5d957.png)

#### *Thank you* for your feature request – we love each and every one!

**Comment by nityanandagohain** [comment]
@palashgdev  we will have to account for this in the new logs explorer page.

**Comment by palashgdev** [comment]
> @palashgdev we will have to account for this in the new logs explorer page.

this would be solved by orderBy right ?

**Comment by nityanandagohain** [comment]
yes @palashgdev
