### ISSUE TITLE
Ability to zoom into graphs by dragging for DB calls and external calls

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#2183]
Currently DB and external calls graph of services page doesn't support dragging in graph to zoom in the smaller timeframe of the graph. 
Dragging support is already added to other graphs services and dashboard page: https://github.com/SigNoz/signoz/pull/2018

**Comment by ksorv** [comment]
@makeavish the PR from where this issue was created is now merged, Would you be able to check if the issue still there.

If yes, I can take it up, else we can close it

**Comment by makeavish** [comment]
@ksorv Issue is still open. You are free to pick it up.

**Comment by makeavish** [comment]
Resolved in latest version
