### ISSUE TITLE
Include Rocky Linux as a choice for OS

### ISSUE THREAD

**Issue by fcpimenta** [SigNoz/signoz#2190]
## Is your feature request related to a problem?

When intslling on a Rocky Linux release 8.x vm, the installation script do not recognize Rocky Linux as an operating system and the process fails.

## Describe the solution you'd like

Please, consider the inclusion of Rocky Linux as a choice for OS.

## Describe alternatives you've considered

To install on Rocky Linux, I included the following lines in the install script /opt/signoz/deploy/install.sh in the case test:

```
            Rocky*)
            desired_os=1
            os="centos"
            package_manager="yum"
            ;;
```

**Comment by srikanthccv** [comment]
Feel free to send a PR :)

**Comment by pendolf** [comment]
PR was accepted in #2203
