### ISSUE TITLE
Difficult to click on metrics graph points to view traces

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#2194]
With the recent introduction of drag to zoom on graphs, it has become challenging to click on graph points and results in unintended drags.
https://www.loom.com/share/24195660d8124864bcff0af2fd74dc16

**Comment by palashgdev** [comment]
The metrics graph is fixed need to fix the database call section graphs

**Comment by palashgdev** [comment]
> The metrics graph is fixed need to fix the database call section graphs

onDragSelect is not present i.e. reason it is working fine... though needs to fix in the dashboard
