### ISSUE TITLE
Test SigNoz chart in different K8s versions of cloud vendors

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/signoz#2197]
Since the previous versions of Kubernetes (K8s) are either out of active support or maintenance support, it is important to make sure [SigNoz Helm chart](https://github.com/SigNoz/charts) is up-to-date and support the newer versions of K8s across different cloud vendors.

- Amazon Elastic Kubernetes Service (EKS) -  Managed NodeGroup
  - [x] 1.22
  - [x] 1.23  (make sure to include EBS driver and `AmazonEBSCSIDriverPolicy` policy)
  - [x] 1.24  (same as above)
  - [ ] 1.25  (not released yet)
- Google Kubernetes Engine (GKE) - Standard
  - [x] 1.23
  - [x] 1.24
  - [x] 1.25
  - [x] GKE Autopilot (resolved by https://github.com/SigNoz/charts/pull/175, make sure to have enough resource quota since requests/limits are overridden to default high min value)
- Azure Kubernetes Service (AKS)
  - [x] 1.23 (verified by @euclidesflores)
  - [x] 1.24 (same as above)
  - [x] 1.25 (same as above)
  - [x] 1.26 (same as above)
- DigitalOcean Kubernetes
  - [x] 1.23  (make sure to have sufficient resources in the cluster or reduce the default  resource.request of all)
  - [x] 1.24  (same as above)
  - [x] 1.25  (same as above)

Any help to validate the same would be much appreciated.

Also, do let us know if you want any other cloud vendor or K8s version to be included.

**Comment by euclidesflores** [comment]
@prashant-shahi please assign me this ticket. I will be validating SigNoz on AKS.

**Comment by euclidesflores** [comment]
Azure Kubernetes Service (AKS)

- [ ] 1.22
- [ ] 1.23
- [x] 1.24
- [ ] 1.25

**Comment by euclidesflores** [comment]
@prashant-shahi please update the issue with my previous comment, thanks!

**Comment by prashant-shahi** [comment]
@euclidesflores Updated! Thanks a lot for taking your valuable time to test SigNoz charts across various K8s versions of Azure Kubernetes Service (AWS).

**Comment by euclidesflores** [comment]
@prashant-shahi let me know if I can help with other ticket.
