### ISSUE TITLE
How to remove service Frontend Mysql Driver this service onUI

### ISSUE THREAD

**Issue by Shulong123** [SigNoz/signoz#2204]
How to remove service Frontend Mysql Driver this service onUI
![image](https://user-images.githubusercontent.com/15952709/217423244-67e3aeb2-b9bc-41aa-9053-40a8795fa5eb.png)

**Comment by palashgdev** [comment]
this are from the sample hotrod application if you make a comment in the docker component this will resolve the issue

**Comment by palashgdev** [comment]
https://signoz.io/docs/operate/docker-standalone/#remove-the-sample-application-from-signoz-dashboard

this will solve the issue

**Comment by hopewise** [comment]
For my case, I already have started signoz without using `docker-compose-minimal.yaml` , what shall I do ? can I re-install with minimal option without losing my data ?
