### ISSUE TITLE
Invite token Issue faced by users

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#2206]
- [ ] I have installed signoz on EKS cluster as a pod and running service while trying to login we are getting, invite token is required.

**Solution**

The first user who has installed SigNoz can create an account. She becomes admin by default. New users need to get invite from admins to sign in to SigNoz
Check the note here - https://signoz.io/docs/userguide/authentication/#supported-roles

Please ask your admin ( the person who has first installed SIgNoz) to send an invite. 

If you are still facing this issue, please ask this question in our slack community ( https://signoz.io/slack ) and we should be able to help you out

**Comment by pranay01** [comment]
@palashgdev @prashant-shahi Is this issue still not solved. I think this is a messaging issue which confuses users

**Comment by mindhash** [comment]
@pranay01 Will this messaging work:

> You need an invitation to create an account. Please ask your admin (the person who has first installed SIgNoz) to send an invite.


The error appears when someone is trying to setup account without an invite token.

**Comment by mindhash** [comment]
Created PR https://github.com/SigNoz/signoz/pull/2215

**Comment by pranay01** [comment]
@mindhash We had a discussion yesterday on introducing a new API, which can detect if an instance of SigNoz already has a user created or not and based on that either show the Create Account page directly or take to the login page

Please sync with @makeavish  on this once.

Here's the updated messaging:

https://github.com/SigNoz/signoz/issues/1860#issuecomment-1422497829

**Comment by srikanthccv** [comment]
Fixed in https://github.com/SigNoz/signoz/pull/2215
