### ISSUE TITLE
New alert channel UI has issues

### ISSUE THREAD

**Issue by patrijua** [SigNoz/signoz#2217]
## Bug description

New alert channel UI has issues. All text fields are missing descriptions and headers what they are and what is the expected input. Also a scaling issue in dropdown  box where to select type of alert channel

![image](https://user-images.githubusercontent.com/57624530/217834695-ee406090-72c9-4365-9494-94ee9f6334c6.png)

## Version information 
* **Signoz version**: 0.15
* **Browser version**: Chrome 109.0.5414.119
* **Your OS and version**: MacOS Ventura 13.1
* **Your CPU Architecture**(ARM/Intel): Intel

**Comment by srikanthccv** [comment]
We should find a way to automatically detect which pages are affected by antd upgrade or check each page explicitly since this is a reoccurring issue.

**Comment by palashgdev** [comment]
>We should find a way to automatically detect which pages are affected by antd upgrade or check each page explicitly since this is a reoccurring issue.

no @srikanthccv untill we have a unit test case for same we won't be able to detect this one... 😢
