### ISSUE TITLE
Error fetching services and traces in signoz frontend(running signoz locally using docker compose)

### ISSUE THREAD

**Issue by ThunderGod77** [SigNoz/signoz#2219]
## Bug description

I am not able to see any services or traces in the front end, it only shows a something-went-wrong popup on the side.

## Expected behavior
I am also not able to  the traces of the default hotrod application

## How to reproduce

1. Installing signoz using docker-compose by following instructions from [here](https://signoz.io/docs/install/docker/)
2. Visiting http://localhost:3301/services

## Version information 
* **Signoz version**:0.15.0
* **Browser version**:brave v 1.47.186
* **Your OS and version**:mac os 13.1
* **Your CPU Architecture**(ARM/Intel): Intel
<img width="1390" alt="Screenshot 2023-02-10 at 10 53 25 AM" src="https://user-images.githubusercontent.com/56389741/218007836-06dd600b-7ed0-4798-a5a1-d4d25535161d.png">

![Screenshot 2023-02-10 at 10 54 41 AM](https://user-images.githubusercontent.com/56389741/218007958-6aa61d71-0604-4484-852d-030969a1e955.png)

**Comment by makeavish** [comment]
@ThunderGod77 Please share response of `/api/v1/services `.
Also share logs of query-service.
And can you try uninstalling and reinstalling?

**Comment by ThunderGod77** [comment]
I guess these are the screenshots of the logs pertaining to the error
![Screenshot 2023-02-10 at 11 20 07 AM](https://user-images.githubusercontent.com/56389741/218012389-3e369c07-0101-4531-8573-1dfdfb8ff8d7.png)
![Screenshot 2023-02-10 at 11 23 04 AM](https://user-images.githubusercontent.com/56389741/218012404-48096825-5ba5-4cfc-8211-4154be5270bf.png)

**Comment by makeavish** [comment]
@ThunderGod77 Please share logs of query-service

**Comment by ThunderGod77** [comment]
Here is the log file
[a.log](https://github.com/SigNoz/signoz/files/10706547/a.log)

**Comment by ThunderGod77** [comment]
I cloned the develop branch instead of the main branch this time and then installed signoz, and it seems to work
The issue might be that this tutorial https://signoz.io/docs/install/docker/ is outdated or the main branch has some issue

**Comment by palashgdev** [comment]
@Cruxashu please have a look

**Comment by ThunderGod77** [comment]
yes...it worked after deleting the repo and following the installation steps again.
