### ISSUE TITLE
4xx chart

### ISSUE THREAD

**Issue by amit-100ms** [SigNoz/signoz#222]
4xx should be treated as errors or should be highlighted in signoz dashboard. As per discussion with @ankitnayan only 5xx are treated as errors while 4xx don't show up as special. 

Solution exepcted:
Please either highlight 4xx in different category or as errors or create a special chart for 4xx.

**Comment by amit-100ms** [comment]
any ideas when will this be picked up/prioritized @ankitnayan ?

**Comment by pranay01** [comment]
hey @amit-100ms 

Currently you can achieve this in our trace page if you have a specific status code to monitor. The aggregate graph below shows it count/rps for that status code. 

We are enhancing this functionality to support regex too. So, you should be able to chose 
`http.status_code REGEX 4??` and this will show a graph of requests having 4XX response code. The list of traces with 4XX response code will be below, so you can explore the responsible traces also. This should be shipped in a weeks time.


Will this serve your use case? 
Though this will need you to select different service every time from the drop down above to see 4xx calls corresponding to it. 

![Screenshot 2021-07-30 at 5 06 29 PM](https://user-images.githubusercontent.com/504541/127647632-09a49573-c456-4b38-a115-1c886faab4ee.png)

**Comment by pranay01** [comment]
@amit-100ms We have shipped this regex filtering feature. The chart in the panel below shows graphs for filtered traces. Attached is loom video -
 https://www.loom.com/share/e808a9f35f8b4a82ad3a9b2d6c95aaa9
