### ISSUE TITLE
Spinner at the Center with New Spining indicator

### ISSUE THREAD

**Issue by Vimalraj571** [SigNoz/signoz#223]
## Is your feature request related to a problem?

Other than the metrics tab The spinner is rendering in the top left which is need a work around i guess

## Describe the solution you'd like

![old_spin](https://user-images.githubusercontent.com/8166149/125295438-db359280-e342-11eb-8088-5a1dcdefd16f.png)

Make the spinner to spin in the center

## Describe alternatives you've considered

![new1](https://user-images.githubusercontent.com/8166149/125558802-690714bd-502d-46be-b7cc-7c1403e880f9.png)

## Additional context

Changed the Spinner style to the Custom Spin Indicator like Above

**Comment by pranay01** [comment]
Displaying spinner in the centre seems the right approach. Will check the PR
