### ISSUE TITLE
Show related logs from trace view

### ISSUE THREAD

**Issue by agronholm** [SigNoz/signoz#2230]
## Is your feature request related to a problem?

No.

## Describe the solution you'd like

I'd like the ability to see log records related to a trace/span when looking at a specific trace. It would show me logs based on their trace/span IDs in a separate panel in the same view.

## Describe alternatives you've considered

Searching for log entries manually based on the trace/span IDs. Works, but not as convenient.

## Additional context

Datadog has this feature in their service.

**Comment by nityanandagohain** [comment]
Hi, now you can go to related logs directly from your traces page.

**Comment by palashgdev** [comment]
https://signoz.io/blog/community-update-25/#correlation-from-logs-to-trace-and-vice-versa
