### ISSUE TITLE
Push docker image with each PR

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#225]
Would be great to push a docker image with each PR raised/changed. Would be of great help in testing out the PR.

**Comment by ankitnayan** [comment]
@rajdas98 Can you pick this up?

**Comment by rajdas98** [comment]
Yes, @ankitnayan. One suggestion- Instead of a new image for each PR, we can create new image tags.

**Comment by ankitnayan** [comment]
> Yes, @ankitnayan. One suggestion- Instead of a new image for each PR, we can create new image tags.

I meant that only 😉

**Comment by pranay01** [comment]
@prashant-shahi Is this fixed now with the `ok-to-test` setup?

**Comment by prashant-shahi** [comment]
yes, it is.

We are not pushing each images built from PRs to DockerHub, but rather using it k3d cluster created in CI to set up the preview environment.
