### ISSUE TITLE
(logs): query range v3

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#2250]
The client should be able to use the request/response payload mentioned in https://github.com/SigNoz/signoz/issues/2237 and be able to get the data for a value type, chart type, table type, and list type.

- [x] https://github.com/SigNoz/signoz/issues/2369
- [x] https://github.com/SigNoz/signoz/issues/2370
- [x] https://github.com/SigNoz/signoz/issues/2371
- [x] https://github.com/SigNoz/signoz/issues/2372
- [x] https://github.com/SigNoz/signoz/issues/2373
- [x] https://github.com/SigNoz/signoz/issues/2374
- [x] https://github.com/SigNoz/signoz/issues/2375
- [x] https://github.com/SigNoz/signoz/issues/2376
- [x] https://github.com/SigNoz/signoz/issues/2573
- [x] https://github.com/SigNoz/signoz/issues/2601
- [x] https://github.com/SigNoz/signoz/issues/2599
- [x] https://github.com/SigNoz/signoz/issues/2594
- [x] https://github.com/SigNoz/signoz/issues/2591

**Comment by nityanandagohain** [comment]
@ankitnayan updated this issue with the new issues related to query range v3 for logs.

**Comment by srikanthccv** [comment]
@nityanandagohain please check which of the remaining can be closed and are getting addressed in separate epic/issues.

**Comment by nityanandagohain** [comment]
@srikanthccv  it will be pickup up this week, this is the epic issue https://github.com/SigNoz/signoz/issues/2594 . Lets close after that ?
