### ISSUE TITLE
Bug:(FE) Handle unCaught Error in component

### ISSUE THREAD

**Issue by palashgupta98** [SigNoz/signoz#227]
## Bug description
There is no fallback component when there is any unhandled Error in the React component

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

<img width="1440" alt="Screenshot 2021-07-16 at 8 23 29 AM" src="https://user-images.githubusercontent.com/29013861/125884486-c1015960-6bcc-427c-aeb2-0bf1fd9bc808.png">

## Expected behaviour

Component must be rendered to show a handful of errors and to show a useful message

## How to reproduce

1. in any component throw a new Error('any message')
2. screen may be black or white

## Version information 
* **Signoz version**:
* **Browser version**:
* **Your OS and version**:

## Additional context
1. https://reactjs.org/docs/error-boundaries.html

**Comment by YounixM** [comment]
Done ✅
