### ISSUE TITLE
S3 Retention Testing

### ISSUE THREAD

**Issue by SenorMooMoo** [SigNoz/signoz#2272]
When S3 retention is enabled but the cluster fails to get the bucket will it continue to use the volumes?

**Comment by prashant-shahi** [comment]
@SenorMooMoo It is safe to say that in case of most scenarios of invalid/inaccessible S3 configurations, SigNoz will not function properly.

In some of the cases, it would help to have multiple shards of ClickHouse prior to adding S3 config. It would do that by attempting to apply S3 config in one of the instances (shards). However, there is expected to be incomplete historical data in SigNoz UI, which could potentially be resolved after we introduce support for ClickHouse replicas.
