### ISSUE TITLE
use browser's HTTP cache with small expiry for tag key/value requests

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#2282]
When a user works with the query builder, the client will send requests to the server asking for the new tag key/value results matching the criteria. The user's typing is instant and frequent; querying the database multiple times within a short duration is inefficient for reasons including the ClickHouse query concurrency. The server can set the [`Cache-Control`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Browser_compatibility) with small expiry that is reasonable enough that it doesn't stale results for regular use cases.

@palashgdev this is what we were referring to when the cache was brought up. With the `Cache-Control` headers set, the browser does all the work.

**Comment by srikanthccv** [comment]
@palashgdev you mentioned something done in react app. Can you elaborate it here?

**Comment by palashgdev** [comment]
>
@palashgdev you mentioned something done in react app. Can you elaborate it here?

we are internally managing a caching layer in the client for the API layer which is based on the query keys and response that we get as a value

if keys(variables/props) do not change we reflect the data from the cache only but to validate the response we make an API to the backend which underneath verifies and updated the response

**Comment by srikanthccv** [comment]
If I understand correctly, the request will be made regardless of the props change. This is probably a component cache or something since the request is sent server to get the response. The `Cache-Control` will prevent the actual network request made in this case and returns the cached response until the time elapses. This doesn't require any extra effort on the front end side. I think we can set the headers on the query service. 

Does 60 seconds make sense `Cache-Control: public, max-age=60`? 

Thoughts @SigNoz/backend @SigNoz/frontend ?

**Comment by palashgdev** [comment]
no I don't think there will be an extra effort regarding the same
