### ISSUE TITLE
FE: [Query Builder] Search Bar (Where Clause)

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#2286]
## Is your feature request related to a problem?

*Please describe.*
Need to build a common search bar in which users can do and generate query

https://www.figma.com/file/i2CsZFl27dhmER6gnx08wj/Integ.-QueryBuilder%2B3SigNalCorrelation?node-id=1%3A8036&t=tkzNwNk8Su1ivj1Y-0

fetching of one query tag involves 3 part 

1. fetching of keys and selection of value
1. selection of the operator
1. selection of the value

Points to look for the development

1. for an operator like existing value can be empty
1. while pressing backspace prev tag can be editable and populate options accordingly 
1. key, operator cannot contain space in it
1. User should freely type and update the options accordingly 

Note: when key, value and operator are selected this will turn into an antd Tag https://ant.design/components/tag

**Comment by srikanthccv** [comment]
>for an operator like existing value can be empty

To make it more clear and explicit, _for operators like `Exists` or `Not Exists`, the value won't be there_

**Comment by palashgdev** [comment]
Operator List: https://www.notion.so/signoz/List-of-filter-operators-e0665c735c0445a49c1894b565f69d0b

**Comment by techchintan** [comment]
Use = , != , > , >= , < , <= instead of  EQUALS , NOT EQUALS , GT , GTE , LT, LTE
