### ISSUE TITLE
Logs Parsing issue for empty string

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#2296]
https://www.loom.com/share/14cf98705eb54657a586f483c6bfed49

**Comment by nityanandagohain** [comment]
@palashgdev  the query builder has no option for creating empty string, if we type empty string it is interpreted differently as shown in the video.

**Comment by nityanandagohain** [comment]
This will be solved by https://github.com/SigNoz/signoz/issues/2853

**Comment by nityanandagohain** [comment]
Support added in new QB with exists operator
