### ISSUE TITLE
Enable colour encoding in loglines

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#2298]
Currently, SigNoz shows colours as encoded characters in logs. Raising this feature request to enable colour coding in loglines.

- [x] Raw View
- [x] Table View
- [x] List View

**Comment by ankitnayan** [comment]
@nityanandagohain please share some dummy data for frontend to work on

**Comment by nityanandagohain** [comment]
If there are two words `hello world` and there is some colour characters in between, then it will result in wrong full text search, we need to check how it should be handled
