### ISSUE TITLE
Unable to select multiple tag values using Trace query builder

### ISSUE THREAD

**Issue by al-mcintosh** [SigNoz/signoz#2300]
## Bug description

Unable to select multiple tag values from the list of possible values in the drop down. e.g. [Tag] [In] [Values]

*Please describe.*  

I'm trying to build a query: Tag in ("0","1","2","etc") but I can't figure out how to select multiple values? 

![trace_qb](https://user-images.githubusercontent.com/45045833/220155958-6b9393a8-04c4-466e-8534-dad092c70844.PNG)

Once I select the first value from the drop down, I'm unable to select and add additional values.

![trace_qb_a](https://user-images.githubusercontent.com/45045833/220155980-247cd99f-e78d-4206-940b-5c8053b3fcae.PNG)

## Expected behavior

Build a query: Tag in ("0","1","2","etc") but I am unable to select multiple values. 

## How to reproduce

1. Navigate to /trace
2.  Select Add Tags Filter
3.  Select Tag (that will have multiple values) 
4.  Select Operator IN
5.  Select Value
6. Unable to select any additional values. 

## Version information 
* **Signoz version**: v0.14.0
* **Browser version**: Chrome Version 110.0.5481.78 (Official Build) (64-bit)
* **Your OS and version**: Windows 10 Version 22H2
* **Your CPU Architecture**(ARM/Intel): 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz

**Comment by ankitnayan** [comment]
@makeavish I think this still exists in `v0.16.1`

**Comment by makeavish** [comment]
Yes @ankitnayan 
To select multiple tags user needs to add new tag filters.

**Comment by ankitnayan** [comment]
> Yes @ankitnayan To select multiple tags user needs to add new tag filters.

Adding another tag filter will make it an `AND` and not `OR`

**Comment by al-mcintosh** [comment]
@makeavish  I am trying to query multiple  `VALUES` for 1 `TAG`  for example:

`db.system in ("mssql","elasticsearch",postgresql)`


It becomes very difficult to build queries by hand for longer tag values, like URLs:

`db.url in ("https://blah.host.net/path/path/search?token=00000000-0000-0000-0000-000000000000-89437c30-dca6-48f3-92bd","https://foo.host.net/path/path/search?token=00000000-0000-0000-0000-000000000000-765ec4772d8d-dca6-48f3-92bd","https://foo.host.net/path/path/search?token=00000000-0000-0000-0000-111111111111-765ec4772d8d-dca6-48f3-92bd")`
