### ISSUE TITLE
feat: create a PR template

### ISSUE THREAD

**Issue by nidhi-tandon** [SigNoz/signoz#233]
## Is your feature request related to a problem?

*Add a PR template so the PR description remains consistent*

## Describe the solution you'd like
The PR template should include the following:
1. Describe what your PR does
2. Write individual changes in points (List of impacted parts in the project for e.g. UI of spans, functionality of traces etc.)
3. Enter any additional message, information, linked issues, etc
4. Checklist  
     - Self-check PR once?
     - Added screenshots to PR?
     - Is the format of your [commit messages](https://www.conventionalcommits.org/en/v1.0.0/) proper?
     - Is [name of your branch](https://dev.to/couchcamote/git-branching-name-convention-cch) is proper?
     - Have you ensured that no sizeable refactors are mixed in this PR?
     - Any manual dev testing is done by you in a staging environment?

**Comment by YounixM** [comment]
Done ✅
