### ISSUE TITLE
frontend: flacky copy to clipboard in log page

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/signoz#2331]
This is not always reproducible. However, it happens clicking around different values to be "auto copied" to clipboard and in few cases any new keystrokes cause that to pop up.
After clicking around the page, it changes back to its normal behaviour.

_Screenshot:_

![image](https://user-images.githubusercontent.com/11138844/220651135-4f7875b5-b268-4386-9c43-a5645df7826c.png)

[Internal Slack Message](https://signoz-team.slack.com/archives/C02TJ466H8U/p1677074119190189?thread_ts=1677068686.057209&cid=C02TJ466H8U)

**Comment by ksorv** [comment]
@prashant-shahi @srikanthccv I found this issue to be very reproducible:

- As mentioned in description above, The object value fields in any list or table are copyable by click on them(behaviour visible as you can see a copy to clipboard pop over)
- As for random strokes, When any of the field is in focus any keyboard click copies the item and shows the notification
- Also the alert box starts appearing after i clicked system on mac keyboard, after that any system key like `command`, `shift`, `option`
  - one, copied the text
  - second, open the alert box
  - This is pretty random, no sure fire way to get it in N mount of strokes

Here's a video with keystrokes, and mouse clicks:

https://user-images.githubusercontent.com/34188267/236635938-e30f4bf0-b1cd-4239-88d8-fdb94613e87a.mov

**Comment by makeavish** [comment]
This is not reproducible in New Logs Explorer Page so closing this.
