### ISSUE TITLE
feat: add commitizen in pre commit hooks

### ISSUE THREAD

**Issue by nidhi-tandon** [SigNoz/signoz#234]
## Is your feature request related to a problem?

*Add commitizen in pre-commit hooks*

## Describe the solution you'd like
Add commitizen via husky as pre-commit hooks 
https://github.com/commitizen/cz-cli

## Describe alternatives you've considered
https://github.com/commitizen/cz-cli#husky

**Comment by Bhavin789** [comment]
Hello @nidhi-tandon , if someone is not already working, can I have a look at this? Thanks.

**Comment by YounixM** [comment]
Done ✅
