### ISSUE TITLE
feat: add prettier and eslint checks in pre commit hooks

### ISSUE THREAD

**Issue by nidhi-tandon** [SigNoz/signoz#235]
## Is your feature request related to a problem?

*Add prettier and eslint checks on staged files while commiting*

## Describe the solution you'd like
We can use [lint staged](https://github.com/okonet/lint-staged) to solve this
Adding prettier and eslint will resolve all the inconsistencies in the code and will help in code maintainability.

**Comment by saideepesh000** [comment]
Hey @nidhi-tandon , I'm assigning this to myself

**Comment by palash-signoz** [comment]
Hi @saideepesh000 I think eslint-prettier is already resolved in this #214 

can you please look into husky.

Do let me know

**Comment by palash-signoz** [comment]
please also look into #234

**Comment by palash-signoz** [comment]
Hi @saideepesh000 
I am taking this issue .. due to inactivity
