### ISSUE TITLE
Create alerts from the dashboard panel

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#2355]
![Image](https://user-images.githubusercontent.com/22846633/220817597-b8169c53-6de2-4c5b-a280-41e30aa0c98e.png)

This button will appear in the right bottom corner of the dashboard edit mode just below the panel settings section. 

A user should be able to create an alert from the dashboard panel. Since the dashboard panel already has the queryId the implementation just needs to redirect the user from the panel to alerts page using the queryId in the URL params.

**Comment by ankitnayan** [comment]
[Y-axis unit in alerts ](https://github.com/SigNoz/signoz/issues/2548) should also be handled IMO. @srikanthccv you may need to get involved on bringing clarity to enabling thresholds with units which might be tricky.

**Comment by ankitnayan** [comment]
https://github.com/SigNoz/signoz/issues/2355
