### ISSUE TITLE
Dropdown antd depreciation warning

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#2360]
There are a few places in which dropdown components need to be updated

- [x] frontend/src/components/TimePreferenceDropDown/index.tsx  
- [x] frontend/src/container/ConfigDropdown/index.tsx
- [x] frontend/src/container/Header/index.tsx:100
- [x] frontend/src/container/ListOfDashboard/index.tsx:233

<img width="773" alt="Screenshot 2023-02-23 at 1 14 22 PM" src="https://user-images.githubusercontent.com/88981777/220847130-dc304667-c68d-4329-b5e4-34929aa274f4.png">

<img width="773" alt="Screenshot 2023-02-23 at 1 17 47 PM" src="https://user-images.githubusercontent.com/88981777/220848845-c34c5be9-c38f-49c1-bb44-72a1e1abb6ec.png">

**Comment by rkmdCodes** [comment]
Hi! @palashgdev Please check this PR #2381 I have added further context there. thanks!

**Comment by rkmdCodes** [comment]
hi @palashgdev @techchintan  sir ,  I have opened a new PR #2424  which will close this issue

**Comment by palashgdev** [comment]
@techchintan @rkmdCodes there are two PR's right now which one is the right one

**Comment by rkmdCodes** [comment]
hi @palashgdev sir, my PR #2424 is the right one  , another PR is by @techchintan sir where he was giving me ideas to fix overlay to menu depreciation , my PR #2424 is closing the issue #2360
Thanks
