### ISSUE TITLE
Set common default time period across different pages on SigNoz

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#2361]
Currently, services and service-map page has a default time period of last 5mins and other pages like exceptions, traces and logs have a default time period of last 30mins. This causes confusion for new users when they try to test instrumented services. They might see traces/exceptions in last 30mins but won't see any services in last 5mins as there was no traffic in last 5mins. 
So setting a standard default timestamp across different pages can avoid this confusion.

**Comment by pranay01** [comment]
@makeavish I think this was done because service map was more resource intensive to calculate for longer period, hence we used a small default time period -  @ankitnayan Is that accurate?

**Comment by makeavish** [comment]
> @makeavish I think this was done because service map was more resource intensive to calculate for longer period, hence we used a small default time period - @ankitnayan Is that accurate?

@pranay01 We have started using Materialized view for service map which improves performance significantly so now we can update default time to 30mins for every page.

**Comment by pranay01** [comment]
Ok, I am fine with it. We can make the default time to 30 min if performance is fine
