### ISSUE TITLE
Add unit test cases for flattener processor

### ISSUE THREAD

**Issue by lalitkale** [SigNoz/signoz#237]
## Bug description
Add unit test cases for flattener processor

## Expected behaviour
Code-Coverage improved for Query service from 0 to ~60% to begin with when measured with `go test -cover`

## How to reproduce
NA

## Version information 
NA

## Additional context
#236

**Comment by pranay01** [comment]
Flattener processor was only part of the setup with druid as datastore. We have deprecated support for druid as a datastore
