### ISSUE TITLE
[UX/UI Feature] Make Table view rows resizable/clickable

### ISSUE THREAD

**Issue by rwjack** [SigNoz/signoz#2387]
Also looking at the columns, they are too big use up a lot of space.

SigNoz:
![image](https://user-images.githubusercontent.com/59068073/221409695-f0bb4392-7c99-48da-a91d-b3c6a0b8d8f7.png)

Competitor:
![image](https://user-images.githubusercontent.com/59068073/221409558-2a34d0f6-4158-48cd-949d-1a1173f0c0c9.png)

I think it's better to have log rows clickable - because often times, the user will be opening the log rather than copying data from it, and it's way easier to open a log entry by clicking anywhere on the log, rather than having to click the  small "<->" expand button on the left side of the screen.

The expand button could be replaced with a Log Level color pattern. (LightBlue=info, Red=error, DarkRed=Critical, etc.)

**Comment by makeavish** [comment]
This is available in latest Logs Explorer page
