### ISSUE TITLE
Translate README in Chinese(Mandarin?)

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#239]
We see many devs from China are using SigNoz. It would be be good if README is translated to Chinese (Mandarin?). I don't have good understanding of different dialects of Chinese, so if folks can comment on what are the most popular dialects - that would be helpful

This will make it easier for devs from China to get started with SigNoz.

**Comment by tonyqus** [comment]
Maybe I can help. I also see a gap of .NET client support in SigNoz

**Comment by pranay01** [comment]
Thanks @tonyqus That would be great. Assigning this issue to you. 

We have not explicitly tested SigNoz for .NET yet but  we support opentelemetry for instrumentation and you can try the instructions mentioned here - https://github.com/open-telemetry/opentelemetry-dotnet

Do let us know also if you are able to successfully instrument .NET - we can add in our docs

**Comment by tonyqus** [comment]
#244
