### ISSUE TITLE
Translate README to German

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#240]
We see many devs from Germany are using SigNoz. It would be be good if README is translated to German.

This will make it easier for devs from Germany and German speaking countries to get started with SigNoz.

**Comment by vincentrohde** [comment]
@pranay01 If this issue is still open, I can help you with the German translation 👍

**Comment by pranay01** [comment]
Sure. would be very helpful @vincentrohde 

Assigning to you

**Comment by vincentrohde** [comment]
@pranay01 I guess this issue could be closed since the PR went through right?
