### ISSUE TITLE
add some badges to the readme

### ISSUE THREAD

**Issue by abhaysingh003** [SigNoz/signoz#242]
## Is your feature request related to a problem?

Add some badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

## Describe the solution you'd like

I will add some badges at the top and also will add links related to them so that the README.md file will look more interactive and awesome.

**Comment by pranay01** [comment]
@SINGH-UMS Can you give more details on what badges you want to add. Agree with the broad idea of adding more badges - but those should be relevant to folks who are exploring the repo :)

**Comment by SINGH-UMS** [comment]
like this @pranay01 -
![image](https://user-images.githubusercontent.com/73235395/127285245-cfce8948-d6f1-4be6-b861-8f55af58a05a.png)

**Comment by pranay01** [comment]
Ok. Can there be more useful tags we can show?

In the above list - I find the following badges which could be useful for our visitors
- Contributions Welcome
- Maintained? Yes
- Forks 

Can you add these in a PR, would be useful I think

**Comment by SINGH-UMS** [comment]
yes I can add them
