### ISSUE TITLE
How can we control the color of each span of the trace flame graph

### ISSUE THREAD

**Issue by xuwei6688** [SigNoz/signoz#2460]
## Is your feature request related to a problem?

*Please describe.*
How can we control the color of each span of the trace flame graph?
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/31433665/225574901-d596dd39-5cad-4b7d-a71c-9c98501a37de.png">

## Describe the solution you'd like
The span color on the flame graph is controlled by the span attribute. The color code can be specified in the attribute. 

## Describe alternatives you've considered
Or other ways to let the user customize the color each span displays on the graph.

#### *Thank you* for your feature request – we love each and every one!

**Comment by ankitnayan** [comment]
@xuwei6688 the attribute should be specified during instrumentation? what's your use case?

**Comment by xuwei6688** [comment]
> @xuwei6688 the attribute should be specified during instrumentation? what's your use case?
At present, it seems that only error is marked in red, or different services have different colors. Can I decide the color?

**Comment by xuwei6688** [comment]
At present, it seems that only error is marked in red, or different services have different colors. Can I decide the color?
Can I use the attribute on the span or some other way to determine the color of this span

**Comment by xuwei6688** [comment]
> @xuwei6688 the attribute should be specified during instrumentation? what's your use case?

**Comment by xuwei6688** [comment]
> @xuwei6688 the attribute should be specified during instrumentation? what's your use case?

Some of the spans are very important, and you want to quickly find them on the flame graph by color

**Comment by xuwei6688** [comment]
> > Some of the spans are very important, and you want to quickly find them on the flame graph by color
> 
> I get the use case now. Let's say we use the `color` field from the attributes of a span to set the color of that span, you would have to add that attribute to the span which is interesting to you, right? And this won't apply to auto-instrumentation. It will only work for custom instrumentation (adding a span manually in code).

yes

**Comment by xuwei6688** [comment]
> I get the use case now. Let's say we use the `color` field from the attributes of a span to set the color of that span, you would have to add that attribute to the span which is interesting to you, right? And this won't apply to auto-instrumentation. It will only work for custom instrumentation (adding a span manually in code).

Yes, this is exactly what I want. Is it supported now? What should I do?
