### ISSUE TITLE
Signoz setup in k8s otel collectors crashing

### ISSUE THREAD

**Issue by Vaibhavi-Tanla** [SigNoz/signoz#2466]
I'm doing a setup in the AKS of signoz i've used below helm charts
helm repo add signoz https://charts.signoz.io
changed the namespace to signoz and used our own standalone clickhouse cluster setup along with zookeeper
Post installation i'm obeserving below issues in OTEL_COLLECTOR
Error is below
PS D:\Signoz> kubectl logs po/signoz-otel-collector-65fbf66f4f-zdntv -n signoz
Defaulted container "signoz-otel-collector" out of: signoz-otel-collector, signoz-otel-collector-init (init)
2023-03-17T10:58:29.571Z        info    service/telemetry.go:111        Setting up own telemetry...
2023-03-17T10:58:29.572Z        info    service/telemetry.go:141        Serving Prometheus metrics      {"address": "0.0.0.0:8888", "level": "Basic"}
2023-03-17T10:58:29.572Z        info    components/components.go:30     Stability level of component is undefined       {"kind": "exporter", "data_type": "metrics", "name": "clickhousemetricswrite", "stability": "Undefined"}
time="2023-03-17T10:58:29Z" level=info msg="Executing:\nCREATE DATABASE IF NOT EXISTS signoz_metrics ON CLUSTER cluster\n" component=clickhouse
time="2023-03-17T10:58:29Z" level=info msg="Executing:\nCREATE TABLE IF NOT EXISTS signoz_metrics.samples_v2 ON CLUSTER cluster (\n\t\t\tmetric_name LowCardinality(String),\n\t\t\tfingerprint UInt64 Codec(DoubleDelta, LZ4),\n\t\t\ttimestamp_ms Int64 Codec(DoubleDelta, LZ4),\n\t\t\tvalue Float64 Codec(Gorilla, LZ4)\n\t\t)\n\t\tENGINE = MergeTree\n\t\t\tPARTITION BY toDate(timestamp_ms / 1000)\n\t\t\tORDER BY (metric_name, fingerprint, timestamp_ms)\n\t\t\tTTL toDateTime(timestamp_ms/1000) + INTERVAL 2592000 SECOND DELETE;\n" component=clickhouse
time="2023-03-17T10:58:29Z" level=info msg="Executing:\nCREATE TABLE IF NOT EXISTS signoz_metrics.distributed_samples_v2 ON CLUSTER cluster AS signoz_metrics.samples_v2 ENGINE = Distributed(\"cluster\", \"signoz_metrics\", samples_v2, cityHash64(metric_name, fingerprint));\n" component=clickhouse
time="2023-03-17T10:58:30Z" level=info msg="Executing:\nALTER TABLE signoz_metrics.samples_v2 ON CLUSTER cluster MODIFY SETTING ttl_only_drop_parts = 1;\n" component=clickhouse
time="2023-03-17T10:58:30Z" level=info msg="Executing:\nSET allow_experimental_object_type = 1\n" component=clickhouse
time="2023-03-17T10:58:30Z" level=info msg="Executing:\nCREATE TABLE IF NOT EXISTS signoz_metrics.time_series_v2 ON CLUSTER cluster(\n\t\t\tmetric_name LowCardinality(String),\n\t\t\tfingerprint UInt64 Codec(DoubleDelta, LZ4),\n\t\t\ttimestamp_ms Int64 Codec(DoubleDelta, LZ4),\n\t\t\tlabels String Codec(ZSTD(5))\n\t\t)\n\t\tENGINE = ReplacingMergeTree\n\t\t\tPARTITION BY toDate(timestamp_ms / 1000)\n\t\t\tORDER BY (metric_name, fingerprint)\n\t\t\tTTL toDateTime(timestamp_ms/1000) + INTERVAL 2592000 SECOND DELETE;\n" component=clickhouse
time="2023-03-17T10:58:30Z" level=info msg="Executing:\nCREATE TABLE IF NOT EXISTS signoz_metrics.distributed_time_series_v2 ON CLUSTER cluster AS signoz_metrics.time_series_v2 ENGINE = Distributed(\"cluster\", signoz_metrics, time_series_v2, cityHash64(metric_name, fingerprint));\n" component=clickhouse
time="2023-03-17T10:58:30Z" level=info msg="Executing:\nALTER TABLE signoz_metrics.time_series_v2 ON CLUSTER cluster DROP COLUMN IF EXISTS labels_object\n" component=clickhouse
time="2023-03-17T10:58:30Z" level=info msg="Executing:\nALTER TABLE signoz_metrics.distributed_time_series_v2 ON CLUSTER cluster DROP COLUMN IF EXISTS labels_object\n" component=clickhouse
time="2023-03-17T10:58:30Z" level=info msg="Executing:\nALTER TABLE signoz_metrics.time_series_v2 ON CLUSTER cluster MODIFY SETTING ttl_only_drop_parts = 1;\n" component=clickhouse
2023-03-17T10:58:31.476Z        info    kube/client.go:101      k8s filtering   {"kind": "processor", "name": "k8sattributes", "pipeline": "metrics", "labelSelector": "", "fieldSelector": "spec.nodeName=aks-nodepool1-18518278-vmss00000f"}
2023-03-17T10:58:31.477Z        info    components/components.go:30     Stability level of component is undefined       {"kind": "exporter", "data_type": "traces", "name": "clickhousetraces", "stability": "Undefined"}
2023-03-17T10:58:31.676Z        info    clickhousetracesexporter/clickhouse_factory.go:146      Patching views  {"kind": "exporter", "data_type": "traces", "name": "clickhousetraces"}
2023-03-17T10:58:32.786Z        info    clickhousetracesexporter/clickhouse_factory.go:116      Running migrations from path:   {"kind": "exporter", "data_type": "traces", "name": "clickhousetraces", "test": "/migrations"}
2023-03-17T10:58:41.160Z        info    clickhousetracesexporter/clickhouse_factory.go:128      Clickhouse Migrate finished     {"kind": "exporter", "data_type": "traces", "name": "clickhousetraces"}
Error: cannot build pipelines: failed to create "clickhousetraces" exporter, in pipeline "traces": code: 62, message: Syntax error: failed at position 2290 (')') (line 43, col 3): ) ENGINE MergeTree()
                PARTITION BY toDate(timestamp)
                ORDER BY (durationNano, timestamp)
                TTL toDateTime(timestamp) + INTERVAL 604800 SECOND DELETE
                SETTING. Expected one of: table property (column, index, constraint) declaration, INDEX, CONSTRAINT, PROJECTION, PRIMARY KEY, column declaration, identifier
2023/03/17 10:58:41 application run finished with error: cannot build pipelines: failed to create "clickhousetraces" exporter, in pipeline "traces": code: 62, message: Syntax error: failed at position 2290 (')') (line 43, col 3): ) ENGINE MergeTree()
                PARTITION BY toDate(timestamp)
                ORDER BY (durationNano, timestamp)
                TTL toDateTime(timestamp) + INTERVAL 604800 SECOND DELETE
                SETTING. Expected one of: table property (column, index, constraint) declaration, INDEX, CONSTRAINT, PROJECTION, PRIMARY KEY, column declaration, identifier
need help to understand this at the earliest please

<img width="650" alt="image" src="https://user-images.githubusercontent.com/79560674/225901715-4a189a93-cda6-492a-aedd-353d31f1adfb.png">

**Comment by srikanthccv** [comment]
Answered on Slack, Please make sure to use the compatible version of ClickHouse (`22.8.8` vs your `22.3`) with the SigNoz release [charts]( https://github.com/SigNoz/charts/blob/7bf7768df013dd5968c0b80de06ca3c3ab651f70/charts/signoz/values.yaml#L100-L111).
