### ISSUE TITLE
Create sample app in django framework showing example of how to instrument with SigNoz

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#247]
We should create a sample app in django framework and show developers can instrument them and visualise on SigNoz UI. Similar to what we have done for Flask app here - https://github.com/SigNoz/sample-flask-app

This should ideally be a new repo in this org in my opinion

**Comment by govindgoel** [comment]
@pranay01 Can I take this up and start working on it.

Thanks
Govind

**Comment by pranay01** [comment]
Sure @govindgoel Assigned to you

**Comment by pranay01** [comment]
@govindgoel Any updates on this issue?

**Comment by bdronneau** [comment]
Hi,
Just passing here because I started to instrument django app. This issue is done your work in https://github.com/SigNoz/sample-django

**Comment by pranay01** [comment]
thanks @bdronneau for pointing this out. Closing the issue
