### ISSUE TITLE
Create sample app in one of the PHP frameworks showing example of how to instrument with SigNoz

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#248]
We should create a sample app in one of the PHP frameworks, e.g. Laravel and show developers can instrument them and visualise on SigNoz UI. Similar to what we have done for Flask app here - https://github.com/SigNoz/sample-flask-app

This should ideally be a new repo in this org in my opinion

**Comment by RamyAllam** [comment]
Yes please, That would be awesome to have for Laravel and WordPress.

**Comment by pranay01** [comment]
@RamyAllam This is already updated  - https://github.com/SigNoz/sample-php-app. Here is the related docs - https://signoz.io/docs/instrumentation/php/

Was this not helpful? Feel free to reopen or open a new issue as needed.
