### ISSUE TITLE
Signoz logs CONTAINS keyword not working

### ISSUE THREAD

**Issue by abhinavramana** [SigNoz/signoz#2493]
## Bug description
https://signoz.wombo.net/logs?q=otelServiceName%20CONTAINS%20%27paint%27 doesn't work : **otelServiceName CONTAINS 'paint'**

https://signoz.wombo.net/logs?q=otelServiceName%20IN%20(%27paint-service-backend-prod%27) works : **otelServiceName IN ('paint-service-backend-prod')**
## Expected behavior

Both should work

**Comment by srikanthccv** [comment]
This is a known bug @nityanandagohain is looking into it — duplicate of #2428.
