### ISSUE TITLE
Tabs on metrics page not evenly spaced out for Macbook Air 13-inch

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#250]
## Bug description

There seem to be more space between 'Application Metrics' and 'External Calls' compared to the space between 'External Calls' and 'Database Calls' on Macbook Air 13 inch model.

![Screenshot 2021-08-03 at 10 00 55 AM](https://user-images.githubusercontent.com/83692067/127958007-38463ccb-534c-4a65-8f2e-5b854499f07e.png)

## Expected behavior
The tabs should be evenly spaced out.

**Comment by ankit01-oss** [comment]
This appears under 'Metrics' side-menu selection.

**Comment by pranay01** [comment]
No longer facing this issue with v0.6.0
