### ISSUE TITLE
Variables with multiple values are merged into one string

### ISSUE THREAD

**Issue by Bergiu** [SigNoz/signoz#2526]
## Bug description

Variables with multiple values are injected incorrectly into the clickhouse query builder. The value that is injected isn't the correct array with the selected values. It's like this: `['A,B,C','D']` instead of `['A','B','C','D']`. The values A, B and C are merged into one string somehow.

It looks like this:
![image](https://user-images.githubusercontent.com/13796963/228868624-d72750a6-45d3-4e94-8e84-20ba348bae81.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/13796963/228868796-d0448c03-8b89-4e51-bf68-23bdba5ff001.png)
(You can see the workaround I'm using in the query field)

## How to reproduce

1. Create a variable in a dashboard of type custom and call it example
2. Add some values separated by comma (for example A, B, C, D)
3. Enable multiple values to be checked
4. Save
5. Select more than 2 of them (for example A, B, C)
6. Add a panel of type value and add this clickhouse query: `select "{{.example}}"` (it's incorrect, but it shows the value that is injected)

![image](https://user-images.githubusercontent.com/13796963/228871807-92e13d1b-e74a-4a4b-b4fb-e9195e357349.png)

The image shows that multiple values are injected incorrectly.

## Version information 
* **Signoz version**: v0.17.0
* **Browser version**: Firefox 111.0.1
* **Your OS and version**: Ubuntu 22.04.2 LTS
* **Your CPU Architecture**(ARM/Intel): Intel

## Additional context

I'm working with the dashboards in signoz and want to add a panel that shows our warnings grouped by the service. Also I want to select which services should be included. For example to only show 3 of them (to compare them). This should work with variables with multiple values. What I expect is that I can select the services in the drop down list of the variable and then the selected services are included into the array of the variable.

**Comment by Bergiu** [comment]
Also I think it's a frontend issue. When selecting another variable, the side sends a PUT request to the server. This request contains the following:
![image](https://user-images.githubusercontent.com/13796963/228890396-c1df3143-3a64-49d0-8c5f-d061ff8f15e7.png)

Maybe that helps to fix this bug.

**Comment by Bergiu** [comment]
It seems that the error is produced in https://github.com/SigNoz/signoz/blob/develop/frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx#L146.

**Comment by srikanthccv** [comment]
This appears to be correct. Feel free to send a PR.
