### ISSUE TITLE
(alerts): query result plot y-axis and threshold should support unit configuration 

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#2548]
There can be many scenarios where the absolute value of the query can be big. For instance, the memory usage is measured in `bytes`, and if the current memory usage is in a few gigs, the charts will start to show numbers in million or billion. This will make it difficult for users to make sense of. 

Example:

<img width="850" alt="Screenshot 2023-04-04 at 4 56 00 PM" src="https://user-images.githubusercontent.com/22846633/229777628-5afa7f50-ec51-4781-830c-56b08669108f.png">

The user should be able to configure the unit, which should be honoured for the threshold input value.

**Comment by palashgdev** [comment]
if units is added in the composite query we need to handle in all the places not just alerts

**Comment by srikanthccv** [comment]
@pranay01 / @ankitnayan frontend implementation detail that should be shared; Since the unit selection dropdown is not part of the query builder container/component, Palash mentioned it needs to be added separately in the explorer, alerts and dashboards based on the Figma design placement and not a one-time effort, unlike other sub-components as the context handling is different in each page. Another concern was if any other things in the near future would come up outside the builder component.
