### ISSUE TITLE
Easy select of timeline in logs like we have in Services dashboard

### ISSUE THREAD

**Issue by pruthvi-itribe** [SigNoz/signoz#2555]
## Is your feature request related to a problem?

*Please describe.*

It would be great if we have select an area in the timeline above to zoom into the logs and dig deeper faster

## Describe the solution you'd like
Have shared in this loom video https://www.loom.com/share/7bb254bc5f46431494e714feef97cab4

## Describe alternatives you've considered
This is there in datadog which helps to navitage to errors or any spikes of logs etc

**Comment by vikrantgupta25** [comment]
we have added similar support in the new logs explorer page where you can scroll through the time line and look for the related logs, do let us know if you have any concerns with the same.

**Comment by vikrantgupta25** [comment]
please re-open the issue if you have any other concerns with the same, thanks!
