### ISSUE TITLE
Signoz UI bug in choosing custom timeframe

### ISSUE THREAD

**Issue by pruthvi-itribe** [SigNoz/signoz#2557]
## Bug description

When choosing custom timeframe value sometimes it does not work, attached a video

## Expected behavior

Works as usual

## How to reproduce

1. Choose a custom timeframe and select timeA to timeB and filter logs
2. Next time change the custom time and this happens as per video
https://www.loom.com/share/f1eb87309cbc4216b3fec63125ba1530

## Version information 
* **Signoz version**: v0.17.0
* **Browser version**: Chrome Version 111.0.5563.146 (Official Build) (arm64)
* **Your OS and version**: Mac OS Ventura 13.2.1 (22D68)
* **Your CPU Architecture**(ARM/Intel):  ARM

**Comment by nityanandagohain** [comment]
Thanks for reporting the bug, it seems an edge case @palashgdev .

So after changing the value if you click on `ok` the value is selected then it works, otherwise it is getting overridden when you press the enter.

**Comment by pruthvi-itribe** [comment]
Sometimes it does not work also when clicking okay.
