### ISSUE TITLE
Enhancement to select single line graph in dashboards

### ISSUE THREAD

**Issue by pruthvi-itribe** [SigNoz/signoz#2572]
## Is your feature request related to a problem?

In signoz dashboards when we have many line graphs in one dashboard, is there a way to select only one graph and unselect all other graphs. Currently we have to manually click each item to disable in the dashboard

## Describe the solution you'd like
on single click we can turn off the current line graph
on double click we can select this and turn off all other graphs
Or else we can have a some switch to turn off all and then give user to select one by one, but drawback with this is, if he doesn't know which metric is that and its just a spike in the graph then it would be tedious

**Comment by srikanthccv** [comment]
This is currently supported. Click on the legend shown at the bottom of the chart to select the line and click on it again to reset to all lines.
