### ISSUE TITLE
logs QB: Enrich meta data in groupby

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#2573]
In the [groupBy function](https://github.com/SigNoz/signoz/blob/2c206e8bf4ed8ff22117a47b0937ad7956badcac/pkg/query-service/app/logs/v3/query_builder.go#L291) the key is not enriched by metadata.

**Comment by nityanandagohain** [comment]
If you see the `getSelectLabels` functions, it enriches the metadata for groupBy in the select fields, so this is not required
