### ISSUE TITLE
incorrect breadcrumbs for settings

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#2577]
https://www.loom.com/share/57a400eac8e24c9fbba002d2f501470f

**Comment by ksorv** [comment]
@srikanthccv Would love to pick this up, Can this assigned to me?

**Comment by ksorv** [comment]
Thanks @srikanthccv

**Comment by ksorv** [comment]
@srikanthccv Need some input here:

<img width="1669" alt="Screenshot 2023-05-05 at 10 35 11 PM" src="https://user-images.githubusercontent.com/34188267/236521717-16a1a519-3912-475c-9994-6a59468f00f6.png">

In this crumb, the `edit` is also clickable, but there is nothing on edit route as expected.

What should be done here? I think we can:

- redirect back to channels
- make edit unclickable
- or we can remove the edit, from `settings/channels/edit/:id` -> `settings/channels/:id`
  - this one is also done in case of `dashboard/:id`

Please let me know what should i do here, Hoping to push it today only.

**Comment by ksorv** [comment]
@srikanthccv I've done it with the 3rd option, keeping in mind the dashboard behaviour.

Please let me know if I need to change something.

**Comment by srikanthccv** [comment]
3rd option seems fine to me.

**Comment by ksorv** [comment]
Okay @srikanthccv that is in the PR mentioned, Please check
