### ISSUE TITLE
alert configuration change doesn't immediately reflect

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#2578]
- Click on edit for an alert
- Edit the configuration and Save
- It shows rule is saved successfully
- Click on edit again
- The configuration shows old data
- Save again
- Pikachu, now the old old data shows up again

https://www.loom.com/share/96fe10f9373f466e8dee3d42830cb3eb

**Comment by ksorv** [comment]
@srikanthccv Please check #2671.

Have added comments in description, please check let me know if that fixes it.
