### ISSUE TITLE
Pagination in Signoz logs not working properly

### ISSUE THREAD

**Issue by pruthvi-itribe** [SigNoz/signoz#2583]
## Bug description
Pagination in logs is not working expected when filters are applied, the next and previous button gets disabled sometimes mostly when going to last page. And also logs per page doesn't work as intended

https://www.loom.com/share/13730c38930e4827bc909813dcad1376

*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior
Pagination to work as expected

## How to reproduce

1. Shared the video link
2.
3.

## Version information 
* **Signoz version**:
* **Browser version**:
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel):

**Comment by nityanandagohain** [comment]
Hi @pruthvi-itribe , when you change the start time of a time range, we keep the current context view of logs. If you want to start with the logs of that time range, you can click on the `go to latest` button.

**Comment by nityanandagohain** [comment]
Let  us know if your issue is resolved, will close this.

**Comment by nityanandagohain** [comment]
Closing this as no comments received.

The new version of explorer page will have infinite scroll and there will be no prev/next button
