### ISSUE TITLE
[Logs] Handle top level columns in AggregateOpeatorCount

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#2591]
Top-level columns of the logs model is not handled in AggregateOpeatorCount

**Comment by nityanandagohain** [comment]
Whether it is a top-level column or a materialized column, we will have to check if the value is present in the row of the column or not, the implementation can be finalised once we solve this issue https://github.com/SigNoz/signoz/issues/2594

**Comment by nityanandagohain** [comment]
Should we handle this issue in the same way https://github.com/SigNoz/signoz/pull/3183#issuecomment-1663738241 ?

@srikanthccv

**Comment by srikanthccv** [comment]
I didn't really understand the question

**Comment by nityanandagohain** [comment]
So I mean, count on top level columns should we ingore the default values like '0' or '' or should we consider them. If we consider them then the count of them will remain same as normal count

**Comment by nityanandagohain** [comment]
Closing this issue, as we don't want to add something from our side.

**Comment by srikanthccv** [comment]
@nityanandagohain question: Is this handled for aggregate operators such as min, avg, etc... on columns that are either materialised or not materialised? For example, MIN of attribute_int64_items where `items` is key from the log attributes. I have checked the tests, but I hope the key exists condition is added for them?

**Comment by nityanandagohain** [comment]
@srikanthccv  do you mean min(key), with/without any groupby. Then we should also add key_exists=true right ?

**Comment by nityanandagohain** [comment]
@srikanthccv  thanks for pointing it out, yes that is missing. Let me create a new PR for that.

**Comment by srikanthccv** [comment]
@makeavish you may want to check this as well https://github.com/SigNoz/signoz/issues/2591#issuecomment-1693120878.
