### ISSUE TITLE
[Logs] Handle top level columns in exists and notexists

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#2592]
As of now the struct is only 
```
	v3.FilterOperatorExists:          "has(%s_%s_key, '%s')",
	v3.FilterOperatorNotExists:       "not has(%s_%s_key, '%s')",
```

**Comment by nityanandagohain** [comment]
Whether it is a top-level column or a materialized column, we will have to check if the value is present in the row of the column or not, the implementation can be finalised once we solve this issue https://github.com/SigNoz/signoz/issues/2594

**Comment by nityanandagohain** [comment]
We need to run exists/nexists on top level fileds i.e trace_id, span_id, trace_flags, severity_number, severity_text.

Should we keep a map and for this top level fields apply the following filters for exists/nexists ?

```
{
trace_id : "trace_id != ''"
span_id : "span_id != ''"
trace_flags: "trace_flags != 0"
severity_number: "severity_number != 0"
severity_text: "severity_text != ''"
}
````

Since the above values are are added by the otel protocol is the above filters right way to go. @srikanthccv  @makeavish 

this is with reference to the changes made in https://github.com/SigNoz/signoz/pull/3183 where we added max default values

**Comment by nityanandagohain** [comment]
We did not add exists_column for top level keys as they are always set by the SDK.

So for these fields,
we can handle exists in this way
```
trace_id : "!=''"
span_id: "!=''"
severity_text: "!=''"
severity_number: ">0"
trace_flags: ">0"
```

we can handle nexists in this way
```
trace_id : "=''"
span_id: "=''"
severity_text: "=''"
severity_number: "=0"
trace_flags: "=0"
```

@srikanthccv  @ankitnayan  does this look good.

**Comment by srikanthccv** [comment]
This looks fine to me, and I don't think there is any other way of doing it.

**Comment by nityanandagohain** [comment]
Yeah, thanks 👍
