### ISSUE TITLE
Unable to filter logs by using fields contained in attributes_string resources_string

### ISSUE THREAD

**Issue by al-mcintosh** [SigNoz/signoz#2639]
## Bug description
*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

After upgrading signoz from `0.16.2` to `0.18.1` log filtering has stopped working. 

In the signoz UI, if I attempt to filter logs by `k8s_namespace_name IN ('lecreuset')`
it results in No logs lines found

I see the resulting query in the query service logs, which returns 0 results:

```
2023-04-24T19:48:02.058Z     [35mDEBUG [0m  clickhouseReader/reader.go:3612 SELECT toInt64(toUnixTimestamp(toStartOfInterval(toDateTime(timestamp/1000000000), INTERVAL 1 minute))*1000000000) as ts_start_interval, toFloat64(count()) as value FROM signoz_logs.distributed_logs WHERE (timestamp >= '1682362080929000000' AND timestamp <= '1682365680929000000' ) AND ( k8s_namespace_name IN ('lecreuset')  )  GROUP BY ts_start_interval ORDER BY ts_start_interval
2023-04-24T19:48:02.060Z     [34mINFO [0m   app/server.go:277   /api/v1/logs/fields timeTaken: 18.868263ms
2023-04-24T19:48:02.060Z     [35mDEBUG [0m  clickhouseReader/reader.go:3468 SELECT timestamp, id, trace_id, span_id, trace_flags, severity_text, severity_number, body,CAST((attributes_string_key, attributes_string_value), 'Map(String, String)') as  attributes_string,CAST((attributes_int64_key, attributes_int64_value), 'Map(String, Int64)') as  attributes_int64,CAST((attributes_float64_key, attributes_float64_value), 'Map(String, Float64)') as  attributes_float64,CAST((resources_string_key, resources_string_value), 'Map(String, String)') as resources_string  from signoz_logs.distributed_logs where ( timestamp >= '1682362080929000000' and timestamp <= '1682365680929000000' ) and ( k8s_namespace_name IN ('lecreuset') )  order by timestamp desc limit 50
2023-04-24T19:48:02.072Z     [34mINFO [0m   app/server.go:277   /api/v1/logs/aggregate  timeTaken: 31.461604ms
2023-04-24T19:48:02.076Z     [34mINFO [0m   app/server.go:277   /api/v1/logs    timeTaken: 35.186776ms
2023-04-24T19:48:09.901Z     [34mINFO [0m   app/server.go:277   /api/v1/version timeTaken: 19.7µs
2023-04-24T19:48:09.901Z     [34mINFO [0m   app/server.go:277   /api/v1/version timeTaken: 47.901µs

```

If i execute the above the query directly on clickhouse, 

```
SELECT
    timestamp,
    id,
    trace_id,
    span_id,
    trace_flags,
    severity_text,
    severity_number,
    body,
    CAST((attributes_string_key, attributes_string_value), 'Map(String, String)') AS attributes_string,
    CAST((attributes_int64_key, attributes_int64_value), 'Map(String, Int64)') AS attributes_int64,
    CAST((attributes_float64_key, attributes_float64_value), 'Map(String, Float64)') AS attributes_float64,
    CAST((resources_string_key, resources_string_value), 'Map(String, String)') AS resources_string
FROM signoz_logs.distributed_logs
WHERE k8s_namespace_name IN ('lecreuset')
ORDER BY timestamp DESC
LIMIT 1

Query id: 93249420-eb13-4a25-927d-dcd62c604543

Ok.

0 rows in set. Elapsed: 0.040 sec.

```

However, if I change:

`WHERE k8s_namespace_name IN ('lecreuset')`

to

`WHERE resources_string['k8s_namespace_name'] IN ('lecreuset')`

it works!

```
SELECT
    timestamp,
    id,
    trace_id,
    span_id,
    trace_flags,
    severity_text,
    severity_number,
    body,
    CAST((attributes_string_key, attributes_string_value), 'Map(String, String)') AS attributes_string,
    CAST((attributes_int64_key, attributes_int64_value), 'Map(String, Int64)') AS attributes_int64,
    CAST((attributes_float64_key, attributes_float64_value), 'Map(String, Float64)') AS attributes_float64,
    CAST((resources_string_key, resources_string_value), 'Map(String, String)') AS resources_string
FROM signoz_logs.distributed_logs
WHERE (resources_string['k8s_namespace_name']) IN ('lecreuset')
ORDER BY timestamp DESC
LIMIT 1

Query id: 78115e38-e4a7-4be9-a5da-9991c8138250

┌───────────timestamp─┬─id──────────────────────────┬─trace_id─┬─span_id─┬─trace_flags─┬─severity_text─┬─severity_number─┬─body───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─attributes_string──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─attributes_int64─┬─attributes_float64─┬─resources_string───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ 1682604232889414500 │ 2Oy0fdASzi9NbUTVEdGi6WIzaVg │          │         │           0 │               │               0 │ 846357a2-f455-4f14-bec4-0a03efb7e8bb|2023-04-27 14:03:52.8752|2023-04-27 14:03:52.8752 +00:00|INFO|Datatier|9|Process|Process: Scan successfully inserted in the database.                                                         │ {'log_iostream':'stdout','log_file_path':'\\var\\log\\pods\\lecreuset_bizapp-944db5486-txkk6_e024b5f7-f42e-4f8c-8511-4be9a2da6e22\\bizapp\\0.log','time':'2023-04-27T14:03:52.8894145Z','logtag':'F','env':'prod','region':'prod-east-us'} │ {}               │ {}                 │ {'k8s_container_name':'bizapp','k8s_namespace_name':'lecreuset','k8s_pod_name':'bizapp-944db5486-txkk6','k8s_container_restart_count':'0','k8s_pod_uid':'2ca41059-4459-4a5f-9419-802f5c5d3f6a','host_name':'agentpool-00000a','signoz_component':'otel-agent','k8s_cluster_name':'','k8s_pod_ip':'10.0.0.97','os_type':'windows','k8s_pod_start_time':'2023-04-12 14:28:25 +0000 GMT','k8s_node_name':'agentpool-00000a'} │
└─────────────────────┴─────────────────────────────┴──────────┴─────────┴─────────────┴───────────────┴─────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.131 sec. Processed 132.70 thousand rows, 176.46 MB (1.01 million rows/s., 1.35 GB/s.)

```

Another observation,  notice the attached screen cap. 

![image](https://user-images.githubusercontent.com/45045833/234892862-e2decc6e-223d-4488-b110-ff1d6d0c0d10.png)

The log query builder labels the k8s fields as **attributes**, but they are part of the resources string. So should the query actually be:

```
WHERE resources_string['k8s_namespace_name'] IN ('lecreuset')
AND  resources_string['k8s_container_name'] IN ('acme')

```

## How to reproduce

1. Visit /logs and attempt to query `k8s_namespace_name IN ('name-that-exists') `
2.
3.

## Version information 
* **Signoz version**:  0.18.1,  0.18.2, 0.18.3
* **Browser version**: Chrome Version 112.0.5615.138 (Official Build) (64-bit)
* **Your OS and version**: Azure Kubernetes version 1.24.10 / Ubuntu 18.04.6 LTS
* **Your CPU Architecture**(ARM/Intel):  Intel

**Comment by nityanandagohain** [comment]
Can you share the output of `show create table logs`

**Comment by al-mcintosh** [comment]
@nityanandagohain  

**show create table logs** failed with:

`Code: 390. DB::Exception: Received from localhost:9000. DB::Exception: Table `logs` doesn't exist. (CANNOT_GET_CREATE_TABLE_QUERY)`



Here is the output from  **SHOW CREATE TABLE signoz_logs.distributed_logs**


```

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE signoz_logs.distributed_logs
(
    `timestamp` UInt64 CODEC(DoubleDelta, LZ4),
    `observed_timestamp` UInt64 CODEC(DoubleDelta, LZ4),
    `id` String CODEC(ZSTD(1)),
    `trace_id` String CODEC(ZSTD(1)),
    `span_id` String CODEC(ZSTD(1)),
    `trace_flags` UInt32,
    `severity_text` LowCardinality(String) CODEC(ZSTD(1)),
    `severity_number` UInt8,
    `body` String CODEC(ZSTD(2)),
    `resources_string_key` Array(String) CODEC(ZSTD(1)),
    `resources_string_value` Array(String) CODEC(ZSTD(1)),
    `attributes_string_key` Array(String) CODEC(ZSTD(1)),
    `attributes_string_value` Array(String) CODEC(ZSTD(1)),
    `attributes_int64_key` Array(String) CODEC(ZSTD(1)),
    `attributes_int64_value` Array(Int64) CODEC(ZSTD(1)),
    `attributes_float64_key` Array(String) CODEC(ZSTD(1)),
    `attributes_float64_value` Array(Float64) CODEC(ZSTD(1)),
    `k8s_container_name` String MATERIALIZED -1,
    `k8s_pod_name` String MATERIALIZED -1,
    `k8s_namespace_name` String MATERIALIZED -1,
    `log` String MATERIALIZED -1,
    `martello_env` String MATERIALIZED -1,
    `host_name` String MATERIALIZED -1,
    `os_type` String MATERIALIZED -1,
    `exception_message` String MATERIALIZED -1,
    `exception_stacktrace` String MATERIALIZED -1,
    `dotnet_ilogger_category` String MATERIALIZED -1,
    `service_version` String MATERIALIZED -1,
    `service_name` String MATERIALIZED -1,
    `vdx_tenant_name` String MATERIALIZED -1
)
ENGINE = Distributed('cluster', 'signoz_logs', 'logs', cityHash64(id)) │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.003 sec.


```

**Comment by nityanandagohain** [comment]
Sorry I meant `signoz_logs.logs` table

**Comment by al-mcintosh** [comment]
Here you go! 


`



SHOW CREATE TABLE signoz_logs.logs

Query id: 984f87a4-5671-4c09-8e02-e3326d76043b

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE signoz_logs.logs
(
    `timestamp` UInt64 CODEC(DoubleDelta, LZ4),
    `observed_timestamp` UInt64 CODEC(DoubleDelta, LZ4),
    `id` String CODEC(ZSTD(1)),
    `trace_id` String CODEC(ZSTD(1)),
    `span_id` String CODEC(ZSTD(1)),
    `trace_flags` UInt32,
    `severity_text` LowCardinality(String) CODEC(ZSTD(1)),
    `severity_number` UInt8,
    `body` String CODEC(ZSTD(2)),
    `resources_string_key` Array(String) CODEC(ZSTD(1)),
    `resources_string_value` Array(String) CODEC(ZSTD(1)),
    `attributes_string_key` Array(String) CODEC(ZSTD(1)),
    `attributes_string_value` Array(String) CODEC(ZSTD(1)),
    `attributes_int64_key` Array(String) CODEC(ZSTD(1)),
    `attributes_int64_value` Array(Int64) CODEC(ZSTD(1)),
    `attributes_float64_key` Array(String) CODEC(ZSTD(1)),
    `attributes_float64_value` Array(Float64) CODEC(ZSTD(1)),
    `k8s_container_name` String MATERIALIZED resources_string_value[indexOf(resources_string_key, 'k8s_container_name')] CODEC(LZ4),
    `k8s_pod_name` String MATERIALIZED attributes_string_value[indexOf(attributes_string_key, 'k8s_pod_name')] CODEC(LZ4),
    `k8s_namespace_name` String MATERIALIZED attributes_string_value[indexOf(attributes_string_key, 'k8s_namespace_name')] CODEC(LZ4),
    `log` String MATERIALIZED attributes_string_value[indexOf(attributes_string_key, 'log')] CODEC(LZ4),
    `env` String MATERIALIZED attributes_string_value[indexOf(attributes_string_key, 'env')] CODEC(LZ4),
    `host_name` String MATERIALIZED resources_string_value[indexOf(resources_string_key, 'host_name')] CODEC(LZ4),
    `os_type` String MATERIALIZED resources_string_value[indexOf(resources_string_key, 'os_type')] CODEC(LZ4),
    `exception_message` String MATERIALIZED attributes_string_value[indexOf(attributes_string_key, 'exception_message')] CODEC(LZ4),
    `exception_stacktrace` String MATERIALIZED attributes_string_value[indexOf(attributes_string_key, 'exception_stacktrace')] CODEC(LZ4),
    `dotnet_ilogger_category` String MATERIALIZED attributes_string_value[indexOf(attributes_string_key, 'dotnet_ilogger_category')] CODEC(LZ4),
    `service_version` String MATERIALIZED resources_string_value[indexOf(resources_string_key, 'service_version')] CODEC(LZ4),
    `service_name` String MATERIALIZED resources_string_value[indexOf(resources_string_key, 'service_name')] CODEC(LZ4),
    `tenant_name` String MATERIALIZED resources_string_value[indexOf(resources_string_key, 'tenant_name')] CODEC(LZ4),
    INDEX body_idx body TYPE tokenbf_v1(10240, 3, 0) GRANULARITY 4,
    INDEX id_minmax id TYPE minmax GRANULARITY 1,
    INDEX log_idx log TYPE bloom_filter(0.01) GRANULARITY 64,
    INDEX k8s_container_name_idx k8s_container_name TYPE bloom_filter(0.01) GRANULARITY 64,
    INDEX os_type_idx os_type TYPE bloom_filter(0.01) GRANULARITY 64,
    INDEX k8s_namespace_name_idx k8s_namespace_name TYPE bloom_filter(0.01) GRANULARITY 64,
    INDEX service_name_idx service_name TYPE bloom_filter(0.01) GRANULARITY 64,
    INDEX env_idx env TYPE bloom_filter(0.01) GRANULARITY 64,
    INDEX tenant_name_idx tenant_name TYPE bloom_filter(0.01) GRANULARITY 64
)
ENGINE = MergeTree
PARTITION BY toDate(timestamp / 1000000000)
ORDER BY (timestamp, id)
TTL toDateTime(timestamp / 1000000000) + toIntervalSecond(86400)
SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.003 sec.`

**Comment by al-mcintosh** [comment]
Is it possible that **attributes** in the following should actually be **resources** ?


 `k8s_namespace_name` String MATERIALIZED **attributes**_string_value[indexOf(**attributes**_string_key, 'k8s_namespace_name')] CODEC(LZ4),

**Comment by al-mcintosh** [comment]
Correction: attribute parsing is working, I can successfully filter logs using:

`env in ('dev')`

**Comment by nityanandagohain** [comment]
Yes please follow this guide to resolve the issue with k8s attributes https://signoz.io/docs/userguide/logs_troubleshooting/#k8s-attribute-filtering-issue-in-logs

**Comment by al-mcintosh** [comment]
@nityanandagohain Thank you for the response. I will work through  https://signoz.io/docs/userguide/logs_troubleshooting/#k8s-attribute-filtering-issue-in-logs

At a glance, I see a typo that should be fixed:

`truncate table logs_atrribute_keys;`

Should be:

`truncate table logs_attribute_keys;`

Please allow me to apply the changes and test. I will update later today.

**Comment by al-mcintosh** [comment]
Following the [K8s Attribute Filtering Issue in Logs](https://signoz.io/docs/userguide/logs_troubleshooting/#k8s-attribute-filtering-issue-in-logs) resolved the issue.

**Comment by nityanandagohain** [comment]
Hey @al-mcintosh  thanks for pointing out the typo, would you like to create a PR for this 

> https://github.com/SigNoz/signoz/issues/2639#issuecomment-1527822824

**Comment by al-mcintosh** [comment]
A pull request? Or Issue?

**Comment by nityanandagohain** [comment]
A pull request is fine.

**Comment by al-mcintosh** [comment]
This file on main? It's not available on develop branch.

https://github.com/SigNoz/signoz.io/blob/main/docs/userguide/logs_troubleshooting.md
