### ISSUE TITLE
Trace Explorer [EPIC]

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#2653]
We would be adding one more page to add/visualise the trace in a more convenient way 

- [x] #2656
- [x] #2655
- [x] #2654

**Comment by srikanthccv** [comment]
@palashgdev, why another epic when there is already one with more fine-grained issues here https://github.com/SigNoz/signoz/issues/2315?

**Comment by palashgdev** [comment]
> #2315

this does not quantify the trace/metrics/logs explorer page

**Comment by palashgdev** [comment]
> @palashgdev, why another epic when there is already one with more fine-grained issues here #2315?



> @palashgdev, why another epic when there is already one with more fine-grained issues here #2315?

I missed the track of Epic thanks for pointing :-D
