### ISSUE TITLE
Invite members: Editing top input box updates buttom boxes 

### ISSUE THREAD

**Issue by shrbb** [SigNoz/signoz#2659]
## Bug description

Editing top input box updates buttom boxes 

## How to reproduce

https://user-images.githubusercontent.com/115218425/235845446-19134f6e-a3f9-40e8-9822-440992f8ea5e.mp4

1. Invite Members
2. Click "Add Another Member" multiple times
3. Enter text in any textbox except the last one

## Version information 
* **Signoz version**: UI 18.*
* **Browser version**: All
* **Your OS and version**: All
* **Your CPU Architecture**(ARM/Intel):

**Comment by palashgdev** [comment]
Closed via https://github.com/SigNoz/signoz/pull/2745
