### ISSUE TITLE
Unable to filter exceptions using resource attributes

### ISSUE THREAD

**Issue by al-mcintosh** [SigNoz/signoz#2675]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Currently, there is only one available field available signoz.collector.id nothing else.

![image](https://user-images.githubusercontent.com/45045833/236843482-7839d7ac-cad3-4e8f-a834-838faae3f410.png)

Here is an exception record that does indeed contain `k8s_namespace_name`  

`select * FROM signoz_traces.distributed_signoz_error_index_v2 limit 1

┌─────────────────────timestamp─┬─errorID──────────────────────────┬─groupID──────────────────────────┬─traceID──────────────────────────┬─spanID───────────┬─serviceName─┬─exceptionType────────────────────────────────────────┬─exceptionMessage───┬─exceptionStacktrace────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─exceptionEscaped─┬─resourceTagsMap────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ 2023-05-02 00:00:12.326284860 │ a78affb938ab4d85ba7364c0351fa656 │ f767290ce9682bc52f8b23267e352bc5 │ e7eca14967f924759b77d39fa062494a │ 63351f06a0bbc171 │ acme-server  │ com.biztech.acme.exceptions.NotFound │ Pin Not Recognized │ com.biztech.acme.central.api.exceptions.NotFound: Pin Not Recognized
│ false            │ {'os.description':'Linux 5.15.0-1035-azure','os.type':'linux','process.pid':'1','process.runtime.name':'OpenJDK Runtime Environment','service.name':'acme-server','telemetry.sdk.language':'java','k8s.deployment.name':'acme','k8s.pod.name':'acme-7c96459d5-mrg5f','k8s.pod.uid':'ebab11df-2a4a-4e27-af67-4af8432b5dc9','container.id':'6eea1b662df0e810d789a792a81677161663817e109c1a30a4dd878b86cf5e71','host.arch':'amd64','telemetry.sdk.version':'1.23.1','k8s.node.name':'agentpool-000013','telemetry.auto.version':'1.23.0','k8s.pod.ip':'10.240.0.41','k8s.pod.start_time':'2023-04-14 06:30:34 +0000 UTC','signoz.collector.id':'89eb1714-a562-4c0f-82f0-9fea2a673757','host.name':'acme-7c96459d5-mrg5f','telemetry.sdk.name':'opentelemetry','k8s.namespace.name':'lecreuset'} │
└───────────────────────────────┴──────────────────────────────────┴──────────────────────────────────┴──────────────────────────────────┴──────────────────┴─────────────┴──────────────────────────────────────────────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘`

## How to reproduce

1. Visit /exceptions
2. Click into the Search and filter field, 
Note: The Loading activity spinner appears for 1 - 2 seconds, then `signoz.collector.id`  (the only filter field option)  appears.

![image](https://user-images.githubusercontent.com/45045833/236843482-7839d7ac-cad3-4e8f-a834-838faae3f410.png)

## Version information 
* **Signoz version**: 0.18.3
* **Browser version**: Chrome 112.0.5615.138 (Official Build) (64-bit)
* **Your OS and version**:  Ubuntu 18.04.6 LTS
* **Your CPU Architecture**(ARM/Intel): linux (amd64)

**Comment by al-mcintosh** [comment]
Confirmed the same is shown on both exceptions and services pages. 

However, since upgrading to v.0.20.2  I now see ` signoz.collector.id`  and `service.namespace`  and nothing else: 

![image](https://github.com/SigNoz/signoz/assets/45045833/f31deb92-8723-48fe-a81b-6a841fa1ae01)

Is it possible that this also related to a service not appearing in the services page?  https://app.slack.com/client/T01HWUTP0LT/C01HWQ1R0BC/thread/C01HWQ1R0BC-1685735068.533419

**Comment by srikanthccv** [comment]
Add the additional dimensions to spans data and configure processor to capture them to show up in this dropdown https://github.com/SigNoz/signoz-otel-collector/tree/main/processor/signozspanmetricsprocessor

**Comment by al-mcintosh** [comment]
@srikanthccv  Is it possible to add these dimenstions to Opentelemetry Contrib otel-collectors?  I have many clusters with otel-collectors that send their data to signoz.

**Comment by srikanthccv** [comment]
If you want them to show up in the suggestions add in the signoz-collector-metrics in your signoz deployment.

**Comment by srikanthccv** [comment]
@al-mcintosh Please any customer dimensions in spanmetrics processor config. For example, in the docker setup, you need to add here https://github.com/SigNoz/signoz/blob/581bd07b35d45b90b9642455394c9d2df2dcc43a/deploy/docker/clickhouse-setup/otel-collector-config.yaml#L73-L81. Please let us know if it's not clear.
