### ISSUE TITLE
support for default timezone in SigNoz UI

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/signoz#2723]
## Is your feature request related to a problem?

Not at the moment. But it could potentially cause issues in the future.

There are a few threads related to timezone management:

1. Org/Tenant Level Timezone Management: The default timezone should be set based on the deployed location. An option to change the timezone should be available later in the organization settings.
2. User-Level Timezone Preference: Consider a scenario where the SigNoz cloud tenant is deployed in India for the organization ACME, and I am an editor for ACME accessing it from the UK. In this case, users might get confused without clear communication of this setup.

## Describe the solution you'd like

- Introduce default timezone for the SigNoz project irrespective of the timezone of the user
- even support for specific timezone per user basis
- display the timezone context to users in time range selectors.

cc @ankitnayan

**Comment by riteshsp2000** [comment]
Hey @prashant-shahi  @palashgdev I'd like to work on this issue.

**Comment by palashgdev** [comment]
sure please go ahead

**Comment by srikanthccv** [comment]
>Not at the moment. But it could potentially cause issues in the future.

Putting a default timezone will cause more issues than using the user's timezone. What potential problems does the browser time cause? Have you seen any application or project doing this?

**Comment by prashant-shahi** [comment]
Idea behind this was to have optional support for default timezone in SigNoz.

This would be desired and helpful in case of companies which are based on specific region, while the people involved might be distributed. Having a common time in SigNoz would be helpful to monitor specific downtime or performance issue by anyone in the team.

Default timezone feature in common in CMS, project management tools, database, and also in some of the web frameworks like Ruby on Rails and Django.

_Note: The changes would be only from frontend side while data format in database layer as well as query-service would remain intact._

**Comment by riteshsp2000** [comment]
So in order to get this feature up, we would be wanting something like a dropdown or equivalent input in the settings panel from where the user can select what timezone they want and depending upon the selection, it would reflect throughout the project.

**Comment by RakshitFK1703** [comment]
Hi @riteshsp2000 @pranay01 @palashgdev 
Are there any updates on this feature request? It is a typical use case for log analysis and a common requirement for many users. Would it be possible to prioritise this?

**Comment by nitin302** [comment]
Any further update on this please?

**Comment by xahhy** [comment]
We also encounter this timezone issue in our production environment. Our logs also log the current timestamp in UTC timezone but when search it on SigNoz UI it used our local timezone which brings inconsistency and unnecessary extra effort for us to use it. It's better to have a dropdown in the log search UI to let us select whether we want to search based on local timezone or UTC like how AWS generally did.

**Comment by prashant-shahi** [comment]
@sharpshooter90 Have updated PR description to include the shared points.

**Comment by GeekBoySupreme** [comment]
PS - All the point mentioned above had already been designed for earlier. 

The timepicker had an iteration where we show them their active timezone. Find the Figma [here](https://www.figma.com/design/egMidgk6VJDXTumxcCYUl1/Periscope---Primitives?node-id=1418-140&t=RAd6oefZDpcxTz16-1)
![image](https://github.com/user-attachments/assets/6e8655c9-c830-4811-a815-8262fa9a53c5)

The user setting up the workspace gets an option to set a workspace timezone (which is default selected to the timezone of where the tenant is deployed). Find the Figma [here](https://www.figma.com/design/TDCBKgMAatMR669uxdLPGk/Onboarding-Epic?node-id=74-26369&t=D9CMRTKljhecpdva-1)
![image](https://github.com/user-attachments/assets/be37b012-70d2-4073-a855-668420266d71)

Timezone mention in workspace settings. Find the Figma [here](https://www.figma.com/design/QPOedFb96RtjeWlfWk3K9k/Settings-Revamp?node-id=2010-1244&t=07x1LT2yx4QrdL0Z-1)
<img width="964" alt="image" src="https://github.com/user-attachments/assets/bc1bdcaa-a671-4f46-963d-3bf2ea029a1f">

We should ideally not need to worry about user timezone, and let the browser handled that based on the computer's timezone. Hence adding a toggle like this should be enough - [Figma](https://www.figma.com/design/QPOedFb96RtjeWlfWk3K9k/Settings-Revamp?node-id=2037-1705&t=07x1LT2yx4QrdL0Z-1)
![image](https://github.com/user-attachments/assets/62347973-7a40-44e7-9d52-dc2d024a5fb9)

**Comment by ankitnayan** [comment]
https://github.com/SigNoz/engineering-pod/issues/1962

**Comment by ankitnayan** [comment]
what if SigNoz's tenant is in `us-east-1`, the customer's machine is in `us-west-1` and the user is in `eu-central-1`

**Comment by micahnz** [comment]
I'd like to see global frontend setting and user level setting, bonus would be switching timezone from a dashboard.

My use case, servers are always UTC and logs are UTC, however we have people viewing dashboards from around the world and who are travelling.

We need to view the dashboards and logs based on different timezones depending on what we are doing, eg. If I am debugging sometime relative to my use I need it to be whatever timezone I am in however I don't always change my computer timezone when I travel because I use multiple clocks amd timezones. I need to be able to change to the timezone I am in quickly and easily without changing my system time.

I also need to view logs and metrics based on the key timezone for a project when reporting to a client, so I want to screenshot a graph but I want it showing EST for the client, I also want to compare the graphs to EST because it gives me insight into the usage in that timezones hours.

I also want to switch to and from UTC when I am comparing events and logs from other places on the server which are not in signoz, in this case its much easier if I switch back to UTC so I don't get lost or confused.

These are my core uses cases for timezone switching.

**Comment by ankitnayan** [comment]
@ahmadshaheer please note these down in the planning for timezone support

**Comment by ahmadshaheer** [comment]
> [@ahmadshaheer](https://github.com/ahmadshaheer) please note these down in the planning for timezone support


@ankitnayan, the solution proposed in the PRD can support @micahnz's use cases.

**Comment by ahmadshaheer** [comment]
EPIC Link: https://github.com/SigNoz/signoz/issues/2723

**Comment by 0cjs** [comment]
> EPIC: [#2723](https://github.com/SigNoz/signoz/issues/2723)

@ahmadshaheer That's this issue. I presume you were trying to point to a PR that implements the timezone support? It would also be handy if you'd give a brief explanation of where to find this and, ideally, an estimated release version so I can tell if the apparent lack of timezone support in the SigNoz I'm using is some sort of problem or if it's just too old.
