### ISSUE TITLE
[Logs] Parsing stacktrace using filelog recevier.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#2729]
Right now stacktrace are treated as individual log lines and the only way to fix it is using multiline config in filelog receiver.

How can we better solve this problem ?

**Comment by srikanthccv** [comment]
Related https://github.com/SigNoz/signoz/issues/2837

**Comment by nityanandagohain** [comment]
Since there are only two solutions to this
* Use OTEL SDK whereever possible
* Writte pattern for multiline when using the filelog receiver ( this will be custom based on the log pattern)

Closing this.

**Comment by daya** [comment]
> line_start_pattern

How can this be achieved for a Ruby / RubyOnRails application

**Comment by srikanthccv** [comment]
That part of the comment refers to filelogreceiver https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver#multiline-configuration which is independent of language/framework
