### ISSUE TITLE
Configure Cypress with Github Actions

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#274]
## Is your feature request related to a problem?

*Please describe.*

## Describe the solution you'd like
There is a CI solution for the Cypress in [Github Actions](https://docs.cypress.io/guides/continuous-integration/github-actions?utm_source=Test%20Runner&utm_medium=CI%20Prompt%201&utm_campaign=GitHub&utm_content=Automatic#Cypress-GitHub-Action)

**Comment by aggmoulik** [comment]
Hey @palash-signoz Are you working on the issue as I am looking for contributing in the project so it looks like a good issue to me.

**Comment by palash-signoz** [comment]
Hi @aggmoulik 
I am not working on this issue. Please go ahead

**Comment by aggmoulik** [comment]
Hey, @palash-signoz I was looking into the issue but which browsers are we targetting.

**Comment by palashgdev** [comment]
Closing for stale reference
