### ISSUE TITLE
Integrate Logs Query builder

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#2747]
Integrate Logs query builder to explorer page

![Image](https://user-images.githubusercontent.com/88981777/240019051-e73c6dbd-47d4-4f5e-9d4d-1020c881a852.png)

**Comment by palashgdev** [comment]
@srikanthccv can you please share the behaviour of logs where clause free text search

**Comment by srikanthccv** [comment]
Will confirm the functionality with team once and update.
