### ISSUE TITLE
add parsed logs and `trace_id` to logs in the demo app

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#2759]
For a better demo, we need
- parsed logs from application to show filtering use cases
- moving from `trace_id` in logs to trace detail and from trace detail to logs

**Comment by nityanandagohain** [comment]
Have a python repo that ingests logs data https://github.com/nityanandagohain/OTLP_Python_logs.

Will add support for ingesting trace data as well so that correlation can also be tested
