### ISSUE TITLE
Logs setting/configuration page

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#2769]
The interesting and selected fields from the left sidebar and several other options are to be moved to the settings page.

**Comment by MatheusBeniniF** [comment]
Hey @srikanthccv, I would love to take on this task.
What is expected for the PR to be accepted?

**Comment by srikanthccv** [comment]
This is not an up-for-grabs issue. It's yet to be finalised what needs to be done. Please find the issues with good-first-issue or help-wanted labels if you want to contribute.

**Comment by srikanthccv** [comment]
superseded by #3063
