### ISSUE TITLE
Refresh Functionality is not working as expected

### ISSUE THREAD

**Issue by palash-signoz** [SigNoz/signoz#277]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  
in the development environment if we make any change. change is not reflected over the browser

## Expected behavior

change should be reflected immediately without manually refreshing the page

## How to reproduce
you can change any text

**Comment by Jacoberson** [comment]
I'd like to try fixing this.

**Comment by ankitnayan** [comment]
okay @Jacoberson, assigning this to you

**Comment by Jacoberson** [comment]
@palash-signoz I guess I'm having trouble understanding where this is happening. It seems to be refreshing for me without having to manually refresh.

**Comment by palash-signoz** [comment]
Hi @Jacoberson 
Please find the video below where I am changing the text in the sidebar

https://user-images.githubusercontent.com/88981777/130705944-c8b459f9-0d35-4c2e-8777-ae7804482b53.mov

Please feel free to add more context

**Comment by palash-signoz** [comment]
although I can see the HMR hot update JSON log in the terminal 

<img width="1222" alt="Screenshot 2021-08-25 at 5 45 39 AM" src="https://user-images.githubusercontent.com/88981777/130706155-bcb8e245-cf41-46fd-970e-5e3789091518.png">

**Comment by Jacoberson** [comment]
@palash-signoz thank you for the information. I've made a PR.
