### ISSUE TITLE
Unable to create alarm with threshold 0

### ISSUE THREAD

**Issue by patrijua** [SigNoz/signoz#2783]
## Bug description

I would like to create alarm about pending pods. For this I want to create alarm which triggers when metric is above 0 or not equal to 0. However, saving of the alert rule fails when threshold is set to 0. There's an error "Please enter a threshold to proceed"

<img width="1084" alt="image" src="https://github.com/SigNoz/signoz/assets/57624530/d541ec0f-0111-45fb-89c8-08aa6ff26267">

<img width="1095" alt="image" src="https://github.com/SigNoz/signoz/assets/57624530/a9cc44bc-c746-4489-a01f-37a40b31728c">

<img width="349" alt="image" src="https://github.com/SigNoz/signoz/assets/57624530/e929a122-def2-41af-a366-e400b3197289">

## Expected behavior

I expect that I can use 0 as a threshold

## Version information 
* **Signoz version**: v0.18.3
* **Browser version**: Chrome 113.0.5672.126

**Comment by srikanthccv** [comment]
This is fixed in v0.19.x version. Please look a the release notes about the upgrade path https://github.com/SigNoz/signoz/releases/tag/v0.19.0

**Comment by srikanthccv** [comment]
Fixed in e21f23874da4b390836f0fc9bb9ad72e3479b185
