### ISSUE TITLE
Dashboard goes to empty state on clicking query builder tab

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#2789]
This occurs when there is an issue with panels created after importing dashboard. The edge cases should be handled better 

https://www.loom.com/share/ce6146547a1442629639a7b57be21827

**Comment by srikanthccv** [comment]
You are working with an old dashboard JSON that works with <= 0.18.3. They must be migrated before you import to make them work in 0.19.x

**Comment by prashant-shahi** [comment]
resolved by https://github.com/SigNoz/dashboards/pull/11

**Comment by prashant-shahi** [comment]
@srikanthccv  For any dashboard JSON that users might have from 0.18.x and prior, it would require additional work to make it work.

That could be made easier, if we add ability in migration script to skip specific dashboard/alert if we detect they are of new format.

That way, users can import old dashboard JSON files in `v0.19` and still be able to run the migration script over the newly added ones.

**Comment by srikanthccv** [comment]
I realized the script was already written to handle this here https://github.com/SigNoz/signoz-db-migrations/blob/c3934cb0a017e53713e031aeda76b3ba6ab285ab/migration-0.x/migrate/dashboards.go#L415-L425, but there was a typo; I fixed it at https://github.com/SigNoz/signoz-db-migrations/commit/5725bbe1c96d14ace3493158a4a12f794e7bb32f. You should be able to run mixed versions of JSON without exiting.

**Comment by srikanthccv** [comment]
I believe this is also completed.

**Comment by prashant-shahi** [comment]
@srikanthccv we should update the docker image and release binaries of the migration script.
Let me get that done.
