### ISSUE TITLE
Saving a dashboard is not intuitive

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#2798]
We should either enable autosave on dashboard or introduce a popup when user moves away from a unsaved state(unsaved dashboard or panel).

Loom video explaining the issue: https://www.loom.com/share/36a93febda004e41b8d6aea8eae6a113

**Comment by ankitnayan** [comment]
@makeavish the panel that you added is still there showing value `4533`. You do not need to `save layout` once you `save` the panel. I do not understand the issue mentioned except that layout changes needs to be saved using `save layout` button. The panels are saved IMO.
