### ISSUE TITLE
Configure  eslint and Prettier github actions

### ISSUE THREAD

**Issue by pal-sig** [SigNoz/signoz#280]
## Is your feature request related to a problem?

*Please describe.*

## Describe the solution you'd like
Configure Eslint and Prettier Github Actions for the frontend

**Comment by js-sapphire** [comment]
Hey @palash-signoz, Can I work on this?

**Comment by palash-signoz** [comment]
Hi @js-sapphire 
Please go ahead

**Comment by pal-sig** [comment]
marking closed against #329
