### ISSUE TITLE
BUG(FE): Flame graph is not working as expected

### ISSUE THREAD

**Issue by palash-signoz** [SigNoz/signoz#282]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

In Trace Section, the flame graph is not in sync with different trace

## Expected behavior
when we change trace this should also change the flame graph with the selected trace

https://user-images.githubusercontent.com/88981777/131209996-79e131f3-92c4-40ea-a55a-f0737ffb5314.mov

## Version information 
* **Signoz version**:
* **Browser version**:
* **Your OS and version**:

**Comment by pranay01** [comment]
fixed by https://github.com/SigNoz/signoz/pull/764 - Updated trace detail page design
