### ISSUE TITLE
[Logs] Live view with new explorer page.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#2822]
PRD on live view with new logs explorer page

- [ ] https://github.com/SigNoz/signoz/issues/3133

**Comment by makeavish** [comment]
@pranay01 Please share Figma design and requirements for this.

**Comment by pranay01** [comment]
UX for Live view

[https://www.figma.com/file/i2CsZFl27dhmER6gnx08wj/Integ.-QueryBuilder%2B3SigNalCorr[…]e=design&node-id=3614%3A18971&mode=design&t=BbcvUaeG1cnjrlNc-1](https://www.figma.com/file/i2CsZFl27dhmER6gnx08wj/Integ.-QueryBuilder%2B3SigNalCorrelation?type=design&node-id=3614%3A18971&mode=design&t=BbcvUaeG1cnjrlNc-1)
