### ISSUE TITLE
(exceptions): errors/exceptions from the logs are missing

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#2837]
At the time of writing, the `Exceptions` tab only shows the exceptions from the span events. As an end user, I would expect the errors/exceptions from the logs to also appear in the `Exceptions` tab listing and be able to search/filter. This might be easier to do if the logs come from the logs SDK since the attributes on the log record and span event are the same for an exception. We might have to use multi-line parsing for the logs collected via traditional means such as files.

**Comment by dpasirst** [comment]
I see this too. `Exceptions` are where the **most** severe problems are surfaced. Please consider prioritizing this.

**Comment by srikanthccv** [comment]
superseded by https://github.com/SigNoz/signoz/issues/5226
