### ISSUE TITLE
legend format should work for the value panel

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#2838]
Legend in the value panel is not working.

**Comment by srikanthccv** [comment]
I recalled this will still be needed. Consider a case there is only one series with a value either one or zero to indicate the uptime and you want to format the series using legend.

**Comment by makeavish** [comment]
> I recalled this will still be needed. Consider a case there is only one series with a value either one or zero to indicate the uptime and you want to format the series using legend.

Understood.
But currently legend doesn't work in value panel, right?

**Comment by srikanthccv** [comment]
Yes

**Comment by srikanthccv** [comment]
I don't recall the real world use-case behind this. Let people ask for it if there is a need.
