### ISSUE TITLE
Regex filter support in Query builder

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#2860]
For complex filtering of traces/logs/metrics attributes regex is required.

**Comment by srikanthccv** [comment]
This is supported for metrics in query service here https://github.com/SigNoz/signoz/blob/3f4cd130ed63f9838e11ede2e9a41526879b95ca/pkg/query-service/app/metrics/v3/query_builder.go#L84-L87

@nityanandagohain I think the logs query builder creates an invalid query with regex operators.
