### ISSUE TITLE
Support functions in formula of query builder

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#2878]
Example: time() function is not supported
<img width="865" alt="Screenshot 2023-06-09 at 10 45 37" src="https://github.com/SigNoz/signoz/assets/9512100/a9bee177-f440-40d4-8b2a-ae115dfe2a75">

**Comment by srikanthccv** [comment]
Closing this as completed since we have support for a time. Please create a new issue for additional functions support.
