### ISSUE TITLE
[Logs] dropdown chip should be removed after selected or it should be smaller

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#2879]
When we select a chip it is difficult to click on the apply button, remove the dropdown chip once it is selected or make it smaller so that apply button can be clicked easily 
https://www.loom.com/share/050f7fc34ca84126ad0e5b2add667b31

**Comment by Damans227** [comment]
Hi @nityanandagohain I have reproduced the[ problem locally](https://www.loom.com/share/2fc0a6e7d9764a9dbad21aa2224a3991). Would you be able to assign this issue to me?

**Comment by Damans227** [comment]
Thx @nityanandagohain If I can make the chip disappear once it is clicked, should I still reduce the chip size? I'm just curious as I think making the chip disappear after clicking once will solve our main problem, which is clicking the apply button with ease.

**Comment by nityanandagohain** [comment]
Don't have a strong opinion but I think reducing it will look better.
@pranay01  any suggestions ?
