### ISSUE TITLE
Test instrumenting ruby applications with OpenTelemetry and sending data to SigNoz

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#289]
We support opentelemetry, so it should be possible to instrument ruby applications and visualise data on SigNoz. But we don't have lots of expertise in Ruby in the core team, so we have not tested this.

https://github.com/open-telemetry/opentelemetry-ruby

It would be good first issue for folks expert in Ruby to test this and report their findings. If this works fine, we can add this to our docs - along with currently supported frameworks

**Comment by cloudsbird** [comment]
Hi Folkz, Now I'm Trying to use Signoz for Ruby on Rails app. If it runs good I will create a documentation on how to do it

**Comment by pranay01** [comment]
@cloudsbird Awesome! Let us know how it goes - and feel free to ask here if you need any help.

**Comment by cloudsbird** [comment]
> @cloudsbird Awesome! Let us know how it goes - and feel free to ask here if you need any help.

Yeay I success to Use Signoz with Ruby on Rails using open telemetry will build the how to soon

**Comment by pranay01** [comment]
Awesome! You can also create a sample Ruby on Rails app using opentelemetry & SigNoz and we can link in our docs and the tutorial

**Comment by cloudsbird** [comment]
https://medium.com/@leunardus.vederis714/monitor-your-ruby-on-rails-app-using-signoz-opentelemetry-b59578f3b252

**Comment by pranay01** [comment]
Hey @cloudsbird This is so cool! 👏

 Thanks for sharing how you have used SigNoz with RoR - something which we didn't have expertise in our team internally.
 
 Do you mind if add instruction from this and add to our docs? Would be very helpful for Ruby on Rails users who may want to try SigNoz

**Comment by cloudsbird** [comment]
> Hey @cloudsbird This is so cool! 👏
> 
> Thanks for sharing how you have used SigNoz with RoR - something which we didn't have expertise in our team internally.
> 
> Do you mind if add instruction from this and add to our docs? Would be very helpful for Ruby on Rails users who may want to try SigNoz
> 
> Unfortunately, works docs are not open source yet - otherwise I would have invite you to contribute directly to the docs

Sure Just invite and I will Contribute

**Comment by pranay01** [comment]
@cloudsbird We have made the SigNoz docs repo public :) - https://github.com/SigNoz/signoz.io

So you can now just contribute directly by opening a PR
Here's the docs you can update based on what you have published in your blog

**Comment by cloudsbird** [comment]
> @cloudsbird We have made the SigNoz docs repo public :) - https://github.com/SigNoz/signoz.io
> 
> So you can now just contribute directly by opening a PR Here's the [docs](https://github.com/SigNoz/signoz.io/blob/main/docs/instrumentation/ruby-on-rails.md) you can update based on what you have published in your blog

Hi Okay, will do soon bro

**Comment by makeavish** [comment]
Blog is published on signoz.io: https://signoz.io/blog/opentelemetry-ruby/
