### ISSUE TITLE
Missing loader at multiple screens in SigNoz UI

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#2893]
After user actions there are multiple places where loader is missing, when API request time is slow then without a loader it feels the action failed.
Few examples: https://www.loom.com/share/5f3295e3392647a2a16e242c4b786e9e?sid=297c37ca-edf9-4162-aefb-87153eb3da32
There are multiple places where loader is missing, this issue is for all of those places.

**Comment by makeavish** [comment]
Related: https://github.com/SigNoz/signoz/issues/1257

**Comment by YounixM** [comment]
@makeavish : Can you please provide the list of screens where we are missing the loaders?

**Comment by YounixM** [comment]
@makeavish : Closing this issue. Feel free to reopen
