### ISSUE TITLE
Alert name and threshold missing

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#2900]
Loom videos: 

- While switching query types: https://www.loom.com/share/49ddf96350a140cba3eb82473e3e4bad?sid=33e23f63-3d49-4b86-b133-a32a667930f1
- After running query: https://www.loom.com/share/1fa553b9f947490e84152d90ed0c2ab8?sid=6f1a8774-b2eb-425e-88d7-56df304030f0

**Comment by makeavish** [comment]
This [issue](https://github.com/SigNoz/signoz/issues/2819) was not fixed in the PR: https://github.com/SigNoz/signoz/pull/2888

**Comment by palashgdev** [comment]
solved via https://github.com/SigNoz/signoz/pull/2905
