### ISSUE TITLE
helm installation Permission denied: Cannot parse definition from metadata file query_views_log.sql  errno: 13, strerror: Permission denied

### ISSUE THREAD

**Issue by Pho3niX90** [SigNoz/signoz#2926]
## Bug description

*Please describe.*  
The statefulset (chi-signoz-clickhouse-cluster) cannot startup

## Version information 
* **Signoz version**: Helm - signoz-0.16.2, tag: 0.20.2
- frontend version: '0.20.2' (docker.io/coolboi567/frontend:0.5.4-unprivileged)
- - see https://github.com/SigNoz/signoz/issues/617
- query-service version: '0.20.2'
- alertmanager version: '0.23.0-0.2'
- otel-collector version: '0.76.1'

## Additional context

`2023.06.17 19:28:00.237066 [ 8 ] {} <Information> Application: Setting max_server_memory_usage was set to 56.47 GiB (62.74 GiB available * 0.90 max_server_memory_usage_to_ram_ratio)
2023.06.17 19:28:00.242411 [ 8 ] {} <Information> CertificateReloader: One of paths is empty. Cannot apply new configuration for certificates. Fill all paths and try again.
2023.06.17 19:28:00.287890 [ 8 ] {} <Information> Application: Uncompressed cache policy name 
2023.06.17 19:28:00.288559 [ 8 ] {} <Information> Context: Initialized background executor for merges and mutations with num_threads=16, num_tasks=32
2023.06.17 19:28:00.288791 [ 8 ] {} <Information> Context: Initialized background executor for move operations with num_threads=8, num_tasks=8
2023.06.17 19:28:00.289144 [ 8 ] {} <Information> Context: Initialized background executor for fetches with num_threads=8, num_tasks=8
2023.06.17 19:28:00.289764 [ 8 ] {} <Information> Context: Initialized background executor for common operations (e.g. clearing old parts) with num_threads=8, num_tasks=8
2023.06.17 19:28:00.290014 [ 8 ] {} <Information> Application: Loading user defined objects from /var/lib/clickhouse/
2023.06.17 19:28:00.290153 [ 8 ] {} <Information> Application: Loading metadata from /var/lib/clickhouse/
2023.06.17 19:28:00.316567 [ 8 ] {} <Error> Application: Caught exception while loading metadata: Code: 76. DB::ErrnoException: Cannot open file /var/lib/clickhouse/store/a40/a4054a23-3e05-4771-b52b-0b5a292958bb/query_views_log.sql, errno: 13, strerror: Permission denied: Cannot parse definition from metadata file /var/lib/clickhouse/store/a40/a4054a23-3e05-4771-b52b-0b5a292958bb/query_views_log.sql. (CANNOT_OPEN_FILE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3ef75a in /usr/bin/clickhouse
1. DB::throwFromErrnoWithPath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) @ 0xa3f07a0 in /usr/bin/clickhouse
2. DB::DatabaseOnDisk::parseQueryFromMetadata(Poco::Logger*, std::__1::shared_ptr<DB::Context const>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool) @ 0x14241c9b in /usr/bin/clickhouse
3. ? @ 0x142ef6cd in /usr/bin/clickhouse
4. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xa4b38a6 in /usr/bin/clickhouse
5. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0xa4b51f7 in /usr/bin/clickhouse
6. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa4b11c8 in /usr/bin/clickhouse
7. ? @ 0xa4b43dd in /usr/bin/clickhouse
8. ? @ 0x7f14746ee609 in ?
9. clone @ 0x7f1474613133 in ?
 (version 22.8.8.3 (official build))
2023.06.17 19:28:00.316677 [ 8 ] {} <Information> Application: Shutting down storages.
2023.06.17 19:28:01.292987 [ 8 ] {} <Error> Application: DB::ErrnoException: Cannot open file **/var/lib/clickhouse/store/a40/a4054a23-3e05-4771-b52b-0b5a292958bb/query_views_log.sql, errno: 13, strerror: Permission denied: Cannot parse definition from metadata file /var/lib/clickhouse/store/a40/a4054a23-3e05-4771-b52b-0b5a292958bb/query_views_log.sql**
2023.06.17 19:28:01.293023 [ 8 ] {} <Information> Application: shutting down
2023.06.17 19:28:01.293125 [ 9 ] {} <Information> BaseDaemon: Stop SignalListener thread
2023.06.17 19:28:01.316328 [ 1 ] {} <Information> Application: Child process exited normally with code 70.`

**Comment by prashant-shahi** [comment]
@Pho3niX90 That unprivileged frontend image was supposed to be just for testing temporarily.
Do try out the new image mentioned in the referenced issue below and let us know if the above issue is resolved.
We can make the unprivileged frontend image public in `signoz/frontend` docker repository.

Ref: https://github.com/SigNoz/signoz/issues/617#issuecomment-1595862581

**Comment by srikanthccv** [comment]
>2023.06.17 19:28:01.292987 [ 8 ] {} Application: DB::ErrnoException: Cannot open file /var/lib/clickhouse/store/a40/a4054a23-3e05-4771-b52b-0b5a292958bb/query_views_log.sql, errno: 13, strerror: Permission denied: Cannot parse definition from metadata file /var/lib/clickhouse/store/a40/a4054a23-3e05-4771-b52b-0b5a292958bb/query_views_log.sql


Make sure the user groups and permissions are set right.

**Comment by Pho3niX90** [comment]
> @Pho3niX90 That unprivileged frontend image was supposed to be just for testing temporarily. Do try out the new image mentioned in the referenced issue below and let us know if the above issue is resolved. We can make the unprivileged frontend image public in `signoz/frontend` docker repository.
> 
> Ref: [#617 (comment)](https://github.com/SigNoz/signoz/issues/617#issuecomment-1595862581)

Thanks, eventually, I ended up reinstalling it with Lens IDE, and everything started working. Unsure what difference the IDE made vs installing via command line.
