### ISSUE TITLE
How to remove own logs in SigNoz

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#2927]
** From Slack Community **
Hi guys, I just started using signoz. Was wondering how I can remove signoz own logs. I've managed to remove the sample app metrics and traces by following this guide - <https://signoz.io/docs/operate/docker-standalone/#remove-the-sample-application-from-signoz-dashboardbut> I see the signoz logs are still coming however. How can I remove? My logs interface is quite noisy as a result of the signoz own logs and I'd like to remove so I'm left with only logs for the application being monitored.  See screenshot of the signoz logs. Also below. Would appreciate if someone can guide me. Thanks in advance :pray:
&gt; 2023-06-17T10:48:05+03:00 | 102.220.12.50 - - [17/Jun/2023:07:48:05 +0000] "GET /api/v1/logs/tail?timestampStart=1686986894073000000 HTTP/1.1" 200 73664 "<http://signoz.domain.xyz:3301/logs?q=>" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
&gt; 
&gt; 2023-06-17T10:48:05+03:00 | 2023-06-17T07:48:05.163Z INFO app/server.go:280 /api/v1/logs/tail timeTaken: 4m50.969067478s
&gt; 
&gt; 2023-06-17T10:48:05+03:00 | 2023-06-17T07:48:05.163Z DEBUG app/http_handler.go:2261 done!
&gt; 
&gt; 2023-06-17T10:48:05+03:00 | 2023-06-17T07:48:05.161Z DEBUG clickhouseReader/reader.go:3541 closing go routine : 172.18.0.10:59372
&gt; 
&gt; 2023-06-17T10:48:04+03:00 | 2023.06.17 07:48:04.850539 [ 47 ] {2107a9a8-84e4-4791-b150-561fbbba4b5d} &lt;Information&gt; executeQuery: Read 798 rows, 6.23 KiB in 0.002790747 sec., 285944 rows/sec., 2.18 MiB/sec.
&gt; 
&gt; 2023-06-17T10:48:04+03:00 | 102.220.12.50 - - [17/Jun/2023:07:48:04 +0000] "GET /logs?q= HTTP/1.1" 200 791 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
&gt; 
&gt; 2023-06-17T10:48:04+03:00 | 2023-06-17T07:48:04.407Z DEBUG clickhouseReader/reader.go:3553 SELECT timestamp, id, trace_id, span_id, trace_flags, severity_text, severity_number, body,CAST((attributes_string_key, attributes_string_value), 'Map(String, String)') as attributes_string,CAST((attributes_int64_key, attributes_int64_value), 'Map(String, Int64)') as attributes_int64,CAST((attributes_float64_key, attributes_float64_value), 'Map(String, Float64)') as attributes_float64,CAST((resources_string_key, resources_string_value), 'Map(String, String)') as resources_string from signoz_logs.distributed_logs where timestamp &gt;='1686988064851955929' and id &gt; '2RIKkvmFr30zGjfEHHa8mJWn4HL' order by timestamp desc, id desc limit 100

[Slack Message](https://signoz-community.slack.com/archives/C01HWUTP4HH/p1686988648230929?thread_ts=1686988648.230929&cid=C01HWUTP4HH)

**Comment by nityanandagohain** [comment]
Duplicate https://github.com/SigNoz/signoz/issues/2855
