### ISSUE TITLE
Drag in time series graph of explorer pages

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#2933]
Drag is missing in the new trace and log explorer pages

**Comment by pranay01** [comment]
@makeavish Can you explain this issue in more detail. What do you mean by drag here?

**Comment by makeavish** [comment]
I meant drag on graph to select time period of time series graph
@pranay01

**Comment by pranay01** [comment]
Yeah, this would be a good feature to have as an enhancement

**Comment by ahmadshaheer** [comment]
Looked into this ticket, but it seems that the drag feature has already been added to the timeseries graph.

**Comment by makeavish** [comment]
Yes this is present in latest versions.
Closing it
