### ISSUE TITLE
feature request: Timerange selector from count chart in logs page

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/signoz#2935]
## Is your feature request related to a problem?

No.

## Describe the solution you'd like

In Logs page, upon selection of specific range using mouse selection in the count chart,
we should only list logs of that selected time range.

## Describe alternatives you've considered

NA

## Additional context

![image](https://github.com/SigNoz/signoz/assets/11138844/aee714c0-3292-4d98-8528-2e672ba89557)

**Comment by sachinmk27** [comment]
@palashgdev @pranay01 May I take this up ?

**Comment by Damans227** [comment]
@palashgdev hi, can you assign me this issue?

**Comment by ankitnayan** [comment]
@nityanandagohain this is fixed, right?

**Comment by nityanandagohain** [comment]
this is added
