### ISSUE TITLE
[Logs] Clear context in asc order

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#2942]
but, lets say in asc mode I am in nth page by clicking the prev/next button n number of times. Now If I try to click on the refresh button near the time button, it still renders the same page and there is not really an option for me to reset unless I manully refresh the browser page. But it should be fine for this use case.

https://github.com/SigNoz/signoz/pull/2895#pullrequestreview-1488031522

**Comment by srikanthccv** [comment]
Completed in https://github.com/SigNoz/signoz/pull/2895
