### ISSUE TITLE
Unable to see full name of attributes/tag in query builder

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#2967]
While adding any `group by` on attributes if attribute name is long then user can't full name, user needs to hover for 5-10s to see full name
<img width="343" alt="Screenshot 2023-06-23 at 16 33 05" src="https://github.com/SigNoz/signoz/assets/9512100/955d2727-d3c4-42a3-a82c-cf13a8c2f2c2">

**Comment by kaushikmacharla07** [comment]
We can do something like this
![Group 319](https://github.com/SigNoz/signoz/assets/139132628/6c674013-73ad-4c9e-85bd-a1d6789d5b72)

**Comment by pranay01** [comment]
@palashgdev is above suggestion by @kaushikmacharla07 possible?

**Comment by palashgdev** [comment]
@kaushikmacharla07 we are using Select with tags mode 

```
https://ant.design/~demos/components-select-demo-tags
```

also, there is a native tooltip to show the details

<img width="598" alt="Screenshot 2023-07-17 at 10 39 43 AM" src="https://github.com/SigNoz/signoz/assets/88981777/8bf8a187-b0cf-4ad9-9843-d114c354f292">

**Comment by kaushikmacharla07** [comment]
I'm fine with the option if we were able to implement it.

**Comment by palashgdev** [comment]
> I'm fine with the option if we were able to implement it.

can you share the antd docs for same?

**Comment by mustajab-ikram** [comment]
Any one working on this? Can I pick it? @palashgdev  @pranay01

**Comment by pranay01** [comment]
Yeah, I think @palashgdev is working on it

**Comment by palashgdev** [comment]
after the discussion with the product team ... we want to test with two approach 

1. if , it is feasible to integrate a tooltip over the options from antd
1. If we are going with the current implementation we need to check why the first option is taking too much time to render the native tooltip 

file reference: `src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx`

**Comment by grvv** [comment]
Hi,

@pranay01 @palashgdev 
Can i work on this issue?

**Comment by palashgdev** [comment]
> Hi,
> 
> @pranay01 @palashgdev 
> Can i work on this issue? 
> 

Yeah sure @grvv please go ahead

**Comment by grvv** [comment]
Hi @palashgdev,

I raised a [PR](https://github.com/SigNoz/signoz/pull/4071) for this.

The native tooltip in this case is a HTML title attribute which is generally slow and isn't easily stylable. So in my implementation I used ant design's tooltip component to show the tooltip.

<img width="670" alt="Screenshot 2023-11-27 at 2 44 03 AM" src="https://github.com/SigNoz/signoz/assets/26812698/59c093c5-b769-414b-8b92-1a7a3d4feef7">
