### ISSUE TITLE
Setting Data Retention Period for Clickhouse

### ISSUE THREAD

**Issue by yashrsharma44** [SigNoz/signoz#300]
## Is your feature request related to a problem?

* POST API to set retention period
* change CH table schema with updated TTL
* test schema migrations for sanity post TTL change

**Comment by yashrsharma44** [comment]
I can take this issue, as we discussed offline cc @ankitnayan

**Comment by pranay01** [comment]
@yashrsharma44 Assigning to you

**Comment by yashrsharma44** [comment]
Adding some more notes for reference - 
* TTL Setup for Clickhouse - https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#table_engine-mergetree-ttl
* Modifying the Table Schema through HTTP API - https://clickhouse.com/docs/en/interfaces/http/
