### ISSUE TITLE
to change admin detail & passward change

### ISSUE THREAD

**Issue by techsachin1** [SigNoz/signoz#3005]
recently install signoz and randomly i have put some details to login but.. now i need to edit admin details like password and mail id.. there is option shows for password change and edit admin but its not working.. please suggest how to do without reinstalling signoz

**Comment by pranay01** [comment]
Hi, if you have forgotten admin password - you should try the steps mentioned here to reset it - https://github.com/SigNoz/signoz/issues/1861#issue-1499692469

**Comment by techsachin1** [comment]
hi @pranay01 thnx for reply.. i want to remove one admin permenatntly.. i have another admin.. kindly share the detils plz

**Comment by srikanthccv** [comment]
The linked instructions are indeed for removing users permanently. 

To see all the users: `select * from users;` and delete a particular user: `delete from users where id=<replace_this_with_id>`
