### ISSUE TITLE
[Logs] Explorer page change default size to 200

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#3015]
Change default size of the logs page to 200.

**Comment by mustajab-ikram** [comment]
I noticed this issue (#3015) regarding changing the default size of the Logs Explorer page to 200 logs per page. I am currently seeing 200 logs per page in my local environment. Can you please confirm if this issue has already been addressed or if it is still open for contribution?

If it is not yet addressed, I would be happy to work on this and make the necessary changes. Kindly assign the issue to me @palashgdev

**Comment by nityanandagohain** [comment]
It's 100 which seems fine
