### ISSUE TITLE
FE: (alerts) Support y-axis formatting in graph and threshold

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#3016]
Currently alerts page doesn't support y-axis formatting similar to dashboard time-series panel. Also setting threshold for some values can be difficult without formatting.

Backend issue: https://github.com/SigNoz/signoz/issues/2548

**Comment by srikanthccv** [comment]
@pranay01, please also provide the design for this.

**Comment by pranay01** [comment]
Will discuss with @kaushikmacharla07 and he should be able to get back with designs

**Comment by pranay01** [comment]
https://signoz-team.slack.com/archives/C02B99JKTMY/p1689322808531239?thread_ts=1689272162.126179&cid=C02B99JKTMY

**Comment by palashgdev** [comment]
added comments https://www.figma.com/file/lE5BDDuulXuGnqvB5GRk1V?node-id=3108:40390&mode=design#499893223

**Comment by srikanthccv** [comment]
Summary of the discussion

--------------

This feature will add two additional things to the current UI

1. Y-axis Unit for the time series chart
2. Unit for the threshold value

Y-axis unit input will be used for formatting the aggregation result value provided by the backend. The rendered values on the axis do not always have the same output unit; to be more precise, take latency example --  it can range from a few milliseconds (20ms) to seconds or even minutes occasionally. 

With the addition of y-axis formatting, it is important to add the threshold unit. For instance, say a user sends disk size metric in `bytes`; when they select the y-axis unit, the graph will probably show values in GBs. Assume users want to set an alert when the size exceeds 10 Gbs. Without threshold unit support, they would have to type the 10,737,418,240, which is not user-friendly. We allow them to select the threshold unit. In the example case, they just need to enter 10 and select the threshold unit as `Gb`.

Implementation parts to take care of:

- The threshold unit should be enabled only when the y-axis selected is made. 
- When the user makes the y-axis selection, the threshold unit is changed to the highest unit shown to the user as default; however, the user can change it. This can be better described with an example. Assume the P99 aggregation on durationNano. Usually, there will be many calls with a few hundred milliseconds and some with a few seconds. The default choice in the threshold unit dropdown should be seconds. Another example with disk size; the y-axis may have Mbs (there could be some machines with little usage), Gbs in the same charts. The default selection will be changed to Gbs.


The list of units we support in alerts is limited to observability use cases. 


1. Data
2. Data rate
3. Time
4. Throughput
5. Misc
6. Bool

Please comment if you have questions or suggestions for doing things differently.

**Comment by palashgdev** [comment]
> Summary of the discussion
> 
> This feature will add two additional things to the current UI
> 
> 1. Y-axis Unit for the time series chart
> 2. Unit for the threshold value
> 
> Y-axis unit input will be used for formatting the aggregation result value provided by the backend. The rendered values on the axis do not always have the same output unit; to be more precise, take latency example -- it can range from a few milliseconds (20ms) to seconds or even minutes occasionally.
> 
> With the addition of y-axis formatting, it is important to add the threshold unit. For instance, say a user sends disk size metric in `bytes`; when they select the y-axis unit, the graph will probably show values in GBs. Assume users want to set an alert when the size exceeds 10 Gbs. Without threshold unit support, they would have to type the 10,737,418,240, which is not user-friendly. We allow them to select the threshold unit. In the example case, they just need to enter 10 and select the threshold unit as `Gb`.
> 
> Implementation parts to take care of:
> 
> * The threshold unit should be enabled only when the y-axis selected is made.
> * When the user makes the y-axis selection, the threshold unit is changed to the highest unit shown to the user as default; however, the user can change it. This can be better described with an example. Assume the P99 aggregation on durationNano. Usually, there will be many calls with a few hundred milliseconds and some with a few seconds. The default choice in the threshold unit dropdown should be seconds. Another example with disk size; the y-axis may have Mbs (there could be some machines with little usage), Gbs in the same charts. The default selection will be changed to Gbs.
> 
> The list of units we support in alerts is limited to observability use cases.
> 
> 1. Data
> 2. Data rate
> 3. Time
> 4. Throughput
> 5. Misc
> 6. Bool
> 
> Please comment if you have questions or suggestions for doing things differently.

in the client, we are showing this unit 

<img width="455" alt="Screenshot 2023-08-01 at 12 15 07 PM" src="https://github.com/SigNoz/signoz/assets/88981777/b02199eb-ad01-47d1-b9c1-e23891963f75">

how it is mapped from backend values 

```
> 1. Data
> 2. Data rate
> 3. Time
> 4. Throughput
> 5. Misc
> 6. Bool
```
