### ISSUE TITLE
FE: (dashboard) Support close the configuration popup by clicking outside 

### ISSUE THREAD

**Issue by dnazarenkoo** [SigNoz/signoz#3017]
Now, if users want to close the configuration popup, they must click on the X button, but the popup can also be closed by clicking outside, because this is the default behavior for popups.
<img width="1437" alt="Screenshot 2023-07-03 at 22 51 02" src="https://github.com/SigNoz/signoz/assets/134951516/4f5ef3ac-983f-45e5-ba17-4dd0a698508f">

**Comment by sachinmk27** [comment]
Hi @makeavish, may i take this up ?

**Comment by dnazarenkoo** [comment]
Hi @sachinmk27, I'll take that in scope with other issues
