### ISSUE TITLE
I see multiple delete actions in Dashboard page

### ISSUE THREAD

**Issue by Rajat-Dabade** [SigNoz/signoz#3018]
## Bug description

On the Dashboard page, there are multiple delete actions.

## Expected behavior
There is should only one delete for each dashboard

## How to reproduce

1. Navigate to Dashboard
2. See the list of Dashboard
3. See the Error, there are 2 columns that have delete action.

## Version information 
* **Signoz version**: v0.21.0-20-g

**Comment by prashant-shahi** [comment]
This issue does not exist in the last release but only in `develop` branch.

**Comment by makeavish** [comment]
This is solved in this PR: https://github.com/SigNoz/signoz/pull/3012
