### ISSUE TITLE
Preserve new columns added by users in trace explorer view

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#3045]
Selected columns should be stored in browser local storage

**Comment by makeavish** [comment]
@dnazarenkoo Here's PR of @yeshev for similar issue in logs: https://github.com/SigNoz/signoz/pull/3055
MIght be helpful for you as it's similar.

**Comment by dnazarenkoo** [comment]
@makeavish this is fixed in this issue [3055](https://github.com/SigNoz/signoz/pull/3055)
