### ISSUE TITLE
Inconsistencies between k8s metrics server `kubectl top nodes` and the `HostMetrics Dashboard (K8s)` metrics

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#3079]
Hello everyone

I followed the <https://signoz.io/docs/tutorial/kubernetes-infra-metrics/#steps-to-export-k8s-metrics-to-signoz|steps> to add k8s-metrics to signoz

but I see inconsistencies between k8s metrics server `kubectl top nodes` and the `HostMetrics Dashboard (K8s)` metrics

For example for one specific node
• `kubectl top nodes` reports 13%
• `CPU Usage` in `HostMetrics Dashboard (K8s)`  reports 20%
While looking at the promQL query, I found that CPU Usage is calculated using this formula
```1 - (avg by(k8s_node_name) (irate(system_cpu_time{k8s_cluster_name="{{.k8s_cluster_name}}",k8s_node_name="{{.k8s_node_name}}",state="idle"}[5m])))```
I also found that it’s CloudWatch CPU utilization metric and definition is similar to the one provided by k8s metrics server

Why does Signoz dashboard use a different definition? how can I implement the metrics server / cloud watch definition in Signoz?

[Slack Message](https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1688532145424859)

**Comment by srikanthccv** [comment]
This should not be the case with the updated dashboards for k8s
