### ISSUE TITLE
[Logs/Traces] Suggestions in order by.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#3088]
Suggestion is not currently present in order by

**Comment by nityanandagohain** [comment]
* In list view order by can be any attribute, but in timeseries order by can by only the things present in group By. ( cannot add timestamp). ( What happens when we switch from list to timeseries with order by fields not present in group by)

* We can order by value in timeseries, but when we switch back to listView it will result in error if order by value is present.

* Suggestion in orderBy work based on the fields present in group by. This is not the case for list view as groupBy is empty. Should we use the attribute_keys endpoint for suggestion of keys here (timestamp has to be added).

**Comment by srikanthccv** [comment]
> Suggestion in orderBy work based on the fields present in group by. This is not the case for list view as groupBy is empty. Should we use the attribute_keys endpoint for suggestion of keys here (timestamp has to be added).

Yes, all columns should be shown for the list view, and the client needs to use attribute_keys API. For reference look at the review comments in this PR https://github.com/SigNoz/signoz/pull/2847

>We can order by value in timeseries, but when we switch back to listView it will result in error if order by value is present.

> In list view order by can be any attribute, but in timeseries order by can by only the things present in group By. ( cannot add timestamp). ( What happens when we switch from list to timeseries with order by fields not present in group by)

groupby, having, order by will be reset when you go from time series to list view and viceversa.

**Comment by srikanthccv** [comment]
Here is the one panel to other panel change written expected behaviour https://github.com/SigNoz/signoz/issues/2410

**Comment by pranay01** [comment]
@nityanandagohain I am not clear on what does Ordering mean in case of time series?
e.g. If we are on a timeseries view, do group by `method` - what is user expected to see in the charts? Is it primarily for the case where there is a limit field also - so that you pick the first say 5 time series.

What is the ordering done based on? for e.g. in case of method - are the methods `GET`, `POST`, `DELETE` etc ordered alphabetically and limit is applied?

**Comment by nityanandagohain** [comment]
Yes, if `method` is in `group by` and you `order by` `method` with limit 2 then you will just get  timeseries with `DELETE` and `GET`

But yeah it doesn't make sense in the chart. cc @makeavish

**Comment by srikanthccv** [comment]
No, the ordering is never based on the labels in the time series but always on the value. We can't say which ones are the final unless we know the aggregation values. Order by method only makes sense in the table view.

**Comment by nityanandagohain** [comment]
Discussed with Srikanth.

So we have a decision to make.
In table view if I group by `method` and then, should we internally first ordery by value and then order by method. Or should we just order by what the user has given us i.e method.

For some users if they have a limit of 3 with order by `method`, they might want to see top 3 methods with most count ordered by their name while rendering.

For some users if they have a limit of 3 with order by `method`, they might just want to see the methods with their count ordered by their name.


While both of them is not wrong we need to go ahead with one.

**Comment by nityanandagohain** [comment]
Decision.
If there is something in ordery by we will honor that, i.e ordery by on method then result will be based on alphabatic order of method.

If there is nothing in order by then we will use `value desc` as order by.

**Comment by pranay01** [comment]
this sounds good to me
