### ISSUE TITLE
Order By doesn't work consistently in timeseries/table view

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#3095]
This is true for logs and traces.

Scenario: Order by any key in graph/table panel in traces/logs. The result is not sorted by the key.

**Comment by nityanandagohain** [comment]
This will be true for metrics as well right ?

**Comment by makeavish** [comment]
> This will be true for metrics as well right ?

Yes, but we don't have ORDER BY in graph view for metrics. And table view is not ready yet for metrics so couldn't verify this.
@srikanthccv Can you please verify if ORDER BY is working fine in table view of metrics.

**Comment by srikanthccv** [comment]
Table view implementation is yet to be completed.

> Order by any key in graph/table panel in traces/logs. The result is not sorted by the key.


What does it mean to sort results by the key in graph view? In general, order by doesn't have any effect in graph/chart view unless a limit is applied which I think is part of the open PRs.
