### ISSUE TITLE
Dashboard-Plot Distinct by tag

### ISSUE THREAD

**Issue by sharpSteff** [SigNoz/signoz#3097]
It would be great to be able to distinct metrics values in the Query Builder by tag.

Alternativly I can also use the ClickHouse Query, but in the docs I could not find any examples to query metrics values

**Comment by srikanthccv** [comment]
> to be able to distinct metrics values in the Query Builder by tag.

I couldn't understand this. What are you trying to do?

**Comment by sharpSteff** [comment]
my app has a "health"-metric, which is sent every 120s. The metric has an client-ID as tag attached.

Let's say I have 100 clients online, so 100 metrics were sent each 120 seconds.


I like to have a graph showing the number clients, which were online in a timeframe of 24h.

I created a query which counts the health-metric and set the aggregation to 24h.
the graph looks very promising, but of course does not represent the actual number of clients, since the aggregation just sums all metrics in a timeframe.

It would be great to somehow tell the aggregation to take only one metric (if available) with a certain tag-value (client -id) into account.

Maybe I miss something here completely easy ...

**Comment by sharpSteff** [comment]
@srikanthccv lets be technical lol.
I basically need an UI equivalent to SQLs COUNT( DISTINCT BY XX)

for traces I was able to create a custom Clickhouse Query with this:

```
SELECT
    day,
    version,
    COUNT(DISTINCT distinct_value) as value
FROM (
    SELECT 
        t1.tagMap['service.instance.id'] as instance,
        splitByChar('-', instance)[1] AS distinct_value,
        t1.tagMap['service.version'] AS version,
        toDateTime(toStartOfDay(t1.timestamp)) AS day
    FROM signoz_traces.signoz_index_v2 t1
    WHERE t1.timestamp > toDateTime64(now() - toIntervalMinute(36000), 0, 'UTC')  
    AND t1.serviceName == 'myService'
    AND t1.name == 'traceName'
    AND t1.tagMap['service.version'] != ''
) AS subquery 
GROUP BY
    version,
    day
ORDER BY version, day ASC
```

It would be great to have COUNT (DISTINCT XX) on UI

**Comment by srikanthccv** [comment]
There is indeed a `COUNT_DISTINCT` in the query builder since 0.19, What version of SigNoz are you using?

**Comment by sharpSteff** [comment]
0.23

Last time I checked COUNT_DISTINCT, there was no option to pass a value. I think it distinct per value as default.

It would be great if the user has the option to specify a value to distinct by. e.g tag-values

**Comment by sharpSteff** [comment]
> It does what you describe you want. Say if you choose COUNT_DISTINCT and aggregate attribute as service.instance.id the count will be distinct values for service.instance.id for selected duration.


than its broken with v0.23. When selecting `Count Distinct` there is no additional field to enter my `tag service.instance.id`

![metrics_distinct](https://github.com/SigNoz/signoz/assets/30927510/85e34901-b525-4d21-9bba-73fcb9d09770)

**Comment by sharpSteff** [comment]
works again in the latest version
