### ISSUE TITLE
Error logs: textPayload: "2023.07.12 11:39:50.981587 [ 488 ] {1ca7459f-02f1-47b0-a612-2197dcc2a366} <Information> executeQuery:

### ISSUE THREAD

**Issue by nevenara1234** [SigNoz/signoz#3118]
## In what situation are you experiencing subpar performance?

I noticed a lot of error messages 

![image](https://github.com/SigNoz/signoz/assets/139354582/ba707a64-ee40-429a-92c3-898971f02802)

How I can fix it?

## How to reproduce

1. Running signoz latest version (default version) on GCP kubernetes

## Your Environment

- kubernetes 

Please provide details of OS version etc.

**Comment by srikanthccv** [comment]
They are not error logs. They are _INFO_ level logs. Whatever UI/tool you are using, it seems to incorrectly label them as error logs.
