### ISSUE TITLE
Signoz backend crashes with "failed to initialize ClickHouse: error connecting to primary db: dial tcp: lookup my-host: device or resource busy”

### ISSUE THREAD

**Issue by svsk417** [SigNoz/signoz#3119]
## Bug description

The signoz backend container (query-service) crashes when running in the following environment:

- Docker version 20.10.21, build baeda1f
- Host System: Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-194-generic x86_64)

The stacktrace is as follows:

```
2023-07-11T08:08:35.570Z	ERROR	clickhouseReader/reader.go:128	failed to initialize ClickHouse: error connecting to primary db: dial tcp: lookup my-host: device or resource busy
go.signoz.io/signoz/pkg/query-service/app/clickhouseReader.NewReader
	/go/src/github.com/signoz/signoz/pkg/query-service/app/clickhouseReader/reader.go:128
go.signoz.io/signoz/ee/query-service/app/db.NewDataConnector
	/go/src/github.com/signoz/signoz/ee/query-service/app/db/reader.go:19
go.signoz.io/signoz/ee/query-service/app.NewServer
	/go/src/github.com/signoz/signoz/ee/query-service/app/server.go:119
main.main
	/go/src/github.com/signoz/signoz/ee/query-service/main.go:119
runtime.main
	/usr/local/go/src/runtime/proc.go:250

```

## Version information

- **Signoz version**: 0.22.0
- **Your OS and version**: Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-194-generic x86_64)

## Additional context

I have also tried this in a different host, where it worked as expected:

- Docker version 20.10.3, build 48d30b5
- Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-211-generic x86_64)

Another thing I have tried is to use a ubuntu 22.04 image as a base image instead of the alpine image with the same result.

**Comment by srikanthccv** [comment]
Can you consistently reproduce this error in the mentioned env?

**Comment by svsk417** [comment]
Hi @srikanthccv, yes, the crash happens every time I try to start the container in the environment.

**Comment by srikanthccv** [comment]
Can you share the logs of clickhouse and zookeeper containers?

**Comment by svsk417** [comment]
Hi @srikanthccv,
sorry for the late respone. I think that the DNS entry for the clickhouse database cannot be retrieved and therefore, we do not see anything in the clickhouse access logs. The log level is debug, so we definately should see something. 
```
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/cluster.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/cluster.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/config.xml'.
Processing configuration file '/etc/clickhouse-server/users.xml'.
Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/users.xml'.
```

**Comment by svsk417** [comment]
These guys

**Comment by svsk417** [comment]
I have found a solution for my problem: 
As far as I understand it the root cause is as follows: 
Since I was running signoz in a docker network, where the dns entries are apparently bigger than 512 bytes, TCP was used instead of UDP for DNS queries. 
In the query-service CGO is enabled, which tells the GO compiler to use the native libraries favorably. On Alpine Linux DNS over TCP has only [recently been added](https://www.theregister.com/2023/05/16/alpine_linux_318/)(Version 3.18).
Therefore the TCP DNS query did not work. 
I added `GODEBUG "netdns=go"` as an environment variable. This [enforces that the application uses the purely in GO implemented DNS resolution](https://pkg.go.dev/net#hdr-Name_Resolution).
Therefore, this problem is mitigated. 

But as alpine now supports DNS over TCP, I would recommend to use that image instead of the old one @srikanthccv :)

**Comment by ankitnayan** [comment]
@svsk417 wasn't the solution already in place? https://github.com/SigNoz/signoz/blob/develop/deploy/docker/clickhouse-setup/docker-compose.yaml#L182

**Comment by svsk417** [comment]
@ankitnayan Oh, yes, indeed, I did not see that. We needed to adapt the docker files a little and I must have missed that env variable. Thanks for the hint. :) 
Then this issue is the reference for those as dumb as me to overlook that one :D
