### ISSUE TITLE
Feat(FE): Configure Jest

### ISSUE THREAD

**Issue by pal-sig** [SigNoz/signoz#312]
## Bug description

Configure JEST(Typescript) with [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/)

**Note: Make sure cypress `expect` does not break**

**Comment by Bhavin789** [comment]
Hi @palash-signoz , can I take a stab at it? Thanks!

**Comment by palash-signoz** [comment]
Hi @Bhavin789 
Sure please go-ahead
