### ISSUE TITLE
Logs Explorer: Show options based on format type selected

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#3128]
the `max lines per row` is only relevant for `Raw` view and `Add a column` is only relevant for `Default` and `Column` view. Should we show only the relevant options on selection of view? Otherwise it creates confusion on what columns would do when I am in Raw view

[Slack Message](https://signoz-team.slack.com/archives/C052TFC709H/p1688897180441299?thread_ts=1688897180.441299&cid=C052TFC709H)

**Comment by pranay01** [comment]
Yeah, this makes sense. Let's only show the relevant options based on format selected

Format : Raw -> Max lines per row
Format : Default -> Add a column
Format : Column -> Add a column

**Comment by nityanandagohain** [comment]
This is resolved
