### ISSUE TITLE
Clickhouse DB suddenly shows TLS error from peer (alert code 80): 80

### ISSUE THREAD

**Issue by yash-ghelani-dsw** [SigNoz/signoz#3144]
Hi I have installed signoz on my RHEL 8 server, which was working well post installation.
But suddenly something went wrong in clickhouse DB and the logs of same shows below error:

> + wget -O /tmp/histogramQuantile https://github.com/SigNoz/signoz/raw/develop/deploy/docker/clickhouse-> > setup/user_scripts/histogramQuantile
Connecting to github.com (20.207.73.82:443)
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer
>+ mv /tmp/histogramQuantile /var/lib/clickhouse/user_scripts/histogramQuantile
mv: can't rename '/tmp/histogramQuantile': No such file or directory
>+ chmod +x /var/lib/clickhouse/user_scripts/histogramQuantile
chmod: /var/lib/clickhouse/user_scripts/histogramQuantile: No such file or directory

I have tried to restart the pod, but still shows same error.

Post the I have check the internet connectivity within the pod, but everything is working fine.

**Comment by srikanthccv** [comment]
Fixed in https://github.com/SigNoz/charts/pull/259

**Comment by srikanthccv** [comment]
It is part of the latest charts release version, `0.19.0`. Which version are you using?

**Comment by yash-ghelani-dsw** [comment]
> It is part of the latest charts release version, `0.19.0`. Which version are you using?

hi, I have shifted to 0.20.0 chart version ..Now its working well
