### ISSUE TITLE
FE: [LOGS] Extra scrollbar in column format logs table view

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#3149]
https://github.com/SigNoz/signoz/assets/26831659/0f5b14d3-2dfd-43a2-b868-e02d663154dd

**Comment by palashgdev** [comment]
no @nityanandagohain scroll bar that you are seeing is from the table component itself and i guess this is expected behaviour

**Comment by nityanandagohain** [comment]
It's is now gone from default and raw format, but present in table format.

**Comment by nityanandagohain** [comment]
This has started appearing again even in raw logs view. we need to priotise this.

@ankitnayan  @YounixM  can we bump this up

**Comment by palashgdev** [comment]
expected behaviour closing this one
