### ISSUE TITLE
Is there doc for Clickhouse schema, and will it be stable?

### ISSUE THREAD

**Issue by fzyzcjy** [SigNoz/signoz#3167]
Hi thanks for the open source lib! Given that we can create custom panels (https://signoz.io/docs/userguide/manage-dashboards/), it seems I need to know the schema. I have briefly checked doc and code but without success (https://github.com/search?q=repo%3ASigNoz%2Fsignoz+%22CREATE+TABLE%22&type=code, https://github.com/search?q=repo%3ASigNoz%2Fsignoz+schema&type=code).

In addition, I wonder whether the schema is guaranteed to be stable, or will it have breaking change over time (e.g. if it is considered as an internal implementation details)?

**Comment by makeavish** [comment]
Here's schema: https://github.com/SigNoz/signoz-otel-collector/tree/main/exporter/clickhousetracesexporter/migrations

It is mostly stable, there are some columns which are pending for deprecation which are mentioned in this doc: https://signoz.io/docs/tutorial/writing-clickhouse-queries-in-dashboard/
Just avoid those columns and you are good to use.

**Comment by makeavish** [comment]
The schema has one major pending update (just new column names), after the update we can mark the schema as stable.

**Comment by fzyzcjy** [comment]
Thank you!
