### ISSUE TITLE
incorrect/missing ID for widget should not make page go blank white screen

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#3169]
It is not clear under what circumstance this issue occurs. Whenever
there is an item in the `layout` array of the dashboard json has an `i` with
some id value with no corresponding widget for that ID in the `widgets`
array, the page goes blank white screen. This has occurred a couple of times
but doesn't happen regularly. The entire page shouldn't be breaking for
one missing widget. Two things to fix
1. Handle missing ids gracefully.
2. Troubleshoot the underlying issue and fix it

**Comment by srikanthccv** [comment]
At the minimum, the entire page shouldn't go blank.

**Comment by sharpSteff** [comment]
any workarround or recovery know to this?

with v0.23.1 this issue happend regulary to me, adding/editing a panel and then close the browser tab without saving
