### ISSUE TITLE
Hide limit param in list view of traces

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#3173]
<img width="548" alt="Screenshot 2023-07-19 at 11 40 35" src="https://github.com/SigNoz/signoz/assets/9512100/20c10c01-231f-4d32-9ce6-a6bfc20f4990">

**Comment by vasukapil** [comment]
Hi , I would like to work on this issue , can you assign this to me .

**Comment by vasukapil** [comment]
@makeavish @palashgdev 

This is the scenario 

<img width="1219" alt="Screenshot 2023-07-21 at 7 52 54 AM" src="https://github.com/SigNoz/signoz/assets/21044485/7bb8de56-f4dd-4b51-a2ab-5e1adc1ffb90">

when we click on LIMIT or the add option we see the below screenshot

<img width="1221" alt="Screenshot 2023-07-21 at 7 52 40 AM" src="https://github.com/SigNoz/signoz/assets/21044485/335b7786-1849-4743-be86-336e4313fd85">

So do I need to remove the LIMIT option from both images?

**Comment by vasukapil** [comment]
<img width="1440" alt="Screenshot 2023-07-21 at 8 10 17 AM" src="https://github.com/SigNoz/signoz/assets/21044485/3b3abd92-ab7e-4d3a-b8f1-5432915eaabf">

<img width="1440" alt="Screenshot 2023-07-21 at 8 10 48 AM" 
src="https://github.com/SigNoz/signoz/assets/21044485/b304edfe-3b05-4953-8aac-2decd62c6be1">

Are these the desired output? @makeavish @palashgdev
