### ISSUE TITLE
Bug(FE): Create Custom ToolTip for the Chart.js

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#318]
## Is your feature request related to a problem?

*Please describe.*
Create a Custom ToolTip for the chart.js

**Comment by pranay01** [comment]
@palash-signoz Can you give more details on why is there a need for a custom tool tip and what are the features a custom tool tip should have?

**Comment by palash-signoz** [comment]
Yeah Sure

Custom Tooltip should have the following features

1. Must follow the ant design

1. Currently When chart.js width and height are small(data points are not visible - image for reference)
<img width="510" alt="Screenshot 2021-09-30 at 10 25 35 AM" src="https://user-images.githubusercontent.com/88981777/135389746-a6c3c934-2c7b-4440-97a3-232582a963b3.png">

**Comment by learning-dev** [comment]
@pal-sig  @pranay01  I can take this up, but I am not clear with what we are expecting with the final view. I see that data points are overlapping. Do I need to fix just that or do we have something else in mind?

**Comment by vikrantgupta25** [comment]
we are moving away from chart.js, this is not needed anymore
