### ISSUE TITLE
Integrate bundlephobia

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#319]
## Is your feature request related to a problem?

*Please describe.*

## Describe the solution you'd like
Integrate [bundlephobia](https://bundlephobia.com/) as Github CI/CD Actions which will tell the size of the different packages in the frontend

**Comment by aneeshrelan** [comment]
Can I take a stab at this? Are we looking to add it on a pull_request action or somewhere else?

**Comment by pranay01** [comment]
sure @aneeshrelan - assigning this issue to you
@palash-signoz should be able to guide you on the details

**Comment by aneeshrelan** [comment]
@pal-sig Can you add some details whenever you get a chance? Thanks!

**Comment by pal-sig** [comment]
Hi @aneeshrelan 

It would be great if we can integrate into PR via Github Action and in the repo also where just by triggering a script will check in the local

**Comment by vg18gupta** [comment]
Hi, @palashgdev is this issue resolved? If not I can work on this.

**Comment by palashgdev** [comment]
no @vg18gupta this is not resolved please go ahead ...

**Comment by YounixM** [comment]
Done ✅
