### ISSUE TITLE
As an open source project it is weird to see posthog analytics tracking everywhere. 

### ISSUE THREAD

**Issue by eglizzy** [SigNoz/signoz#32]
As an open source project it is weird to see posthog analytics tracking everywhere.

**Comment by pranay01** [comment]
Hey @eglizzy, thanks for your note. We had debated this internally, before adding analytics to SigNoz. But one of the issues we found where open source projects lack compared to SaaS products is the quality of user experience. And, we think that for building great software you need some understanding of what users are using or where they are facing issues.

Our thinking resonates with what James takes about in this blog - 
https://posthog.com/blog/open-source-telemetry-ethical


“All tracking is bad, many say. We disagree. Done right, it enables more and better software in the world. When it's applied to open source, it often enables more free software for anyone to use.”

Though having said that, I agree we don’t ask very explicit permission from users of opting out. I will add an issue to track this more closely and would be very happy if anyone in the community picks it up.

**Comment by pranay01** [comment]
Tracking issue for opt out path from analytics - https://github.com/SigNoz/signoz/issues/33#issue-818262590
