### ISSUE TITLE
Show page name instead of default heading in SigNoz app

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#3201]
<img width="344" alt="Screenshot 2023-07-26 at 12 56 51" src="https://github.com/SigNoz/signoz/assets/9512100/099d4749-cf08-495c-8bad-1a42b29498e9">

**Comment by mustajab-ikram** [comment]
@palashgdev can I work on this one?

**Comment by palashgdev** [comment]
yeah sure you can add react helmet

with route config against title
