### ISSUE TITLE
Operator `IN` is case sensetive in query.

### ISSUE THREAD

**Issue by Rajat-Dabade** [SigNoz/signoz#3210]
## Bug description
- While trying to build the query for the latency graph, notices that the operator `IN` was case sensitive in `filter.items` for traces/metrics.
- The query_range API call was returning with a `404` status code. 

![Screenshot 2023-07-19 at 7 53 35 AM](https://github.com/SigNoz/signoz/assets/26198062/960abfa4-3fd3-4ad1-9a7d-8efad71e04ab)
![Screenshot 2023-07-19 at 7 53 53 AM](https://github.com/SigNoz/signoz/assets/26198062/fce4df55-9a8f-4573-8db4-643297af9578)

## Expected behavior
- The query_range API should work regardless of the operator `IN` case sensitivity. 

## Version information 
* **Signoz version**: v0.24.0-16-g

**Comment by palashgdev** [comment]
@Rajat-Dabade we need to convert from FE side also
