### ISSUE TITLE
FE: chart metrics name suggestion not updated when text is update

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/signoz#3217]
## Bug description

In Dashboards section, the metrics name suggestions not updated (or reduced) in Frontend even though network shows API call was made with correct response.

_Screenshot 1:_

<img width="666" alt="Screenshot 1" src="https://github.com/SigNoz/signoz/assets/11138844/78693fae-5e60-47ca-bbcb-1557252dd225">

_Screenshot 2:_

<img width="643" alt="Screenshot 2" src="https://github.com/SigNoz/signoz/assets/11138844/e5ab7ca8-1459-469d-825c-5531db93bec3">

## Expected behavior

Show updated list of suggestions in the metrics name dropdown list.

## How to reproduce

1. Create a chart in a new dashboard
2. Type `k8s_node_cpu`
3. You will see the suggestions consisting of irrelevant items

## Version information 
* **Signoz version**: v0.24
* **Browser version**: Version 1.51.110 Chromium: 113.0.5672.77
* **Your OS and version**: MacOS
* **Your CPU Architecture**(ARM/Intel): ARM (M1)

**Comment by vasukapil** [comment]
@palashgdev @Rajat-Dabade Are you working on this issue? If not can I work on it?

**Comment by palashgdev** [comment]
Sure @vasukapil

**Comment by mustajab-ikram** [comment]
Hello @palashgdev , I have investigated the issue and believe that the problem might be related to search debouncing (just a wild guess). I would like to work on fixing this issue (#3217). 
Could you please assign it to me so that I can start working on it? 
Thank you
