### ISSUE TITLE
Disable grafana import until it is updated to work with new Query builder

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#3223]
Recently SigNoz query builder was released with support for Logs and Traces. Grafana import has not been updated to work with new query builder so we should disable it to avoid bad user experience.

**Comment by kost2191** [comment]
Hello, team!
What are the plan to return this? It is crucial to be able to switch to signoz with prom exporters and importing from grafana all dashboards

**Comment by ayush-rathore-quartic** [comment]
This is affecting us as well, Do we have a plan or workaround to resume the 'Import Grafana JSON' functionality?
