### ISSUE TITLE
FE: (logs) Abnormal behaviour of query range filter

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#3226]
Here is the video which exlpains the issue

https://github.com/SigNoz/signoz/assets/26831659/36c5d469-f245-4904-8f38-d19391f1e080

cc @srikanthccv @ankitnayan

**Comment by srikanthccv** [comment]
The operators are case-sensitive. There is no `ncontains` but `NOT_CONTAINS`. When you do `level nCONTAINS info`, it will ignore `level` and treat `n` as key. This is an issue everywhere except the full-text search special case. I can't recall why we made it case-sensitive. Let me think and come back on this.

**Comment by nityanandagohain** [comment]
Closing this as we have separete issue https://github.com/SigNoz/signoz/issues/3645
