### ISSUE TITLE
Dashboard lost panel clickhouse queries after upgrading from v0.19 to v.0.25

### ISSUE THREAD

**Issue by alimehrabikoshki** [SigNoz/signoz#3230]
## Bug description

After upgrading from v0.19.0 to 0.25.0 on Docker via install.sh script, all previously created panels lost their clickhouse query on the UI
<img width="437" alt="image" src="https://github.com/SigNoz/signoz/assets/79400736/9f6cb64f-df21-43a5-872f-3fb1fdb6e195">

<img width="386" alt="image" src="https://github.com/SigNoz/signoz/assets/79400736/7e32298d-653a-4d68-bb94-087925bb5773">

I had about 6 panels and this happened to all of them
I can see in the exported json that the queries are still there:
```json
"clickhouse_sql": [
  {
     "disabled": false,
    "legend": "",
    "name": "A",
    "rawQuery": "SELECT\n    toStartOfInterval(timestamp, toIntervalDay(7)) AS interval,\n    count  (DISTINCT stringTagMap['xxx']) AS value\nFROM\n    signoz_traces.signoz_index_v2\nWHERE\n timestamp > now() - INTERVAL 180 DAY\n    AND stringTagMap['xxx'] NOT IN ('unknown')\n    AND stringTagMap['xxx'] NOT LIKE 'xxx.%'\n    AND stringTagMap['xxx'] NOT LIKE '%xxx%'\nGROUP BY\n     interval\n"
          }
        ],
```
## Expected behavior

Clean migration of panels between versions

## Version information 
* **Signoz version**: v0.25.0
* **Browser version**: Chrome 115
* **Your OS and version**: hosted on centos 7 3.10
* **Your CPU Architecture**(ARM/Intel): Intel

**Comment by srikanthccv** [comment]
It should be `query` instead of `rawQuery`. One quick solution is to export the dashboard json using the `Share` option. And update the key from `rawQuery` to `query` and upload again and delete the old one.

**Comment by alimehrabikoshki** [comment]
This worked, thank you
