### ISSUE TITLE
FE: (dashboard) Error when clicking on a panel type

### ISSUE THREAD

**Issue by dnazarenkoo** [SigNoz/signoz#3234]
https://github.com/SigNoz/signoz/assets/134951516/d8c6015b-4109-4202-bfe9-e2fc7ce427e6

**Comment by srikanthccv** [comment]
When does this happen? I am not able to reproduce this. Do production users face this issue?

**Comment by dnazarenkoo** [comment]
> When does this happen? I am not able to reproduce this. Do production users face this issue?

This is reproduced when we get an error from the API call, and it looks strange to the user because we don't show them any notifications

**Comment by srikanthccv** [comment]
Stale!
