### ISSUE TITLE
Table View Enhancement 

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#3249]
- [x] Ordering of columns via queryNames A,B,C...F1.F2 [https://github.com/SigNoz/signoz/issues/3840]
- [x] Sorting of columns via asc/desc.
Column Sorting in Tables: It would be incredibly helpful if we could sort columns in the tables by both ascending and descending order. This would streamline our data analysis significantly.  -> https://github.com/SigNoz/signoz/pull/5114
Context -> https://signoz-team.slack.com/archives/C05AXQL92BT/p1715348260465959
- [x] #3277 -> expressed concerns in the ticket for the same 
- [x] https://github.com/SigNoz/signoz/issues/4088
- [ ] #5259
- [x] #5260
- [ ] #5261
- [x] #5262
- [ ] https://github.com/SigNoz/engineering-pod/issues/1691

**Comment by srikanthccv** [comment]
@Vikrant2520 we used to have column sorting in tables but it doesn't seem to exist now. That would be very helpful feature for users https://signoz-team.slack.com/archives/C05AXQL92BT/p1715348260465959

**Comment by vikrantgupta25** [comment]
all the tasks in this epic are complete, closing the same.

**Comment by srikanthccv** [comment]
Closing this since we main EPIC.
