### ISSUE TITLE
Configure whyDidyouRender

### ISSUE THREAD

**Issue by pal-sig** [SigNoz/signoz#325]
## Is your feature request related to a problem?

The first step towards app optimization

*Please describe.*
Configure [whyDidYouRender](https://github.com/welldone-software/why-did-you-render) under the development env

**Note: make sure it is compatible with all the [custom hooks](https://github.com/welldone-software/why-did-you-render#custom-hooks) that we are using in the project **

**Comment by idiglove** [comment]
Hi, I would like to try this as my first issue, thanks :)

**Comment by pranay01** [comment]
Cool - assigning to you @idiglove

**Comment by friilancer** [comment]
Are there still plans to implement this? I could take it up

**Comment by pranay01** [comment]
sure @friilancer Assigning to you. Do comment here if you have any questions

**Comment by friilancer** [comment]
Alright, will do

**Comment by pal-sig** [comment]
Hi @friilancer 
This issue is already fixed ([ref](https://github.com/SigNoz/signoz/blob/main/frontend/src/wdyr.ts))
