### ISSUE TITLE
Signoz frontend goes blank in the new logs explorer when I try to filter for service_name

### ISSUE THREAD

**Issue by abhinavramana** [SigNoz/signoz#3255]
## Bug description

Signoz frontend goes blank in the new logs explorer when I try to filter for service_name / Otelservicename If the log body contains a huge payload.

## How to reproduce

https://drive.google.com/file/d/1gAs7RWYO3BgKuMJb2qcA_MvFAoT-pdzZ/view?usp=drive_link

* **Signoz version**: v0.25.0
* **Browser version**: Firefox
* **Your OS and version**: 116.0 (64-bit)
* **Your CPU Architecture**(ARM/Intel):  Intel

**Comment by srikanthccv** [comment]
We can show the loader when the API request is not yet completed.

**Comment by ankitnayan** [comment]
@nityanandagohain is this still relevant?

**Comment by nityanandagohain** [comment]
not relevant now
