### ISSUE TITLE
Is support Prisma?

### ISSUE THREAD

**Issue by KokoTa** [SigNoz/signoz#3257]
I use SigNoz with nestjs, and get request monitor funny.

But i can't check sql time when use Prisma.

Is my fault or not support prisma?

**Comment by makeavish** [comment]
@KokoTa SigNoz supports all libraries which has opentelemetry support.
Primsa has opentelemetry support: https://www.prisma.io/blog/tracing-tutorial-prisma-pmkddgq1lm2#set-up-automatic-instrumentation-for-prisma

**Comment by KokoTa** [comment]
@makeavish Thanks for your help^ ^
