### ISSUE TITLE
New Log Explorer: Table header is having wrong style in light mode

### ISSUE THREAD

**Issue by davesmits** [SigNoz/signoz#3258]
## Bug description

The table header in the new log explorer shows in its dark theme (or lacking a light there). Some texts are unreadable or only readable when hoving over it with the mouse

<img width="1731" alt="image" src="https://github.com/SigNoz/signoz/assets/3148438/d1bde25d-46c1-4993-9a49-fe9fc87290c6">

## Expected behavior

Component shows in a light theme where text is always readable

## How to reproduce

1. Open signoz in light theme
2. navigate to logs
3. navigate to "try new log explorer"
4. Notice the black bar below the graph

## Version information 
* **Signoz version**: 0.25.0
* **Browser version**: Edge 115
* **Your OS and version**: Windows 11
* **Your CPU Architecture**(ARM/Intel): Intel

**Comment by dnazarenkoo** [comment]
@palashgdev can I take it?
