### ISSUE TITLE
Broken where clause in logs explorer

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#3274]
Where clause in logs explorer doesn't work when multiple queries are added.

The query is not built correctly at frontend, filter param is empty: 
![image](https://github.com/SigNoz/signoz/assets/9512100/a629db8c-ba6d-4fe1-a0ef-e5a1046181c5)

**Comment by mustajab-ikram** [comment]
can I work on it, @palashgdev ?

**Comment by palashgdev** [comment]
Sure @mustajab-ikram

**Comment by palashgdev** [comment]
@mustajab-ikram can you share the pr by today ?

**Comment by mustajab-ikram** [comment]
yes, I will try my best to provide it in needed time.
