### ISSUE TITLE
UI/UX: Better log detail page.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#3276]
Current log detail page.
![image](https://github.com/SigNoz/signoz/assets/26831659/922cf968-bdc0-45fa-bb68-98f022aa7128)

![image](https://github.com/SigNoz/signoz/assets/26831659/2b8e27bd-52ef-4790-beab-aed9fe5a4ba4)

Suggested changes
* Also `dataType` suffix should be removed from the detail page i.e `attributes_string` should be `attributes`

* Users assume that `attributes_string` is actually a prefix for `attributes_string.msg` which is not the case.

* Json should merge all the attributes_type to attributes, resources_type to resources

**Comment by mustajab-ikram** [comment]
I have worked on log details page, shall I pick this? @pranay01

**Comment by nityanandagohain** [comment]
Hi @mustajab-ikram  we have to decide more on this, you can pick up once the changes we need to do is finalized.
