### ISSUE TITLE
Upgrade clickhouse to 23.7.3

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#3294]
Need to upgrade 23.7.3 , one of the main reason is we need this fix https://github.com/ClickHouse/ClickHouse/pull/50104

- [ ] Logs @nityanandagohain 
- [ ] Metrics @srikanthccv 
- [x] Traces @makeavish 
- [ ] Deployment @prashant-shahi

**Comment by srikanthccv** [comment]
I have yet to test this thoroughly, but so far, I didn't find anything breaking.

**Comment by nityanandagohain** [comment]
I have upgraded clickhouse on k8s while load was getting generated, didn't find any issue .
