### ISSUE TITLE
Logs filter U/X: Improve how attributes are shown in logs filter UI.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#3299]
* When an attribute is selected we show it as `<type>_<name>` where  `<type>` can be `tag/resource`   and `<name>` is the name of the attrbute.
![image](https://github.com/SigNoz/signoz/assets/26831659/44483617-c46b-4130-89e8-90e3e3f0716a)

* Once the attribute is selected it becomes just `<name>`
![image](https://github.com/SigNoz/signoz/assets/26831659/e66174d1-48e6-47f2-a45d-39fd945cee13)

* We need a better way to convery the user what is the `type` and `dataType` of the tag instead of the aboe

**Comment by pranay01** [comment]
`dataType` could be `int64` or `string`

**Comment by pranay01** [comment]
Figma Design - https://www.figma.com/file/i2CsZFl27dhmER6gnx08wj/Integ.-QueryBuilder%2B3SigNalCorrelation?type=design&node-id=4211%3A20265&mode=design&t=JlXlGD1o8XhNN9OL-1
