### ISSUE TITLE
Continuously loading on create dashboard UI

### ISSUE THREAD

**Issue by kaushikmacharla07** [SigNoz/signoz#3306]
Bug description
When I try to add a layout in the Dashboard page, I see that its continuously loading and not showing up anything in there. I don't think thats the expected behaviour.

<img width="2240" alt="image" src="https://github.com/SigNoz/signoz/assets/139132628/595113ad-705d-4ef9-85a7-135f8a2ac460">

**Comment by dnazarenkoo** [comment]
@kaushikmacharla07 @pranay01 @palashgdev  can I take this and what should replace the current behavior?
