### ISSUE TITLE
Filter services in the UI by their namespace

### ISSUE THREAD

**Issue by adirmatzkin** [SigNoz/signoz#333]
## Is your feature request related to a problem?

* *service.name* attribute shouldn't be unique across multiple namespaces, so multiple services with the same name can not be distinguished in the UI (see [OTELs *service* semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#service)).
* Navigating through the UI when there are many services is hard.
As much as I noticed, the problem might occur at 3 different views - 'Metrics', 'Traces' and 'Service Map'.

## Describe the solution you'd like

Make use of the *service.namespace* attribute if passed in OTEL_RESOURCES_ATTRIBUTES.
That use should be implemented in a form of a filtering option for each view, to select only interested namespaces.
### Metrics & Service Map views
These views seem to show all services by default.
Adding a dropdown menu of a checklist to select only interested namespaces should do the job.
In addition to all namespaces, add an 'all' option to select all namespaces. This option should be the default selection.
### Traces view
This view seem to offer all services in the dropdown menu by default (in the 'Filter Traces' segment).
I recommend adding another dropdown menu, before the service dropdown.
The services options in the dropdown will be filtered by the selected namespaces in the new namespace dropdown.
In addition to all namespaces, add an 'all' option to select all namespaces. This option should be the default selection.

## Additional context

[Beginning of discussion on Slack](https://signoz-community.slack.com/archives/C01HWUTP4HH/p1633190484110900) 
[More context from Slack](https://signoz-community.slack.com/archives/C01HWUTP4HH/p1633231682113300)
@pranay01 @ankitnayan

#### *Thank you* for your feature request – we love each and every one!

**Comment by pranay01** [comment]
![Screenshot 2022-06-03 at 1 17 35 AM](https://user-images.githubusercontent.com/504541/171725761-b25ca1ea-8474-43d8-a9ec-fa8ce19b9e87.png)

@adirmatzkin we have added support for services.namespace attribute  now. You can filter based on this in Services list page.

Relevant docs - https://signoz.io/docs/userguide/metrics/#steps-to-add-resource-attributes

**Comment by makeavish** [comment]
Closing it as we already added support for `services.namespace` attribute
