### ISSUE TITLE
Panel being cloned is saved when the discard button is clicked

### ISSUE THREAD

**Issue by Damans227** [SigNoz/signoz#3344]
## Bug description

Upon cloning a panel and clicking discard, the cloned panel is saved instead of being discarded. 

Screen-recording of the bug: 

https://www.loom.com/share/f6f18737364247dfa2915a0dc00a706e

## Expected behavior

Panel should be discarded. 

## Version information 
* **Signoz version**: v0.25.5

**Comment by srikanthccv** [comment]
This is working as expected. The "Discard" is to discard any temporary changes made to the panel's state and not discard the clone operation.

**Comment by palashgdev** [comment]
this is not the issue closing for now
