### ISSUE TITLE
[Logs] FE: Switch to new explorer and depricate old explorer page

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#3349]
New explorer should be the default one and the old explorer should be present in the button `use old explorer`

**Comment by palashgdev** [comment]
@nityanandagohain what kind of deprecating message we are showing on the old Explorer page

**Comment by palashgdev** [comment]
also, we have a trace explorer Do we need to consider that one also?

**Comment by makeavish** [comment]
> also, we have a trace explorer Do we need to consider that one also?

That will moved after we have fast filters on trace explorer

**Comment by makeavish** [comment]
Remember to also switch correrlation to new logs explorer page.
Eg: Show related logs on trace detail page should redirect to new logs explorer page.
