### ISSUE TITLE
LOGS [FE] Show error message while removing selected fields.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#3356]
In the old explorer page, remove a top level selected field :- 
ex:- `trace_id`, `span_id`, `severity_text`, `severity_number`.

Note : this errors are not present on staging, it is present in changes made here https://github.com/SigNoz/signoz/pull/3275

You will get an error
```
{
    "status": "error",
    "data": "Failed to update filed in the DB",
    "errorType": "bad_data",
    "error": "cannot update static fields"
}
```

Display the error message on the UI.

**Comment by palashgdev** [comment]
@nityanandagohain can you deploy this one for me
