### ISSUE TITLE
Back button doesn't work on traces/logs explorer page

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#3366]
https://www.loom.com/share/47d40a619eda4415840a3e4d6e2484f4?sid=aee03d78-9400-4b2f-8847-d2252f1fffeb

**Comment by mustajab-ikram** [comment]
hey @palashgdev, please assign, will wrap it quickly.

**Comment by nodaddy** [comment]
This issue has been resolved in my local setup, raising a PR by EOD
@palashgdev
