### ISSUE TITLE
FE: Fix login after building without `ee` folder

### ISSUE THREAD

**Issue by jsanant** [SigNoz/signoz#3367]
## Bug description

After removing the `ee` directory and building Signoz, we are able to log in and explore the UI. 

But after logout, the login doesn't work because the frontend sends an API call to `/api/v1/loginPrecheck` which is part of the [ee query-service](https://github.com/SigNoz/signoz/blob/5ac105beca19e6b43887388386950ef669ad52a7/ee/query-service/app/api/api.go#L105).

![Screenshot 2023-08-17 at 4 31 45 PM](https://github.com/SigNoz/signoz/assets/10994557/d739d9f6-45fd-4f8d-8ded-17d1adba7373)

## Expected behavior

Login should work without any issues after compiling without `ee` folder

## How to reproduce

1. Import `model` from `pkg` library in the [dynamic_config.go](https://github.com/SigNoz/signoz/blob/5ac105beca19e6b43887388386950ef669ad52a7/pkg/query-service/integrations/signozio/dynamic_config.go#L9) file
2. Delete the `ee` folder
3. Build the frontend and query-service
4. Start frontend service and also start query-service by passing `--skip-top-level-ops` argument
5. Login into Signoz and create a user. Logout and then try logging in again.

## Version information 
* **Signoz version**: v0.24.0
* **Browser version**: Chrome 115.0.5790.114
* **Your OS and version**:  macOS Ventura & 13.2
* **Your CPU Architecture**(ARM/Intel): ARM

**Comment by vishalsharma1800** [comment]
Hi team, I'd like to take up this issue, can someone please assign it to me?

**Comment by srikanthccv** [comment]
This is not up-for-grabs. Please find a another good-first-issue/help-wanted ticket.

**Comment by makeavish** [comment]
@vishalsharma1800 You can fetch feature flag API to check if it's OSS version and then decide based on that whether to call loginPreCheck API
```
curl --location 'localhost:8081/api/v1/featureFlags'
```
<details open>
<summary>Sample response:</summary>
<br>

```
{
    "status": "success",
    "data": [
        {
            "name": "DurationSort",
            "active": true,
            "usage": 0,
            "usage_limit": -1,
            "route": ""
        },
        {
            "name": "TimestampSort",
            "active": true,
            "usage": 0,
            "usage_limit": -1,
            "route": ""
        },
        {
            "name": "USE_SPAN_METRICS",
            "active": false,
            "usage": 0,
            "usage_limit": -1,
            "route": ""
        },
        {
            "name": "PreferRPM",
            "active": true,
            "usage": 0,
            "usage_limit": -1,
            "route": ""
        },
        {
            "name": "OSS",
            "active": true,
            "usage": 0,
            "usage_limit": -1,
            "route": ""
        }
    ]
}
```

</details>

**Comment by srikanthccv** [comment]
That's not the right fix. It should always call the login precheck because that decides what to show to user. The right fix is implementing the endpoint and responding with the payload that is relevant.

**Comment by srikanthccv** [comment]
The regular flow is, A user enters their email and the request is made to backend to fetch the details. There is a `isUser` which is universal check whether it's an SSO or not. After this step is complete, the options to show password or SSO approach is decided based on the status of SSO but the existance of `isUser=true` is mandatory (otherwise a message is shown to user to get the invite). Please make sure to implement the API since it's the direct requirement.

**Comment by vishalsharma1800** [comment]
Hi, I have implemented the API in pkg and was trying to run local tests but they are failing because invite endpoint is returning empty response in the testcases, any suggestions to fix this?
