### ISSUE TITLE
FE: Live Logs Enchantment 

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#3380]
Improvement's

- [x] handle the position of the go-live button in the logs-explorer page
- [x] pass the previously fetched data to the go-live page
- [ ] initial connection for the live tail is taking around 35 seconds
- [x] should not wipe the previous logs when we press resume
- [x] expanded view action column name is truncated and it should have a width for the column to look good
- [x] Remove the back button and add the exit live view button next to the pause/resume button
- [x] add the loading state which highlights that the client is fetching the data from the backend

**Comment by ashutosh887** [comment]
Should I work on this @palashgdev ?

**Comment by ankitnayan** [comment]
@palashgdev which of the tasks are completed?

**Comment by palashgdev** [comment]
> @palashgdev which of the tasks are completed?

all are completed but in the 3 point there is still the scope

**Comment by palashgdev** [comment]
@nityanandagohain do check if we can reduce this one
