### ISSUE TITLE
Bug(FE): duplicate @babel/core packages

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#339]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

There are two packages of `@babel/core` one in [dependencies](https://github.com/SigNoz/signoz/blob/main/frontend/package.json#L26) and another one in [devDependecies](https://github.com/SigNoz/signoz/blob/main/frontend/package.json#L129) 

<img width="1430" alt="Screenshot 2021-10-13 at 10 27 45 PM" src="https://user-images.githubusercontent.com/88981777/137179125-f29fcd68-5c94-4958-85be-8b90b8d86ed6.png">

## Expected behavior

1. The warning should be removed
1. There should be only one dependency

## How to reproduce

1. run dev script via `yarn dev`
2. you will see in the terminal

**Comment by exequiel09** [comment]
Hi @pal-sig I'll take this on 🙏

**Comment by pranay01** [comment]
cool, assigning to you @exequiel09

**Comment by exequiel09** [comment]
Removed dupe `@babel/core` package via #341
