### ISSUE TITLE
Parent traceID not propogating to REST calls using otelgin.Middleware

### ISSUE THREAD

**Issue by Connect2naga** [SigNoz/signoz#3390]
HI 

Trying sample Application using Gin and otelgin.Middleware() to stich chain of REST API calls. Below is the scenario tried(taken as base  mentioned in https://signoz.io/blog/opentelemetry-gin/).
1. Make rest call to Books Application  
2. Books applications make call to Stores Applications to get all books from All stores
3. Store applications just return empty.

![image](https://github.com/open-telemetry/opentelemetry-go-contrib/assets/13164500/4bf2ebd8-d9a3-4561-99f8-12095edf5a31)

Actually Books API call and Store Api calls' should be linked.  But it not happening and both calls having different TraceID.

Note : Same tried with Mux it is working.

Screenshots:
Books Application:
![image](https://github.com/open-telemetry/opentelemetry-go-contrib/assets/13164500/788c0016-b23d-4ddf-a74d-349d282f40c0)

Store Application:
![image](https://github.com/open-telemetry/opentelemetry-go-contrib/assets/13164500/d0d022c5-cc6d-408f-88c2-6ed59d830e4e)

Example code available in https://github.com/Connect2naga/Examples/tree/main/Standalone

Please correct me if any thing missed or need to change the configuration.

**Comment by srikanthccv** [comment]
It is not propagating because you have not set one. Please set the propagator and check again.

```golang
...
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(propagation.TraceContext{}))
...
```

**Comment by jkwang-a** [comment]
@Connect2naga @Naga2HPE 
you need add:
![Image](https://github.com/user-attachments/assets/1468d025-cacd-4a21-8d4c-e72a67b21f1c)
