### ISSUE TITLE
Dark mode toggle should be centre aligned rather than right aligned

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#34]
![photo_2021-03-01 22 21 49](https://user-images.githubusercontent.com/504541/109530298-8f452800-7adc-11eb-8cd8-4d044b20156e.jpeg)

**Comment by anweshknayak** [comment]
@pranay01  this is fixed in latest pull. Closing this? 

![Screenshot 2021-06-05 at 11 29 25 AM](https://user-images.githubusercontent.com/8139783/120882013-b0914500-c5f2-11eb-87b7-f4fbacc456e3.png)
