### ISSUE TITLE
clickhouse system log tables are enabled with no TTL

### ISSUE THREAD

**Issue by davisagli** [SigNoz/signoz#3411]
## Bug description

The clickhouse config in this repository has the clickhouse system log tables (such as `query_log`) enabled, but with no TTL. As a result, records accumulate in these tables and eat disk space over time.

Example: https://github.com/SigNoz/signoz/blob/develop/deploy/docker-swarm/clickhouse-setup/clickhouse-config.xml#L752

Note that this is unrelated to the data retention settings in SigNoz.

## Expected behavior

The clickhouse config suggested in this repository should either disable these tables (if they are not needed -- see https://stackoverflow.com/questions/75370327/disable-clickhouse-logs-in-the-system-database/75374179#75374179) or set a reasonable TTL.

## Version information 
* **Signoz version**: 0.26.1

## Additional context

https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-system-tables-eat-my-disk/

**Comment by prashant-shahi** [comment]
This change would be needed specific for Docker Standalone and Docker Swarm clickhouse configuration.

For Kubernetes, we have TTL of 30 days enabled by default for `query_log`, `part_log` and `trace_log` system tables, that can be altered using override values.

Ref: https://github.com/SigNoz/charts/blob/main/charts/clickhouse/values.yaml#L508-L525

cc @ankitnayan @srikanthccv

**Comment by srikanthccv** [comment]
This is done, every system log table has configurable TTL now.
