### ISSUE TITLE
optimize build time of frontend and query-service

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/signoz#3415]
## In what situation are you experiencing subpar performance?

The build time of SigNoz is slow. Currently, it takes around 10 minutes for `build-pipeline`, while almost half an hour for Docker buildkit to create multi-arch image.

## How to reproduce

1. Raise a PR in signoz repo
2. Check the build time in `build-pipeline` workflow
3. After any PR is merged, check the build-push time in `push` workflow

## Your Environment

- [x] Linux
- [ ] Mac
- [ ] Windows

## Additional context

NA

**Comment by ashutosh887** [comment]
@prashant-shahi I would love to work on this!

**Comment by prashant-shahi** [comment]
@ashutosh887 Any PR contributions to optimize the build time would be greatly appreciated.

**Comment by srikanthccv** [comment]
A good part of this process is slow because we use QEMU to emulate the arm64. Build the assets outside and copy them.
