### ISSUE TITLE
Users with `viewer` permissions see `free plan` even when the company is on `enterprise plan`

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#3416]
Even when the company is on enterprise plan the users with `viewer` permissions see:
- Try SigNoz Cloud banner
- Free Plan under SigNoz Status

![Screenshot 2023-08-23 at 3 21 51 PM](https://github.com/SigNoz/signoz/assets/12460410/cf10a46e-b89f-4652-807b-ae60c84431d3)

**Comment by prashant-shahi** [comment]
This is happening for all non-admins i.e. `Viewer` and `Editor`.

`GET /api/v1/licenses` should be open to all users (except Public).

Not sure if the full body should there in response. I advice to go with `true`/`false` instead. And create another API call to fetch the details of the enterprise license like key, validity, etc.

_Screenshot:_

<img width="844" alt="Screenshot 1" src="https://github.com/SigNoz/signoz/assets/11138844/1273b7ea-b6bc-41a0-88ec-09dc960188a8">

**Comment by makeavish** [comment]
This is fixed in latest release as we migrated to `/v2/licenses` which is accessible by VIEWER.
