### ISSUE TITLE
The page "services/goApp?tab=OVER_METRICS" is blank

### ISSUE THREAD

**Issue by nengc** [SigNoz/signoz#3442]
## Bug description
When I open the `services/goApp?tab=OVER_METRICS` , if the browser is full screen, the page will blank. And when i open the page with smaller browser size, it will work. And when i scroll the page, it will blank agin.

And the tab `services/goApp?tab=DB_CALL_METRICS` can be opened.

<img width="1423" alt="image" src="https://github.com/SigNoz/signoz/assets/19792047/89ff972f-4117-40a0-9484-d4d24a8b8cb3">

<img width="1390" alt="image" src="https://github.com/SigNoz/signoz/assets/19792047/0fccdc0d-e58e-450e-8e7b-646762c0a134">

<img width="1425" alt="image" src="https://github.com/SigNoz/signoz/assets/19792047/3d6d589a-8ff7-4981-9b08-c16e33fb7083">

<img width="1427" alt="image" src="https://github.com/SigNoz/signoz/assets/19792047/a48b5907-97f4-4284-9efa-fce0878d859c">

## How to reproduce

1. Use the `https://github.com/SigNoz/sample-golang-app` repo to generate data
2. Open the page `/services/goApp?tab=OVER_METRICS` with the full browser size, it will blank
3. Set the browser size smaller and refresh. The page can opened. But after i scroll the page, it will blank agin

## Version information 
* **Signoz version**: v0.27.0
* **Browser version**: Version 116.0.5845.110 (Official Build) (x86_64)
* **Your OS and version**: MacOS 12.6.8
* **Your CPU Architecture**(ARM/Intel):  Intel

**Comment by srikanthccv** [comment]
This is not reproducible for me. It works all the time.

**Comment by palashgdev** [comment]
@nengc can you share the response that the client is receiving

**Comment by nengc** [comment]
Hi @palashgdev, there is no response. Seems the frontend params error.
<img width="1373" alt="image" src="https://github.com/SigNoz/signoz/assets/19792047/e83a01d9-e5ec-4faa-996d-299545521330">

**Comment by nengc** [comment]
Hi @srikanthccv , I only use the https://github.com/SigNoz/sample-golang-app repo. And the config is the same as the example.

**Comment by palashgdev** [comment]
> Hi @palashgdev, there is no response. Seems the frontend params error.
> 
> <img width="1373" alt="image" src="https://github.com/SigNoz/signoz/assets/19792047/e83a01d9-e5ec-4faa-996d-299545521330">
> 
> 

would it possible to share the pr for same

**Comment by nengc** [comment]
> > Hi @palashgdev, there is no response. Seems the frontend params error.
> > <img alt="image" width="1373" src="https://user-images.githubusercontent.com/19792047/265655425-e83a01d9-e5ec-4faa-996d-299545521330.png">
> 
> would it possible to share the pr for same

I set up the SigNoz for testing. And not very familiar with the code. Seems the “Error Percentage” went wrong.

**Comment by luciantimar** [comment]
Hi,
The issue is reproduced in 0.30.0 , 0.31.1. 
![image](https://github.com/SigNoz/signoz/assets/7078152/805becd0-6204-4dc7-a40e-b9bd241db5a0)
The error is from React Query, but I cannot figure out which query is the culprit and what is wrong with that query
![image](https://github.com/SigNoz/signoz/assets/7078152/294f68db-ce04-4799-82dd-c4cc39a925ba)

Best reagrds,
Lucian

**Comment by luciantimar** [comment]
I found out that culprit is "le' property, 
![image](https://github.com/SigNoz/signoz/assets/7078152/48877041-c5ff-41cf-9b6a-eba417e21107)

Why I am not getting any values , i don't know but temporary I have set metricsBucket to an empty array if 'dat.le' is null, and the page is dsiplayed.

```
<ApDexMetrics
			handleGraphClick={handleGraphClick}
			delta={data?.data.delta}
			metricsBuckets={data?.data.le||[]}
			onDragSelect={onDragSelect}
			topLevelOperationsRoute={topLevelOperationsRoute}
			tagFilterItems={tagFilterItems}
			thresholdValue={thresholdValue}
		/>
```
