### ISSUE TITLE
After upgrading to v0.28.0, the service details page becomes a white page.

### ISSUE THREAD

**Issue by lilos** [SigNoz/signoz#3483]
## Bug description
![image](https://github.com/SigNoz/signoz/assets/40874554/a3d8f829-5ab0-4129-b0cf-2a787ed6d757)
![image](https://github.com/SigNoz/signoz/assets/40874554/a5c6c560-9a48-47a5-8af0-d5cebe62f374)

## Version information 
signoz v0.28.0
k8s helm install

**Comment by srikanthccv** [comment]
Same as https://github.com/SigNoz/signoz/issues/3442, @palashgdev please check.

**Comment by lilos** [comment]
Hello, have you found the problem?

**Comment by lilos** [comment]
v0.29.1 has returned to normal
