### ISSUE TITLE
Saving a panel should not cause all the other panels to re-render 

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#3570]
Saving a panel causes all the other panels to re-render. This is not needed. The re-render should only happen when the auto-refresh time is hit or a user reloads using the reload-icon

**Comment by palashgdev** [comment]
@YounixM if we navigate back from edit widget page to widget page... on the componentmount api call is made then how to solve this one ?

**Comment by YounixM** [comment]
As this is a route change, the page container will be mounted / unmounted and API calls are made to get the required data for the panel.  If we don't want the other panels to re-render, the only option would be to open the edit view in the modal. 

We can avoid the API calls by caching the data before entering into edit mode, but the panels will still re-render as they will be mounted again.

**Comment by YounixM** [comment]
As it's not feasible without the UI flow update, closing this for now.
