### ISSUE TITLE
Introduce collapsable rows of panels

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#3571]
Today all the panels are at the same level of grouping. We should have a grouping mechanism for panels. Eg, in an argocd dashboard each of the below components should have their panels logically grouped
- API Controller metrics
- server metrics
- repo metrics 

Having a collapsable set of panels will also help in reducing API calls on browsing. Unless the row is uncollapsed, the API calls for the panels should not be made. By default, the 1st row can be uncollapsed

**Comment by srikanthccv** [comment]
Perhaps it's time to prioritize this (again). I have been creating integration assets and it would be really good to have this capability.

**Comment by Vikrant2520** [comment]
the change for this has been merged. Closing the issue.
