### ISSUE TITLE
LOGS [FE] Operator suggestion Logic

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#3585]
Let's say If I type `email ex`

Currently it shown suggestions
```
email ex

email ex =

email ex !=

email ex contains....
```

Instead it should be
```
email ex

email exists
```

This is with the condition that keys in logs won't contain space i.e the key `email` will never contain space.

**Comment by siddhant1** [comment]
I can try picking this up

**Comment by srikanthccv** [comment]
I would suggest picking an issue that has the label good-first-issue or help-wanted. This one is not straightforward for a person unfamiliar with the codebase.

**Comment by makeavish** [comment]
Similar to https://github.com/SigNoz/signoz/issues/3478

**Comment by Vikrant2520** [comment]
@YounixM i can pick this up , please assign this to me , Thanks!
