### ISSUE TITLE
query-builder: support for aggregator query of aggregator query

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/signoz#3632]
Using aggregator function over another aggregator function.

Example CPU usage query:

```
100 * avg(1 - rate(system_cpu_time{state="idle"}[5m])) by (k8s_node_name)
```

**Comment by srikanthccv** [comment]
This is done and available under /v4/query_range, the aggregator of the aggregator is essentially the same as the s ability to choose time and space aggregation.
