### ISSUE TITLE
Upgrade otel-collector and otel-collector-contrib versions in fork 

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#364]
Current otel-collector fork from SigNoz is from v0.26

There are some new features added in the newer versions of otel collector which would be helpful to have

Specifically -

`4318` was introduced as default port in `v0.32.0`
setting CORS headers was added in `v0.30.0`

**Comment by ankitnayan** [comment]
upgraded to `v0.43.0`

**Comment by pranay01** [comment]
@ankitnayan Where was the PR for this? In otel contrib repo? Would be good to link it here for future reference

**Comment by ankitnayan** [comment]
@pranay01  It was a complete upgrade and added a new branch at https://github.com/SigNoz/opentelemetry-collector-contrib/tree/signoz-v0.43.0

We need to define process to maintain otel-collector-contrib going further.

**Comment by pranay01** [comment]
ok
