### ISSUE TITLE
Bug(FE): Cancel Token

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#366]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Right now there is no cancel token passed in the api which will help to cancel the request 

## Expected behavior

Api should get cancel probably this will help when the component is unmounted the api call 

## Additional context
https://github.com/axios/axios#cancellation

**Comment by sharathkumar55** [comment]
Hi @palashgdev can i work on this issue to start my open source contribution
