### ISSUE TITLE
List type panel for logs & traces in dashboard

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#3661]
There is no option to view loglines in the panels today. There should be an option to view logs as listview and table view in the panels

**Comment by ankitnayan** [comment]
@nityanandagohain it is not possible to view loglines in `table view` panel type in the dashboards today, right? I see a necessary aggregation option that must be chosen even in table view

**Comment by nityanandagohain** [comment]
Yeah since we considered table view to be tabular representation of aggregated values

**Comment by pranay01** [comment]
Had a user call today who needed this feature as well

**Comment by GeekBoySupreme** [comment]
Find the designs [here](https://www.figma.com/file/lE5BDDuulXuGnqvB5GRk1V/SigNoz-OSS---v2-Designs?type=design&node-id=7308%3A1695&mode=design&t=aZ5vm2KbQV4dkPuK-1)

**Comment by nityanandagohain** [comment]
Left, comments please have a look.

**Comment by pranay01** [comment]
PRD notion doc - https://www.notion.so/signoz/PRD-List-View-for-Dashboards-2bc2ad163b2242f58353aabbeb69bc4d?pvs=4
