### ISSUE TITLE
Inconsistency in Graph Legend Color

### ISSUE THREAD

**Issue by Calm-Rock** [SigNoz/signoz#3663]
## Bug description

Please check this [video](https://www.loom.com/share/e9365c3d45304412a52cd919e665d516?sid=f910f1a2-f141-49ce-9f8b-c25d32421064) for reference.

## Expected behavior
Ideally since a user might view the dashboards and charts on a frequent basis so the colors of a particular legend say p90,p99.p50 values should remain the same to avoid any confusion.

## How to reproduce

Checkout the video for this.

## Version information 
* **Signoz version**: Cloud
* **Browser version**:
* **Your OS and version**: MacOS; Ventura
* **Your CPU Architecture**(ARM/Intel):  ARM

**Comment by palashgdev** [comment]
logic for colour assignment happens in a round-robin fashion @Rajat-Dabade can you check when we open the full view we reflect the same colours

**Comment by Rajat-Dabade** [comment]
@palashgdev will look into it.

**Comment by makeavish** [comment]
Assign different colors to different legends in charts.
Here there are two legends but both have same color assigned which makes it confusing
![image](https://github.com/SigNoz/signoz/assets/9512100/cd57cde8-2585-468d-8710-35bf8481c661)

**Comment by YounixM** [comment]
This is addressed now. We introduced a hash function to generate legend color based on name.
