### ISSUE TITLE
Feature: Ability to copy queries in  dashboard panels.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#3664]
A panel might contain n queries. I might want to create copy one previous query and then make some slight changes. As of now that's not possible but will be a helpful feature. cc @ankitnayan

**Comment by pranay01** [comment]
@nityanandagohain When you say copy a query, do you mean copying the queries made from filters in the query builder?

**Comment by nityanandagohain** [comment]
Yeah @pranay01 , lets say I have created n filters in query A.

I want to create query B with the same filters as A but a different aggreate attribute or group BY, in that case I have to type each filter again. This gets difficults when number of queries and number of filter gets higher.

**Comment by Vikrant2520** [comment]
As discussed with @nityanandagohain this needs UX inputs , so will pick up once finalised.

**Comment by GeekBoySupreme** [comment]
> I want to create query B with the same filters as A but a different aggreate attribute or group BY,
The new designs for Query Builder already contain a control to duplicate a query -
![image](https://github.com/SigNoz/signoz/assets/15321738/cf201d30-8e4c-4ec4-9f73-5286503782b3)

**Comment by srikanthccv** [comment]
I agree with @raj-k-singh, a small icon that is visible by default is better.

**Comment by YounixM** [comment]
<img width="2559" alt="Screenshot 2024-03-12 at 1 04 51 PM" src="https://github.com/SigNoz/signoz/assets/3520897/cb7527dd-f666-4a7d-b47b-a4f4dd8c1762">

We can clone the queries now.
