### ISSUE TITLE
LOGS: [FE] Dot support in frontend

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#3681]
* if attribute name is `test.key` i.e it contains dot then only `test` is displayed in detail page
* filtering from the detail page also doesn't work for these attributes.

REF https://github.com/SigNoz/signoz/issues/3553

**Comment by nityanandagohain** [comment]
@YounixM  can we prioritise this cc @ankitnayan

**Comment by YounixM** [comment]
Assgined to @raj-k-singh as he will be picking this.
