### ISSUE TITLE
Incorrect error message in Latency filter in trace page 

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#369]
Even when min value is less than max value, the error message on min value is not removed

Expected behavior : If min value is less than max value, then no error message should be shown
![min-max](https://user-images.githubusercontent.com/504541/142002217-6a48246c-a573-4a5b-b44b-8ddac1d1d4a6.png)

**Comment by aggmoulik** [comment]
Hey @pranay01 I am picking up this issue.

**Comment by pranay01** [comment]
cool, assigning this to you @aggmoulik  - feel free to ask any questions on the expected behavior

**Comment by palash-signoz** [comment]
Closing as this is not in the new UI
