### ISSUE TITLE
Options on selecting Errors, Status in custom trace aggregation page don't make sense

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#370]
If Error, status is selected in trace visualisation page - the option shown don't make sense
![Screenshot 2021-11-16 at 7 31 50 PM](https://user-images.githubusercontent.com/504541/142002512-ed5f720a-3961-4994-89f7-ff306642d5f9.png)

**Comment by makeavish** [comment]
Stale issue. Closing it.
