### ISSUE TITLE
IN chips should be created without pressing enter

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#3709]
When using IN operator in filter user has to press enter key to complete filter. Rather we can use mouse movement to complete filter.

**Comment by palashgdev** [comment]
@makeavish We don't know when data is completed for the user so Enter is the place to know user has completed entering the data

**Comment by srikanthccv** [comment]
This is not just for `IN` but should be applied to other operators also. When the focus moves out of the search box we should complete the last chip.
<img width="1286" alt="Screenshot 2024-01-04 at 12 36 59 PM" src="https://github.com/SigNoz/signoz/assets/22846633/e4317016-b7ab-4711-8f7d-e043bdb8c5a6">
