### ISSUE TITLE
Show time range dropdown option in alert creation page 

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#3721]
## Bug description

It's unclear to users what the time range of the preview chart is on the alert creation page. The global time range dropdown is present on every page except alerts. This is confusing and unclear for users.

**Comment by ankitnayan** [comment]
Just enabling the global time range dropdown should be fine? 
The `during the last` param in the alerts configuration can be treated independently?

**Comment by srikanthccv** [comment]
Yes, we should enable the global time range and treat the query over the last X minutes independently.
