### ISSUE TITLE
LOGS[FE]: Rendering escaped characacters

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#3723]
The escaped characters are not rendered properly in detail page.

Also if the line is long then the rendering(indentation) can be better instead of something like this 
![image](https://github.com/SigNoz/signoz/assets/26831659/f2e2bbf7-65fd-4a1d-b0c0-e3e1b432c20d)

**Comment by YounixM** [comment]
@nityanandagohain : As these are handled now, can we close this?

**Comment by YounixM** [comment]
As discussed on call, addressed the mentioned issues. Closing this.
