### ISSUE TITLE
LOGS [BE] : Check not empty string not working

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#3725]
LOGS QB, if there is an attribute then `key != ""` is not working as reported by @makeavish

**Comment by nityanandagohain** [comment]
So it's working but how to use it in the UI is not good. instead of `email != ''` the query looks like this `email !=  ` where there is an extra space
![image](https://github.com/SigNoz/signoz/assets/26831659/f32dd3a5-9958-4daa-a97f-b94e197c0f5d)
and it works @makeavish 


@pranay01 @GeekBoySupreme we will need better ux for this.

**Comment by makeavish** [comment]
closing in favor of https://github.com/SigNoz/signoz/issues/3762
