### ISSUE TITLE
Bug(FE): Remove time filter from settings page

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#374]
Currently settings page has a time filter component also. Though there is no use of the time filter component on settings page, as the items in settings page don't change on the basis of time selected.

Expected Behavior: Time filter component should be removed from the settings page

version: v0.4.4

![Image 17-11-2021 at 0 07](https://user-images.githubusercontent.com/504541/142045769-ed2451ca-e49a-44cd-8046-c539e61113c4.jpg)

**Comment by Mohmn** [comment]
can u plz assign this to me I want to work on my first pr at this weekend

**Comment by pranay01** [comment]
Sure - assigned it to you @Mohmn

**Comment by Mohmn** [comment]
![Screenshot from 2021-11-19 22-42-59](https://user-images.githubusercontent.com/37132584/142664902-767089dd-5f16-4154-825a-53d9be95e075.png)


**i believe this is what I had to do**

**Comment by pranay01** [comment]
Yeah, looks fine. But this should be removed only in the settings page and not in other pages. 
cc: @pal-sig if you have any inputs on this for @Mohmn

**Comment by Mohmn** [comment]
yep, I have removed time filter only from the settings page.
will create a  pr then
