### ISSUE TITLE
Add `createdBy`, `createdAt`, `updatedBy` and `updatedAt` fields in the alert list page

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#3740]
This helps in auditing the changes in alerts.

**Comment by ankitnayan** [comment]
**Since `API_KEY` is an org entity:**
For alerts created via `API_KEY` there should be an account associated with each API_KEY that shows up in the `createdBy` and `updatedBy` fields?

If `API_KEY` were in the scope of individual users, we could use the email of the user to show up in those fields

**Comment by ankitnayan** [comment]
`API_KEY` should ideally be specific to the user and the scopes should apply to them too. Default the `API_KEY`s of a user will have the scope of the user

**Comment by ankitnayan** [comment]
At SigNoz, we have `API_KEY` attached to a user so it should be fine to show the user or user + `API_KEY` name to show in the `createdBy`, `updatedBy` fields

**Comment by GeekBoySupreme** [comment]
Adding 4 fields to the table might be a stretch. 
There are 2 things we can do instead -
- Adding a widget of sort inside the specific alert, below the instructions (or above)
<img width="800" alt="image" src="https://github.com/SigNoz/signoz/assets/15321738/06c18f41-1e88-4cd8-be83-be8fd0247228">
- Adding a tooltip to the alert name in the table view mentioning `Last updated at <timestamp> by <name>` or `Created at <timestamp> by <name>`

**Comment by GeekBoySupreme** [comment]
Another way to edit and show things in the table itself might be this -
![image](https://github.com/SigNoz/signoz/assets/15321738/b047bb32-f668-4829-b902-ea8abe0effbc)

- Smaller column width for `Status` and `Severity`. 
- `Labels` collapsed to only show 3 labels and the rest are abstracted under a `+n` pill which opens a dropdown menu on clicking showing the rest of the labels.
- The actions column was removed and all the actions were listed under an ellipsis
- The avatar circle in the `Last updated` column can show the email on hover.
- The Last updated would be same as created when an alert is just created.

As an extra feature on top, we can simply add the gear with dropdown to toggle what columns are shown.

**Comment by ankitnayan** [comment]
> `Labels` collapsed to only show 3 labels and the rest are abstracted under a +n pill which opens a dropdown menu on clicking showing the rest of the labels.

We should show only those chips which fit in fixed % width for the column as the value of 1st/2nd chip can be very large (I have seen this go weird in current UI). Clicking on `+X` to show remaining on dropdown is good which will also suffer due to large texts. We should always put ellipsis and show full on hover in practice for such use cases where the text size can be huge.

> The avatar circle in the Last updated column can show the email on hover.
We have 4 fields to plan. We can show both `editedBy` and `editedAt` on hover of the avatar icon
1. CreatedBy
2. CreatedAt
3. EditedBy
4. EditedAt

**Comment by GeekBoySupreme** [comment]
> We should show only those chips which fit in fixed % width for the column as the value of 1st/2nd chip can be very large (I have seen this go weird in current UI). Clicking on +X to show remaining on dropdown is good which will also suffer due to large texts.

Yes, this should be a rule of thumb for the chips. Cap them to a character count and add trailing ellipsis.
I don;t mind adding a bunch of data to the tooltip on the avatar.

**Comment by ankitnayan** [comment]
>I don;t mind adding a bunch of data to the tooltip on the avatar.

Is it a good idea to replace avator icon with something similar to `info` icon which will show all 4 values on hover?
