### ISSUE TITLE
Not clear what is the default retention period when user has not made any changes in retention setting page

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#378]
When a user lands on the settings page for the first time after installing SigNoz, the retention period for metrics and traces are shown as 0. It is not clear what does that mean?  

Are the metrics and traces not retained at all? What does that mean?

Expected Behavior: The retention page should show what is the default retention period, even when user reaches it for the first time
![Image 17-11-2021 at 12 02](https://user-images.githubusercontent.com/504541/142146981-bf74aa6c-e928-43ad-987f-fb01699174d0.jpg)

**Comment by pranay01** [comment]
Current metrics and traces are set with infinite retention. Make this  7days for metrics and 2 days for traces by default

**Comment by pal-sig** [comment]
default response is from the server .. so i think backend should this case

**Comment by pranay01** [comment]
Message to be dispalyed if either Metrics or Traces retention period is not set yet
![retention-initial](https://user-images.githubusercontent.com/504541/143024917-e200de1a-f493-434b-a136-221b4d08245f.png)

**Comment by pranay01** [comment]
Message when neither Metrics or Traces is set yet.

_Retention Period not set for Metrics or Traces yet. Please set by choosing below_

**Comment by ankitnayan** [comment]
> default response is from the server .. so I think the backend should handle this case
when there is no retention period set, the backend gives -1 as the response of metrics and traces resp. Seems like a correct response from the backend. The frontend needs to check for -1 in metrics and traces resp and show the corresponding msg.

**Comment by pranay01** [comment]
@ankitnayan Have discussed this with @pal-sig on a possible solution. Not a dependency on backend as of now

**Comment by ankitnayan** [comment]
@pranay01 what should the textbox display when retention is not set in either of the cases? 
Currently, it displays `0`, should it be `-1` which backend sends or shall we put `NA` which has to be replaced by a number as user inputs value.

**Comment by pranay01** [comment]
I think `0` is fine - as we already show the yellow message in the top.

Case 1: If only metrics is not set

Retention Period not set for Metrics yet. Please set by choosing below

Case 2: If only traces is not set

Retention Period not set for Traces yet. Please set by choosing below

Case 3: If neither metrics nor traces is set

Retention Period not set for Metrics or Traces yet. Please set by choosing below
