### ISSUE TITLE
FE: Timerange is not working on URL

### ISSUE THREAD

**Issue by cgomezluengo** [SigNoz/signoz#3790]
## Bug description

I am trying to share logs from a specified timerange and filters.

Creating a filter by k8s_namespace_name and set the timerange in a custom timerange.

I copy the URL and change the timerange that should be this part  timeRange=%7B%22start%22%3A1698147394000%2C%22end%22%3A1698233796000%2C%22 
that means **start** 1698147394000 and **end** 1698233796000

This still happening when I use the share button
![image](https://github.com/SigNoz/signoz/assets/5550020/847437d5-2980-4f26-b2db-51000f87ea20)

http://{URL}/logs-explorer?options=%7B%22selectColumns%22%3A%5B%5D%2C%22maxLines%22%3A2%2C%22format%22%3A%22list%22%7D&timeRange=%7B%22start%22%3A1698147394000%2C%22end%22%3A1698233796000%2C%22pageSize%22%3A100%7D&compositeQuery=%257B%2522queryType%2522%253A%2522builder%2522%252C%2522builder%2522%253A%257B%2522queryData%2522%253A%255B%257B%2522dataSource%2522%253A%2522logs%2522%252C%2522queryName%2522%253A%2522A%2522%252C%2522aggregateOperator%2522%253A%2522noop%2522%252C%2522aggregateAttribute%2522%253A%257B%2522id%2522%253A%2522------false%2522%252C%2522dataType%2522%253A%2522%2522%252C%2522key%2522%253A%2522%2522%252C%2522isColumn%2522%253Afalse%252C%2522type%2522%253A%2522%2522%252C%2522isJSON%2522%253Afalse%257D%252C%2522filters%2522%253A%257B%2522items%2522%253A%255B%255D%252C%2522op%2522%253A%2522AND%2522%257D%252C%2522expression%2522%253A%2522A%2522%252C%2522disabled%2522%253Afalse%252C%2522having%2522%253A%255B%255D%252C%2522stepInterval%2522%253A240%252C%2522limit%2522%253Anull%252C%2522orderBy%2522%253A%255B%257B%2522columnName%2522%253A%2522timestamp%2522%252C%2522order%2522%253A%2522desc%2522%257D%255D%252C%2522groupBy%2522%253A%255B%255D%252C%2522legend%2522%253A%2522%2522%252C%2522reduceTo%2522%253A%2522sum%2522%257D%255D%252C%2522queryFormulas%2522%253A%255B%255D%257D%252C%2522promql%2522%253A%255B%257B%2522name%2522%253A%2522A%2522%252C%2522query%2522%253A%2522%2522%252C%2522legend%2522%253A%2522%2522%252C%2522disabled%2522%253Afalse%257D%255D%252C%2522clickhouse_sql%2522%253A%255B%257B%2522name%2522%253A%2522A%2522%252C%2522legend%2522%253A%2522%2522%252C%2522disabled%2522%253Afalse%252C%2522query%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%25224cd6b481-fbf0-40ba-b869-9aa602b70462%2522%257D

But when I enter with another browser, I still see the las 15 mins (the default)
![image](https://github.com/SigNoz/signoz/assets/5550020/083cefee-0b25-4f38-bb2e-4055e9b865ac)

## Expected behavior

When share the link with the timerange setted. the logs that should be displayed, should be within that timerange

## How to reproduce

1. Go to Front end and log in
2. Filter logs by something (in this case by k8s_namespace_name) and put a custom timerange 
3. Copy the url or click on the share button.
4. Enter with that url, you will see the last 15 mins instead the custom timerange.

## Version information 
* **Signoz version**:
* FE: 0.32.0
* **Browser version**:
* Chrome Versión 118.0.5993.88 (Build oficial) (64 bits)
* **Your OS and version**:
* Ubuntu 22.04.3 LTS

## Additional context

I am trying to put SigNoz on a Kubernetes Cluster and record logs from Cluster that are deploying on CI/CD. 
And I need to create a link so that the devs can see the logs that SigNoz collects from that particular cluster.

**Comment by nityanandagohain** [comment]
Thanks for reporting the issue. I tried to replicate the issue. The time range seems to copied correctly for me, just that the log line is not visible sometime.

**Comment by cgomezluengo** [comment]
> Thanks for reporting the issue. I tried to replicate the issue. The time range seems to copied correctly for me, just that the log line is not visible sometime.

Did you try with another user ?

**Comment by nityanandagohain** [comment]
Right, here are the issues.
* While sharing link the timerange doesn't work when the link is used by a different user.
* When sharing link of a log line after scrolling n times, it doesn't work.

**Comment by YounixM** [comment]
@Vikrant2520: Please look into this issue.
