### ISSUE TITLE
Too many API calls for variables are done

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#3803]
https://www.loom.com/share/03bfc2c6729c4aca8623a66e7b4bb6bd?sid=0de75101-075e-4ab7-98d5-e4a72bea24dd

**Comment by srikanthccv** [comment]
@YounixM I believe your changes here https://github.com/SigNoz/signoz/pull/4010 improved this a lot. Please close if there are no further improvements to be made.
