### ISSUE TITLE
Placeholders for filter traces input boxes

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#381]
## Is your feature request related to a problem?
Yes, currently if you go to `trace` tab, the inpux boxes under `Filter traces` has no hint/label text to show the user what they are supposed to do with it.

## Describe the solution you'd like
It would be good to have placeholder texts in each input box so that a first time user has a cue of what capabilities does `Filter Traces` has. 

My suggestions:
1st box: `services`
2nd box: `operations`

Not sure about the 3rd box.

## Additional context
![image](https://user-images.githubusercontent.com/83692067/142246278-ace413a8-fdbe-42de-8313-416b324c76f6.png)

**Loom Video**
https://www.loom.com/share/9f51c72a0e0c4078b9eeba6b18b54bf8

**Comment by friilancer** [comment]
Can I work on this?

**Comment by palash-signoz** [comment]
Closing as this is not in the new UI
