### ISSUE TITLE
[FE]: React Grid layout handling in the dashboard 

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#3819]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Handle `empty` and duplicate i in the react layout lib

**Comment by srikanthccv** [comment]
Other cases mentioned here https://github.com/SigNoz/signoz/issues/3169

**Comment by palashgdev** [comment]
fixed in #3830
