### ISSUE TITLE
Incorrect localhost as source URL in alerts

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#3828]
## Bug description

The source URL was set to localhost:3301 for alerts created on monitor cloud instances. The expected URL shouldn't be localhost but the whole correct domain of the cloud instance with stringified alert json.

I couldn't reproduce this. The source is set on the client side; there was nowhere in the backend to debug it. But I will keep it open to see if any other users faced this and also look at the client-side code.

**Comment by srikanthccv** [comment]
I couldn't reproduce this. Keeping it open for some time to see if others face it.

**Comment by prashant-shahi** [comment]
@srikanthccv I have seen this issue in StagingApp when users had created it with local SigNoz FE pointed at StagingApp backend.

**Comment by srikanthccv** [comment]
Not reproducible.
