### ISSUE TITLE
Option to interpret No Data as zero data

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#3829]
## Bug description

We show "No Data", where the query returns nothing, which usually happens when no samples are received for the duration. Users have use cases where the absence of data is the same as zero for them. The desired output should be configurable by user case by case.

**Comment by makeavish** [comment]
Is this issue related to https://github.com/SigNoz/signoz/issues/1463?

**Comment by srikanthccv** [comment]
Loosely related but primarily independent.

**Comment by srikanthccv** [comment]
This is very common request: https://signoz-team.slack.com/archives/C05GQNXL3FG/p1699298851398549?thread_ts=1699298774.138579&cid=C05GQNXL3FG

**Comment by srikanthccv** [comment]
This is done
