### ISSUE TITLE
Ordering of columns in clickhouse query in table view of dashboards

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#3840]
ordering of columns is not respected in table view of dashboards when writing a clickhouse query

**Comment by palashgdev** [comment]
@ankitnayan can you share loom video for same ?

**Comment by vikrantgupta25** [comment]
This has been taken care of here -> https://github.com/SigNoz/signoz/pull/5041 

https://github.com/SigNoz/signoz/assets/54737045/f7c7aa52-7967-47aa-952f-07d5758a2c82
