### ISSUE TITLE
Allow using {{start_timestamp}} and {{end_timestamp}} in dashboard variables when using clickhouse query

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#3841]
Support for different templates for using timestamps in metrics, traces and logs.
https://signoz.io/docs/tutorial/writing-clickhouse-queries-in-dashboard/

**Comment by srikanthccv** [comment]
This should already be supported 

ClickHouse queries - https://github.com/SigNoz/signoz/blob/4ef973ceb6fb3cafea35ab220242ea2d4090dd41/pkg/query-service/app/parser.go#L1045
PromQL queries - https://github.com/SigNoz/signoz/blob/4ef973ceb6fb3cafea35ab220242ea2d4090dd41/pkg/query-service/app/parser.go#L1069

**Comment by srikanthccv** [comment]
This is already supported; hence closing.
