### ISSUE TITLE
Make the `Tags` column in triggered alerts page behave same as the alerts list page?

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#3871]
The current view

![Screenshot 2023-11-01 at 11 04 20 PM](https://github.com/SigNoz/signoz/assets/12460410/9b54789f-fbe0-49cb-bfe9-03805cab7a25)

**Comment by joemiltonm** [comment]
Hi,
I've made changes to fix this issue and have created a PR, please review it. 
(https://github.com/SigNoz/signoz/pull/3873)

**Comment by ankitnayan** [comment]
fixed by https://github.com/SigNoz/signoz/pull/3873
