### ISSUE TITLE
[FE] History tab on license page

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#3892]
The History tab line is misaligned.

<img width="404" alt="Screenshot 2023-11-03 at 16 18 37" src="https://github.com/SigNoz/signoz/assets/9512100/48f35f43-91f8-4758-843d-f85242a13047">

**Comment by Abhishek329** [comment]
@palashgdev I'm interested in resolving this issue. Please feel free to assign it to me

**Comment by palashgdev** [comment]
fixed via https://github.com/SigNoz/signoz/pull/4006
