### ISSUE TITLE
Should we use `topK` clickhouse function instead of order by and limit as it seems topK is frequently used

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#3900]
https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/topk

**Comment by srikanthccv** [comment]
It doesn't help, `topK` gives the most frequently appeared value (ex: top 10 ages among a population sample etc...).

```sql
SELECT topK(5)(number)
FROM
(
    SELECT arrayJoin([1, 1, 2, 3, 4, 4, 5, 6, 7, 8, 8, 8, 9, 10, 11, 12]) AS number
)

Query id: b4bcbc91-b057-4e01-8d05-8f7c227925f9

┌─topK(5)(number)─┐
│ [8,1,4,2,3]     │
└─────────────────┘

1 row in set. Elapsed: 0.029 sec.
```

**Comment by srikanthccv** [comment]
I am going to close this since the topk is based on the frequency of the value and has no relation to order by limit which works on the actual value.
