### ISSUE TITLE
Lookback delta discrepancy b/w RangeQuery and InstantQuery for promql

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#3917]
## Bug description

Metrics that are reported with some delay (common on AWS) require an offset in the query to work. For range queries, there is an additional look-back delta of 5 minutes which doesn't exist for alerts (since it uses Instant query).

**Comment by ankitnayan** [comment]
> For range queries, there is an additional look-back delta of 5 minutes

This is not clear. Please explain more

**Comment by srikanthccv** [comment]
That description is not fully correct. Today PromQL alerts run an instant query for each evaluation interval. The instant selector uses the value from the most recent sample(s). The maximum lookback period to fetch this recent sample is (now-5min, now); there can be more but it will use the latest one. The range query is an instant query at each step interval. 

The main issue here is, that metrics from AWS arrive late, commonly 10m late. Since the query service uses the instant query for alerts and AWS metrics arrive late there will never be an alert because of this. This is where the major issue is with what they see in UI and what happens in query service. When they visit the alert page, which uses a range query, they may see some data which makes them think the alert should trigger. The linked PR updates alerts to use the range query for eval window.

**Comment by ankitnayan** [comment]
thanks. This is much clear now
