### ISSUE TITLE
The page “/services/goApp?tab=OVER_METRICS” is blank again

### ISSUE THREAD

**Issue by nengc** [SigNoz/signoz#3923]
## Bug description

When I open the “/services/goApp?tab=OVER_METRICS”，before i scroll the page, everything is OK. But after i scrolled it, an error occurred, and the page became blank.

![image](https://github.com/SigNoz/signoz/assets/19792047/0f749944-41f9-4c8b-a294-4a7c9c5cae52)

![image](https://github.com/SigNoz/signoz/assets/19792047/c7a1a2ce-dddb-4962-b27d-ff107d5648a1)

![image](https://github.com/SigNoz/signoz/assets/19792047/881453bb-b435-4227-8e44-9337f60adb13)

![image](https://github.com/SigNoz/signoz/assets/19792047/3da7ddae-3f7c-4a56-bef6-673ddc5599f7)

## How to reproduce

1. Using the repo "https://github.com/SigNoz/sample-golang-app" to produce the data.
2. Open the page "/services/goApp?tab=OVER_METRICS".
3. Scroll the page.

## Version information 
* **Signoz version**: v0.33.1
* **Browser version**:119.0.6045.106
* **Your OS and version**:win11
* **Your CPU Architecture**(ARM/Intel): Intel

**Comment by palashgdev** [comment]
this is fixed with https://github.com/SigNoz/signoz/pull/3749 is available over develop... will released today with the patch version
