### ISSUE TITLE
Sorting of dashboard list should be preserved even after opening a dashboard and coming back

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#3938]
Currently, the sorting behavior is not maintained after a dashboard is opened and user comes back

https://www.loom.com/share/728ec188880043919e795f03049fc8a8?sid=75cea3c5-4b43-4245-b0c7-79a15410e977

**Comment by palashgdev** [comment]
@Rajat-Dabade can you reflect the url when we change the table filters

**Comment by keshavg2** [comment]
Hi, @pranay01 and @palashgdev Can I work on this issue?

**Comment by pranay01** [comment]
@YounixM is this issue open to be taken up by contributors?

**Comment by pranay01** [comment]
hey @keshavg2 - Feel free to work on the issue. Assigning it to you

**Comment by keshavg2** [comment]
Thanks @pranay01
