### ISSUE TITLE
Add `Test` button in new alert channel page 

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#395]
## Is your feature request related to a problem?

Currently there is now way to test if the alert channel is correctly configured unless an alert is actually fired.

## Describe the solution you'd like

Add Test button in the Create Alert Channel page which sends dummy message to configured alert channel so that user can confirm that the channel is correctly configured

## Additional context

Design - 
![Content](https://user-images.githubusercontent.com/504541/142820304-ff26ac45-1308-487d-b73d-266f2378b512.png)

**Comment by ankitnayan** [comment]
https://github.com/SigNoz/signoz/pull/994
https://github.com/SigNoz/signoz/pull/993
