### ISSUE TITLE
FE: dashboard id api giving 404 poping up in the detail page everywhere

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#3958]
this api request which keeps piping everywhere... we need to add the check to disable the api call
when there is no dashboardId

<img width="1792" alt="Screenshot 2023-11-14 at 1 53 48 PM" src="https://github.com/SigNoz/signoz/assets/88981777/d63fd209-6232-4028-969f-c468c0f453b2">

**Comment by YounixM** [comment]
@Vikrant2520: You can pick this.

**Comment by Vikrant2520** [comment]
This PR resolves :- https://github.com/SigNoz/signoz/pull/4066

**Comment by Vikrant2520** [comment]
PR for the issue has been merged CC :- @YounixM
