### ISSUE TITLE
Exception type seems abnormal

### ISSUE THREAD

**Issue by nengc** [SigNoz/signoz#3986]
## Bug description

I set the exception type in the span, but it is not work. The exception type in signoz always "*errors.errorstring"

<img width="960" alt="image" src="https://github.com/SigNoz/signoz/assets/19792047/190b7787-2048-4f9f-b14b-c05d5dfb5942">

<img width="960" alt="image" src="https://github.com/SigNoz/signoz/assets/19792047/60e9269a-3ce9-4591-9064-c06f97abc6b7">

<img width="960" alt="image" src="https://github.com/SigNoz/signoz/assets/19792047/02b29c10-bf26-4d54-9f35-203b883d49b8">

## How to reproduce

1.
2.
3.

## Version information 
* **Signoz version**: develop 9333fdc
* **Browser version**:
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel):

**Comment by srikanthccv** [comment]
The `RecordError` of SDK overrides your option with `semconv.ExceptionType(typeStr(err))` https://github.com/open-telemetry/opentelemetry-go/blob/98b32a6c3a87fbee5d34c063b9096f416b250897/sdk/trace/span.go#L428-L450. Please create an issue in upstream repo if you think this is undesired.

**Comment by nengc** [comment]
Hi @srikanthccv , thanks! I will check it.
