### ISSUE TITLE
Ability to share a link to the widget in maximized View mode

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#3990]
## Is your feature request related to a problem?

There is no way to create a shareable link to the widget in "View" mode with maximized UI. 

## Describe the solution you'd like

A shareable link to the specific widget in "View" mode. 

## Describe alternatives you've considered

Open the widget in "Edit" mode and share the link.

## Additional context

https://signoz-team.slack.com/archives/C05GQNXL3FG/p1700238670737189

<img width="1228" alt="Screenshot 2023-11-18 at 7 05 04 AM" src="https://github.com/SigNoz/signoz/assets/22846633/ad058e16-f586-4379-946a-7c10ea0add5c">

The state is not retained in the URL hence not shareable.

**Comment by palashgdev** [comment]
Closed via https://github.com/SigNoz/signoz/pull/4052
