### ISSUE TITLE
Update the selected logs background to follow theme

### ISSUE THREAD

**Issue by YounixM** [SigNoz/signoz#3997]
## Bug description
Update the selected logs background to follow the theme

*Please describe.*  
  
![image](https://github.com/SigNoz/signoz/assets/3520897/bb470d99-ae5a-4341-b98b-fb443dab5cd1)
![image](https://github.com/SigNoz/signoz/assets/3520897/6394c4c3-467b-49cb-8efa-47e28d39d264)

## How to reproduce

1. Logs Explorer - List View - Copy link -> opened copied link in a new tab
2. The background color of the selected log isn't in line with the theme

**Comment by YounixM** [comment]
This is good @joemiltonm . Thanks

**Comment by Naresh-kumar-Thodupunoori** [comment]
@makeavish is this still open ?
If yes, I would like to work on this

**Comment by makeavish** [comment]
This is fixed in latest version
