### ISSUE TITLE
Logs page display no logs in List view

### ISSUE THREAD

**Issue by luciantimar** [SigNoz/signoz#4028]
## Bug description

I have upgraded query service from 0.31.1 to 0.34 and now I am getting any logs and query service is returning the below error:

**Request sent from UI**

`{"start":1700642190000,"end":1700663790000,"step":60,"variables":{},"compositeQuery":{"queryType":"builder","panelType":"list","builderQueries":{"A":{"dataSource":"logs","queryName":"A","aggregateOperator":"noop","aggregateAttribute":{"id":"------false","dataType":"","key":"","isColumn":false,"type":"","isJSON":false},"filters":{"items":[],"op":"AND"},"expression":"A","disabled":false,"having":[],"stepInterval":60,"limit":null,"orderBy":[{"columnName":"timestamp","order":"desc"}],"groupBy":[],"legend":"","reduceTo":"sum","offset":0,"pageSize":100}}}}` 

**Response from query service**

`{
    "status": "error",
    "data": {
        "A": "SELECT timestamp, id, trace_id, span_id, trace_flags, severity_text, severity_number, body,CAST((attributes_string_key, attributes_string_value), 'Map(String, String)') as  attributes_string,CAST((attributes_int64_key, attributes_int64_value), 'Map(String, Int64)') as  attributes_int64,CAST((attributes_float64_key, attributes_float64_value), 'Map(String, Float64)') as  attributes_float64,CAST((attributes_bool_key, attributes_bool_value), 'Map(String, Bool)') as  attributes_bool,CAST((resources_string_key, resources_string_value), 'Map(String, String)') as resources_string from signoz_logs.distributed_logs where (timestamp \u003e= 1700642160000000000 AND timestamp \u003c= 1700663760000000000) order by timestamp desc LIMIT 100 OFFSET 0"
    },
    "errorType": "bad_data",
    "error": "encountered multiple errors: error in query-A: code: 47, message: Missing columns: 'attributes_bool_key' 'attributes_bool_value' while processing query: 'SELECT timestamp, id, trace_id, span_id, trace_flags, severity_text, severity_number, body, CAST((attributes_string_key, attributes_string_value), 'Map(String, String)') AS attributes_string, CAST((attributes_int64_key, attributes_int64_value), 'Map(String, Int64)') AS attributes_int64, CAST((attributes_float64_key, attributes_float64_value), 'Map(String, Float64)') AS attributes_float64, CAST((attributes_bool_key, attributes_bool_value), 'Map(String, Bool)') AS attributes_bool, CAST((resources_string_key, resources_string_value), 'Map(String, String)') AS resources_string FROM signoz_logs.distributed_logs WHERE (timestamp \u003e= 1700642160000000000) AND (timestamp \u003c= 1700663760000000000) ORDER BY timestamp DESC LIMIT 0, 100', required columns: 'trace_id' 'span_id' 'attributes_bool_value' 'timestamp' 'id' 'body' 'trace_flags' 'severity_number' 'attributes_int64_key' 'attributes_float64_value' 'resources_string_value' 'resources_string_key' 'severity_text' 'attributes_string_key' 'attributes_int64_value' 'attributes_string_value' 'attributes_float64_key' 'attributes_bool_key', maybe you meant: 'trace_id', 'span_id', 'attributes_int64_value', 'timestamp', 'id', 'body', 'trace_flags', 'severity_number', 'attributes_int64_key', 'attributes_float64_value', 'resources_string_value', 'resources_string_key', 'severity_text', 'attributes_string_key', 'attributes_string_value' or 'attributes_float64_key'"
}`

The upgrade was done just by changing the image version from 0.31.1 to 0.34.1 in deployment files.

## Version information 
* **0.34.1**:

Did I miss something on upgrade or should have to do any specific steps.

**Comment by nityanandagohain** [comment]
This was added recently, please check if it ran successfully 
https://github.com/SigNoz/signoz/blob/d9950d92237dd7db3935fdb37684e64db7273ca5/deploy/docker/clickhouse-setup/docker-compose.yaml#L217

**Comment by luciantimar** [comment]
It worked, 
Thank you for your fast response
