### ISSUE TITLE
Legend formatted in line chart are not scrollable 

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#4036]
How should one use the scrollable bar presented on this chart? It's not usable
<img width="291" alt="Screenshot 2023-11-22 at 11 17 38 PM" src="https://github.com/SigNoz/signoz/assets/22846633/eab1d5cc-7e54-45d4-9542-681cb1a45f97">

**Comment by makeavish** [comment]
Duplicate of https://github.com/SigNoz/signoz/issues/3898
