### ISSUE TITLE
Logs in Context: Showing X lines number doesn't change if more lines are shown

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#4067]
Small issues. The number X in `Showing X lines..` messages in logs in context feature should update if users selects `Show 10 more lines`

https://www.loom.com/share/e618c40d7acc4c828fd4061044f03c3e?sid=8d3a9280-59f4-45fe-8897-cf01bf2e946e

**Comment by subhajit20** [comment]
hey @pranay01 I would like to fix this.
could you assign it to me?

**Comment by YounixM** [comment]
@subhajit20: Assigned it to you.  Thanks for contributing.

**Comment by YounixM** [comment]
@subhajit20: Please share the PR once ready.

**Comment by subhajit20** [comment]
Already opened the pr
https://github.com/SigNoz/signoz/pull/4069

**Comment by vikrantgupta25** [comment]
the view for logs context has been updated in the latest designs. hence closing the issue as we do not utilise this view anymore
