### ISSUE TITLE
Editing View of Charts should be disabled in Lock mode

### ISSUE THREAD

**Issue by YounixM** [SigNoz/signoz#4075]
## Bug description

![image](https://github.com/SigNoz/signoz/assets/3520897/76148bd7-b0c1-4bf3-bead-22ddb0eaa7b0)

## Expected behavior
Editing View of Charts should be disabled in Lock mode

## How to reproduce
1.  Open a locked dashboard
2.  Click on the actions menu of the widget
3.  Click on View
4.  Users are allowed to select legends and save the view

**Comment by Vikrant2520** [comment]
Hey @YounixM i would like to pick this up, Thanks!
