### ISSUE TITLE
Warn before Save for updated queries that didn't "Stage & Run"

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#4087]
## Bug description

- Create a panel
- Select an aggregate operator
- Apply some filters
- Save the panel without running the query

## Expected behavior

- Either the last state should be saved or the user should be warned to run before saving.

**Comment by YounixM** [comment]
This is done ✅ . We show a confirm modal when the user has unsaved changes in the panel before discarding changes.
