### ISSUE TITLE
Cloned a disabled alert, the status is Ok and in options we get the enable option.

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#4110]
Cloned a disabled alert, the status is Ok and in options we get the enable option.

_Originally posted by @YounixM in https://github.com/SigNoz/signoz/issues/4082#issuecomment-1831289081_

**Comment by srikanthccv** [comment]
This is the main issue we are trying to fix and what I mentioned in the video here. When I tested it seemed working (the cloned disabled alert should be in disabled state). If this is not fixed I am not sure what is the PR doing. Let me test again.

**Comment by srikanthccv** [comment]
This is no longer an issue
