### ISSUE TITLE
Is there any way to decrease font size in logging viewer?

### ISSUE THREAD

**Issue by darklow** [SigNoz/signoz#4126]
For some reason logging font size is unproportionally large. Is there any way to decrease font size to fit more logs, or to override dashboard css in some official way? Thank you.

Here is the preview. Log font-size seems even larger than UI. I would decrease 1rem -> 0.75rem even: 
<img width="526" alt="image" src="https://github.com/SigNoz/signoz/assets/445304/d9f0fc38-4ea0-4028-9384-3326f8993da4">

**Comment by srikanthccv** [comment]
This is now available with "small" font size option
