### ISSUE TITLE
Color logs are supported partially, still missing in some views

### ISSUE THREAD

**Issue by darklow** [SigNoz/signoz#4139]
Colored logs are shown correctly in the list, however they are still shown 

In the log details we still see color prefixes and content is unreadable:
<img width="837" alt="image" src="https://github.com/SigNoz/signoz/assets/445304/1993e6a9-23a8-4fdb-ae87-5047c9570611">

Meanwhile in the list, everything is correct:
<img width="1230" alt="image" src="https://github.com/SigNoz/signoz/assets/445304/cb90e8f6-47d3-4555-8359-5129ea83efe2">

Related to https://github.com/SigNoz/signoz/issues/2082

**Comment by nityanandagohain** [comment]
@vikrantgupta25  please check if this is still relevant.

**Comment by vikrantgupta25** [comment]
yes @nityanandagohain this is still relevant, fixing this

**Comment by vikrantgupta25** [comment]
colored logs should be working in all the views now.
