### ISSUE TITLE
FE: Requests are not cancelled 

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#4147]
If I am in a dashboard and then the dashboard is still loading, if I reduce the timerange the previous requests are not cancelled from the frontend until response is received. Which hampers the newer requests.

Related: https://github.com/SigNoz/signoz/issues/366

**Comment by ankitnayan** [comment]
@nityanandagohain this is making the UI unusable. Is there a request timeout of 60s in-place till this is fixed from the frontend?

**Comment by nityanandagohain** [comment]
yes there is req timeout of 60 secs, but the issue is that, if there are 10-15 api calls which are running and new queries are fired then the newer calls also get's slow.

**Comment by YounixM** [comment]
@palashgdev: Closing https://github.com/SigNoz/signoz/issues/366. 4147 is being tracked in Kanban board
