### ISSUE TITLE
Persist state using URL in the alerts page

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#4153]
For the alerts dashboard page, can you please add URL params so it's easy to navigate and go back and forth while keeping the current selection?
It would also be nice to at least search based on `labels`, `alert name,` and `severity`

[Slack Message](https://signoz-team.slack.com/archives/C05AXQL92BT/p1701732093114649?thread_ts=1701732093.114649&cid=C05AXQL92BT)

**Comment by srikanthccv** [comment]
@Rajat-Dabade just checking if you had time to work on this. Let's complete it before you pick up any big tasks.

**Comment by Rajat-Dabade** [comment]
@srikanthccv On it.
