### ISSUE TITLE
Query name not visible for PromQL alerts in alerts page

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#4158]
https://www.loom.com/share/5deed8e397af45ee87f8e54c0701f30b?sid=83a6be66-c96d-4fce-9ede-26cf555b4597

**Comment by keshavg2** [comment]
Hi, @srikanthccv and @YounixM  Can I work on this issue?

**Comment by YounixM** [comment]
Sure @keshavg2 . Assigning the ticket to you.

**Comment by YounixM** [comment]
This is done ✅
