### ISSUE TITLE
Query edit doesn't send the query text to preview request

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#4174]
## Bug description

- Create/Edit the query
- Update the query
- Click on `Test Run Query`
- See the n/w tab for request payload
- `query` in the payload is sent as an empty string
<img width="1013" alt="Screenshot 2023-12-06 at 8 05 00 PM" src="https://github.com/SigNoz/signoz/assets/22846633/b2022b5c-5e36-48cf-a1b4-b3433357a02b">

**Comment by YounixM** [comment]
Fixed:  https://github.com/SigNoz/signoz/pull/4210
