### ISSUE TITLE
FE(Dashboard): no data text position 

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#4194]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

https://github.com/SigNoz/signoz/assets/88981777/59040f62-4ca8-4233-a699-f9de97122855

## Expected behavior

No Data should be in center position

**Comment by Rajat-Dabade** [comment]
Already addressed in https://github.com/SigNoz/signoz/pull/4144#issuecomment-1838201978

**Comment by palashgdev** [comment]
reopened as pr is open... marked the pr to close this issue
