### ISSUE TITLE
Reducing browser size causes API end point table to over flow

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#42]
Steps to reproduce
-----------
- Open Application detail page by clicking a service
- Reduce browser width size
- After some width size, the API endpoint table overflows

![Screenshot 2021-04-17 at 8 33 27 PM](https://user-images.githubusercontent.com/504541/115117470-52fe5600-9fbc-11eb-9b0c-ff4ba52a34ab.jpg)

**Comment by ankitnayan** [comment]
duplicate of #112
