### ISSUE TITLE
Feat(UI): Add webpack bundle analyser 

### ISSUE THREAD

**Issue by pal-sig** [SigNoz/signoz#421]
## Is your feature request related to a problem?

*Please describe.*
with BUNDLE_ANALYSER=true in the `.env` should start the bundle analyser

would be good if we can analyse both for development and production environment

**Comment by Anurag5086** [comment]
Can I pick up this issue?

**Comment by Anurag5086** [comment]
@pal-sig @pranay01 

> Can I pick up this issue?

**Comment by Anurag5086** [comment]
I have raised a PR, please assign this issue to me.

**Comment by pal-sig** [comment]
Closed solves via #503
