### ISSUE TITLE
Show checkbox options for dashboard variables

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#4218]
## Is your feature request related to a problem?

>It'd be nice if the drop down for variables had a checkbox. This would be useful for when I want to select all but one metric. I'd select All, then unselect the 1 I don't want selected. Currently with Signoz today, I have to go through and select every single variable I need.

**Comment by YounixM** [comment]
@Rajat-Dabade: What's the status of this task?

**Comment by SagarRajput-7** [comment]
Done under this PR - https://github.com/SigNoz/signoz/pull/5191

pending for review and merge

**Comment by srikanthccv** [comment]
@SagarRajput-7 The bug I mentioned here https://signoz-team.slack.com/archives/C02TJ466H8U/p1718194817205719?thread_ts=1718175690.454299&cid=C02TJ466H8U is still there and breaks the dashboard with a mix of single select and multi-select chained variables. It's best if you verify the changes yourself to avoid the back and forth. If you prefer communication on the GitHub issue/PR, I will be happy to do the same.

**Comment by SagarRajput-7** [comment]
Thanks, @srikanthccv - I will check and fix this.
