### ISSUE TITLE
docker compose setup fails due to clickhouse

### ISSUE THREAD

**Issue by nitin302** [SigNoz/signoz#4239]
## Bug description

*Please describe.*  
Tried to install signoz with docker compose - https://signoz.io/docs/install/docker/#install-signoz-using-docker-compose. It throws an error as below for Container signoz-clickhouse.

*If this affects the front-end, screenshots would be of great help.*  

## How to reproduce

1.
2.
3.

## Version information 
* **Signoz version**: 0.35.1
* **Browser version**: Version 120.0.6099.109 Google Chrome
* **Your OS and version**: MacOS 12.6.5
* **Your CPU Architecture**(ARM/Intel): ARM Apple Silicon

## Additional context

chown: /var/lib/clickhouse/.gitkeep: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile.go: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/.gitkeep: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile.go: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/.gitkeep: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile.go: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/.gitkeep: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile.go: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/.gitkeep: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile.go: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/.gitkeep: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile.go: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/.gitkeep: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile.go: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/.gitkeep: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile.go: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/.gitkeep: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile.go: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/.gitkeep: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile.go: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/.gitkeep: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile.go: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/.gitkeep: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile.go: Permission denied
chown: /var/lib/clickhouse/user_scripts/histogramQuantile: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/user_scripts: Permission denied
chown: /var/lib/clickhouse/: Permission denied
chown: /var/lib/clickhouse/: Permission denied

**Comment by nitin302** [comment]
any help please?

**Comment by prashant-shahi** [comment]
This usually happens when the permissions of ClickHouse data files are changed.

Can you make sure file permissions for `deploy/docker/clickhouse-setup/data` are permissive?

**Comment by nitin302** [comment]
I have given full permission.

```
cd docker/clickhouse-setup/data
ls -ls
total 0
0 drwxrwxrwx  2 user  staff  64 Dec 15 17:19 clickhouse
0 drwxrwxrwx  2 user  staff  64 Dec 15 17:21 zookeeper-1
```

Is there any command you'd like me to run?

**Comment by nitin302** [comment]
any more help @prashant-shahi ?

**Comment by nitin302** [comment]
I was able to resolve the issue. it was due to rancher-desktop:
https://github.com/rancher-sandbox/rancher-desktop/issues/1209#issuecomment-1370181132
