### ISSUE TITLE
query_range api failure

### ISSUE THREAD

**Issue by sati-max** [SigNoz/signoz#4270]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

query_range api in Logs -> Logs Explorer -> Query Builder fails when attribute you want to group by contains characters OUTSIDE this regex [a-zA-Z0-9_:]. I've seen this bug reporter previously here: https://github.com/SigNoz/signoz/issues/3019 and the related merge request that apparently fixes it here: https://github.com/SigNoz/signoz/pull/3023 but the commit that merged it (https://github.com/SigNoz/signoz/commit/2722538e82d683bc8e2b9f69b8205d1a93f0e106) does ONLY apply to Query Builder in Traces, the part that fixed Logs wasn't merged

## Expected behavior

Query Builder allows to group by attributes that contain characters outside of regex [a-zA-Z0-9_:]

## How to reproduce

1. Create a query in Query Builder where the attribute that will be group by contains characters outside of regex [a-zA-Z0-9_;] like -
2. The query fails
3. 

## Version information 
* **Signoz version**: 0.35.1
* **Browser version**: 
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel): 

#### *Thank you* for your bug report – we love squashing them!

**Comment by srikanthccv** [comment]
This is fixed. Please try https://github.com/SigNoz/signoz/releases/tag/v0.36.0-rc.1

**Comment by sati-max** [comment]
Thanks, I see that 0.36.0 is now a stable release. I'll update to it then.
