### ISSUE TITLE
Fill gaps option doesn't get saved when editing dashboard

### ISSUE THREAD

**Issue by sati-max** [SigNoz/signoz#4280]
Hello

## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

The "fill gaps" option while editing dashboard doesn't get saved: 
![image](https://github.com/SigNoz/signoz/assets/47517196/b4723335-8463-4ca9-8741-e25a4a9bf9a7)

If I set it to enabled, save dashboard, edit again - it's still set as disabled. While editing it works correctly, but the state is not being saved. 

Also in the YAML export it doesn't seem to by any sort of information about the state of fill gaps.

## Expected behavior
The Fill gaps option should be correctly saved.

## How to reproduce

1. Create dashboard
2. Edit dashboard
3. Set Fill gaps to enabled
4. Save
5. Go back = fill gaps is still disabled

## Version information 
* **Signoz version**: 0.35.1
* **Browser version**: Firefox (latest), Chrome (latest) - the same behaviour
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel): 

#### *Thank you* for your bug report – we love squashing them!

Cheers!

**Comment by srikanthccv** [comment]
@palashgdev, not persisting user selection makes the feature useless. Please look into this.

**Comment by b4s36t4** [comment]
if I can work on this, would love to raise the PR.
