### ISSUE TITLE
Check the inconsistant charts in logs

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#4314]
Check the inconsistant charts in logs

**Comment by nityanandagohain** [comment]
When the charts rendered is <= 6 hrs, the chart rendered has a proper spacing of 5 mins for the ingestion-tester. The step interval is `60` seconds

i.e 12:00, 12:05, 12:10 ....


But when the chart rendered is of 1 Day, the step interval is `240` seconds. So the ingestion graph gets a bit distorted.
12:10, 12:14. 12:18, 12:22 , 12:30 .... 


But for the same 1 Day query if I change the step interval to `300` seconds, the spacing gets correct.
10:25, 10:30, 10:35, 10:40



In 240 intervals since the data is getting ingested every 5 mins and the step is 240, there is no data in 12:26. So there appears an empty bar and this thing continues.

cc @ankitnayan

**Comment by ankitnayan** [comment]
I see... so things are fine. It's just due to aggregation interval that we have chosen? Is there a way to make this intuitive to the user? How does DD show this?
