### ISSUE TITLE
Log search is too slow if none of the selected fields are used for filtering

### ISSUE THREAD

**Issue by spsneo** [SigNoz/signoz#4315]
## Log search is too slow if none of the selected fields are used for filtering

If a team member forgets adding a filter on selected field, it ends up in long running query. 

## There should be a way to configure certain minimum filters on selected fields before searching log.

**Comment by ankitnayan** [comment]
It should not be too slow. What is the period of logs selected 15mins/30mins/6hrs? And what is the data ingestion rate?

**Comment by sid-rpf** [comment]
@ankitnayan This gets slow when the duration is in the range of 3days or above.

**Comment by spsneo** [comment]
@ankitnayan - this gets slow when the duration is beyond 3 days.

**Comment by ankitnayan** [comment]
@nityanandagohain is this expected?

**Comment by nityanandagohain** [comment]
Here is more context to this thread https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1703758888438039

Basically, he wants to restrict queries which don't have any selected field in the filter.


The search being slow also depends on various factors if the data range is 3 days
* Amount of granules scanned 
* Granularity of search
* Resources allocated.

**Comment by ankitnayan** [comment]
I don't understand. When there is no filter is specified and we have timestamp as the sorting key, should it matter if the range selected is 5 mins or 1 day or 1 week? We just show the latest say 100 loglines which should always be there in the latest granule. What am I missing?

>This can solved by having proper selected fields and projections in place and in some cases resources
The usecase of using the right filters or having a projection is not relevant to this issue where the user wants to just see the latest logs without any filters.
