### ISSUE TITLE
Service map date range filter

### ISSUE THREAD

**Issue by suiluj** [SigNoz/signoz#433]
## Is your feature request related to a problem?

I would like to see a service map for a specific date range.

## Describe the solution you'd like

The Service Map show a drop down menu to select 1 or 5 minutes.
Is it possible to add the custom date range? (the same as with the different views for traces or metrics)

**Comment by pranay01** [comment]
hey @suiluj What is the use case you have for adding custom date range? Would be helpful if you can specify in more detail? How long a time range you are looking for

**Comment by suiluj** [comment]
hi @pranay01 

here are some details:

In my case i had some traces stored which are a few days old. At the moment i do not record new trace data live. So the service map shows as empty because it only takes the last few minutes.

Another idea why a custom range is useful: You could compare chaning services behaviours. For example open one tab with service map before a specific date and one tab after (perhaps an update which changed services or updated new ones)

**Comment by pranay01** [comment]
Got it @suiluj 

Would love to know - what are you trying to achieve with service map for past time? Is it primary for comparison between 2 time stamps?

Currently we have limited this to last 1min and 5min as service map was designed primarily to act as indicator of current status of the service. Also, the page is heavy to compute for long time periods

**Comment by makeavish** [comment]
We have added date range filter for service map. 
Closing this.
