### ISSUE TITLE
The initial value service.instance.id is overwritten and displayed as an hex encoded string

### ISSUE THREAD

**Issue by nleclercq** [SigNoz/signoz#4338]
## Bug description

Despite the fact that we do explicitly set the “service.instance.id” to a given “name” (e.g., “sys/tg_test/1”) - when we create the opentelemetry::sdk::resource::ResourceAttributes - the Signoz backend displays it as a hex encoded string (e.g., 00d89a8c-a710-4174-8098-fa99921ccbed). 

## Expected behavior

We should retrieve the specified name in the Signoz backend.

## How to reproduce
In c++ 

```
opentelemetry::exporter::otlp::OtlpGrpcExporterOptions opts;
opts.endpoint = cfg.extract_grpc_host_port(cfg.collector_traces_endpoint);
opts.use_ssl_credentials = false;

auto exporter = opentelemetry::exporter::otlp::OtlpGrpcExporterFactory::Create(opts);

auto processor = opentelemetry::sdk::trace::SimpleSpanProcessorFactory::Create(std::move(exporter));

auto resource_attributes = opentelemetry::sdk::resource::ResourceAttributes{{"service.name", "TangoTest"},{"service.instance.id", "sys/tg_test/1"}};

auto resource = opentelemetry::sdk::resource::Resource::Create(resource_attributes);

auto provider = opentelemetry::sdk::trace::TracerProviderFactory::Create(std::move(processor), resource);
```

## Version information 
* **Signoz version**: 0.36.2
* **Browser version**: Safari 17.2.1 
* **Your OS and version**: macOS Sonoma 14.2.1 (23C71)
* **Your CPU Architecture**(ARM/Intel): ARM64 (Apple Silicon M1)

## Additional context

<img width="1565" alt="image" src="https://github.com/SigNoz/signoz/assets/19185982/51364792-b311-4b15-8047-e887c7a1d2b4">

**Comment by nleclercq** [comment]
I obtain the expected result with Jaeger. Let me double-check that however.

**Comment by nleclercq** [comment]
Note that the `service.instance.id`is not overwritten for logs.

**Comment by sharpSteff** [comment]
This is the commit in the otel-collector causing the issue => https://github.com/SigNoz/signoz-otel-collector/commit/d1dc659eae9eddf93c88bf567d4346f105601789

I think the changes in processor/signozspanmetricsprocessor/processor.go:751 causes the issue.
Instead of using the signozID ("signoz.collector.id")
`resourceAttr.PutStr(signozID, p.instanceID)`

the AttributeServiceInstanceID is used:
`resourceAttr.PutStr(semconv.AttributeServiceInstanceID, p.instanceID)`

**Comment by sharpSteff** [comment]
Reverting this line, seems to work. I have no idea if this has any side effects
https://github.com/sharpSteff/signoz-otel-collector/commit/e8005a542c67a16342ab4664f2c2876f0f8565fb

**Comment by cedstrom** [comment]
+1.  This breaks the functionality of being able to see which backend serviced this request for me.  I'll have to roll a new release to emulate this.  Please fix.
