### ISSUE TITLE
Feat(UI): Filter parameters in window location

### ISSUE THREAD

**Issue by dchennaraidu** [SigNoz/signoz#434]
## Is your feature request related to a problem?

Yes, would be great to have filtered parameters in the URL bar

- Need ability to share my view with team mates
- Bookmarking URL so which I view frequently

## Describe the solution you'd like
Updating URL bar, if we user applies any filter
- Service Name
- Min / Max latency
- Operation Name
- Tags filters

## Additional context
![image](https://user-images.githubusercontent.com/12108102/144415158-ecd299e1-c091-4ec4-8384-03f370af1e0a.png)

**Comment by pranay01** [comment]
Thanks a lot @dchennaraidu for sharing this issue. Seems like a good use case

**Comment by pranay01** [comment]
@dchennaraidu The feature to show parameters of trace filters in URL is shipped in the latest [release](https://github.com/SigNoz/signoz/releases/tag/v0.5.3) for the default helm chart. Can you check if this serves your use case?

Attached is a screenshot

![Image 20-12-2021 at 19 45](https://user-images.githubusercontent.com/504541/146781215-5a645faf-229d-4fb5-b019-be51eb2003c6.jpg)

**Comment by pranay01** [comment]
@dchennaraidu Can you add more details on what do you mean by `Bookmarking URL so which I view frequently`? 
Will this use case not be served by just bookmarking the URL in the browser?

**Comment by dchennaraidu** [comment]
@pranay01 I phrased it wrong, yes both are similar

**Comment by pranay01** [comment]
@dchennaraidu Do check the URL features in the new release also - and if your use cases are met. If its fine, we can close the issue

**Comment by pranay01** [comment]
https://github.com/SigNoz/signoz/issues/434#issuecomment-999211156
