### ISSUE TITLE
[FE] Queries fail on tags

### ISSUE THREAD

**Issue by trajan0x** [SigNoz/signoz#4343]
## Bug description

*Please describe.*  

So this one is odd, we've been seeing it across a few versions. We'll select a tag from the dropdown and when we submit, the xhr payload will not show the string value.

https://github.com/SigNoz/signoz/assets/83933037/4aa7fe3a-2910-4654-9999-d33cfd94058b

## Expected behavior

Tag filter works

Show the string value

## Version information 
* **Signoz version**: 0.34.4  (I realize this outdated, but upgrade is blocked by #4342 which we're currently investigating)
* **Browser version**:   Google Chrome | 120.0.6099.199 (Official Build) (arm64)
* **Your OS and version**:  OSX 14.0 (23A344)
* **Your CPU Architecture**(ARM/Intel):  ARM64

## Additional context

If it's at all helpful, full code for the application inputting the spans is available at synapsecns/sanguine#1650 This/the repo covers all spans being inputted and how. I don't think it's relevant, but perhaps the semconv version or something is helpful

**Comment by makeavish** [comment]
@trajan0x This is not reproducible in latest version.
Please reopen if it's reproducible
