### ISSUE TITLE
Bug(FE): Unable to view graph when legend text length is more

### ISSUE THREAD

**Issue by dchennaraidu** [SigNoz/signoz#437]
## Bug description

Unable to view graph at all

## Expected behaviour

- Ability to select only specific graph legends
- Trim legend length (On hover display full text)
- Or any better way of viewing graph

## How to reproduce

1. Use Http Client Instrumentation
2. Make external API calls to various domains

## Version information 
* **SigNoz version**: 0.3.2
* **Browser version**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36

## Additional context
![image](https://user-images.githubusercontent.com/12108102/144432037-6d7b3187-5c9d-48b5-bb50-f92f02b10e1a.png)

**Comment by pranay01** [comment]
thanks for raising this issue @dchennaraidu Should be an easy fix by restricting the height which legends can take

**Comment by pranay01** [comment]
@dchennaraidu this is fixed by https://github.com/SigNoz/signoz/pull/461
