### ISSUE TITLE
ApDex not working on service page. 

### ISSUE THREAD

**Issue by Rajat-Dabade** [SigNoz/signoz#4394]
<img width="1403" alt="Screenshot 2024-01-19 at 2 03 21 AM" src="https://github.com/SigNoz/signoz/assets/26198062/cdee0bed-ab9b-4332-a72d-1cb08edbf24b">

**Comment by srikanthccv** [comment]
See https://signoz-team.slack.com/archives/C02TJ466H8U/p1705628723733609?thread_ts=1705593343.018129&cid=C02TJ466H8U
