### ISSUE TITLE
Support windows environment for onboarding

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#4415]

**Comment by pranay01** [comment]
Should get merged on 29 July

**Comment by Calm-Rock** [comment]
Review done from my end - pending on @YounixM.
PR - [here](https://github.com/SigNoz/signoz/pull/5525)

**Comment by Calm-Rock** [comment]
PR is merged.

**Comment by pranay01** [comment]
@Calm-Rock was it part of yesterday's SaaS release?

**Comment by Calm-Rock** [comment]
No @pranay01 Pranay. This was part of the release that went today.
The PR had some minor changes in the markdown files and was approved yesterday.

This is live in onboarding now.
