### ISSUE TITLE
Tool tip on hovering over spans in Flamegraph view in trace detail page appears cluttered

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#454]
## Bug description

Tool tip on hovering over spans in Flame graph view in trace detail page appears cluttered

![Screen Recording 04-12-2021 at 1 26](https://user-images.githubusercontent.com/504541/144665404-9e683eab-36fa-4605-b3d0-91cd69423657.gif)

## Expected behavior

The tooltip should have a dark background over which to show text so that it doesn't get cluttered with the other text elements

## How to reproduce

1. Go to traces page from. left panel
2. Click any spans in the span list
3. Hover over spans in the flame graph view

## Version information 
* **Signoz version**: v0.5.2
* **Browser version**:  Version 96.0.4664.55 (Official Build) (arm64)
* **Your OS and version**: macOS Monterey

**Comment by pranay01** [comment]
this seems to be an issue only in dev environment. Closing it for now

**Comment by Anurag5086** [comment]
Hey @pranay01, can i take up this issue?

**Comment by pranay01** [comment]
@Anurag5086 I think this is not appearing in all environments. I saw this issue only in the dev environment. I think as a first step we should check if this is repeating for you. 

Assigning this to you for now. But before writing any code - can you report if you are seeing this repeat

**Comment by Anurag5086** [comment]
@pranay01 I think this is repeating for me as well. 

![image](https://user-images.githubusercontent.com/54763478/144737457-adad014b-17df-4e52-81f0-522cd6a13e36.png)


![image](https://user-images.githubusercontent.com/54763478/144737444-8145f83b-bfad-4798-b99a-9d7bca87015a.png)

**Comment by pranay01** [comment]
ok - but only in dev environment right? I don't see this issue after installing SigNoz docker images

@pal-sig Do you have any ideas on why this could be happening?

**Comment by aryanshridhar** [comment]
This is because, commit 3e0f5a8 accidentally removed `style-loader` from webpack config file due to which the relevant CSS file ([`TraceGraph.css`](https://github.com/SigNoz/signoz/blob/main/frontend/src/modules/Traces/TraceGraph.css)) isn't attached to the tsx file.
Added pr #468 if this looks fine :)
