### ISSUE TITLE
Panel graph results are all disabled 

### ISSUE THREAD

**Issue by al-mcintosh** [SigNoz/signoz#4568]
## Bug description

*Please describe.*  

I have noticed the following of late, when I open a dashboard that requires selecting a variable value (that is used in the panel queries) :

1. Open dashboard with no variable selected, all panels show `no data`
2. Choose a variable value
3. The panels populate but all graph values are disabled. see screen capture. 

I have also noticed, that if I switch browser tabs or minimize the browser and come back the dashboard, the variable chooser becomes empty and all panels show `no data`  i.e. back to step  1. above.

Thanks!

![image](https://github.com/SigNoz/signoz/assets/45045833/a617423a-8ce6-4a54-8173-99c5b15a29c3)

## How to reproduce

1.
2.
3.

## Version information 
* **Signoz version**: v0.39.0
* **Browser version**: Chrome
* **Your OS and version**: Windows
* **Your CPU Architecture**(ARM/Intel):

**Comment by DIVANSHMAHAJAN** [comment]
Is this issue open ?

**Comment by al-mcintosh** [comment]
Still an occurs in v0.40.0

Thanks

**Comment by YounixM** [comment]
@al-mcintosh: Thanks for reporting the issue. We will fix this issue soon. 

Will reach out to you if we need some more info.

**Comment by al-mcintosh** [comment]
FYI only 

Two new observations:

1. Panels populate will all graph values disabled on on dashboards that do **NOT** have have a dashboard attribute. 
2. When all graph values are disabled,  I can only enable one result at a time. Each time I click on a disabled result,  the previously enabled result becomes disabled. (seems only one result can be enabled at a time).


Sorry for the spam and good luck!

**Comment by Rajat-Dabade** [comment]
@al-mcintosh, Thank you for sharing, 

For the 2nd one i.e.
> When all graph values are disabled, I can only enable one result at a time. Each time I click on a disabled result, the previously enabled result becomes disabled. (seems only one result can be enabled at a time).

You can enable all the graphs by clicking on the active legend. 

https://github.com/SigNoz/signoz/assets/26198062/999a814d-80b4-451c-963c-61ea8d680db0

For the 1st one, can you share the recorded video (maybe a loom video) with inspect open so we can debug it more if there is any error? 
Thank you.
