### ISSUE TITLE
LOGS[FE]: Use selected column/attribute as pinned attributes.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#4577]
When a column/attribute is selected to be shown with log lines it should be shown as pinned attributes in the logs detail page.

![image](https://github.com/SigNoz/signoz/assets/26831659/435326ca-1829-465c-933c-460eeed1ab67)

**Comment by GeekBoySupreme** [comment]
Added a mock for this - adding columns should be the sole way to pin attributes.
![image](https://github.com/SigNoz/signoz/assets/15321738/dcecaf49-b028-40a1-8fb4-18024ccd8068)

Find the design board [here](https://www.figma.com/file/L0vX330RkWn7ZpelMpkPHL/Logs?type=design&node-id=2070%3A2001&mode=design&t=jzaVI14QmKyAnZWZ-1) and the icon for pin [here](https://www.figma.com/file/egMidgk6VJDXTumxcCYUl1/Periscope---Primitives?type=design&node-id=630%3A3&mode=design&t=DlbUfjsmtdTR1por-1)

**Comment by ankitnayan** [comment]
is this done?
