### ISSUE TITLE
Make troubleshooting easy for Installation and Instrumentation

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#460]
# Point of failures

1. SigNoz does not install correctly
2. Application not able to connect/discover the otel-collector endpoint
3. Application not emitting data due to misconfiguration

## Solution to point 2
A checker in the application where the users can paste their run commands, we extract the otel-collector endpoint and test whether it is accessible or not by sending sample data. This will resolve connectivity issues between application and otel-collector

**Comment by ankitnayan** [comment]
### Usecase
What should be the troubleshooting steps if somebody instruments the app and the app runs properly - but the user doesn't see any data on the SigNoz dashboard?

**Comment by Siddhant-K-code** [comment]
I think we can start with *1* Installation.

Can you elaborate more about the issue you are facing in installation?

_Ref: https://signoz.io/docs/deployment/requirement/_

**Comment by makeavish** [comment]
I think this is picked by @prashant-shahi

**Comment by prashant-shahi** [comment]
I had created series of PRs to ease down the troubleshoot across platforms.

https://github.com/SigNoz/troubleshoot/pulls?q=is%3Apr+is%3Aclosed

I think we can close this issue.
/cc @ankitnayan
