### ISSUE TITLE
Date range desynchronizing when swapping between views

### ISSUE THREAD

**Issue by wss-alubic** [SigNoz/signoz#4606]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

![image](https://github.com/SigNoz/signoz/assets/158481638/5ce46577-531a-48de-899f-2a6ee0093b73)

Moving between different panels results in the date ranges changing in unpredictable ways.  I'm not sure if this is intended UX, but it's very confusing as a user.

## Expected behavior

I expect the global date range to stick to what I set it to instead of constantly reverting to different values.

## How to reproduce

1. Go to services
2. Choose a date range, custom date range possibly might be required
3. Click a service
4. Use the browsers back button
5. The date range is now different, and when you click it, it looks completely different?  am I viewing a week even though the dates dont match?

## Version information 
* **Signoz version**:
* **Browser version**:
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel):

**Comment by wss-alubic** [comment]
Just to add more context to this bug, I discovered that it feels like each "view" within the UI seems to save its own custom date range.  Hitting "back" in the browser is what caused the weirdness in the screenshot.  I previously selected 1 week, but it's showing 1 minute instead.

**Comment by YounixM** [comment]
@wss-alubic: Every view has its own custom time. That's the expected behavior. Most of the users want different time range selected for different views.

I tried selecting and time range and then using the browser back button to visit the previous view, it works as expected. Would it be possible for you to share a quick video recording of the issue, it will help a lot.

**Comment by wss-alubic** [comment]
@YounixM I can't seem to reproduce the issue today, back button works as expected.
