### ISSUE TITLE
Show history of triggered alerts and their alerting states

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#4609]
The `triggered alerts` section only shows which rules are currently in the firing state.

Having a history of fired alerts would help in looking back even when the alert is now resolved to do RCA. Currently this is dependent on looking to the notification of the alert channel set.

This will also help in running some analysis on the types of alerts fired and avg resolution time, etc.

**Comment by pranay01** [comment]
[Summary recording for alert history (~6 mins)](https://www.veed.io/view/e1bc2e33-5f8a-4d97-b662-bff70adc45ea?panel=share)
[Link to the wireframes](https://excalidraw.com/#room=f6bd4b1a0144985515d1,Uq7PZXh216X9y_nta2sMfw) (check for Recent updated screens frame for the current scope)
[Link to the PRD stories](https://www.notion.so/signoz/Triggered-alerts-history-88271688c980434da1c2b72c44b2b546?pvs=4#11f1d02f57674f70a9be6ebc600bff64)

**Comment by sudeepSigNoz** [comment]
@srikanthccv @pranay01 sharing the progress. I need to finish few more details in this one. 
https://www.figma.com/design/fD7ZUYgwqb5wWLtw6aVOwD/SigNoz-Designs?node-id=76-6687&t=zLPsWSImTVRskxHS-4

- use components and atomic elements from the design system
- add missing nuances
- create prototype
- dev hand off spec and documentation update
- story updates and documentation in PRD

I will be targeting for this to cover today and share a recording on this.

**Comment by pranay01** [comment]
I think it has the right items, but doesn't look polished. I am hoping it will look better after using components in design systems

Also, for timeline view - we can improve the aesthetics. You had shown dot-line-dot type of visualization - that looked better to me

**Comment by sudeepSigNoz** [comment]
Updates: 
- added overall status
- visual improvements

Pending items

- Header actions 
  - share
  - Mute 
  - Edit Rule
  - Add Button icons 
- Sidebar
  - active state + icon

- Timeline chart
  - timeline  time x axis
  - filters
- interaction on timeline
- Consistency on the section headers (surf in design system)

- Prototype the entire flow (optional)
  - zero state
  - list view
  - create view
  - alert channel view 
  - How to reach the history section/page (mandatory)

- Timeline view zoom in + reset
- Page/section level ability to refresh


- Suggestions
  - validate and iterate on the labels and UX copy

**Comment by sudeepSigNoz** [comment]
@pranay01  @srikanthccv @GeekBoySupreme 

sharing the updates for alerts visual design here: 
- [walkthrough video for context](https://www.veed.io/view/a250a606-4692-4b47-906a-8c56cdc88b6a?panel=share)
- [figma design link](https://www.figma.com/design/fD7ZUYgwqb5wWLtw6aVOwD/SigNoz-Designs?node-id=110-16767&t=Mt07L4EVuxNCv6n7-4)

Once you guys do an async review then we can get on a call on Monday for the dev Hand off

**Comment by sharpshooter90** [comment]
@YounixM design team is reviewed the flows and visual design and all the issues in visuals are resolved

[here is the alert page figma link: ](https://www.figma.com/design/jWPCZEqdeA0yDYvixLQ42k/Alerts?node-id=2733-15237&t=sY7eOwbZHsNn6Fqi-4)

let me know if we need to get on a call or async communication for next actions.

**Comment by sharpshooter90** [comment]
parent issue : https://github.com/SigNoz/signoz/issues/3825

**Comment by sharpshooter90** [comment]
@srikanthccv latest [alert history design hand off link: ](https://www.figma.com/design/jWPCZEqdeA0yDYvixLQ42k/Alerts?node-id=2733-198)
