### ISSUE TITLE
Allow variables in Query builder filters and input fields

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#4610]
## Describe the solution you'd like

Add variables support in Query builder filters and input fields

## Describe alternatives you've considered

Using Clickhouse for now, as dashboard variables are only supported in clickhouse queries.

**Comment by srikanthccv** [comment]
One can use the variables in the query builder as well. Use the same syntax `host_name IN {{.host_name}}`

**Comment by makeavish** [comment]
> One can use the variables in the query builder as well. Use the same syntax `host_name IN {{.host_name}}`

It's not working currently as expected. Variable is not getting updated/replaced in filter of query builder.

<img width="1006" alt="Screenshot 2024-02-28 at 12 30 26" src="https://github.com/SigNoz/signoz/assets/9512100/91a593d8-bca7-48c4-8c0b-65e3b10774fa">

**Comment by srikanthccv** [comment]
All the variables will be replaced in the query-service (for all query types), not in the frontend. Where are you testing this?

**Comment by srikanthccv** [comment]
This has been supported for a very long time now; added at the same time when variables were added. Example https://stagingapp.signoz.io/dashboard/ab30ba72-5be1-426f-811d-bb7a166d30f4?startTime=1709113921874000000&endTime=1709115721874000000

**Comment by makeavish** [comment]
> This has been supported for a very long time now; added at the same time when variables were added. Example https://stagingapp.signoz.io/dashboard/ab30ba72-5be1-426f-811d-bb7a166d30f4?startTime=1709113921874000000&endTime=1709115721874000000

Yeah I am able to verify it works now. I made a typo in variable name. 
Thanks for helping.
