### ISSUE TITLE
Cannot enter time values in date selector

### ISSUE THREAD

**Issue by svalaskevicius** [SigNoz/signoz#4624]
## Bug description

The previous time range selector used to allow selecting based on time - hours and minutes. Cannot do that with the new date picker.

## Expected behavior

Select a small window of time to look at traces

## How to reproduce

1. click on the date selector
2. try to get 3 minute interval view
3.

## Version information 
* **Signoz version**: 0.40.0
* **Browser version**:
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel):

**Comment by YounixM** [comment]
This has been addressed. ✅
