### ISSUE TITLE
Metric value isn't updated

### ISSUE THREAD

**Issue by leocavalcante** [SigNoz/signoz#4629]
## Bug description
The Metric value doesn't update.

I'm sending through a Collector, so I added the `debug` exporter to make sure what I'm sending:
```
ScopeMetrics #2
ScopeMetrics SchemaURL: 
InstrumentationScope otelcol/statsdreceiver 1.0.0
Metric #0
Descriptor:
     -> Name: skeleton.my_custom_counter
     -> Description: 
     -> Unit: 
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Delta
NumberDataPoints #0
Data point attributes:
     -> foo: Str(bar)
StartTimestamp: 2024-02-29 14:34:05.337754833 +0000 UTC
Timestamp: 2024-02-29 14:35:05.337995548 +0000 UTC
Value: 1
        {"kind": "exporter", "data_type": "metrics", "name": "debug"}
```
It looks great, it is a Delta+Monotonic+Sum and the value is `1`.

I can find the Metric at the SigNoz dashboard, but the query results in zero:
<img width="1400" alt="Screenshot 2024-02-29 at 11 49 03" src="https://github.com/SigNoz/signoz/assets/183722/1f732e39-07d4-4adc-85b2-f2f6d5b8a27f">

## Expected behavior
I'd like to query for `skeleton_my_custom_counter` and see the value of `1` that I sent.

## How to reproduce

1. Send a Delta+Monotonic+Sum with some >0 value.
2. Query for it to see if it is actually >0.

## Version information 
* **Signoz version**: 0.40.0
* **Browser version**: 
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel): 

## Additional context

> [!NOTE]
> I'm reforcing the `Delta+Monotonic+Sum` idea because Gauges are working.

**Comment by srikanthccv** [comment]
We had this discussion in the past and I believe it is the same issue. Please follow the suggestion here https://community-chat.signoz.io/t/13551760/hi-folks-wave-i-ve-the-logging-exporter-logging-my-monotonic#58f9d5d5-4ce0-4fd4-bfa9-d2506fa97caf.

**Comment by srikanthccv** [comment]
Soon, We are making it such that you don't neet to set the flag explicitly.

**Comment by leocavalcante** [comment]
Oh, right. Thanks for reminding me that!
