### ISSUE TITLE
Timestamp column in New Trace Explorer list view

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#4630]
New Trace explorer list view is missing timestamp column

**Comment by ankitnayan** [comment]
@makeavish is this important? Is this a frontend or backend issue?

**Comment by makeavish** [comment]
> @makeavish is this important? Is this a frontend or backend issue?

It is important ask by a user and we need to discuss a solution, shouldn't be difficult as backend already sends timestamp but it's not part of columns and needs to be hardcoded on frontend
cc: @YounixM

**Comment by makeavish** [comment]
Merged to develop
