### ISSUE TITLE
Error in script section while using Windows 

### ISSUE THREAD

**Issue by Devesh21700Kumar** [SigNoz/signoz#467]
## Bug description

While Using Windows OS and running the server locally , the  `"dev": "NODE_ENV=development & webpack serve --progress",` in the scripts needs an & in between which i have added.
Without the `&` it shows the following error.

![image](https://user-images.githubusercontent.com/59202075/144991112-c7e0183c-5fdb-48d4-b95d-5030097afda6.png)

## Expected behavior

Should run correctly on running yarn dev without any errors

## How to reproduce

1. Use Windows OS
2. run yarn dev

## Version information 
* **Signoz version**: 0.5.2
* **Your OS and version**: Windows 11

**Comment by pranay01** [comment]
@Devesh21700Kumar If the new addition of `&` also works for other platforms like linux and mac, can you create a PR to fix this issue? Or is this issue platform dependent?

**Comment by Devesh21700Kumar** [comment]
> @Devesh21700Kumar If the new addition of `&` also works for other platforms like linux and mac, can you create a PR to fix this issue? Or is this issue platform dependent?

Its Platform Dependent.
Yeah, I'll try to fix it.

**Comment by pal-sig** [comment]
i think this is only encountered when we are using power shell based terminal... not with git bash

**Comment by Devesh21700Kumar** [comment]
> i think this is only encountered when we are using power shell based terminal... not with git bash over the windows

Idts because I encountered this error using the git bash terminal itself.

**Comment by Devesh21700Kumar** [comment]
https://www.npmjs.com/package/run-script-os
This is the package that might do the task.
There's an *os* tag in package.json as well but that is not too much supportive ( might lead to errors later )

Other than these two I don't think a possible solution exists to the issue.
