### ISSUE TITLE
Alert Muting Rules

### ISSUE THREAD

**Issue by wss-alubic** [SigNoz/signoz#4685]
## Is your feature request related to a problem?

We've got alerts with queries that detect metrics dropping to 0 during normal business hours.  NewRelic allows us to mute alerts in advance, to avoid triggering during holidays and planned maintenance, with a start datetime and an end datetime.

## Describe the solution you'd like

A feature that lets us add a "mute rule" where an alert is automatically disabled during the specified timeframe, and then re-enabled outside the window, as long as we haven't manually disabled the alert.

## Describe alternatives you've considered

- Manually logging into SigNoz and disabling/enabling alerts.  This would require dedicated staff.
- Writing a script that enables/disables alerts via your API on a scheduled timer.
- Checking timestamp data in the alert query itself to avoid non critical business hours.  This would add a lot more maintenance burden on us than a simpler UI.

#### *Thank you* for your feature request – we love each and every one!

**Comment by al-mcintosh** [comment]
Going to mention https://github.com/SigNoz/signoz/issues/4722 as there seems to be some similarity. Thanks!

**Comment by srikanthccv** [comment]
Users can now schedule maintenance!
