### ISSUE TITLE
BUG(UI): Theme preference is lost when we refresh the page

### ISSUE THREAD

**Issue by pal-sig** [SigNoz/signoz#469]
## Bug description

switch to light mode and make a refresh . it switch back to dark mode.

https://user-images.githubusercontent.com/88981777/145029162-017b1566-93ca-416c-bbdb-1048a773a4f2.mov

## Expected behavior
it should remember the preference 

If we can store this in local storage then i think we could solve the problem

**Comment by aryanshridhar** [comment]
Working on it 👍
