### ISSUE TITLE
FE: `Aggregate Every` value is not respected in alerts query builder

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#4703]
The value of `Aggregate Every` if changed is not respected by frontend and stepInterval is sent as 60 only.

https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1710226504823589

**Comment by srikanthccv** [comment]
I am updating the priority for this to P0 since we end up writing a lot of ClickHouse queries anytime the user wants to custom aggregation interval.

**Comment by vikrantgupta25** [comment]
waiting on the backend changes for the same.
