### ISSUE TITLE
Create docs on how to use new metrics query builder to create dashboards and alerts

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#4712]
We have launched an updated metrics query builder recently ( Mar 2024)
 https://signoz.io/newsroom/launch-week-1-day-2/

The docs for creating queries from query builder should be updated accordingly https://signoz.io/docs/userguide/query-builder/

**Comment by Calm-Rock** [comment]
@pranay01 the docs have been updated with a section for Metrics Query Builder - https://signoz.io/docs/userguide/query-builder/#metrics-query-builder

Does this resolve the issue ? If yes, please close this issue.
