### ISSUE TITLE
LOGS: Update histogram to show logs by severity

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#4727]
Update histogram to show logs by severity as right now it shows just the count graph, but count by severity text will be more helpful.

cc @pranay01 @GeekBoySupreme

**Comment by ankitnayan** [comment]
https://www.notion.so/signoz/Logs-Improvements-8e8bf4f888b64078b8dc361b2252bfd4?pvs=4#8b5d75b33bae4316b3275604204f3c80

**Comment by vikrantgupta25** [comment]
perf for group by severity_text and severity_number. - https://www.notion.so/signoz/group-by-severity_text-78339feea9914f1c839f01f999904ad9 

@nityanandagohain @ankitnayan
