### ISSUE TITLE
feat: Back to top Button

### ISSUE THREAD

**Issue by vedant-jain03** [SigNoz/signoz#474]
## Is your feature request related to a problem?

Back to top button make it easy for the user to scroll to the top.

*Please describe.*

## Describe the solution you'd like

- will add a new component and place it in position: absolute

#### *Thank you* for your feature request – we love each and every one!

**Comment by vedant-jain03** [comment]
@pal-sig is the issue valid?

**Comment by pal-sig** [comment]
> @pal-sig is the issue valid?

can you please define the use case here

**Comment by vedant-jain03** [comment]
The popularity of responsive web design has led to a proliferation of single-column, long-page designs both on mobile and desktop.  A consequence of these designs has been the Back to Top button, which is a shortcut that allows users to quickly navigate to the top of the page.
As we have documentation I think it will be user-friendly if we put this feature.

**Comment by pal-sig** [comment]
cc: @pranay01

**Comment by pranay01** [comment]
hey @vedant-jain03 I don't think it will be very relevant for the current product as we don't have much vertical height in most of the pages of the product. So closing for now. 
Thanks for the suggestion though!
