### ISSUE TITLE
PromQL metrics query not working on version 0.41+

### ISSUE THREAD

**Issue by zoeyuanz** [SigNoz/signoz#4740]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

After upgrade to SigNoz 0.41.1, when add query to dashboard, PromQL metrics query not working on both version 0.41.0 and 0.41.1, after reverting both query service and frontend to 0.40.0 (didn't try 0.40.1), it works.

![image](https://github.com/SigNoz/signoz/assets/144173458/c40eebff-d3e0-44ed-8d61-b56b240431c1)
![image](https://github.com/SigNoz/signoz/assets/144173458/678d0582-850d-4293-a9fa-5a1e1178695f)

## Expected behavior
Have data returned and diagram rendered.

## How to reproduce

1. Choose an exist metrics using query builder
2. Query that metrics with PromQL

## Version information 
* **Signoz version**: 0.41.1 (all signoz component), 0.41.0(revert query service and frontend to 0.41.0)
* **Browser version**:  chrome 122.0.6261.129
* **Your OS and version**: AmazonLinux2
* **Your CPU Architecture**(ARM/Intel): intel

## Additional context
We deployed with helm chart on kubernetes

#### *Thank you* for your bug report – we love squashing them!
Thanks a lot for your attention and time!

**Comment by srikanthccv** [comment]
I wasn't able to reproduce this. The screenshot shows one with the builder and the other with promql. Does it work with the builder but not PromQL?

**Comment by zoeyuanz** [comment]
Yes, query builder works fine while promql always shows `no data`.

**Comment by srikanthccv** [comment]
Is it just this metric or happening with all metrics?

**Comment by zoeyuanz** [comment]
It happens with all metrics

**Comment by srikanthccv** [comment]
I am not able to reproduce this. If you could provide more information or steps to reproduce that would help.

**Comment by zoeyuanz** [comment]
I bump up the version to 0.42.0 and issue still existed.

PromQL works fine for the metrics collected directly by SigNoz OpenTelemetry collector.

But I have the SigNoz collector also as the end point to receive metrics sending from other OpenTelemetry collector.

Those metrics have problem with PromQL query, and the behaviours are like the screen shots above.

**Comment by katepangLiu** [comment]
> I bump up the version to 0.42.0 and this issue still exists.↳
> 
> PromQL works fine for the metrics collected directly by SigNoz OpenTelemetry collector.↳
> 
> But I have the SigNoz collector also as the end point to receive metrics sending from other OpenTelemetry collector.↳
> 
> Those metrics have problem with PromQL query, and the behaviours are like the screen shots above.↳

@zoeyuanz  Maybe you can debug it with file exporter, find the difference in metrics.

**Comment by zoeyuanz** [comment]
After further investigations, I think the issue I face may related to: 

1. Metrics send to signoz collector OTLP endpoint are missing in V4 tables (distributed_time_series_v4_1day, distributed_time_series_v4, distributed_samples_v4)
2. Query builder's metrics searching bar query and PromQL query only query V4 tables

Do you have any suggestions or ideas about why the metrics send to the OTLP endpoint can't insert into V4 tables properly?

**Comment by srikanthccv** [comment]
Did you make any modifcation to the config? Or Do you see any error logs in the signoz-otel-collector(s)?

**Comment by zoeyuanz** [comment]
> Did you make any modifcation to the config? Or Do you see any error logs in the signoz-otel-collector(s)? What is the collector version you are using?

Thank you so much for the suggestions! It happened that I'm using an older version of signoz-otel-collector(s). All works fine once I update the image to latest.

Thanks once again for the time and help, really appreciate it.
