### ISSUE TITLE
Issue Encountered: ClickHouse Configuration File Permissions Blocking Signoz docker Installation

### ISSUE THREAD

**Issue by nrashok** [SigNoz/signoz#4743]
## Bug description

I encountered an issue while attempting to install Signoz in an [Docker Standalone](https://signoz.io/docs/install/docker/) using the provided install.sh script. The installation process fails with the following error message:

`0. Poco::FileAccessDeniedException::FileAccessDeniedException(String const&, int) @ 0x0000000015468529 in /usr/bin/clickhouse
1. Poco::FileImpl::handleLastErrorImpl(String const&) @ 0x0000000015469b70 in /usr/bin/clickhouse
2. ? @ 0x000000001546b506 in /usr/bin/clickhouse
3. ? @ 0x0000000015476f89 in /usr/bin/clickhouse
4. Poco::FileInputStream::FileInputStream(String const&, unsigned int) @ 0x000000001547757b in /usr/bin/clickhouse
5. Poco::FileStreamFactory::open(Poco::Path const&) @ 0x00000000154a7d25 in /usr/bin/clickhouse
6. Poco::URIStreamOpener::open(String const&) const @ 0x00000000154a6e79 in /usr/bin/clickhouse
7. Poco::XML::EntityResolverImpl::resolveSystemId(String const&) @ 0x00000000153db9d5 in /usr/bin/clickhouse
8. Poco::XML::EntityResolverImpl::resolveEntity(String const*, String const&) @ 0x00000000153db739 in /usr/bin/clickhouse
9. Poco::XML::SAXParser::parse(String const&) @ 0x00000000153d4352 in /usr/bin/clickhouse
10. Poco::XML::DOMBuilder::parse(String const&) @ 0x00000000153c59d8 in /usr/bin/clickhouse
11. Poco::XML::DOMParser::parse(String const&) @ 0x00000000153c4ea2 in /usr/bin/clickhouse
12. DB::ConfigProcessor::processConfig(bool*, zkutil::ZooKeeperNodeCache*, std::shared_ptr<Poco::Event> const&) @ 0x0000000012fdfbc0 in /usr/bin/clickhouse
13. DB::ConfigProcessor::loadConfig(bool) @ 0x0000000012fe3534 in /usr/bin/clickhouse
14. BaseDaemon::initialize(Poco::Util::Application&) @ 0x000000000cae4de0 in /usr/bin/clickhouse
15. DB::Server::initialize(Poco::Util::Application&) @ 0x000000000c88fc18 in /usr/bin/clickhouse
16. Poco::Util::Application::run() @ 0x00000000153b26ba in /usr/bin/clickhouse
17. DB::Server::run() @ 0x000000000c88f9d1 in /usr/bin/clickhouse
18. Poco::Util::ServerApplication::run(int, char**) @ 0x00000000153bb539 in /usr/bin/clickhouse
19. mainEntryClickHouseServer(int, char**) @ 0x000000000c88c8ca in /usr/bin/clickhouse
20. main @ 0x0000000007216ad8 in /usr/bin/clickhouse
21. ? @ 0x00007fbcc400c083
22. _start @ 0x0000000005f6f12e in /usr/bin/clickhouse
 (version 24.1.2.5 (official build))
Processing configuration file '/etc/clickhouse-server/config.xml'.
Poco::Exception. Code: 1000, e.code() = 13, Access to file denied: /etc/clickhouse-server/config.xml, Stack trace (when copying this message, always include the lines below):`

## Expected behavior
The installation process should complete successfully without encountering any access permission issues with the ClickHouse configuration file

## How to reproduce

1. git clone -b main https://github.com/SigNoz/signoz.git && cd signoz/deploy/
2. ./install.sh

## Version information 
* **Signoz version**: latest 
* **Browser version**: NA
* **Your OS and version**:  Oracle Linux 8.9
* **Your CPU Architecture**(ARM/Intel):  Intel
Docker Version: 24.0.7
ClickHouse Server Version: 24.1.2-alpine

## Additional context

![image](https://github.com/SigNoz/signoz/assets/20737358/1b0255ee-fe7d-4f69-af83-9ffadadb635a)

<img width="437" alt="Screenshot 2024-03-25 123546" src="https://github.com/SigNoz/signoz/assets/20737358/e73d745d-8bcf-45c0-a3c4-1bfb9cbc2003">

Full log dump link  : https://gitlab.com/-/snippets/3690972/raw/main/logs-ch.log

Setting the permissions using the command: sudo chmod -R 777 /etc/clickhouse-server/
Running the install.sh as root does not change the result

**Comment by nrashok** [comment]
Resolved after setting permissions using 'sudo chmod -R 777 signoz/docker' on Oracle Linux. Closing this.

**Comment by mapio** [comment]
> Resolved after setting permissions using 'sudo chmod -R 777 signoz/docker' on Oracle Linux. Closing this.

In what sense making all file world readable and writable is a fix? Is this the recommended way to run this software?
