### ISSUE TITLE
LOGS[FE]: Don't retry request if i/o timeout on backend 

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#4767]
Donn't retry requests which response is 400 and the body contains `i/o timeout` with status `error` . The request should also not be triggered with auto refresh.

Response code is 400 with body

```
{
    "status": "error",
    "data": {
        "A": "read: read tcp 10.88.14.242:54096-\u003e10.92.9.230:9000: i/o timeout"
    },
    "errorType": "bad_data",
    "error": "error in builder queries"
}
```

**Comment by nityanandagohain** [comment]
@Vikrant2520 since the entire issue is not addressed are you going to open a new issue or should I reopen this one so that we don't miss it.

**Comment by Vikrant2520** [comment]
@nityanandagohain yes will be opening a separate ticket for the same, as that needs a bit of refactor

**Comment by Vikrant2520** [comment]
https://github.com/SigNoz/engineering-pod/issues/1234
