### ISSUE TITLE
Improve visibility for toolbar

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#4771]
Saved views are less visible to user

**Comment by makeavish** [comment]
@YounixM Updated design

![Image](https://github.com/SigNoz/signoz/assets/9512100/136dfdf1-8250-48e1-b792-cce6fab0ae3a)

**Comment by makeavish** [comment]
> @YounixM change the colour scheme of the Add to dashboard button to the same ones as that of Stage and run query.
And in the containers where we have the toolbar, add a padding/margin of 80px to the tabpanels

> I'd also point out here once that the solution we arrived at now was also due to a slight mischaracterization of the feedback we received from the users.
Users wouldn't want to hide/unhide the toolbar often. User would want to see the data unhindered, which was blocked by the lack of bottom spacing :eyes: (and the ideal solution was not a hide button, it was more bottom spacing)

**Comment by YounixM** [comment]
https://github.com/SigNoz/signoz/pull/4824 - Merged
