### ISSUE TITLE
Notification Close Button Visibility Issue in Dashboard UI

### ISSUE THREAD

**Issue by Ompragash** [SigNoz/signoz#4788]
## Bug Description
Reporting a minor UI bug within the Signoz dashboard. Specifically, after deleting a dashboard, a notification appears in the top-right corner displaying the message `DASHBOARD_TITLE Deleted Successfully`. However, the issue arises with the visibility of the close button (`X`), which is not easily clickable due to poor visibility. This becomes particularly problematic because the `+ New Dashboard` button is also located in the top right corner of the Signoz UI, leading to potential user interface confusion.

Screenrecording: https://github.com/SigNoz/signoz/assets/21008429/9bddd86d-972d-4f97-b31f-ffc1d170db80

Screenshot:
![Screenshot 2024-04-01 at 11 01 19 PM](https://github.com/SigNoz/signoz/assets/21008429/c4925df5-2c52-4939-ab34-3e6a05ad2628)

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior

- The expected behavior is for users to easily close the notification immediately after a dashboard title is deleted. The close button (X) should be clearly visible and not obscured by the notification message itself.

## How to reproduce

- Navigate to the dashboard section and create a new dashboard (label it as a dummy dashboard for testing purposes).
- Attempt to delete the newly created dashboard by clicking on `Delete` under the `Action` column and confirm the deletion.
- Observe the notification that appears in the top right corner. Notice that the close button (`X`) is not clearly visible as it overlaps with the notification message, making it difficult to interact with.

## Version information 
* **Signoz version**: Signoz Cloud
* **Browser version**: Google Chrome (Version 122.0.6261.129 (Official Build) (arm64))
* **Your OS and version**: MacOS Ventura 13.6.1
* **Your CPU Architecture**(ARM/Intel): ARM

**Comment by Vikrant2520** [comment]
this has been fixed ✅
