### ISSUE TITLE
User Preference API

### ISSUE THREAD

**Issue by YounixM** [SigNoz/signoz#4796]
User Preference API to help store user preferences across user sessions.

This will also help reduce storing a lot of data in local storage.

Use case - > https://signoz-team.slack.com/archives/C05AXQL92BT/p1716600256934909?thread_ts=1716589743.951289&cid=C05AXQL92BT

**Comment by YounixM** [comment]
@vikrantgupta25 : Add TDD, Estimates around this.

**Comment by vikrantgupta25** [comment]
will start working on the TDD today, we already have a base TDD/PRD ready but want to revamp and revisit that again.. Will be able to provide proper estimates once the TDD is ready.

**Comment by vikrantgupta25** [comment]
PRD/TDD for the same :- https://www.notion.so/signoz/Preference-Framework-55b6ab60b1ad4ea3a6584814e16be031
