### ISSUE TITLE
Allow New Traces Explorer to be pinned on sidebar

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#4809]

**Comment by Dessix** [comment]
I suspect the root request here is that the user doesn't want to have to click the "Try new traces explorer" button every time they click traces. Is there a compelling reason to go back to the "old" one continuously, or should it be possible to simply persist the user's selection, like with the log explorer tab?

**Comment by makeavish** [comment]
This is irrelevant as new explorer page is now default
