### ISSUE TITLE
Layout issue around screen sizes for get-started page

### ISSUE THREAD

**Issue by SagarRajput-7** [SigNoz/signoz#4831]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

![image](https://github.com/SigNoz/signoz/assets/162284829/804395b6-8f1f-43cc-9f50-a49faac64fd7)

## Expected behavior

Page should be responsive and layout should handle screen sizes better

## How to reproduce

1.
2.
3.

## Version information 
* **Signoz version**:
* **Browser version**:
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel):

**Comment by makeavish** [comment]
<img width="1440" alt="Screenshot 2024-04-10 at 22 19 40" src="https://github.com/SigNoz/signoz/assets/9512100/5231574e-1fe1-45c3-9d4d-be4e32fb6885">

**Comment by SagarRajput-7** [comment]
Fixed with this - https://github.com/SigNoz/signoz/pull/4859
