### ISSUE TITLE
Dashboard panel time not respected.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#4835]
If the panel of a dashboard is using last 1 day time range it is not respected.

**Comment by YounixM** [comment]
Fixed by: https://github.com/SigNoz/signoz/pull/4836

**Comment by YounixM** [comment]
Identified similar issue in edit panel -> time preference -> Stage & Run Query flow.

@Rajat-Dabade is fixing the issue. Will close the issue once this is done.

**Comment by YounixM** [comment]
Fixed by :  https://github.com/SigNoz/signoz/pull/4842 

Closing the issue.
