### ISSUE TITLE
Error in query in Value Panel

### ISSUE THREAD

**Issue by bka9** [SigNoz/signoz#4855]
## Bug description
Creating a value panel from a function that combines two queries fails with an error of "there can be only one active query for value type panel".
*Please describe.*  
![image](https://github.com/SigNoz/signoz/assets/560648/388f466d-5bc2-4915-ba48-70a06c964b8b)

## Expected behavior
Should display the latest value from the function.

## How to reproduce

1. Create Value Panel
2. Add query A, and hide
3. Add query B, and hide
4. Add a function
5. Run query

## Version information 
* **Signoz version**: 
* query-service: 0.42.0
* otel-collector: 0.88.19
* **Browser version**:
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel):

**Comment by deep-iimjobs** [comment]
hello @bka9, i was trying to find out error percentage too but could not find the right metric for A.
I tried F1 = A*100/B where B is "signoz_calls_total", but can't find a metric for A. could you please help me figure it out.
