### ISSUE TITLE
Remove Table default.signoz_spans as it's not being used

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#486]
## Bug description
Table default.signoz_spans is not being used but still the query service is initializing it.

## Expected behavior
Table default.signoz_spans should be removed from the code as it's not being created by clickhouse image.

**Comment by amustaque97** [comment]
Hi, I would love to work on this issue!

**Comment by pranay01** [comment]
@amustaque97 Assigned the issue to you

**Comment by pranay01** [comment]
sure, thanks for the contribution @amustaque97
