### ISSUE TITLE
Bug in alert threshold unit

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#4873]
loom: https://www.loom.com/share/538e1de82324458396cebb49e8298715?sid=1e360936-f991-4e46-bdf2-dd30f0570250

**Comment by makeavish** [comment]
It's happening after stage and run query.
Not able save the query as well.
![image](https://github.com/SigNoz/signoz/assets/9512100/fe9133a5-54df-403e-97c0-9aa7c157bc08)

**Comment by SagarRajput-7** [comment]
Fixed under this PR - https://github.com/SigNoz/signoz/pull/4875
