### ISSUE TITLE
loading is missing in Full view of the Widget

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#490]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

When user click on the refresh button there is no loading shown to the user

<img width="749" alt="Screenshot 2021-12-10 at 8 09 12 PM" src="https://user-images.githubusercontent.com/88981777/145591249-78e4e288-c531-499b-81a4-69c3b2291123.png">

## Expected behavior
Loading should be shown to the user when the AJAX call response is in pending state

bonus to shown a error if there is any in form antd snackbar with prev data

**Comment by NishidhJain** [comment]
Hello @pal-sig, I would like to work on this issue.

**Comment by pal-sig** [comment]
Sure @NishidhJain

**Comment by NishidhJain** [comment]
Hey @pal-sig, I have resolved "Loading should be shown to the user when the AJAX call response is in pending state" bug but didn't understood "bonus to shown a error if there is any in form _**antd snackbar with prev data**_" clearly. Can you please elaborate about it?

**Comment by sf-pchakraborty** [comment]
@palashgdev Is this fixed? or are there additional changes requested?
