### ISSUE TITLE
Frontend - Add Unit to Pie chart

### ISSUE THREAD

**Issue by paulohmorais** [SigNoz/signoz#4904]
Hey please add unit to pie chart too

Im my example I need change the unit to bytes to show the values in GB.

Check image

![image](https://github.com/SigNoz/signoz/assets/31579998/72988497-845d-4fec-94c9-0a0f080df8f1)

## Describe the solution you'd like

The solution is add units option like others chart

example:
![image](https://github.com/SigNoz/signoz/assets/31579998/3acb1436-92eb-4887-b74b-b4aecba78fa5)

#### *Thank you* for your feature request – we love each and every one!

**Comment by paulohmorais** [comment]
![image](https://github.com/user-attachments/assets/2a1d6429-fca3-4c45-a29f-c72a0202bc87)

The pie chart keeps without any possible unit.
Please, it doesn't make sense in a pie chart that dont show any value for example in GB, Percent (0-100).

For example, on print, I need to see the values in GB. Because the pie chart is for the size of each database of PostgreSQL.

**Comment by srikanthccv** [comment]
Until the unit is officially supported, you can use the formula as a temporary workaround to achieve your desired result. For example `A / 1024 / 1024 / 1024`.
