### ISSUE TITLE
svg fill color mismatch

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#492]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Light Mode
<img width="547" alt="Screenshot 2021-12-10 at 8 15 55 PM" src="https://user-images.githubusercontent.com/88981777/145592329-c30272dd-ff3f-469b-89ce-285530a3be06.png">

Dark Mode
<img width="547" alt="Screenshot 2021-12-10 at 8 17 41 PM" src="https://user-images.githubusercontent.com/88981777/145592617-e54c3247-8e20-483e-8d02-4377f8776edc.png">

## Expected behavior
in light mode, dark mode both should be visible and both should have same color

**Comment by vedant-jain03** [comment]
Can I work on this issue @pal-sig ?

**Comment by pal-sig** [comment]
Sure

**Comment by vedant-jain03** [comment]
@pal-sig It will be really helpful if you provide steps to reproduce the bug.

**Comment by pal-sig** [comment]
Just switch from dark to light mode

**Comment by Devesh21700Kumar** [comment]
@pal-sig https://github.com/SigNoz/signoz/pull/504
Check out this PR which fixes the issue

**Comment by palashgdev** [comment]
Fixed
