### ISSUE TITLE
Span status message should be stored and shown in UI

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#4925]
## Bug description

Only the status code is captured and stored https://github.com/SigNoz/signoz-otel-collector/blob/main/exporter/clickhousetracesexporter/clickhouse_exporter.go#L373. Just knowing span has an error status doesn't help. The main part of the status is the message which adds more detail about the error.

**Comment by ankitnayan** [comment]
also, span kind

**Comment by nityanandagohain** [comment]
@ankitnayan are you talking about storing the string value of SpanKind ? as of now we just store the numerical value.

**Comment by ankitnayan** [comment]
> @ankitnayan are you talking about storing the string value of SpanKind ? as of now we just store the numerical value.

yes

**Comment by nityanandagohain** [comment]
@makeavish  suggested not to store the value in DB as we already store the integer value of SpanKind, and since it's an enum we should just use the string values for it.

**Comment by srikanthccv** [comment]
> since it's an enum we should just use the string values for it

Please elaborate. What do you mean by _just use the string values for it_. Are you suggesting we write the conversion logic b/w enum and their corresponding string representation in the query service? The users should be seeing the `SPAN_KIND_SERVER` for kind and `STATUS_CODE_ERROR` status code instead of whatever number it is shown currently. And remember they should be able to write the ClickHouse queries also.

**Comment by nityanandagohain** [comment]
> write the conversion logic b/w enum and their corresponding string representation in the query service

Yeah I meant that.

Yes if the user want's to write clickhouse queries they will have to remember that conversion logic.
@makeavish  any opinions here ? for logs we store both the values like severity_text and severity_number even though we can do the conversion.

**Comment by nityanandagohain** [comment]
The otel-collector PR is merged https://github.com/SigNoz/signoz/pull/5120#pullrequestreview-2092954578 .

The qs-pr will be merged after the next release. This is to allow at-least a week of time for data backfill.

One suggestions from Srikanth is to remove `kind` from suggestions,
https://github.com/SigNoz/signoz/pull/5120#pullrequestreview-2092954578

If anyone has any opinions please let know.

**Comment by nityanandagohain** [comment]
Issue for frontend https://github.com/SigNoz/signoz/issues/5363
