### ISSUE TITLE
Better button spacing for explorer toolbars

### ISSUE THREAD

**Issue by GeekBoySupreme** [SigNoz/signoz#4927]
<img width="769" alt="image" src="https://github.com/SigNoz/signoz/assets/15321738/e66b9e4d-c784-4f11-9d27-6c67f0d2e5cc">
The buttons on the toolbar look abruptly cut off on the right. All the 3 buttons with text labels need a 16px (1rem) right padding.

**Comment by Rohitk131** [comment]
Hello, can explain this issue little bit more, I want to work on it

**Comment by YounixM** [comment]
Sure @Rohitk131 . You can pick this up

**Comment by Rohitk131** [comment]
> Sure @Rohitk131 . You can pick this up

Thanks
