### ISSUE TITLE
make useQuery Hook 

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#493]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

This logic on this file is quite [repetitive](https://github.com/SigNoz/signoz/blob/main/frontend/src/container/GridGraphLayout/Graph/index.tsx#L55) and [this one](https://github.com/SigNoz/signoz/blob/main/frontend/src/container/GridGraphLayout/Graph/FullView/index.tsx#L36)  

which can be abstracted into one single hook

**Comment by veerreshr** [comment]
@pal-sig could you please assign me this issue?

**Comment by pal-sig** [comment]
Sure @veerreshr

**Comment by aryanshridhar** [comment]
Hey @veerreshr, Are you still working on it?

**Comment by veerreshr** [comment]
Sorry @aryanshridhar , I got busy with my exams. Someone can take this issue

**Comment by pal-sig** [comment]
@aryanshridhar would you like to work ?

**Comment by aryanshridhar** [comment]
@pal-sig Yup :)

**Comment by pranay01** [comment]
@aryanshridhar Assigned to you

**Comment by sf-pchakraborty** [comment]
@palashgdev I think this issue should be closed. The PR where this issue was mentioned, has already been closed.

**Comment by palashgdev** [comment]
Thanks @sf-pchakraborty
