### ISSUE TITLE
run production build in locally server

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#498]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

run production build in local server

## Expected behavior
write a script while will run the production build locally (production build=>`/build`)

**Comment by Siddhant-K-code** [comment]
Currently it is creating under `./frontend/build`

**Comment by Siddhant-K-code** [comment]
Are we facing the same issue with the `dev` version? If it is so, then we have to change add some routes to handle `/`. Else I will look into it more.

**Comment by YounixM** [comment]
✖️  Stale Issue - Closing for now.
