### ISSUE TITLE
Why need `.` in using dashboard variables?

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#4983]
Can't we just use `{{variable}}` rather than `{{.variable}}` when using dashboard variables?

**Comment by srikanthccv** [comment]
This is already supported. Both `{{variable}}` and `{{.variable}}` should work. Example https://stagingapp.signoz.io/dashboard/9c87e192-20e8-43f5-be81-9fec41d4d861?relativeTime=30m
