### ISSUE TITLE
Frontend: Contrast Issue with Light/Dark Mode Toggle Button 

### ISSUE THREAD

**Issue by veerreshr** [SigNoz/signoz#500]
## Bug description
I Believe there is some contrast issue with dark/light mode toggle button, It is bit difficult for a person visiting first time to identify the toggle button in light mode. It looks like a dot rather than a toggle switch ( when compared with its background color ).
![Screenshot from 2021-12-12 23-00-49](https://user-images.githubusercontent.com/59141533/145723023-539f3b83-4c19-483c-a775-127d497d193b.png)

## Expected behavior
Better visibility of the button with better contrast ratio

## How to reproduce

1.Run the application locally
2.Observe the toggle button in top left and change it to light mode
3.Observe the same button which is difficult to predict it as toggle switch

## Version information 
* **Signoz version**:
* **Browser version**: Brave Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)
* **Your OS and version**: Ubuntu 20.04.3 LTS

**Comment by pranay01** [comment]
Thanks @veerreshr for raising the issue

**Comment by veerreshr** [comment]
@pranay01 If you could suggest me a solution I could work on this. Something I am thinking is to include a contrasting border for the switch.

**Comment by Devesh21700Kumar** [comment]
#505 will solve this

**Comment by pranay01** [comment]
solved by #505
