### ISSUE TITLE
Schema for filtering by type of resource attributes

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#5009]
We need to decide the type of sorting key to use when the querying patterns have orchestration specific labels
1. K8s
2. ECS
3. Nomad
4. Serverless
5. VMs
6. Fargate
7. Beanstalk

**Comment by nityanandagohain** [comment]
Irrelevant issue as of now since, we have moved to a fingerprint-based method. Issues with adding more hierarchy might come up for different sources, but the sorting key need not change
