### ISSUE TITLE
Shouldn't run migration when there's no initial schema

### ISSUE THREAD

**Issue by ManiMozaffar** [SigNoz/signoz#5043]
## Bug description

If there's no schema out there, why would we run the migration?
I don't care about my old telemetry data, I can just delete the clickhouse's db and run the new version, it should create models and stamp the latest version identifier of migration, without trying to run all the migration, for smoother experience. 

## Expected behavior

Should skip running migration, if there's no previous schema setup.

## How to reproduce

1. Delete clickhouse
2. Try to run the service again

## Version information 
* **Signoz version**: 0.44
* **Browser version**: Not related
* **Your OS and version**: Mac OS
* **Your CPU Architecture**(ARM/Intel): ARM

**Comment by srikanthccv** [comment]
The final version of the latest schema doesn't exist as a standalone statement. It has to be via migration. This step is quick and already smooth.
