### ISSUE TITLE
Fix colors for graphs in light mode and dark mode

### ISSUE THREAD

**Issue by YounixM** [SigNoz/signoz#5111]
https://signoz-team.slack.com/archives/C02TJ466H8U/p1717012027918879?thread_ts=1716659629.520939&cid=C02TJ466H8U

**Comment by YounixM** [comment]
@GeekBoySupreme: Please share the graph color set for light and dark modes.

We have faced multiple issues regarding color contrast in light and dark modes. We would require different colors which are visible in both modes.

**Comment by YounixM** [comment]
@SagarRajput-7: Please take care of adding / testing for the same.

**Comment by YounixM** [comment]
@SagarRajput-7: What's the ETA on this?

**Comment by SagarRajput-7** [comment]
> @SagarRajput-7: What's the ETA on this?

Shuvam is yet to start - https://signoz-team.slack.com/archives/C03AXVC598Q/p1717669103037749?thread_ts=1717431602.911169&cid=C03AXVC598Q

**Comment by GeekBoySupreme** [comment]
robin: '#3F5ECC',
    dodgerBlueDark: '#0C6EED',
    steelgreen: '#003f5c',
    steelgrey: '#2f4b7c',
    steelpurple : '#665191',
    steelindigo : '#a05195',
    steelpink : '#d45087',
    steelcoral : '#f95d6a',
    steelorange : '#ff7c43',
    steelgold : '#ffa600',
    steelrust : '#de425b',
    steelgreen : '#41967e'
    mediumOrchidDark: '#C326FD',
    seaBuckthornDark: '#E66E05',
    seaGreen: '#219653',
    turquoiseBlueDark: '#0099CC',
    silverDark: '#757575',
    outrageousOrangeDark: '#F9521A',
    roseBudDark: '#EB6437',
    deepSkyBlueDark: '#0595BD',
    royalBlue: '#3366E6',
    avocadoDark: '#8E8E29',
    mintGreenDark: '#00C700',
    chestnut: '#B34D4D',
    limaDark: '#6E9900',
    olive: '#809900',
    beautyBushDark: '#E25555',
    danube: '#6680B3',
    oliveDrab: '#66991A',
    lavenderRoseDark: '#F024BD',
    electricLimeDark: '#84A800',
    radicalRed: '#FF1A66',
    harleyOrange: '#E6331A',
    gladeGreen: '#66994D',
    hemlock: '#66664D',
    vidaLoca: '#4D8000',
    rust: '#B33300',
    red: '#FF0000', // Adding more colors, we need to get better colors from design team
    blue: '#0000FF',
    green: '#00FF00',
    purple: '#800080',
    magentaDark: '#EB00EB',
    pinkDark: '#FF3D5E',
    brown: '#A52A2A',
    teal: '#008080',
    limeDark: '#07A207',
    maroon: '#800000',
    navy: '#000080',
    gray: '#808080',
    skyBlueDark: '#0CA7E4',
    indigo: '#4B0082',
    slateGray: '#708090',
    chocolate: '#D2691E',
    tomato: '#FF6347',
    steelBlue: '#4682B4',
    peruDark: '#D16E0A',
    darkOliveGreen: '#556B2F',
    indianRed: '#CD5C5C',
    mediumSlateBlue: '#7B68EE',
    rosyBrownDark: '#CB4848',
    darkSlateGray: '#2F4F4F',
    fuchsia: '#FF0AFF',
    salmonDark: '#FF432E',
    darkSalmonDark: '#D26541',
    paleVioletRedDark: '#E83089',
    mediumPurple: '#9370DB',
    darkOrchid: '#9932CC',
    mediumSeaGreenDark: '#109E50',
    lightCoralDark: '#F85959',
    darkSeaGreenDark: '#509F50',
    sandyBrownDark: '#D97117',
    darkKhakiDark: '#99900A',
    cornflowerBlueDark: '#3371E6',
    mediumVioletRed: '#C71585',
    paleGreenDark: '#0D910D',

**Comment by GeekBoySupreme** [comment]
Colour array for light mode ☝🏼

**Comment by YounixM** [comment]
@GeekBoySupreme : Are we keeping the existing colours for dark mode ? Few colors have contrast issue and I thought that was communicated.

**Comment by SagarRajput-7** [comment]
light mode color have been added under this PR - https://github.com/SigNoz/signoz/pull/5192
