### ISSUE TITLE
FE: Viewer access users shouldn't see Org settings

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#5113]
![Image](https://github.com/SigNoz/signoz/assets/9512100/31cd1a4e-1727-42d9-b4dc-e9bcdc101e15)

**Comment by SagarRajput-7** [comment]
@makeavish - I checked this and it is working fine, are you sure you had viewer permission at that time - 

I also checked via code `current_org_settings: ['ADMIN']` that we have a permission check in place so this should not break 

https://github.com/SigNoz/signoz/assets/162284829/d6705c8a-77ea-40d8-ba21-e31dbc78f395

**Comment by makeavish** [comment]
I am also not able to reproduce this, maybe it was due to API failure, closing it
