### ISSUE TITLE
timestamp_ms column missing on k8s install

### ISSUE THREAD

**Issue by realkarmakun** [SigNoz/signoz#5122]
## Bug description

Attempting to set retention period for Metrics on clean 0.46.0 k8s install results in error.

![изображение](https://github.com/SigNoz/signoz/assets/20980281/a837a5a2-ec9e-4d36-bfd5-16d111e9b83e)

Traces and logs work as expected though.

The following error can be seen in the logs:

```
2024.05.31 08:47:24.506741 [ 666 ] {6345e71c-4a66-492f-88ab-e0242a325b9c} <Error> DDLWorker: Query /* ddl_entry=query-0000000184 */ ALTER TABLE signoz_metrics.time_series_v4_1day MODIFY TTL  toDateTime(toUInt32(timestamp_ms / 1000), 'UTC') + toIntervalSecond(5184000), toDateTime(toUInt32(timestamp_ms / 1000), 'UTC') + toIntervalSecond(1209600) TO VOLUME 's3' wasn't finished successfully: Code: 47. DB::Exception: Missing columns: 'timestamp_ms' while processing query: 'toDateTime(toUInt32(timestamp_ms / 1000), 'UTC') + toIntervalSecond(5184000)', required columns: 'timestamp_ms' 'timestamp_ms'. (UNKNOWN_IDENTIFIER), Stack trace (when copying this message, always include the lines below):
```

## Expected behavior
Retention period would be successful

## How to reproduce

1. Clean install SigNoz helm chart on a kubernetes cluster
2. Try changing retention period for metrics

## Version information 
* **Signoz version**: 0.46.0
* **Browser version**: Firefox 126.0.1
* **Your OS and version**: Windows 10
* **Your CPU Architecture**(ARM/Intel):  Intel

**Comment by prashanth-nani** [comment]
We are facing the same issue. timestamp_ms column is missing
