### ISSUE TITLE
Missing loading spinner in `Settings` tab.

### ISSUE THREAD

**Issue by aryanshridhar** [SigNoz/signoz#515]
## Bug description

The loading spinner in `Settings` tab is missing when the user saves the retention values.

<strong>Issue</strong>

https://user-images.githubusercontent.com/53977614/146073022-036a89c9-6c1b-42bf-b24f-a04d7a1c79b9.mov

## Expected behavior

The loading spinner should be visible as it was earlier.

## How to reproduce

1. Navigate to `Settings` tab.
2. Save the retention values.
3. The loading spinner should be visible within the space generated.

## Version information 
* **Signoz version**: 0.5.3
* **Browser version**: FF 95.0 (64-bit)
* **Your OS and version**: MacOS Monterey, 12.0.1 (Apple silicon)

**Comment by pranay01** [comment]
this is fixed in v0.6.2
