### ISSUE TITLE
LOGS[FE]: Key DataType not respected and DataType not shown for materialised columns

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#5150]
* Respect the data type of the key
* respect the tagType of the Key (updated)
* Show the type and dataType even if it's materialized.

https://github.com/SigNoz/signoz/assets/26831659/69517cb5-097b-48ad-aadf-8e3846c5e1ca

**Comment by atmask** [comment]
Just to add on to this. I have also been looking into this as it's been impacting me. The `Tag` value is also not respected when there is a `tag` and `resource` with the same name.

**Comment by YounixM** [comment]
@vikrantgupta25 : As discussed, assigning this to you.

**Comment by vikrantgupta25** [comment]
we also need a way to differentiate between the different kinds of attributes. let's say we type `customAttribute = X` without using the suggested options, we wouldn't know if the customAttribute is a tag / resource etc.

**Comment by vikrantgupta25** [comment]
another issue with the same is no difference and wrong data being shown in the selected columns 
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/f5e9112c-e7cd-42f3-a380-7fd9962a45e9">

and no visible difference in the option to add more columns

**Comment by vikrantgupta25** [comment]
https://github.com/SigNoz/signoz/issues/5645

**Comment by vikrantgupta25** [comment]
will be taken care here - https://github.com/SigNoz/signoz/pull/5659

**Comment by vikrantgupta25** [comment]
https://github.com/SigNoz/signoz/issues/5359
