### ISSUE TITLE
Improve icon overlaps with `Dashboard` pagination panel

### ISSUE THREAD

**Issue by aryanshridhar** [SigNoz/signoz#516]
## Bug description

The Chat icon (Improve feedback button) within the `Dashboard` tab overlaps with the pagination panel.

<strong>Issue</strong>

<img width="327" alt="Screenshot 2021-12-15 at 1 49 27 AM" src="https://user-images.githubusercontent.com/53977614/146073725-cfd28ca6-b9ed-40a6-80dc-b309ca0da752.png">

## Expected behavior

Open to discussion.

## How to reproduce

1. Navigate to the `Dashboard` tab.
2. Scroll to the bottom.

## Version information 
* **Signoz version**: 0.5.3
* **Browser version**: FF 95.0 (64-bit)
* **Your OS and version**: MacOS Monterey, 12.0.1 (Apple silicon)

**Comment by pranay01** [comment]
Yeah, faced this issue myself also. @pal-sig any suggestions on how this should be handled?

**Comment by NishidhJain** [comment]
Hello @aryanshridhar @pranay01, we could move pagination towards left or center
