### ISSUE TITLE
Do not use timestamp filter when searching by traceID

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#5163]
traceID should be fetched irrespective of the time period chosen

**Comment by makeavish** [comment]
@ankitnayan Can we prioritize this as P0?

This is also reported by getlantern: https://app.intercom.com/a/inbox/wmkurvb7/inbox/shared/all/conversation/4054#part_id=comment-4054-8417

>Trace lookup by ID is veeeery slow. I think took at least 30 seconds to fetch one trace by ID

**Comment by nityanandagohain** [comment]
@makeavish was something like this already worked upon ?

**Comment by makeavish** [comment]
> @makeavish was something like this already worked upon ?

Yes, search on TraceID is now fast as we are now reducing search space by restricting time range to start and end time of traceID. 

This issue seems to be different. It mentions user should not be constrained by selected timestamp when searching by traceID.
