### ISSUE TITLE
Improvements in logs explorer - to show more log lines

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#5169]
Changes I would find useful in logs explorer. Reduce the font size (default font size of the terminal text on linux/mac) so I can see more log lines and get rid of the padding (or whatever it is called) at the bottom so I can see some more log lines.

[Slack Message](https://signoz-team.slack.com/archives/C03AXVC598Q/p1717755541819279?thread_ts=1717755541.819279&cid=C03AXVC598Q)

**Comment by GeekBoySupreme** [comment]
@YounixM remove the padding on the top and bottom of the logs container and bump down the font size to 13px (Check with 12px once but that might not be too legible)
![image](https://github.com/SigNoz/signoz/assets/15321738/4a33c76e-a74a-43cf-b8d1-f02fb610079f)

**Comment by vikrantgupta25** [comment]
@GeekBoySupreme that padding was suggested by design because we had an issue where the views toolbar overlaps with the bottom most logs.that would come back the moment we remove this padding.

**Comment by ankitnayan** [comment]
1. https://www.notion.so/signoz/Logs-Improvements-8e8bf4f888b64078b8dc361b2252bfd4?pvs=4#2b3309e0ff46480e825829ee3fbccb6a
2. https://www.notion.so/signoz/Logs-Improvements-8e8bf4f888b64078b8dc361b2252bfd4?pvs=4#8b5d75b33bae4316b3275604204f3c80

**Comment by vikrantgupta25** [comment]
https://github.com/SigNoz/engineering-pod/issues/1205

**Comment by vikrantgupta25** [comment]
this is done
