### ISSUE TITLE
List of filtered spans doesn't seem clickable

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#517]
Clicking on a line-item in the table takes to flamegraphs. A user has pointed out to @pranay01 that the line items does not seem clickable.

<img width="1235" alt="Screenshot 2021-12-15 at 12 38 47 PM" src="https://user-images.githubusercontent.com/83692067/146139876-5cc104bb-cf21-4ddb-9bb6-8b51fe716603.png">

**Comment by aryanshridhar** [comment]
How about we have something like this ?

![IMG_1030](https://user-images.githubusercontent.com/53977614/146911971-73ef2b02-c19b-4bf0-98fc-b9d75da0b3f0.jpg)

(Took from my phone to show that cursor as well!)

**Comment by palash-signoz** [comment]
> @ankit01-oss can you check if the new release v0.6.1 solves this issue?
> 
> @palash-signoz @aryanshridhar I think we still don't have hand icon when moving over list of spans. Would this be relatively simple to implement?

yes @pranay01 it just css only... easy to implement

**Comment by pranay01** [comment]
cool @palash-signoz - Is this the PR which fixes this? -https://github.com/SigNoz/signoz/pull/755

**Comment by palash-signoz** [comment]
Yes @pranay01

**Comment by aryanshridhar** [comment]
Cool!
