### ISSUE TITLE
Improve the appearance of the footer section 

### ISSUE THREAD

**Issue by UdaykiranRegimudi** [SigNoz/signoz#5173]
The current appearance of the footer section is not optimal. It appears too long and could benefit from a more polished and professional design. 
![Uploading Screenshot 2024-06-08 165537.png…]()

**Comment by srikanthccv** [comment]
The image attached is broken.

**Comment by UdaykiranRegimudi** [comment]
![Screenshot 2024-06-08 165537](https://github.com/SigNoz/signoz/assets/98547514/7f1a6fdd-9c5f-45b6-87ac-12ed359aedae)

**Comment by srikanthccv** [comment]
This repo is not for the website changes.
