### ISSUE TITLE
Error rates in `Top Endpoints` table

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#518]
Users want to check errors rates for top endpoints in this table.

<img width="597" alt="Screenshot 2021-12-15 at 12 45 39 PM" src="https://user-images.githubusercontent.com/83692067/146140715-2437065f-a3df-4522-b70c-97049a5d138a.png">

**Comment by pranay01** [comment]
@ankitnayan this should be easy to do right? Do we have API based error data?

**Comment by ankitnayan** [comment]
> this should be easy to do right? 

yes. Nothing major but changing API. But this section is pending to be changed to metrics. Right now it is calculated from trace data.

> Do we have API based error data?

Not clear what you mean

**Comment by pranay01** [comment]
> Do we have API based error data?

> Not clear what you mean

I meant different Endpoints in a service will have different error rates. So we need to have APIs with error rate for different endpoints

**Comment by ankitnayan** [comment]
Right, that can be done

**Comment by ankitnayan** [comment]
Will be picked up together with SpanMetricsProcessor to convert trace APIs to metrics APIs
