### ISSUE TITLE
Facing issues in clicking on smaller spans in flamegraph

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#519]
Smaller spans in the flamegraph have issues in getting clicked.

Try clicking on smaller spans in the second line shown in the screenshot below 👇

<img width="925" alt="Screenshot 2021-12-14 at 8 19 40 PM" src="https://user-images.githubusercontent.com/83692067/146021187-0ac4e1af-a327-4196-8475-ef82c068582e.png">

**Comment by pranay01** [comment]
fixed by https://github.com/SigNoz/signoz/pull/764 - Updated trace detail page design

Please reopen if the issue persists
