### ISSUE TITLE
SMTP setup for alertmanager not documented

### ISSUE THREAD

**Issue by jansorg** [SigNoz/signoz#5205]
## Bug description

I unsuccessfully attempted to configure an email notification channel for alerts. I found https://signoz.io/docs/operate/query-service/user-invitation-smtp/ and followed it, but it didn't work.

On Slack, I finally found the needed info, see below. This should be mentioned in the documentation.

## Expected behavior

On slack, I found [this](https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1714124887450909?thread_ts=1714117467.786099&cid=C01HWQ1R0BC):
> For the email alerts, you need to set following environment variables in alertmanager:
> ALERTMANAGER_SMTP_FROM: alerts@domain.com
> ALERTMANAGER_SMTP_HOST: smtp.domain.com
> ALERTMANAGER_SMTP_PORT: "587"
> ALERTMANAGER_SMTP_AUTH_USERNAME: user
> ALERTMANAGER_SMTP_AUTH_PASSWORD: password

## Version information 
* **Signoz version**: 0.47.0

**Comment by prashant-shahi** [comment]
Docs to configure email alert channel can be found here: https://signoz.io/docs/alerts-management/notification-channel/email/#configuring-alertmanager

**Comment by jansorg** [comment]
Thanks! I was unable to find this. I searched for `smtp` in the docs, which only returned the page for the invite setup:
![image](https://github.com/SigNoz/signoz/assets/11473063/08a43b0e-45b3-4b95-b4b7-5c5c94202e5d)

**Comment by prashant-shahi** [comment]
> Thanks! I was unable to find this. I searched for `smtp` in the docs, which only returned the page for the invite setup: ![image](https://private-user-images.githubusercontent.com/11473063/339109658-08a43b0e-45b3-4b95-b4b7-5c5c94202e5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMjIxNjUsIm5iZiI6MTcxODIyMTg2NSwicGF0aCI6Ii8xMTQ3MzA2My8zMzkxMDk2NTgtMDhhNDNiMGUtNDViMy00Yjk1LWI0YjctNWM1Yzk0MjAyZTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE5NTEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzN2E5OTAzNGRkYjk3MzYxNjcwYTI4MjM1MDRiNWI5NmRiY2JiYzM0NjBkMDkzZTQzNzdmNTFmN2EyMTcxZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NsoIgrpP6vS7-QWOA3k03ZH1aLVIvTowLyo7r65s3Po)

^ cc @ankit01-oss @YounixM

**Comment by YounixM** [comment]
@jansorg : Thanks for reporting the issue and sorry for the inconvenience. Will improve the search capabilities soon.

**Comment by prashant-shahi** [comment]
Closing the GitHub issue for now.

@YounixM please track the website search improvement issue in a separate issue.

**Comment by YounixM** [comment]
<img width="1920" alt="Screenshot 2024-06-25 at 1 46 02 PM" src="https://github.com/SigNoz/signoz/assets/3520897/5e979837-0266-468f-a6b8-055702fce207">


@jansorg : The issue with search is fixed now. Thanks for reporting the issue and sorry the inconvenience again.

**Comment by jansorg** [comment]
@YounixM No worries :) Thank you!
