### ISSUE TITLE
hint text for important labels

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#521]
For a first-time user, it can be difficult to understand the nomenclature we have used in the dashboard. For example, a user did not understand what are `external calls`. 

**Suggestion**
We can create definitions and show them on hovering as shown in the screenshot below 👇. The hover text describes what `KD` stands for. 
Source: https://ahrefs.com/

<img width="225" alt="Screenshot 2021-12-15 at 1 05 51 PM" src="https://user-images.githubusercontent.com/83692067/146143269-c986a6f0-8809-42cc-9e48-d297ad71cfb1.png">

**Comment by pranay01** [comment]
this is something which we have implemented. Will be merged in next release 
PR - https://github.com/SigNoz/signoz/pull/501
