### ISSUE TITLE
Bug in uplot charting when grouping by high cardinality column

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#5211]
https://www.loom.com/share/b1fff4bbea9048caa12e5d3087930151?sid=5341cb3e-9821-4287-b30c-9d8071fe05bb

**Comment by SagarRajput-7** [comment]
Fixed under this PR - https://github.com/SigNoz/signoz/pull/5200


https://github.com/SigNoz/signoz/assets/162284829/b914a6ea-a515-48bc-8fbb-25f3b609d08c
