### ISSUE TITLE
`Server` & `Client` dropdown under filter traces not intuitive to users

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#522]
Not intuitive to users what `server` and `client` represent in this dropdown. This is the last filter under `Filter Traces`.

<img width="220" alt="Screenshot 2021-12-15 at 1 57 55 PM" src="https://user-images.githubusercontent.com/83692067/146151019-5681d28c-fe29-409f-b792-ca0fc44bdfdb.png">

**Comment by pranay01** [comment]
v 0.6.0 and later doesn't have Server and Client drop down
