### ISSUE TITLE
Show the panel description with info icon

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#5233]
There is nowhere to see the panel description except in edit mode. One shouldn't be required to edit the panel to see the description. Something like below is easier.
![Screenshot 2024-06-15 at 3 57 39 PM](https://github.com/SigNoz/signoz/assets/22846633/5a57e744-5335-48cd-bfd3-9cba367fc5bb)

**Comment by GeekBoySupreme** [comment]
This was already designed as a part of panel enhancements for the dashboard. Find it [here](https://www.figma.com/design/HMJO1IdO8Yxj1lZcaHMCP1/Dashboards?node-id=2061-5781&t=3XzSJe9xHYCJdll8-1)

https://github.com/user-attachments/assets/12472f1f-f936-49f5-a724-74cafae79eee

**Comment by GeekBoySupreme** [comment]
Enhancing the tooltip a bit more

**Comment by srikanthccv** [comment]
@GeekBoySupreme What would be the best way to show error information in view mode? For instance, the panel query failed because it exceeded the amount of bytes/rows a query is allowed to process. How do we show that?

**Comment by SagarRajput-7** [comment]
Done under this - https://github.com/SigNoz/signoz/pull/6133

**Comment by SagarRajput-7** [comment]
> @GeekBoySupreme What would be the best way to show error information in view mode? For instance, the panel query failed because it exceeded the amount of bytes/rows a query is allowed to process. How do we show that?

we currently show an error in the hover of the icon - 
<img width="650" alt="image" src="https://github.com/user-attachments/assets/bcbe2d0f-cb44-4b33-b81c-b81ebf7625ea">


I closed this issue, as it was for the description part, which is done, let me know if we need to re-open or track the error info on another ticket
