### ISSUE TITLE
New Traces Explorer shows UTC time instead of browser time

### ISSUE THREAD

**Issue by prashanth-nani** [SigNoz/signoz#5234]
## Bug description

New Traces Explorer is showing UTC time while the logs explorer and trace details pages are showing browser local time

**New Traces Explorer**
![image](https://github.com/SigNoz/signoz/assets/8893755/4e6d963d-b490-4787-9e69-29b26ff2d789)

**Trace Details Page:**
![image](https://github.com/SigNoz/signoz/assets/8893755/4d7e32e6-dd40-49ee-9486-6ed3b40935ab)

**Logs Explorer:**
![image](https://github.com/SigNoz/signoz/assets/8893755/5f1a0a56-a44e-4f12-bf02-d87e23f4fea5)

## Expected behavior
New Traces Explorer should show browser time

## Version information 
* **Signoz version**: 0.47.0

**Comment by SagarRajput-7** [comment]
This issue will be fixed with this PR - https://github.com/SigNoz/signoz/pull/5191

Thanks for reporting.
