### ISSUE TITLE
More user-friendly filters for an insights oriented dashboard

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#524]
The current filters on `trace-filter-page` seem more DIY to users, and it's not very intuitive to users what steps should be taken from here. If we can have filters based on actionable things like slowest endpoints, most time-consuming traces etc., it can be more useful to users.

<img width="801" alt="Screenshot 2021-12-15 at 2 27 31 PM" src="https://user-images.githubusercontent.com/83692067/146155061-38a2f0be-b0e3-4c84-96e6-7843628281bf.png">

**Comment by makeavish** [comment]
Closing in favor of https://github.com/SigNoz/signoz/issues/2770
