### ISSUE TITLE
Dropdown under filter traces for the sample HOT R.O.D app confusing to user

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#525]
This dropdown has no headings or hint text as to what it contains. A user got confused if this was `list of services` or `span types` as `mysql` and `Redis` are also there. 

Filter looks like this upon landing(no headings on hint text) 👇

<img width="202" alt="Screenshot 2021-12-15 at 2 36 58 PM" src="https://user-images.githubusercontent.com/83692067/146156565-b11f03f9-b025-4583-92b7-51a07250e9ae.png">

A dropdown appears when the user clicks inside the box. The list is not intuitive about what category the filter items belong to.

<img width="216" alt="Screenshot 2021-12-15 at 2 37 12 PM" src="https://user-images.githubusercontent.com/83692067/146156610-ecc45973-1707-41ba-9aae-972c3872268a.png">

**Comment by aryanshridhar** [comment]
There's an open pr for it - #384

**Comment by pranay01** [comment]
This should be solved with v0.6.0 where trace filter page is redesigned
