### ISSUE TITLE
feat(FE): Ask for confirmation before deleting dashboard from dashboard list

### ISSUE THREAD

**Issue by NishidhJain** [SigNoz/signoz#526]
## Bug description
If by mistake user clicks on `Delete` action in dashboard list, it would directly delete that particular dashboard without asking for confirmation. So, adding an extra layer of confirmation before deleting would be a good idea. Also, changing the `Delete` from just a text to button with red color will signify its meaning more specifically.

![prev-dashboard-list](https://user-images.githubusercontent.com/61869195/146167458-5ac2b444-7eb0-4851-9b32-aa6c33025352.PNG)

## Expected behavior
When user clicks on `Delete` a modal should open and ask for confirmation whether to delete the dashboard or not as shown in below screenshot.

![confirmation-dailog](https://user-images.githubusercontent.com/61869195/146164851-b3a668b9-cc37-405a-9baa-8ead72bff550.PNG)

Changing the `Delete` to a button with red color

![new-delete-btn](https://user-images.githubusercontent.com/61869195/146165505-9ce1f25c-731a-4a9a-8b50-d6bfb6aa08dd.PNG)
 

## How to reproduce

1. Navigate to `Home / dashboard`
2. Click on `delete` action.
3. Dashboard would be directly deleted without asking for confirmation

**Comment by NishidhJain** [comment]
Hello, @pal-sig @palashgdev I would like to work on this issue if you think it should be implemented.

**Comment by pranay01** [comment]
@NishidhJain Seems like a relevant feature - assigning it to you. Please use antd components only

**Comment by NishidhJain** [comment]
Sure, @pranay01 I would use only antd components.

**Comment by NishidhJain** [comment]
Hello @pranay01, I have raised a PR for the same. Please have a look at it.
PR  #534

**Comment by devinstasafe** [comment]
@pranay01 @ankitnayan : this is very much needed as even I have lost configured dashboards, I have shared the link with others and they deleted by mistake.

**Comment by ankitnayan** [comment]
> @pranay01 @ankitnayan : this is very much needed as even I have lost configured dashboards, I have shared the link with others and they deleted by mistake.

@devinstasafe this will be fixed in upcoming release. PR fixing this is already merged https://github.com/SigNoz/signoz/pull/534
