### ISSUE TITLE
Global search and column search

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#5260]
Sometimes tables can be large and without a search option, it's difficult to work with the data. We should support the search on the table. We can only support the global search for the initial task and see if there is real interest from the users for a column-wise search.

The table header should be sticky at top and should not be hidden when scrolling.

**Comment by vikrantgupta25** [comment]
@SagarRajput-7 please check this, you have a similar issue assigned to you for the same. Thanks!

**Comment by SagarRajput-7** [comment]
> @SagarRajput-7 please check this, you have a similar issue assigned to you for the same. Thanks!

Yes, I have a list panel table search request -https://github.com/SigNoz/engineering-pod/issues/1212

But have to check the scope for the above once we have a solution.

**Comment by SagarRajput-7** [comment]
Added global search and sticky header:


https://github.com/user-attachments/assets/86825627-7289-423d-a409-987b3c5ae32e
