### ISSUE TITLE
Threshold does not appear to work

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#5262]
It's not clear what is thresholds supposed to do it the table panel type. It doesn't seem to work either.

https://www.loom.com/share/4bd7966d726d4f3caf4d5910b5436b96?sid=b21faea1-dcfd-40b1-bced-6cee1039a092

**Comment by abhi12299** [comment]
This is working fine. Did you do something else that I missed?

https://github.com/user-attachments/assets/ef2bde5d-e1e8-4a48-93c0-ce53fab841e3

**Comment by SagarRajput-7** [comment]
@srikanthccv, @vishalsharma1800  - Its working fine for me also, please check:

https://github.com/user-attachments/assets/c731f546-418e-4c62-bd7c-621465cf2701


But as for the understanding of what threshold should mean for the table panel, it is still unclear as here we have comparison operators like - `>` `<` `>=` `<=` which mostly doesn't make any sense when comparing a string value, like serviceName, etc.

**Comment by makeavish** [comment]
> @srikanthccv, @makeavish - Its working fine for me also, please check:
> 
>  Screen.Recording.2024-09-22.at.6.58.05.PM.mov 
> But as for the understanding of what threshold should mean for the table panel, it is still unclear as here we have comparison operators like - `>` `<` `>=` `<=` which mostly doesn't make any sense when comparing a string value, like serviceName, etc.

Looks like it works now, we should only should show float/int columns in suggestions

**Comment by srikanthccv** [comment]
@SagarRajput-7 please see _Table panel where threshold doesn't work_ panel here https://stagingapp.signoz.io/dashboard/73d39077-bc3b-42ad-86c5-b3ed962af521?relativeTime=30m

**Comment by SagarRajput-7** [comment]
Fixed under this - https://github.com/SigNoz/signoz/pull/6079
