### ISSUE TITLE
Parent span shows less duration than combined duration of child spans in sample hotROD application

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#529]
Parent span shows less duration than combined duration of child spans. Flamegraph shown below is from the sample hotROD application which shows be default in the SigNoz dashboard.

<img width="909" alt="Screenshot 2021-12-16 at 11 02 12 AM" src="https://user-images.githubusercontent.com/83692067/146314023-a2d45023-6d69-4d01-b609-3fd23065f6d7.png">

**Comment by ankitnayan** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md

Quoting some texts from the above link
> Each span has zero or one parent span and zero or more child spans, which represent causally related operations. A tree of related spans comprises a trace. A span is said to be a root span if it does not have a parent. Each trace includes a single root span, which is the shared ancestor of all other spans in the trace. 

Logic in exporter where It is done now:
https://github.com/SigNoz/opentelemetry-collector-contrib/blob/create-metrics/exporter/clickhouseexporter/clickhouse_exporter.go#L53-L97

@makeavish @00imvj00 please go through the above links and we can discuss further based on your inputs.

**Comment by makeavish** [comment]
Closing this issue as it is stale now.
