### ISSUE TITLE
[FR] UI indicates whether your query filter uses a Tag or Resource attribute

### ISSUE THREAD

**Issue by atmask** [SigNoz/signoz#5359]
Seomtimes there are valid uses cases where a `resource attribute` and a `tag attribute` have the same name. It took a long time to realize that the query bar for logs wasn't respecting the selected type between tag and resource (related issue: https://github.com/SigNoz/signoz/issues/5150). To discover this I had to dig into the network tab on chrome and find the query. 

The UI should have a visual indication that let's user's know whether their query filter key is using a tag or resource. This could be as simply as T or R icon

![image](https://github.com/SigNoz/signoz/assets/28781746/3ed101e7-5e2c-4f72-b328-2551190343ef)

**Comment by nityanandagohain** [comment]
@GeekBoySupreme  please let us know your thoughts on this form design point of view.

**Comment by GeekBoySupreme** [comment]
I think you'd have the icon on the suggestion dropdown too for it to be relevant/useful. And you can also colour code the `T` and `R` - so the pill can be of some colour for tag attribute and something else for resource attribute.

**Comment by vikrantgupta25** [comment]
this has been resolved with the new search
