### ISSUE TITLE
Infra monitoring (Out of the box module)

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#5373]
Today you can import dashboards for monitoring infrastrcuture like VMs, Kubernetes clusters in SigNoz, but there is no dedicated infra monitoring module ( may be as a tab in the left side bar) where users can go and out of the box get status of their infrastructure. Building such a module would enable users to get understanding of the infra out of the box

It should have out of box metrics for 

- [ ] VMs
- [ ] K8s Clusters
- [ ] ECS clusters
- [ ] Fargate nodes 
etc

**Comment by ankitnayan** [comment]
+ show APM, spans and logs from the selected host

**Comment by pranay01** [comment]
PRD - https://www.notion.so/signoz/PRD-Show-infrastructure-lists-more-easily-Infra-Monitoring-module-9a4bdc889dcc4f0cb06b9377d10a9570

**Comment by pranay01** [comment]
- Initial focus is on completing the correlation story with infra module
- Lists of Hosts & K8s clusters
