### ISSUE TITLE
Enhancing metrics and traces with K8s attributes

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#539]
`k8sattributes` processor 
https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor

**Splunk's sample config**
https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/values.yaml
https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/templates/config/_otel-agent.tpl

**resourcedetectionprocessor**
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor

**Comment by pranay01** [comment]
@ankitnayan Can you add more details on what is expected to be done in this issue?

**Comment by grandwizard28** [comment]
This has been added to our helm charts: https://github.com/SigNoz/charts
