### ISSUE TITLE
LOGS[BE]: Index not utilized when wrtiing contains queries for attribute

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#5406]
We added support of body index in this PR https://github.com/SigNoz/signoz/pull/4787 which helps in utilising the clickhouse indexes when we search for anything inside the body  also it is case insensitive.

For attribute as of now contains is a case insensitive operation

* If we make the same changes w.r.t to index for attributes then the other operators like `=,IN` will also become case insensitive if we try to use the same index.
* If we keep it case sensitive then there shouldn't be a problem.

But if we keep it case sensitive how do we communicate this to the user.

cc @ankitnayan @srikanthccv @raj-k-singh

**Comment by ankitnayan** [comment]
@raj-k-singh please provide your suggestions

**Comment by nityanandagohain** [comment]
We decided that we wanted to go with case insensitive search for all attribute values, 

In new schema
* Resource filtering is case-insensitive for all operators.
* No way to apply the same for `attributes` as there are limitations with how indexes on maps work.


```
CREATE TABLE test_table
(
    id UInt64,
    value Map(Int64, String),
    index value_key_index mapKeys(value) TYPE bloom_filter GRANULARITY 4,
    index value_value_index arrayMap(x -> lower(x), mapValues(value)) TYPE bloom_filter GRANULARITY 4
) ENGINE=MergeTree ORDER BY id;


INSERT INTO test_table
SELECT number as id, map(number, toString(number)) as value
FROM numbers(1000000);

EXPLAIN indexes = 1
SELECT *
FROM test_table
WHERE has(value, 10000)

reason: - clickhouse does an exact match to the filter vs index name: eg:- if index is lower(body) then where clause should have lower(body).
In the above case since there is no match it doesn’t work.
After discussion with Srikanth these are the three options we have
* choose indexing for contains and all operators and keep everything case sensitive for attributes- (not backward compatible)
* choose indexing for contains and double the storage by duplicate attributes column with values in lower case - double storage size
* keep case insensitive without indexing for contains - cannot do as we want to rely on maps
```

**Comment by nityanandagohain** [comment]
Contains now uses an index in the new schema

limitations:-
* attributes search is case sensitive
* resources and body search is case insensitive

ref :- https://github.com/SigNoz/signoz/issues/5555
