### ISSUE TITLE
LOGS[BE]: Typecasting error for float values to be parsed as int64

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#5407]
```
{
                            "id": "67ac8ef5-a040-41f4-b15c-7ff407cc1341",
                            "key": {
                                "key": "community",
                                "dataType": "int64",
                                "type": "tag",
                                "isColumn": true,
                                "isJSON": false,
                                "id": "community--int64--tag--true"
                            },
                            "op": "in",
                            "value": 2399
                        }
  ````
  
  retsults in error because the interface defaults to float64 and when it tries to convert to int64 then it fails as it's not present.
  
  
  ref https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1719895767318709?thread_ts=1718983580.145599&cid=C01HWQ1R0BC

**Comment by nityanandagohain** [comment]
So the issue is

* if there is an attributed name `attr` and we are receiving float64 values.
* Suddenly we receive a int64 value for the same attribute, we will treat it as a new attribute.


Now the frontend is breaks in a different way even if I filter for the float64 value it sends the dataType as int64

```
{
      "id": "d0b53eef-7357-4005-a70f-379107cfb329",
      "key": {
          "key": "community_v1",
          "dataType": "int64",
          "type": "tag",
          "isColumn": false,
          "isJSON": false,
          "id": "community_v1--int64--tag--false"
      },
      "op": "in",
      "value": 899.2
  }
```

because of which it results in a failure.


ex generator
```
response_time_ms = random.choice([1.1, 2.2, 1234.23, 234.32, 23453.23, 23423.23, 899.2, 89992.2, 2399])
logger2.warning('{"message":"hello"}', extra={"res_v1": response_time_ms})
```
now `res_v1` will have a int as well as float attr.

**Comment by ankitnayan** [comment]
also, I recommend reading uber's blog on how they manage changing attribute types to check if they have any better suggestions

**Comment by nityanandagohain** [comment]
On uber's blog they have three types string, number and bool.
https://blogadmin.uberinternal.com/wp-content/uploads/2022/08/Screen-Shot-2021-02-18-at-6.29.02-PM.png?uclick_id=44c3e43c-33db-416a-8c13-74e3c3474fca

they are not keeping in64 and float64 they are treating it as number with dataType as float64

**Comment by ankitnayan** [comment]
so that is same as we thought

**Comment by nityanandagohain** [comment]
went with `numbers` in the new schema instead of `int64` and `float64` . Where everything is stored as float64
