### ISSUE TITLE
Create new Golang sample app instrumentation with UI

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#542]
Create/Update [existing Golang sample app](github.com/SigNoz/sample-golang-app) to have a basic UI similar to [flask sample app](https://github.com/SigNoz/sample-flask-app)
Features:
- Frontend to interact with the sample app
- DB operation
- Error on an endpoint

**Comment by meerasndr** [comment]
If this is still available, I can take a stab at it.

**Comment by makeavish** [comment]
Sure @meerasndr 
Assigning this issue to you.
You can create a PR over current sample golang app repo.

**Comment by makeavish** [comment]
DB instrumentation was added to sample golang app: https://github.com/SigNoz/sample-golang-app
