### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by ohyoona** [SigNoz/signoz#5424]
## Bug description
![image](https://github.com/SigNoz/signoz/assets/63778463/603ac7af-960b-4db3-914f-ab03669fd5ef)

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior
run dashboard detail

## How to reproduce

1. run dashboard detail (/dashboards/{uuid})
2.
3.

## Version information 
* **Signoz version**: 0.49
* **Browser version**: 
* **Your OS and version**: window 10
* **Your CPU Architecture**(ARM/Intel):

**Comment by sameemcodes** [comment]
@ohyoona can you explain how to simulate this bug locally

**Comment by yaoh125** [comment]
@sameemcodes 

1. Click the Dashboard menu.
2. An error occurs when you click on details in the dashboard list.

**Comment by yaoh125** [comment]
@srikanthccv Thank  you! It seems to be working normally. 👍
