### ISSUE TITLE
Async clickhouse migrations

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#5433]
Any release that involves a schema migration that mutates the old data such as the DROP column, index causes the migrations to fail frequently. This creates a dirty version issue which requires a manual intervention. This approach is not scalable when there are hundreds of tenants and it is not good for our OSS users who don't know how to address the issue. The collector does not get upgraded when the migrator fails. 

- the collector insertions fail because the half-finished schema is not compatible with the old collector version
- the migrator continues to fail because of the dirty version
- when we drop the `schema_migrations` to address the dirty migration it triggers all of the past mutations. For example, the 10th migration of logs drops the original `tokenbf` index and creates a new index with `ngram`. Now, say some migration that came after the 10th migration fails. The way we resolve this today is by dropping the `schema_migrations` table and running them again. Now the 10th migration runs again which drop the index on `ngram` and recreates on `ngram` again. The migrator can potentially fail here itself if the time taken to drop the index is beyond 180 seconds.
- The mutations triggered block even simple DDL queries that are as simple as `CREATE DATABASE`
- Then we intervene to kill the mutations which are not guaranteed to be killed immediately making the ingestion affected deterministically. 

Our internal instances of failures are known from the recent 0.49.1 but the same happened for 0.47 traces migration too and here are the past instances of community users getting affected because of this.

- Upgrade to v0.47.0 https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1717682395257909
- Upgrade to v0.49.0 https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1720054405725319

**Comment by ankitnayan** [comment]
>the collector insertions fail because the half-finished schema is not compatible with the old collector version

Please share examples when this happens
1. Drop column executed in 1 shard and not in the other 2 shards should not cause ingestion issues due to inconsistent schema as ingestion is not even trying to write in the column that is to be dropped.
2. Create column executes in 1 shard and incomplete in the other 2 shards. But as create column is non-mutation + lightweight, this should never happen?
3. Different schema at `distributed_logs` and at `logs` can cause issues when there is a pending ddl?

**Comment by srikanthccv** [comment]
> Please share examples when this happens

1. Creating a column that doesn't have a default value for fallback

> Create column executes in 1 shard and incomplete in the other 2 shards. But as create column is non-mutation + lightweight, this should never happen?

The creation of the column is not the problematic step but the subsequent operation in the current migration file that could fail.

Assume you created a new col assuming the upgrade will be smooth and the collector will start to write to column but migration failed and inserts fail because of mismatch in expected columns https://github.com/SigNoz/signoz-otel-collector/blob/main/exporter/clickhousetracesexporter/writer.go#L102 

2. Dropping a column

>Drop column executed in 1 shard and not in the other 2 shards should not cause ingestion issues due to inconsistent schema as ingestion is not even trying to write in the column that is to be dropped.

The problem is, that the collector upgrade won't happen unless the migrator job executes successfully. The problem here is collector still tries to write to a column that no longer exists.

3. Rename a column

The rename is implemented mutation is not expected to be complete immediately. The rename can succeed in one shard but not in another creating incompatibility. 

4. Update a column 

We never had to do this but the same case will happen where the collector is still writing with the old schema but the migration failed.

> Different schema at distributed_logs and at logs can cause issues when there is a pending ddl?

Yes
