### ISSUE TITLE
`server` & `client` filter needs a hint text for users to understand the use case

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#544]
New users need some context on what data these filters are used for: `server` & `client`

<img width="248" alt="Screenshot 2021-12-21 at 12 16 44 PM" src="https://user-images.githubusercontent.com/83692067/146884308-6cbe0ed4-2a3e-410f-8f47-b2f1a89302a0.png">

**Comment by pranay01** [comment]
this is not there in trace filter page UI from v0.6.0
