### ISSUE TITLE
Bug in `server` and `client` filter

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#545]
### Case I
Number of calls for `server` and `client` filter does not add up to the total.

✅ Total calls = Calls for (`server` + `client`)

Total frontend calls count at 11:46 am is 1344 as seen in the screenshot with `no filter` selected for server/client.

<img width="1233" alt="Screenshot 2021-12-21 at 12 22 27 PM" src="https://user-images.githubusercontent.com/83692067/146885013-d793f240-faaa-4719-a7b5-974842864ee1.png">

For `server` filter selected, number of calls count at 11:46 am is 56.

<img width="1232" alt="Screenshot 2021-12-21 at 12 32 11 PM" src="https://user-images.githubusercontent.com/83692067/146886127-1887ecf6-c761-4bf0-907d-f47ac8b655cb.png">

For `client` filter selected, number of calls count at 11:46 am is 672.
<img width="1230" alt="Screenshot 2021-12-21 at 12 26 55 PM" src="https://user-images.githubusercontent.com/83692067/146885531-2d4a0f06-8964-4448-bdc9-d952aadaa983.png">

Calls for (`server` + `client`) = 672 + 56 = 728 while the total calls count is 1344 with no filter selected.

### Case II
For some `endpoints`, even though total calls count is shown for no filters selected, there are no calls shown when either `server` or `client` is selected.
<img width="1227" alt="Screenshot 2021-12-21 at 12 29 25 PM" src="https://user-images.githubusercontent.com/83692067/146885817-c2fdb45d-0737-4425-9079-5f9fa81a8788.png">

<img width="1236" alt="Screenshot 2021-12-21 at 12 29 43 PM" src="https://user-images.githubusercontent.com/83692067/146885888-ab36101d-5d30-4e5f-a98a-4e5250f20de6.png">

<img width="1229" alt="Screenshot 2021-12-21 at 12 30 23 PM" src="https://user-images.githubusercontent.com/83692067/146885926-f78acae7-927d-40b2-b859-3e303fc647b9.png">

**Comment by ankitnayan** [comment]
Not building as this is not in Datadog UI or Figma
