### ISSUE TITLE
Having suggestions for `Tag Value` will make onboarding easier for first-time users

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#546]
Currently we don't show any suggestions for `Tag Value`. For a user exploring SigNoz for the first-time with data from the sample app, there is no way of knowing what to input in `Tag Value`

<img width="778" alt="Screenshot 2021-12-21 at 12 37 16 PM" src="https://user-images.githubusercontent.com/83692067/146886607-02efbe0b-93c4-4948-abbc-132f8ebfd867.png">

**Comment by makeavish** [comment]
Exists in trace explorer page
