### ISSUE TITLE
Alerts based on deviations from baseline

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#5469]
Implement alerting from deviations from mean => ( Mean + 2/3/4* sigma )

**Comment by ankitnayan** [comment]
Nice... @YounixM will you have some bandwidth to pick this up next week? If so, @srikanthccv can schedule a meet or if notion docs are enough to give an overview and get the design work started after a go-ahead on the plan

**Comment by ankitnayan** [comment]
@srikanthccv the next question I see users asking why was this alert marked anomalous! Can we have a way to send this with the API response as maybe description and also print out to logs of the QS?

**Comment by srikanthccv** [comment]
> Can we have a way to send this with the API response as maybe description

Yes, this API would return back all the context

 > also print out to logs of the QS
 
By this, I am assuming we should have the exact details of all the values printed in logs, if so, this will be needed even for us to understand. I have added some logs here https://github.com/SigNoz/signoz/compare/develop...anomaly-detection#diff-8cb0c66d798294eee45016205f530d321345767ea305d7dfc7ea3019cc1050a4R1180-R1204 but will be adding more.

**Comment by YounixM** [comment]
Yes @ankitnayan : I can pick this up next week.

**Comment by pranay01** [comment]
@YounixM is this shipped?

**Comment by srikanthccv** [comment]
This is done

**Comment by pranay01** [comment]
@srikanthccv have we also published docs for this?

**Comment by srikanthccv** [comment]
@pranay01 yes, https://signoz.io/docs/alerts-management/anomaly-based-alerts/
