### ISSUE TITLE
Add codeowners to automate PR reviewers assignment

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#547]
-  @ankitnayan for backend
- @pal-sig and @pranay01 for frontend

**Comment by pal-sig** [comment]
@00imvj00 i think github bot does this one.. based on the label

**Comment by pal-sig** [comment]
also this can be useful https://github.com/srvaroa/labeler

**Comment by pranay01** [comment]
@prashant-shahi we do have codeowners set up in the repo now right? Can this be closed

**Comment by prashant-shahi** [comment]
yes, we have codeowners set up for the repo. #633

Closing the issue.
