### ISSUE TITLE
`Latency` button use-case and labeling

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#548]
A user thought if he clicks on the `Latency` button shown in the screenshot below then the options will be things like `RPS`, `Error  Rates` as those two are other important dimensions that users like to see data by. There might be a expectation mismatch here.

<img width="729" alt="Screenshot 2021-12-21 at 12 42 13 PM" src="https://user-images.githubusercontent.com/83692067/146887227-bd663f75-8e4b-4db9-aa94-24d1086d93dc.png">

Also, we need to think about use-case for filtering data by particulate latency points. When asked, the user mentioned he will generally investigate the peak datapoints and filling in latency datapoints manually would not be a good use-case for him.

**Comment by ankit01-oss** [comment]
We can update the `Latency` label to `Choose latency` or `Choose Latency Duration` to avoid confusion

**Comment by pal-sig** [comment]
> We can update the `Latency` label to `Choose latency` or `Choose Latency Duration` to avoid confusion

@pranay01 thoughts on this one ? seems legit to me

**Comment by genzyy** [comment]
Can I take this up?

**Comment by pranay01** [comment]
@genzyy We are updating this page soon - so let's make improvement only after the updated trace filter page is released.

You can track the new trace filter page in this issue - https://github.com/SigNoz/signoz/issues/575

**Comment by pranay01** [comment]
This issue is now solved with new trace filter page released with v0.6.0
