### ISSUE TITLE
`Server` filter should be selected by default in `trace-filter` page

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#550]
As the common use case for investigating data for a particular service/endpoint is the total number of incoming requests handled by the service/endpoint, the below filter should have `server` as the default selected filter.

<img width="804" alt="Screenshot 2021-12-21 at 12 51 23 PM" src="https://user-images.githubusercontent.com/83692067/146888132-eb99ce9f-2427-4c50-a277-ac91b08928cf.png">

Currently the default is nothing selected with data shown being the sum total of calls for both `server` and `client` combined.

<img width="854" alt="Screenshot 2021-12-21 at 12 53 31 PM" src="https://user-images.githubusercontent.com/83692067/146888390-e714ca19-b3ec-43e1-ada2-be15bd688303.png">

**Comment by aryanshridhar** [comment]
Picking this up!

**Comment by palash-signoz** [comment]
Closing as there is no such option in the new UI
