### ISSUE TITLE
Allow to change column units for formula output

### ISSUE THREAD

**Issue by cmartell-at-ocp** [SigNoz/signoz#5504]
## Is your feature request related to a problem?
Yes

## Describe the solution you'd like
It would be nice if we were able to change the column units for formula outputs when using a Table panel. At the moment, it is only possible to change the units for queries (e.g. A, B, C) but not of formulas (e.g. F1, F2)

## Describe alternatives you've considered
N/A

## Additional context
In my case, I need to multiply the output of my query A by 1000 (to convert unix timestamp in seconds to milliseconds), but I'm then unable to change the unit of my formula output to Datetime.

![image](https://github.com/user-attachments/assets/4d3e00d3-b287-4cd0-a0f9-47b6c7457f75)

**Comment by Vivekcoder43** [comment]
**Add Unit Customization for Formulas**:

>  Extend the existing unit customization functionality to include formula outputs. This would allow users to set the appropriate units for any calculated values in the Table panel.

**Comment by ankitnayan** [comment]
https://github.com/SigNoz/signoz/pull/5638
