### ISSUE TITLE
Ability to edit panel when the query is running

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#5521]
The panel does not show an option when the query is running. If due to selection of a larger time period or poor query, the query takes a long time to return, there is no way to edit the panel and the query.

I am expecting the ability to edit a panel to remain even when the query for the panel is running in a dashboard

**Comment by souravpurkait360** [comment]
Can you provide some more details?

**Comment by makeavish** [comment]
Similar to https://github.com/SigNoz/signoz/issues/5702
