### ISSUE TITLE
Dashboards[FE]:  Locked indicator moves when scrolling.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#5522]
Locked indicator moves when scrolling.

Reproduce:- 
* Create 3 or more panels so that you can scroll.
* Now lock the dashboard.
* Scroll the dashboard, the `locked` highlight will move as well.

https://github.com/user-attachments/assets/769389da-963e-4c3c-95c9-b4982c400d8c

**Comment by YounixM** [comment]
@vikrantgupta25 : this is fixed right ?

**Comment by vikrantgupta25** [comment]
yes @YounixM this has been fixed

**Comment by YounixM** [comment]
Cool.. Closing the issue.
