### ISSUE TITLE
Improve QB search performance

### ISSUE THREAD

**Issue by YounixM** [SigNoz/signoz#5543]
1. All results are not shown
    `block` - should also show block_id, currently it doesn't
    
2. Filters are delayed

**Comment by YounixM** [comment]
@vikrantgupta25 : Please pick it up as part of QB improvements

**Comment by vikrantgupta25** [comment]
sure @YounixM will take care as the part of the cleanup

**Comment by vikrantgupta25** [comment]
these will be resolved when QB search v2 is released.

**Comment by vikrantgupta25** [comment]
done with v2
