### ISSUE TITLE
Allow insecure SMTP settings

### ISSUE THREAD

**Issue by EinavDanielDX** [SigNoz/signoz#5556]
## Currently, Alertmanager forces use of SSL

I'm trying to configure alertmanager SMTP settings. I run Signoz in EKS cluster which has internal email-relay platform, which means I don't require SSL configuration but this can't be done in current version of Signoz, I just get the following error:

```level=warn ts=2024-07-22T11:30:53.815Z caller=notify.go:718 component=dispatcher receiver=Test integration=email[0] msg="Notify attempt failed, will retry later" attempts=1 err="send STARTTLS command: x509: certificate is valid for localhost, not email-relay-service.my-namespace.svc.cluster.local"```

## Describe the solution you'd like
I would like to be able to disable/enable SMTP SSL using env variables such as:
ALERTMANAGER_SMTP_REQUIRE_TLS: "false"
ALERTMANAGER_INSECURE_SKIP_VERIFY: "true"

**Comment by srikanthccv** [comment]
Supported in https://github.com/SigNoz/alertmanager/pull/35
