### ISSUE TITLE
Remove refresh time filter from `trace-detail` page and show a timestamp

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#561]
Refresh Time filter is not valid for trace-detail page. We can replace it with a timestamp.

<img width="255" alt="Screenshot 2021-12-24 at 12 55 47 PM" src="https://user-images.githubusercontent.com/83692067/147329228-3b6dc597-f266-4c17-b713-d7617f51eb17.png">

**Comment by siddhantparekh** [comment]
Hey @ankit01-oss 

Which timestamp do you mean should be put in place of refresh?

**Comment by pal-sig** [comment]
> Hey @ankit01-oss
> 
> Which timestamp do you mean should be put in place of refresh?

Hi @siddhantparekh 
We need to add Trace detail in this [logic](https://github.com/SigNoz/signoz/blob/main/frontend/src/container/Header/index.tsx#L11)

**Comment by siddhantparekh** [comment]
Hey @pal-sig 

Just adding TRACE_GRAPH to the array won't work since it's a dynamic path. I've used matchPath form react-router-dom to make it work. Please check the image below out once and let me know if it will do the job.

![possible-fix](https://user-images.githubusercontent.com/24934757/147408126-49ad4ed4-4563-412d-aa4d-ed1a4f700f17.png)

**Comment by pal-sig** [comment]
> Hey @pal-sig
> 
> Just adding TRACE_GRAPH to the array won't work since it's a dynamic path. I've used matchPath form react-router-dom to make it work. Please check the image below out once and let me know if it will do the job.
> 
> ![possible-fix](https://user-images.githubusercontent.com/24934757/147408126-49ad4ed4-4563-412d-aa4d-ed1a4f700f17.png)

@siddhantparekh Yes i think this will work ... only i would suggest to use `forEach` instead of `for`

would you like to raise a PR ?

**Comment by siddhantparekh** [comment]
> > Hey @pal-sig
> > Just adding TRACE_GRAPH to the array won't work since it's a dynamic path. I've used matchPath form react-router-dom to make it work. Please check the image below out once and let me know if it will do the job.
> > ![possible-fix](https://user-images.githubusercontent.com/24934757/147408126-49ad4ed4-4563-412d-aa4d-ed1a4f700f17.png)
> 
> @siddhantparekh Yes i think this will work ... only i would suggest to use `forEach` instead of `for`
> 
> would you like to raise a PR ?

I did try forEach but it wasn't reflecting the bool which was returned by the function in the render. I didn't debug it yet but ended up writing a for to make it work. I'll raise a PR with the current version for now.

**Comment by pal-sig** [comment]
> Add fix Logic for trace graph #577

yes return does not work in forEach

ok will check this PR
