### ISSUE TITLE
No pagination for any table in the entire product

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#5624]
I am guessing the default pagination is removed from the table component and it affected everything (dashboards, services overview, etc...). This makes the experience bad because there can be several 100s of values in tables and also makes the page render slowly.

To reproduce visit any service with a high number of operations. Or see this [dashboard](https://stagingapp.signoz.io/dashboard/eef4a4b3-dc71-42fb-8f4e-25d01c552110/new?widgetId=05586181-91ab-49a1-8524-765beec9556a&graphType=table&compositeQuery=%7B%22builder%22%3A%7B%22queryData%22%3A%5B%7B%22aggregateAttribute%22%3A%7B%22dataType%22%3A%22float64%22%2C%22id%22%3A%22signoz_calls_total--float64--Sum--true%22%2C%22isColumn%22%3Atrue%2C%22isJSON%22%3Afalse%2C%22key%22%3A%22signoz_calls_total%22%2C%22type%22%3A%22Sum%22%7D%2C%22aggregateOperator%22%3A%22rate%22%2C%22dataSource%22%3A%22metrics%22%2C%22disabled%22%3Afalse%2C%22expression%22%3A%22A%22%2C%22filters%22%3A%7B%22items%22%3A%5B%5D%2C%22op%22%3A%22AND%22%7D%2C%22functions%22%3A%5B%5D%2C%22groupBy%22%3A%5B%7B%22dataType%22%3A%22string%22%2C%22id%22%3A%22service_name--string--tag--false%22%2C%22isColumn%22%3Afalse%2C%22isJSON%22%3Afalse%2C%22key%22%3A%22service_name%22%2C%22type%22%3A%22tag%22%7D%2C%7B%22dataType%22%3A%22string%22%2C%22id%22%3A%22operation--string--tag--false%22%2C%22isColumn%22%3Afalse%2C%22isJSON%22%3Afalse%2C%22key%22%3A%22operation%22%2C%22type%22%3A%22tag%22%7D%2C%7B%22dataType%22%3A%22string%22%2C%22id%22%3A%22http_status_code--string--tag--false%22%2C%22isColumn%22%3Afalse%2C%22isJSON%22%3Afalse%2C%22key%22%3A%22http_status_code%22%2C%22type%22%3A%22tag%22%7D%2C%7B%22dataType%22%3A%22string%22%2C%22id%22%3A%22signoz_collector_id--string--tag--false%22%2C%22isColumn%22%3Afalse%2C%22isJSON%22%3Afalse%2C%22key%22%3A%22signoz_collector_id%22%2C%22type%22%3A%22tag%22%7D%5D%2C%22having%22%3A%5B%5D%2C%22legend%22%3A%22%22%2C%22limit%22%3Anull%2C%22orderBy%22%3A%5B%5D%2C%22queryName%22%3A%22A%22%2C%22reduceTo%22%3A%22avg%22%2C%22spaceAggregation%22%3A%22sum%22%2C%22stepInterval%22%3A60%2C%22timeAggregation%22%3A%22rate%22%7D%5D%2C%22queryFormulas%22%3A%5B%5D%7D%2C%22clickhouse_sql%22%3A%5B%7B%22disabled%22%3Afalse%2C%22legend%22%3A%22%22%2C%22name%22%3A%22A%22%2C%22query%22%3A%22%22%7D%5D%2C%22id%22%3A%228eaa006e-6e81-4328-ad7f-2c277176cb40%22%2C%22promql%22%3A%5B%7B%22disabled%22%3Afalse%2C%22legend%22%3A%22%22%2C%22name%22%3A%22A%22%2C%22query%22%3A%22%22%7D%5D%2C%22queryType%22%3A%22builder%22%7D&relativeTime=1d) for example with one day time range

**Comment by YounixM** [comment]
Merged ✅
