### ISSUE TITLE
For smaller spans, time shown in gantt charts gets in a vertical column

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#563]
For smaller spans, the time shown in ms is getting elongated in a vertical line.

<img width="872" alt="Screenshot 2021-12-24 at 1 00 15 PM" src="https://user-images.githubusercontent.com/83692067/147329613-63afba51-7391-42bd-8c4e-b26655beb098.png">

**Comment by pranay01** [comment]
fixed by https://github.com/SigNoz/signoz/pull/764 - Updated trace detail page design
