### ISSUE TITLE
feat: Configure Puppeteer in Docker

### ISSUE THREAD

**Issue by palash-signoz** [SigNoz/signoz#564]
@ankitnayan https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker

_Originally posted by @pal-sig in https://github.com/SigNoz/signoz/issues/508#issuecomment-1000707088_

**Comment by rahulrana95** [comment]
@pal-sig we can use playwright which is built at top of pupetter

**Comment by pal-sig** [comment]
> @pal-sig we can use playwright which is built at top of pupetter

Hi @rahulrana95 i think we won't be going ahead with the Puppeteer as there is another issue which solve the critical css part

ref: https://github.com/SigNoz/signoz/issues/569

**Comment by pranay01** [comment]
@palash-signoz Should we close this issue as #569 is already merge?

**Comment by palash-signoz** [comment]
Yes Closing
