### ISSUE TITLE
FullView `Refresh` button within Dashboard panel isn't working.

### ISSUE THREAD

**Issue by aryanshridhar** [SigNoz/signoz#574]
## Bug description

While working on another issue I came up with this bug as - The `Refresh` button within a specific dashboard (when in FullView) isn't working as expected.

## Expected behavior
The application metric should refresh which would update the graph.

## Screenshot
![Screenshot 2021-12-29 at 10 50 50 PM](https://user-images.githubusercontent.com/53977614/147687831-fdf0a54a-1c25-4e0f-bbc2-efbccbbbeb72.png)

(The `Refresh` button on upper top right corner should update the metrics)

## How to reproduce

1. Navigate to any application in dashboard.
2. Click on the `FullView` icon to view the graph in a dedicated modal.
3. Click the refresh button.

## Version information 
* **Signoz version**: 0.5.4
* **Browser version**: 95.0.2 (64-bit)
* **Your OS and version**: macOS Monterey 12.1

**Comment by pranay01** [comment]
@aryanshridhar Can you share a loom video/screen capture of the issue, not very clear from a screenshot

**Comment by aryanshridhar** [comment]
@pranay01 Yup thought of doing that, but seems like my loom free trial is over!

**Comment by aryanshridhar** [comment]
Let me see if I can debug this today!

**Comment by pranay01** [comment]
@aryanshridhar the new datapoints only come every minute. Can you try waiting for around a minute and then try refreshing?
Exiting full screen view, changes the time period to 5min automatically which causes the graph to refresh.
Changing automatically to 5 min is a bug - https://github.com/SigNoz/signoz/issues/481

cc: @pal-sig

**Comment by aryanshridhar** [comment]
The Refresh button still isn't working (after waiting for a min) when set to `Global Time`.

**Comment by aryanshridhar** [comment]
Found the previously opened issue - #388.

**Comment by pranay01** [comment]
@pal-sig Was able to duplicate this issue in the latest release as well. Can you check this

**Comment by pal-sig** [comment]
> @pal-sig Was able to duplicate this issue in the latest release as well. Can you check this

Raised a PR for this issue https://github.com/SigNoz/signoz/pull/590 Thanks @aryanshridhar for the issue


as the issue is only with the Global Selected Filter in which min max time is same

**Comment by aryanshridhar** [comment]
Awesome!
