### ISSUE TITLE
Bug in dashboard rename

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#5780]
https://www.loom.com/share/f072b0cf0c744892bb6ea38ff9fcca6a?sid=3e158cb6-e754-4d7d-9fd8-b0121bb09014

**Comment by abhi12299** [comment]
can i be assigned to this?

**Comment by makeavish** [comment]
> can i be assigned to this?

Assigned

**Comment by abhi12299** [comment]
@makeavish please review the PR

**Comment by makeavish** [comment]
> @makeavish please review the PR

Hey @abhi12299 Thanks for your PRs

Someone from FE team will be reviewing these PRs soon.

**Comment by SagarRajput-7** [comment]
done under this - https://github.com/SigNoz/signoz/pull/5821
