### ISSUE TITLE
 Cloudformation and terraform module to integrate with AWS

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#5784]
Honeycomb has similar module:
<img width="872" alt="Screenshot 2024-08-28 at 10 58 54" src="https://github.com/user-attachments/assets/c553c8d7-00ec-4b84-9255-60c8721c324b">

https://docs.honeycomb.io/integrations/aws/

**Comment by godwintrav** [comment]
Hi @makeavish I can work on this. Can you elaborate more on what needs to be done

**Comment by makeavish** [comment]
> Hi @makeavish I can work on this. Can you elaborate more on what needs to be done

Hey @godwintrav 
Please a look at the issues with the "help-wanted" or "good-first-issue" label. If an issue is not labelled with those tags, then they are not up for grabs as it would require too much context.

**Comment by Calm-Rock** [comment]
Current Update: 
This is being picked up by Shruti.

She is researching different methods in which we can do this and will list them down along with any questions she has for each method.

Meanwhile @eKuG is also looking into this.

**Comment by Calm-Rock** [comment]
Update: This will be picked up by @raj-k-singh, along with the integrations.

**Comment by Calm-Rock** [comment]
Closing this issue since we won't be proceeding with this.
