### ISSUE TITLE
Panel style updates

### ISSUE THREAD

**Issue by GeekBoySupreme** [SigNoz/signoz#5788]
Besides the visual update, there are 2 more things that need to be taken care of in panels -
- How the controls show up when hovered over the panel (with the consideration that panels are resizable and the controls should expose based on the panel size)
- Improving legends
- Improving the tooltips

We currently have 2 types of visualization panels on the console : 
**Category I** ⎯ The ones custom-built in dashboard (by users)
**Category II** ⎯ The ones we show by default in pages like `Services` (by us)
In the second category, we have more control over how the chart and its colours render, also it'd have less configurability. This issue primarily tackles how the general appearance and functioning of panels and options happen in the dashboard - the ones made by the user : **Cat I**

A lot of these scenarios would be carried over the panels of **Cat II** mentioned above 👆🏼. These panels would have more enhancements and tweaks that would be picked up as and when the relevant pages (for APM and infra-monitoring are picked up).

Here is the Figma with the [details](https://www.figma.com/design/HMJO1IdO8Yxj1lZcaHMCP1/Dashboards?node-id=2988-8879&t=JWn6EsvSc03Y0BJw-1) ⎯ and the [Prototype](https://www.figma.com/proto/HMJO1IdO8Yxj1lZcaHMCP1/Dashboards?page-id=2988%3A8477&node-id=2988-8478&viewport=705%2C384%2C0.2&t=Aqewq5buy75DlefX-8&scaling=min-zoom&content-scaling=fixed&hide-ui=1).

https://github.com/user-attachments/assets/57d4955b-4d49-4a5f-9778-9b643a8941eb

### Notes for **Panel controls** : ###
- The controls become visible on hovering over the panel.
- We would currently show 2 quick options (`Copy link` and `Expand`) which can be modified and replaced with other more relevant options. 
- An info icon to show panel details would show the description in a tooltip on hover. This icon need not be visible if a panel does not have a description (user has not added a description). All default SigNoz-defined panels should have a prewritten description.
- An ellipsis button to expose more options.
- A small icon on the bottom right corner. The mouse pointer can be changed to this 👇🏼 (basically adding more visual affordance and a bit of delight : [Notes for frontend](https://www.freecodecamp.org/news/how-to-make-a-custom-mouse-cursor-with-css-and-javascript/#:~:text=To%20use%20this%2C%20you%20just,URL%20using%20the%20url%20value.&text=From%20the%20code%20snippet%20above,image%20specified%20in%20url()%20.)
![image](https://github.com/user-attachments/assets/2a0c9b3a-6d15-449e-8588-bf9d190452b9)

### Notes for **Table panel** : ###

https://github.com/user-attachments/assets/6a5db2fd-c43c-4dee-a189-8e83a8162af4

- For columns that can be sorted, the interaction is laid out above 👆🏼 
- The elements in the first row are colored robin because I wanted them to be treated as links - that the user can click on the entire row and would be taken to the relevant correlated view. If the rows and the first column elements are not clickable, they should be colored a more neutral vanilla-100.
- The pagination structure has been slightly changed to look cleaner.
- For columns with defined units, the units need to be shown inside a pill, the way we have shown `% of total` in the prototype above 👆🏼 
- The first column has a slightly different background because it is supposed to be fixed while the panel scrolls horizontally. Vertically even the first column stays in place and scrolls vertically. In both cases, we don't need to show the scrollbars in the panel unless the user is actually scrolling.
- The highlighted area inside the panel reflect the area that is supposed to be scrollable (except the first column which stays fixed) - the column needs to be fixed so that when the users scroll to see values of other columns to the right, the retain context of what entity they're seeing the value of.
<img width="726" alt="image" src="https://github.com/user-attachments/assets/ae393717-8c1e-42b9-943a-5c21fde52f98">

The horizontally scrolled state looks like this 👇🏼 
![image](https://github.com/user-attachments/assets/a8ed1c8c-7911-4f60-8113-7ad6b793cf1f)

### Notes for **Time series** and other charting panels : ###
- The vertical gridlines in the time series panels have been removed to make the charts look cleaner. We just have the horizontal gridlines.
- While hovering, the horizontal crosshair line has been removed. We only show the vertical gridline only.
Removing one kind of gridline in both these cases helped make the panel look cleaner.
- Note that the new color of the gridlines in both the scenarios are significantly lighter to afford guidance but also does not become noisy.

#### Legends ####

https://github.com/user-attachments/assets/ad068854-862c-4867-ba56-fc83fe9dd15c

The legends are restricted to have 2 lines. Any more items that are condensed inside a `+n more` button. In our current state you often have a small vertical area that you can scroll through to see legends, which looks and feels really bad.

#### Tooltips ####

![image](https://github.com/user-attachments/assets/b53789ef-e062-4b03-89b2-fd054c7887b4)

The tooltips have been cleaned up to show the legends and values in a much more structured way.

We currently allow users to click on a point in panels under APM monitoring to show the option of `View Traces`. To allow seamless and better correlation, we should show that option across all panels and data types that allow us to do the same, or show whichever is available. 
- The new tooltip shows those options wherever relevant even without clicking, clicking at a point simply locks the tooltip in place and you can go click on the option to `View trace` or `View related logs`. 
- Since the options are also visible on hover, the user, while hovering, can hit the mentioned key on the keyboard to go to related logs or traces, without having to take the extra clicking burden.

![image](https://github.com/user-attachments/assets/3a5dab48-127d-4b92-8b1f-dfa7b0162ee1)

#### Timebrush ####

<img width="785" alt="image" src="https://github.com/user-attachments/assets/0a5d04b6-34b1-4743-84d8-bdbdafc39e11">

Currently, the charts shown under `Services` allow the users to select a sub timeframe from a chart and that reflects across all the charts, this has been an oft-requested user feature too for the dashboard time series panels. The issues we have addressed and enhanced here here -
- Currently, the highlighted section is not properly visible, we are adding some color to the selection to make it apparent what the selected portion is.
- On [`mousedown`](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousedown_event) event in the chart, we should assume that the user is about to drag and select an area and stop showing the tooltip then. Currently the tooltip remains visible while dragging and adds noise. We can show the tooltip again when the selection is over - on `mouseup` event (if the hover interaction is still active)
- A new button for reset gets added to the controls and does not completely withdraw with the other tools. It remains visible even without hovering on the panel.

![image](https://github.com/user-attachments/assets/c0f71164-db6e-4ab0-aaba-906fa08f2df2)

### Extra notes ###

- A question might arise that since the custom time selection with the timebrush affects the timepicker, shouldn't we place the reset option near the timepicker - as that would allow all the panels to be reset at once : and yes, we can definitely do that. If we follow that approach, I can tweak the timepicker design to accommodate a reset button that activates whenever a timebrush is used.
- The spacing between `the top row with the panel name and controls` and the chart itself is 20px
<img width="887" alt="image" src="https://github.com/user-attachments/assets/ac655830-fefe-4576-b8a7-82b9ba773716">

**Comment by GeekBoySupreme** [comment]
@srikanthccv @SagarRajput-7 take a look. I have detailed out the behaviours in the description. A lot of the pointers mentioned for time series panel also apply to the pie chart, histogram, horizontal and vertical bar charts too (which is why I did not add them separately).

We can do something a bit more fun and delightful and outrageous for the timebrush (time selection interaction) :P 
![image](https://github.com/user-attachments/assets/690ff2c2-7775-4e6c-b5dc-f17cd6bd19b7)

As if the hands are opening the chart up for further inspection. The hand on the left is hard coded into the starting line, while the mouse pointer becomes the second hand on the right.

**Comment by srikanthccv** [comment]
## Panel controls

>We would currently show 2 quick options (Copy link and Expand) which can be modified and replaced with other more relevant options.

Please also include edit by default.



## table

>If the rows and the first column elements are not clickable, they should be colored a more neutral vanilla-100.

The row should be clickable because than individual entry because when there are multiple columns, which is very common, we should be able to show the correlations based on all the relevant context. 

>For columns with defined units, the units need to be shown inside a pill, the way we have shown % of total in the prototype above 👆🏼


Please help me understand more details about this. Is the idea that unit will be at the header but not in the cell? If so, I do not think this is a good idea because the formatted values would not be uniform in nature. Take an example the unit of measurement for latency is ms. Depending on the service latency can be different. Some could have 100ms latency and on average few services could have like 3.5s and one or two services with some outliers having 1.5 min so it's important to show the unit in the cell. 

>The first column has a slightly different background because it is supposed to be fixed while the panel scrolls horizontally.

To make it generic, all the labels columns should be fixed and numeric columns should be scrollable.

>Vertically even the first column stays in place and scrolls vertically. In both cases, we don't need to show the scrollbars in the panel unless the user is actually scrolling.

This is not clear. What does _first column stays in place_ mean?

### additional points to considee in design

1. Ability to search in table globally or per column.

2. How should table view deal with long values for label columns: example https://github.com/SigNoz/engineering-pod/issues/1691.

3. Width of the columns and how to adjust them.


## time series

>We only show the vertical gridline only.
>Removing one kind of gridline in both these cases helped make the panel look cleaner.

Please update the video, it's not playing and I don't fully understand the interaction here.

>The legends are restricted to have 2 lines. Any more items that are condensed inside a +n more button. In our current state you often have a small vertical area that you can scroll through to see legends, which looks and feels really bad.

We should have the ability to see the legends on the right side of the chart because sometimes the labels are very long and we cannot see more than 1 legend combination. 


>The tooltips have been cleaned up to show the legends and values in a much more structured way.

This is fine when there is no custom legend format. But if users has custom legend format, we won't show the same structure highlighted in the design.


>We currently allow users to click on a point in panels under APM monitoring to show the option of View Traces. To allow seamless and better correlation, we should show that option across all panels and data types that allow us to do the same, or show whichever is available.

We won't be doing this for now because it's a independent work on its own. But from design perspective, I agree we should show all options avaialble.

>The new tooltip shows those options wherever relevant even without clicking, clicking at a point simply locks the tooltip in place and you can go click on the option to View trace or View related logs.

The usual requirement is to click on the specific point in time and line and see the traces/logs. So that should be the main interaction to target for.

### Timebrush

>Currently the tooltip remains visible while dragging and adds noise. We can show the tooltip again when the selection is over - on mouseup event (if the hover interaction is still active)


Which tooltip is this referring to?

**Comment by srikanthccv** [comment]
Also please skim through the issues mentioned here https://github.com/SigNoz/signoz/issues/5598

**Comment by GeekBoySupreme** [comment]
> Please also include edit by default.

Note for @SagarRajput-7 : The interactions remain the same, you can just substitute out the `copy link` CTA with the `Configure` option.

> The row should be clickable because than individual entry because when there are multiple columns, which is very common, we should be able to show the correlations based on all the relevant context.

Yes, the row would be clickable (but we are not picking it up right away. Would take this up when we allow rows to be clickable)

> Is the idea that unit will be at the header but not in the cell?

This is for when we start allowing normalizing a column to have a single unit. Not necessary for now.

> To make it generic, all the labels columns should be fixed and numeric columns should be scrollable.

Yes. Correct.



> 1. Ability to search in table globally or per column.

You can now do that.

https://github.com/user-attachments/assets/a9e2a4b8-2a43-4893-8ce9-1da7a23dfd75

>How should table view deal with long values for label columns: example https://github.com/SigNoz/engineering-pod/issues/1691.

We limit a max width and then add ellipsis. Before it reaches ellipsis, we chunk them down to 3 lines (I don't think we allow number of lines to be controlled here, but if we do, let them define the max number. 3 is an arbitrary limit we're setting by default. The user should be able to change that as necessary).


> 3. Width of the columns and how to adjust them.

We should allow them to change the column width in the edit panel screen. Not in the panel itself.

> Please update the video, it's not playing and I don't fully understand the interaction here.

Explained on the call. We remove unnecessary gridlines in the chart background and while hovering. @SagarRajput-7 we essentially remove the vertical gridlines on the panel, and just retain the horizontal gridline. And while hovering on the panel, we just show the dotted vertical gridline, not the horizontal.


> We should have the ability to see the legends on the right side of the chart because sometimes the labels are very long and we cannot see more than 1 legend combination.

We would have both. For panels with sufficient width to render the legends on the right, we would shift them to the bottom as defined. What should be this width for this layout shift, I'd leave it up to you @srikanthccv @SagarRajput-7. The legend shifts to the bottom when the panel is resized to smaller than the specified width. The legends on the size should be at a distance of 20px from the edge of the chart, and have a spacing of 16px from the right edge.

> But if users has custom legend format, we won't show the same structure highlighted in the design.

Does not change anything. The legend would always be a combination of color, label, and value. The user defining a custom legend is essentially just editing the label.

> We won't be doing this for now because it's a independent work on its own. But from design perspective, I agree we should show all options available.

Fair. This is not getting picked up right away. More relevant for panels under services.

> Which tooltip is this referring to?

The tooltip that comes up when you are hovering on the chart. When the mouse is pressed and dragged, we don't need to show the tooltip.

**Comment by GeekBoySupreme** [comment]
> https://github.com/SigNoz/signoz/issues/5366#issuecomment-2194020181

This is handled in the legend design I have sent.


Also, in case you folks want to build column-specific search -

https://github.com/user-attachments/assets/b74a5221-c013-40db-aa0a-ecd93dcf01d6
