### ISSUE TITLE
Show total number of widgets in collapsed section

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#5815]
The current UI doesn't show the number of widgets when the row group is collapsed. Show the count of widgets for the collapsed section like `<Section name> (10 widgets)`
![Screenshot 2024-08-31 at 9 13 12 AM](https://github.com/user-attachments/assets/70756da8-58e8-42d9-aae9-662962686acc)

**Comment by Jeetch8** [comment]
Hii, can you assign me this issue.
Please

**Comment by Jeetch8** [comment]
Hii,
Can you please elaborate on where does this component is located

**Comment by YounixM** [comment]
@Jeetch8 : Thanks for your interest in contributing to this PR. I see there is a PR open for this already.
