### ISSUE TITLE
docs: Tutorial for Instrumentation for PHP web apps

### ISSUE THREAD

**Issue by ceefour** [SigNoz/signoz#582]
PHP looks like a less mature OpenTelemetry implementation, but it exists: https://github.com/open-telemetry/opentelemetry-php#installation

If possible, additional instrumentation tutorial for these popular frameworks would be helpful:

1. [Zend Framework 3](https://framework.zend.com/learn)
2. [WordPress](https://wordpress.org/)
3. [Silverstripe](https://www.silverstripe.org/)
4. [Symfony](https://symfony.com/)

**Comment by pranay01** [comment]
@pranshuchittora Can you create docs and blogs based on the examples you have tried for PHP apps

**Comment by pranay01** [comment]
https://signoz.io/docs/instrumentation/php/ - this is fixed now

**Comment by ceefour** [comment]
Awesome!
