### ISSUE TITLE
Get the id for newly created alert from the API response and redirect it to the cloned alert

### ISSUE THREAD

**Issue by ahmadshaheer** [SigNoz/signoz#5866]
when we want to duplicate/clone an alert, the current behavior is that we fetch all alerts and redirect to the last one. a better option will be to redirect to the newly created alert using the alert id that we get in the response of create alert API.

**Comment by ahmadshaheer** [comment]
@srikanthccv, please let me know when this API change is done. we need the id of the newly created/updated alert in the response after the creation/updating is successful .

**Comment by srikanthccv** [comment]
@ahmadshaheer I see the create call is already returning a data object which contains the `id`. The update should not return back anything except success https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.6. You already know the resource you updated so why do you need it from the API?
