### ISSUE TITLE
Ability to save columns also with views in logs

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#5882]
Usecase based on this reddit discussion

![github-logs](https://github.com/user-attachments/assets/49e96106-e56c-4594-bfed-1279513c7405)

**Comment by KieranP** [comment]
Was about to create a ticket for the same thing. Viewing application logs requires different column data than viewing syslogs for example. So being able to save which columns are selected along with the query would be most helpful.

**Comment by daniel100097** [comment]
I need this too 😅
