### ISSUE TITLE
Helm uninstall isn't cleaning chi-signoz-cluster-0-0-0 pod

### ISSUE THREAD

**Issue by ybettan** [SigNoz/signoz#589]
## Bug description

Helm uninstall isn't cleaning chi-signoz-cluster-0-0-0 pod

## Expected behavior

Helm uninstall should remove all the resources created by the chart upon `helm install`

## How to reproduce

1. `helm install signoz deploy/kubernetes/platform -n platform --create-namespace`
2. wait for all the pods to be in `Running` state
3. `helm uninstall signoz -n platform`

```
root signoz (main) $ oc get pods -n platform -w
NAME                                READY     STATUS        RESTARTS   AGE
chi-signoz-cluster-0-0-0            1/1       Running       0          1h
otel-collector-7749b4bd9d-fxhbt     0/1       Terminating   3          1h
clickhouse-operator-8cff468-fn2vl   0/2       Terminating   0          1h
signoz-frontend-5f974845cb-k7r7v    0/1       Terminating   0          1h
signoz-frontend-5f974845cb-k7r7v   0/1       Terminating   0         1h
signoz-frontend-5f974845cb-k7r7v   0/1       Terminating   0         1h
clickhouse-operator-8cff468-fn2vl   0/2       Terminating   0         1h
clickhouse-operator-8cff468-fn2vl   0/2       Terminating   0         1h
otel-collector-7749b4bd9d-fxhbt   0/1       Terminating   3         1h
otel-collector-7749b4bd9d-fxhbt   0/1       Terminating   3         1h
```

## Version information 
* **Signoz version**:
* **Browser version**:
* **Your OS and version**:

**Comment by pranay01** [comment]
@prashant-shahi Does this issue still persist after latest helm chart improvements?

**Comment by prashant-shahi** [comment]
@pranay01 yes, we still have this issue because of ClickHouse operator and associated resources aren't deleted when helm release is deleted.

Unfornately for removing the same, we will have to either manually `kubectl delete` those resources or delete the namespace itself.

```bash
kubectl delete namespace platform
```

Read more here: https://signoz.io/docs/operate/kubernetes/#uninstall

**Comment by pranay01** [comment]
I see. So this is something which can't be fixed @prashant-shahi - and we can close this issue as we have noted this in docs 

or are there ways to fix this?

**Comment by prashant-shahi** [comment]
@pranay01  Now, that I think of it again.
We could actually use label filter with `clickhouse.altinity.com/app=chop` to delete all Clickhouse Operator items.

```bash
# uninstall helm release
helm -n platform uninstall "my-release"

# deletes PVCs (except for clickhouse pvc)
kubectl -n platform delete pvc --selector app.kubernetes.io/instance=my-release

# deletes all components by Clickhouse Operator
kubectl -n platform delete all,svc,cm,pvc -l "clickhouse.altinity.com/app=chop"
```

**Comment by prashant-shahi** [comment]
Appropriate uninstall instructions have been included in our K8s Operate docs: https://signoz.io/docs/operate/kubernetes/#uninstall
