### ISSUE TITLE
"Import JSON" with blank uuid creates unreachable new dashboard

### ISSUE THREAD

**Issue by Rindrics** [SigNoz/signoz#5976]
## Bug description

Although "Import JSON" with blank uuid although causes error (Fig. 1),
- it creates invalid table row whose link target does not ends with dashboard uuid (Fig. 2, need reloading page after closing JSON editor) 
- the `dashboards/[id]` page of the new dashboard is unreachable because its URL is the same with `dashboards/` page 
- the created table row cannot be deleted (Fig. 3 & 4)

##### Fig. 1
<img width="983" alt="image" src="https://github.com/user-attachments/assets/ddaf552d-e11c-47f5-bcc5-7ab09d84958e">

##### Fig. 2
<img width="926" alt="image" src="https://github.com/user-attachments/assets/987ca53d-1053-43e2-859f-378b94d79c64">

##### Fig. 3

<img width="980" alt="image" src="https://github.com/user-attachments/assets/7cf84d0c-985c-4736-b46c-68ae9a8ccb97">

##### Fig. 4

<img width="949" alt="Screenshot 2024-09-15 at 2 56 16" src="https://github.com/user-attachments/assets/39bfc514-71ab-4f3c-9201-200c3d42bf77">

## Expected behavior

- Importing JSON definition with blank uuid (or any other nonexistent uuid) should not create new dashboard
- Every table row in dashboard list page
  - should have valid link target that ends with target dashboard uuid (Fig. 5)
  - can be deleted if needed to

##### Fig. 5

<img width="919" alt="image" src="https://github.com/user-attachments/assets/441bffe9-458c-42cf-acff-aaf40c58cfbb">

## How to reproduce

1. create an original dashboard from "+New dashboard" >> "Create dashboard"
2. get dashboard definition in JSON format by clicking "Copy as JSON" or "Export JSON"
3. insert the obtained JSON into the JSON editor by clicking "+New dashboard" >> "Import JSON"
4. set the dashboard ID to an empty string, I mean `uuid = ""`
5. press "Import and Next"
  - error message appears and no screen transition
6. close the JSON editor by close button ("x" on topright) and reload dashboard list page
7. confirm a new dashboard row on the top of the dashboard list
8. confirm the link to the added dashboard is `{BASE_URL}/dashboard/` (I mean no uuid in the URL tail)
9. confirm clicking on this dashboard link only reopens the very same screen, and you cannot delete this dashboard link.

## Version information 
* **Signoz version**: v0.54.0
* **Browser version**: Google Chrome Version 128.0.6613.121 (Official Build) (x86_64)
* **Your OS and version**: macOS 13.6.7
* **Your CPU Architecture**(ARM/Intel): Intel

**Comment by Rindrics** [comment]
I tried to working on this, but found that test on query-service fails by default.
I think adding CI with test on query-service may be a good idea.

**Comment by SagarRajput-7** [comment]
Fixed under this - https://github.com/SigNoz/signoz/pull/6145
