### ISSUE TITLE
[Dashboard Request] KEDA

### ISSUE THREAD

**Issue by grandwizard28** [SigNoz/signoz#6019]
## Dashboard Name

KEDA Monitoring Dashboard

---

#### Section: Cloud Event Metrics

---

## Expected Dashboard Variables (Add as available)

- `deployment.environment`
- `namespace`
- `scaler.name`
- `scaledobject.name`
- `job.name`

---

## Additional Comments or Requirements

- The dashboard should include panels that focus on both the scaler activity and resource health, with emphasis on errors, latencies, and queue states to help identify bottlenecks in KEDA's scaling operations.

---

## 📋 Notes

Please review the [CONTRIBUTING.md](https://github.com/SigNoz/dashboards/blob/main/CONTRIBUTING.md) for guidelines on dashboard structure, naming conventions, and how to submit a pull request.

Use official KEDA otel exporter: https://keda.sh/docs/2.15/integrations/opentelemetry/

Refer to KEDA grafana dashboard for reference: https://github.com/kedacore/keda/blob/main/config/grafana/keda-dashboard.json

**Comment by wardahub-design** [comment]
maybe this will help
https://bit.ly/4evXrQ6

you may need to install the c compiler

**Comment by hackerup** [comment]
wow

**Comment by its-samarth** [comment]
what's the data source for this dashboard? @makeavish @grandwizard28

**Comment by prajwalsangole777** [comment]
/attempt #6019 
Plan:-
Set Up KEDA and OpenTelemetry
Variables: Include filters like deployment.environment, namespace, scaler.name, scaledobject.name, and job.name.
Panel Design
Build with Grafana
Testing & Refinement

**Comment by makeavish** [comment]
@prajwalsangole777 You don't have to build with Grafana, please read issue carefully and contributing docs as well: https://github.com/SigNoz/dashboards/blob/main/CONTRIBUTING.md

**Comment by animeshd9** [comment]
@makeavish i have too made a pull request a few days back. Did you check my pr ?
