### ISSUE TITLE
FE: Remove dock-able sidebar

### ISSUE THREAD

**Issue by YounixM** [SigNoz/signoz#6073]
Sidebar should be in undocked state always and should expand only on hover.

**Comment by sahilpatel342** [comment]
Hello I would like to take a shot at this. I am fairly new to open source and think this is a great issue for me to tackle. Any additional information or guidance would be appreciated.

**Comment by motuz0001** [comment]
Hi, I would like to take this issue and try to fix it. It would be part of my school project

**Comment by iamvinayvk** [comment]
@YounixM  I think it is updated in #6083.

**Comment by YounixM** [comment]
Yes @iamvinayvk , this has already been fixed.

**Comment by YounixM** [comment]
@motuz0001 : Let me share a few good first issues with you, you can pick the ones you are comfortable with
