### ISSUE TITLE
CSS scoping issue in the query builder dropdown.

### ISSUE THREAD

**Issue by sudeepSigNoz** [SigNoz/signoz#6118]
This issue occurs only on the first page load. If the user refreshes the page, the layout renders properly. The following files are involved:
frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.styles.scss
frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/QueryBuilderSearch.styles.scss
Both files share the CSS rule for the .content {...}  class. When a user navigates from another page where LogsFormatOptionsMenu.styles.scss  is already loaded in the DOM, the outdated .content {...} styling will be applied the first time the user clicks on the filter.
An easy fix would be to rename the class and move the style rules into the new class to avoid conflicts.
You can refer to more information on global scope and the cascading nature of CSS for further reading
https://css-tricks.com/regarding-css-global-scope/#:~:text=The%20global%20nature%20of%20CSS,properties%20walk%20into%20a%20bar.

**Comment by sharpshooter90** [comment]
cc @vikrantgupta25

**Comment by sharpshooter90** [comment]
![image](https://github.com/user-attachments/assets/7c55c6a7-bc70-4beb-976b-607c8a676274)

**Comment by vikrantgupta25** [comment]
unable to replicate the issue, @sharpshooter90 can you please add more details around the same? Thanks!

**Comment by sharpshooter90** [comment]
@Vikrant CSS global scope is a tricky one, I have documented the ways to reproduce this here
https://www.loom.com/share/f690c97d6c4e4a14a7383b01d07fdeec?sid=fd257dda-0545-400f-aee3-aed9f4f4e24e
