### ISSUE TITLE
Wrong timeline selected for `Go to related logs` functionality from traces

### ISSUE THREAD

**Issue by Dhruv-Garg79** [SigNoz/signoz#6124]
## Bug description

When we use `Go to related logs` from the traces detail page, the timeline selected is wrong many times, as when I change the timelines logs are visible.

![Screenshot 2024-10-05 at 4 09 20 PM](https://github.com/user-attachments/assets/0c7a5aef-8ba5-4dce-9777-ab8a03240007)

## Expected behavior

The timeline selected should be correct so that logs are properly visible.

## How to reproduce

1. Go to traces
2. Click on any trace
3. Then click on go to related logs
4. Check if the timeline selected is correct or not (this happens on random, not for all traces/logs)

## Version information 
* **Signoz version**: 0.54
* **Browser version**: Chrome - Version 128.0.6613.138
* **Your OS and version**: MacOS 14.6.1
* **Your CPU Architecture**(ARM/Intel): ARM

## Additional context
Signoz is deployed on m6a machines on EKS and uses amazon linux 2

**Comment by pranay01** [comment]
@YounixM @vikrantgupta25 is this issue fixed? Can we close the issue, if yes?

**Comment by Dhruv-Garg79** [comment]
just verified that this issue still persists as of v0.61.0 release

**Comment by vikrantgupta25** [comment]
Fixed the issue here - https://github.com/SigNoz/signoz/pull/6634
