### ISSUE TITLE
sample-application is "ready" k8s wise before it is actually ready.

### ISSUE THREAD

**Issue by ybettan** [SigNoz/signoz#613]
## Bug description

sample-application doesn't have a readiness prob, therefore, it gets traffic as soon as the container is up but the sample application needs a better readiness prob that will ensure that the app is ready to get traffic.

## Expected behavior
```
kubectl -n sample-application run strzal --image=djbingham/curl \
  --restart='OnFailure' -i --rm --command -- curl -X POST -F \
  'locust_count=6' -F 'hatch_rate=2' http://locust-master:8089/swarm
```
Should work directly after the sample application pod is marked as `ready` by k8s

## How to reproduce
Not 100% reproducible, on my machine and also on github runners (CI) it happens when:

1. create a k3d cluster `k3d cluster create signoz`
2. deploy the sample application and wait for it to be erady:
```
kubectl create ns sample-application
kubectl -n sample-application apply -Rf sample-apps/hotrod/
kubectl -n sample-application get deploy --output name | xargs -r -n1 -t kubectl -n sample-application rollout status --timeout=300s
```
3. send the load 
```
kubectl -n sample-application run strzal --image=djbingham/curl \
  --restart='OnFailure' -i --rm --command -- curl -X POST -F \
  'locust_count=6' -F 'hatch_rate=2' http://locust-master:8089/swarm
```
4. check `locust-master-*` logs in `sample-application` ns and see that traffic isn't arriving yet

## Version information 
* **Signoz version**: images built locally from master
* **Browser version**:
* **Your OS and version**: centos 8.4 and also github runners

#### *Thank you* for your bug report – we love squashing them!

FYI
@ankitnayan 
@prashant-shahi

**Comment by pranay01** [comment]
@prashant-shahi Is this fixed now?

**Comment by prashant-shahi** [comment]
This was issue seen in `e2e-k3s` environment.

It has been resolved in e2e-k3s workflow by running in the following order:
- install HotROD
- install signoz chart wait for cluster to be ready
- start HotROD swarm to generate data
