### ISSUE TITLE
Ingestion Settings Tab is missing

### ISSUE THREAD

**Issue by amurilloc** [SigNoz/signoz#6131]
### Discussed in https://github.com/SigNoz/signoz/discussions/6094

<div type='discussions-op-text'>

<sup>Originally posted by **hopewise** September 30, 2024</sup>
Hello

We have installed signoz **v0.54.0** on AWS EC2 server, but we noticed that ingestion settings tab is missing as per snap shot, as per this doc https://signoz.io/docs/ingestion/signoz-cloud/keys/

My user is with admin role. We installed signoz via the Install Script as this doc https://signoz.io/docs/install/docker/#install-signoz-using-the-install-script

<img width="1201" alt="Screenshot 2024-09-30 at 2 33 44 PM" src="https://github.com/user-attachments/assets/48843bbf-dbb1-4206-ab59-b6bbaf17f6c1">

</div>

**Comment by Calm-Rock** [comment]
Hey @amurilloc !
Thanks for pointing this out.

Ingestion key is a [SigNoz Cloud](https://signoz.io/teams/) specific feature as of now.

Raised a PR to fix the doc - [here](https://github.com/SigNoz/signoz-web/pull/850)

**Comment by papalardo** [comment]
So, why use SigNoz self-hosted if we cant send data??

**Comment by Calm-Rock** [comment]
It is possible to send data using Self-Hosted SigNoz. Please check the instructions for Self-Hosted SigNoz in the relevant docs.

Also, you can ask any doubts you have during setup in the Slack Community - https://signoz.io/docs/community/#slack

**Comment by papalardo** [comment]
> It is possible to send data using Self-Hosted SigNoz. Please check the instructions for Self-Hosted SigNoz in the relevant docs.
> 
> Also, you can ask any doubts you have during setup in the Slack Community - https://signoz.io/docs/community/#slack

Im saw here, sorry for the question. Thanks for the awesome work
