### ISSUE TITLE
Trace Explorer `List view` Table Header Displays `Key` Instead of `Title`

### ISSUE THREAD

**Issue by sharpshooter90** [SigNoz/signoz#6137]
In the Trace Explorer, the table header is currently showing the ‘Key’ field rather than the expected ‘Title’ field.

**Steps to Reproduce**

	1.	Navigate to the Trace Explorer within the application.
	2.	Observe the table header in the displayed trace data.

**Expected Behavior**

The table header should display the ‘Title’ field.

**Actual Behavior**

The table header is displaying the ‘Key’ field instead of the ‘Title’ field.

**Screenshots/Logs**

<img width="1590" alt="image" src="https://github.com/user-attachments/assets/996330aa-eba0-4e77-adc7-1628a5606812">

**Code reference**
https://github.com/SigNoz/signoz/blob/ef4b70f67b014393483c0adb079a2c732c323d9e/frontend/src/container/TracesExplorer/ListView/utils.tsx#L66

**Comment by sharpshooter90** [comment]
cc @vikrantgupta25

**Comment by vikrantgupta25** [comment]
@sharpshooter90 we do not have any title field for the traces explorer columns. the key is the one we get from the api response for `BaseAutoCompleteData` which should be fine as users select those keys from the options dropdown.

**Comment by vikrantgupta25** [comment]
@sharpshooter90 please re-open the issue if we have any different goal from the ticket.
