### ISSUE TITLE
No logs from signoz in kubernetes

### ISSUE THREAD

**Issue by Rafael-Schippers** [SigNoz/signoz#6168]
## Bug description

*Please describe.*  
Fresh install of signoz in kubernetes doesn't produce any logs

## Expected behavior
It should automatically pull logs from kubernetes

## How to reproduce

1. Install signoz with values file that only sets ingress for frontend

## Version information 
* **Signoz version**:
* v0.55
* **Browser version**:
 Firefox 130.0
* **Your OS and version**:
Rocky 9 and kubernetes rke2 (rancher)
* **Your CPU Architecture**(ARM/Intel): 
amd64
## Additional context
I tried signoz a few months ago and back then it was able to pull logs, but now I retried signoz and it doesn't automatically pull logs anymore.

**Comment by Rafael-Schippers** [comment]
Some additonal information. I tried to set up fluentbit to send logs to SigNoz with fluent-forward and it worked. But I was still hoping SigNoz would be able to do this out of the box. The problem with fluent-bit is that the JSON looks like this.

{
  "body": "",
  "id": "2nIE4nFRbiIEcBFGyrwwUB8LrRT",
  "timestamp": "2024-10-11T13:06:40.816433149Z",
  "attributes": {
    "_p": "F",
    "fluent.tag": "kube.var.log.containers.img-creator-messages-pats-5b97fcb859-k92f9_pats_dotnet-core-077887791b0b3c215ba15d6063f585a13c92cb2f3afdd2734289499bcced14e5.log",
    "kubernetes": "{\"annotations\":{\"cattle.io/timestamp\":\"2024-09-30T13:44:25Z\"},\"container_hash\":\"registry.git.ap.be/k8s/webdev/pats/services/img-creator-for-messages@sha256:0929f280b486db21a71b727083a5cff153cbdde7d9ac4f2e4670ee6774cce7ec\",\"container_image\":\"registry.git.ap.be/k8s/webdev/pats/services/img-creator-for-messages:8.0.5\",\"container_name\":\"dotnet-core\",\"docker_id\":\"077887791b0b3c215ba15d6063f585a13c92cb2f3afdd2734289499bcced14e5\",\"host\":\"srv-rke-241\",\"labels\":{\"app\":\"img-creator-messages-pats\",\"pod-template-hash\":\"5b97fcb859\"},\"namespace_name\":\"pats\",\"pod_id\":\"7cecd464-3fc5-4695-b7f9-de2322fc8cd5\",\"pod_name\":\"img-creator-messages-pats-5b97fcb859-k92f9\"}",
    "stream": "stdout",
    "time": "2024-10-11T15:06:40.816433149+02:00"
  },
  "resources": {},
  "severity_text": "",
  "severity_number": 0,
  "span_id": "",
  "trace_flags": 0,
  "trace_id": ""
}

Wich is not ideal since all the information sits in kubernetes now.

**Comment by srikanthccv** [comment]
It has been split into two now. There is a `signoz` chart which just contains the main SigNoz installation and `k8s-infra` for collecting the logs/metrics in the k8s cluster. Please see https://signoz.io/docs/tutorial/kubernetes-infra-metrics/

**Comment by srikanthccv** [comment]
if you have any issues installing `k8s-infra` chart, open an issue here https://github.com/SigNoz/charts
