### ISSUE TITLE
Questions about Function Usage

### ISSUE THREAD

**Issue by JellyTony** [SigNoz/signoz#6182]
## Is your feature request related to a problem?

Yes. The problem is with the log retrieval experience and the log mapping functionality.

1. Is there no query history for log retrieval? The user experience feels suboptimal.
2. Is there a global mapping function for logs? For example, if the logs output by the service are "app_id":"1001","app_name":"bff","app_version":"v1.0.0", while the otel service name requires service.name and service.id, how can we map these to your system? Additionally, for log levels, if logs are not printed according to your requirements, it feels like many features cannot be utilized.

## Describe the solution you'd like

1. Implement a query history feature for log retrieval to improve user experience.
2. Introduce a global mapping function that allows users to map their custom log fields to the required otel fields (e.g., service.name and service.id). Additionally, provide flexibility in log levels so that users can still utilize features even if they do not strictly adhere to the required log format.

## Describe alternatives you've considered

1. Manually keeping track of query histories, which is inefficient and inconvenient.
2. Creating custom scripts or middleware to convert log formats before sending them to your system, which adds extra complexity and maintenance overhead.

## Additional context
```json
{"app_id":"1001","app_name":"bff","app_version":"v1.0.0"}
```

**Comment by srikanthccv** [comment]
>Implement a query history feature for log retrieval to improve user experience.

https://github.com/SigNoz/signoz/issues/5144

>Introduce a global mapping function that allows users to map their custom log fields to the required otel fields (e.g., service.name and service.id). Additionally, provide flexibility in log levels so that users can still utilize features even if they do not strictly adhere to the required log format.


No, this is unlikely to happen. The whole point of OTeL sem conv is to standardise the telemetry data to avoid such issues. We rely on the fact the data follows sem combs and builds on top of it otherwise, it would be a lot of effort to support different formats.

>Creating custom scripts or middleware to convert log formats before sending them to your system, which adds extra complexity and maintenance overhead.

This has to be done at some step, and the best place it should happen is before data is written to the database. Please start adopting the OTeL conventions.

**Comment by JellyTony** [comment]
> OTeL sem conv

Could you please tell me which fields in Signoz's logs, metrics, and traces use the OTeL semconv standard? Is there any documentation available?

**Comment by srikanthccv** [comment]
https://github.com/open-telemetry/semantic-conventions

**Comment by JellyTony** [comment]
```json
{
  "Timestamp": 1586960586000, // JSON needs to make a decision about
  "Attributes": {
    "http.status_code": 500,
    "http.url": "http://example.com",
    "my.custom.application.tag": "hello",
  },
  "Resource": {
    "service.name": "donut_shop",
    "service.version": "semver:2.0.0",
    "k8s.pod.uid": "1138528c-c36e-11e9-a1a7-42010a800198",
  },
  "TraceId": "f4dbb3edd765f620", // this is a byte sequence
                                 // (hex-encoded in JSON)
  "SpanId": "43222c2d51a7abe3",
  "SeverityText": "INFO",
  "SeverityNumber": 9,
  "Body": "20200415T072306-0700 INFO I like donuts"
}
```
Is there a log example? I followed the above JSON format for collection, but it still can't be recognized.

**Comment by srikanthccv** [comment]
Where did you get the json reference? SigNoz accepts data using OTLP protocol, and format for otlp json is this https://github.com/open-telemetry/opentelemetry-proto/blob/main/examples/logs.json

**Comment by JellyTony** [comment]
> Where did you get the json reference? SigNoz accepts data using OTLP protocol, and format for otlp json is this https://github.com/open-telemetry/opentelemetry-proto/blob/main/examples/logs.json

Is it only camel case? Can't it be snake case?

**Comment by JellyTony** [comment]
> Where did you get the json reference? SigNoz accepts data using OTLP protocol, and format for otlp json is this https://github.com/open-telemetry/opentelemetry-proto/blob/main/examples/logs.json

https://github.com/open-telemetry/oteps/blob/main/text/logs/0097-log-data-model.md#example-log-records

**Comment by JellyTony** [comment]
If I use Zap to log to a file without integrating OTel logs, does this format not comply with the OTel protocol for logs?

**Comment by srikanthccv** [comment]
>Is it only camel case? Can't it be snake case?

It should be exactly as mentioned in the json example.

>If I use Zap to log to a file without integrating OTel logs, does this format not comply with the OTel protocol for logs?

No, however, you can still read them using filelog receiver https://signoz.io/docs/userguide/collect_logs_from_file/ and parse them https://signoz.io/docs/logs-pipelines/introduction/
