### ISSUE TITLE
UI Bug: Vertical text

### ISSUE THREAD

**Issue by skonky** [SigNoz/signoz#6186]
## Bug description

> A picture is worth a thousand words

https://github.com/user-attachments/assets/c178c378-673a-4207-9db1-9b65f077a886

**Comment by Dare-devil-23** [comment]
Hey, I can help to fix this issue, can be fixed by adjusting the grid or flexbox layout.

**Comment by YounixM** [comment]
Assigned it to you @Dare-devil-23 .

**Comment by dhirenmathur** [comment]
Hi @YounixM I used potpie to generate a simple low level design to help you get to the correct code to fix this: 
https://app.potpie.ai/chat/01934538-8208-7d9c-b297-5659faf5b6d7
Hope it is useful!

**Comment by skonky** [comment]
already fixed
