### ISSUE TITLE
Dashboard page does not call API on clicking on `apply` button

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#620]
The `apply` button does not make an api call
![Screenshot 2022-01-17 at 10 17 19 PM](https://user-images.githubusercontent.com/12460410/149809211-c4e740e5-d65e-4090-9927-2f5e9ecde925.png)

**Comment by SoniaisMad** [comment]
Hello :) 
I would like to contribute, do you think you could assign this one to me ?

**Comment by pranay01** [comment]
Sure @SoniaisMad assigning it to you. Feel free to ask questions if you need any help

**Comment by SoniaisMad** [comment]
@pranay01 I am looking into this issue, but i don't understand the issue , what behavior is expected ?

Because when you have a widget configured, when i change my title for example, and hit apply, it works perfectly

**Comment by SoniaisMad** [comment]
[Enregistrement de l’écran 2022-01-25 à 14.20.45.zip](https://github.com/SigNoz/signoz/files/7933865/Enregistrement.de.l.ecran.2022-01-25.a.14.20.45.zip)

**Comment by pranay01** [comment]
@ankitnayan can you share what was the issue and check the video shared by @SoniaisMad

**Comment by ankitnayan** [comment]
@SoniaisMad please find the issue as I see in this loom video https://www.loom.com/share/af4201de6b2c43d39cdca1a8236473b5

**Comment by SoniaisMad** [comment]
@ankitnayan Thanks for the video and your detailed explanation, i understant better the issue now ! 
I'll work on it :)
