### ISSUE TITLE
feat: Support for basic auth and Login 

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#625]
## Is your feature request related to a problem?

Currently SigNoz doesn't have concept  of user login. Though for organizations which have different team members using the product it may be helpful to provide each user a separate login to SigNoz and ability to invite different team members  in the same org

## Describe the solution you'd like
- [ ] Ability to have a authenticated login mechanism - users should be able to login vi email/password or other auth mechanisms
- [ ] Support for auth mechanisms like Google auth and Github login
- [ ] Ability to invite other members of the team to SigNoz org
- [ ] Basic level of RBAC like Edit and View only permissions

**Comment by praddy26** [comment]
What is the expected timeline for this feature?

**Comment by praddy26** [comment]
I would like to work on this feature. Please assign me this issue.

**Comment by pranay01** [comment]
@ankitnayan Do we have tech requirements clear on this for someone to get started?

**Comment by MuthukumarHelios** [comment]
@pranay01  are we planning to store the  user record(who has registered) in `singnoz database` ex: postgress or mongodb

**Comment by ankitnayan** [comment]
@praddy26 we have already involved someone to start working on this soon. Would be great to have you get started into some other issue. Let me come back soon with something good to get started.

**Comment by praddy26** [comment]
> @praddy26 we have already involved someone to start working on this soon. Would be great to have you get started into some other issue. Let me come back soon with something good to get started.

@ankitnayan 
Thanks for the advise.
