### ISSUE TITLE
Legenda in Frequency Chart / Explorer section

### ISSUE THREAD

**Issue by marcoberri** [SigNoz/signoz#6270]
## Describe the solution you'd like
Hi, 
is possible simplify legenda from {severity_text="INFO"} to "INFO" from  Frequency Chart in "Explorer" section?
tnx

## Additional context

![image](https://github.com/user-attachments/assets/c44ef76b-508a-4f7a-a924-a76d3e6dcee9)

**Comment by vikrantgupta25** [comment]
this is done!
