### ISSUE TITLE
Arithmetic operators are removed from Dashboard query builder formulas 

### ISSUE THREAD

**Issue by al-mcintosh** [SigNoz/signoz#6274]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

In the Dashboard query builder, if a formula contains brackets with arithmetic operators `A  / (A + B)`  the arithmetic operators are removed if you later edit the Panel Details leaving you with an invalid expression: `A  / (A  B)` 

## How to reproduce

1.  Create a Dashboard Panel 
2. Include a formula `A  / (A + B)` 
3. Save Changes.
4. Edit Panel and notice the error `API responded with 400 - invalid expression A / (A B) : Cannot transition token types from VARIABLE [A] to VARIABLE [B] status: error`
5. Notice that the `+` is missing. 

## Version information 
* **Signoz version**: v0.56.0
* **Browser version**: Chrome / 130.0.6723.59 (Official Build) (arm64)
* **Your OS and version**: MAC
* **Your CPU Architecture**(ARM/Intel):

**Comment by vikrantgupta25** [comment]
hey @al-mcintosh thanks for reporting the issue. we have identified the issue and will release the fix soon!
