### ISSUE TITLE
[Bug] fresh local installation, no metrics

### ISSUE THREAD

**Issue by StefanSa** [SigNoz/signoz#6277]
## Bug description
i have installed the latest version locally.
Get traces and logs but no metrics (hostmetrics).

Any idea why the metrics are missing here?
thx

## Expected behavior
the metrics are collected and displayed.

## How to reproduce
Installation according to documentation

## Version information 
* **Signoz version**: 0.56
* **Browser version**:
* **Your OS and version**: openLeap 15.6
* **Your CPU Architecture**(ARM/Intel): Intel

**Comment by pranay01** [comment]
@StefanSa Can you share what steps/docs you followed to get the metrics?

**Comment by pranay01** [comment]
@StefanSa closing this isse since I didn't receive any update from you. Feel free to re-open it if this issues is not solved, and do provide more details on what exact steps you followed, etc
