### ISSUE TITLE
FE[TRACES]: Query range api is triggered twice when trace explorer page is loaded.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#6308]
Query range api is triggered twice when trace explorer page is loaded.

https://github.com/user-attachments/assets/76242bf3-08ee-4004-9a5b-46d4b7eba137

**Comment by maninaik** [comment]
The TracesExplorer/ListView component gets rendered multiple times and maxTime and minTime changes throughout renders. I'm thinking we could add a debounce to the queryKey of the query-range API. (idk if it's the best solution)
