### ISSUE TITLE
Improve traces list view ux when there are more columns

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#6326]
![Screenshot 2024-10-30 at 8 26 12 PM](https://github.com/user-attachments/assets/5c7d5c7a-f90a-43fc-9623-f9fd5c803369)

**Comment by YounixM** [comment]
@srikanthccv : Could you share the screenshot / screen recording of the issues related to list view here please.

**Comment by srikanthccv** [comment]
![traces_view](https://github.com/user-attachments/assets/bf4f0588-ac31-4829-b813-f3283e9144b4)
