### ISSUE TITLE
live log is not available

### ISSUE THREAD

**Issue by luugh** [SigNoz/signoz#6466]
## Bug description

I installed signoz using the helm method from the official docs and got an error when using the live log as shown below. What should I do to get it back to normal?

![image](https://github.com/user-attachments/assets/f7fafe31-fbf9-460d-9294-f68818f873fc)
![image](https://github.com/user-attachments/assets/02c820a0-a644-4629-89bd-acb93bf5de9b)

## Expected behavior

The live log can be used

## How to reproduce

N/A

## Version information 
* **Signoz version**: 0.58.0
* **Browser version**: chrome 131.0.6778.69
* **Your OS and version**: 
* **Your CPU Architecture**(ARM/Intel):  amd64

## Additional context
N/A

**Comment by nityanandagohain** [comment]
it's fixed in 0.58.1 https://github.com/SigNoz/signoz/releases/tag/v0.58.1

**Comment by luugh** [comment]
> 它在 0.58.1 中已修复https://github.com/SigNoz/signoz/releases/tag/v0.58.1

Okay, I'll try it.

**Comment by nityanandagohain** [comment]
please hold, we have some issue in 0.58.1 . Will ping here once a new version is released.

**Comment by srikanthccv** [comment]
Fixed now, please upgrade to v0.58.2
