### ISSUE TITLE
Missing formula sign after save

### ISSUE THREAD

**Issue by marcoberri** [SigNoz/signoz#6483]
## Bug description
Missing formula sign after save

## How to reproduce

1. write a formula on F1 Query Builder in Panel, the formula is A+B and save
2. edit the same panel
3. the formula missing "+" sign.

see attachments

## Version information 
* **v0.56.0**:
* **Chrome 131.0.6778.70**:
* **Windows 10 Pro 22H2**:
* **Intel**

## Additional context
![image](https://github.com/user-attachments/assets/ede4cf31-08f1-4871-9695-39fe70022737)
![image](https://github.com/user-attachments/assets/a6091d78-eb74-409c-936e-807532505f34)
![image](https://github.com/user-attachments/assets/782168fb-051a-4c1b-bac4-24a03e4d6763)

**Comment by srikanthccv** [comment]
Fixes in https://github.com/SigNoz/signoz/pull/6276. Please upgrade to latest version.
