### ISSUE TITLE
Formula not working with panel in dashboard

### ISSUE THREAD

**Issue by svsk417** [SigNoz/signoz#6484]
## Bug description
If I run any formula to be shown in a panel within a dashboard the result yielded is "No data". 
If I run the single queries on which the formula is based on, the correct value is shown.

## Expected behavior
The sum of the two values is shown.

![A](https://github.com/user-attachments/assets/17394ad6-39fa-4c67-b4f3-cfb9e40dcbbe)
![B](https://github.com/user-attachments/assets/9a6fd2a4-3427-4009-a9da-26ca04da33d2)
![AplusB](https://github.com/user-attachments/assets/ae8e3413-8bda-4dc7-b225-d40af07042b4)

## How to reproduce

Create a panel as shown in the screenshots.

## Version information 
* **Signoz version**: 0.58.2
* **Browser version**: 
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel):

**Comment by pranay01** [comment]
@svsk417 Is this only happening for this specific query and formula? Or none of the formulae are working?

**Comment by svsk417** [comment]
Hi @pranay01, this is happening to all my formulas. 
Even if I just devide the CPU utilization by the number of CPU cores I get no result.

**Comment by aniketio-ctrl** [comment]
please assign this to me
