### ISSUE TITLE
We should change the colour of this banner to robin-500

### ISSUE THREAD

**Issue by GeekBoySupreme** [SigNoz/signoz#6487]
The banner on top uses a different shade of purple. This should be Robin-500.

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/664ddc73-ff3f-4460-87b0-003dc33b512b">

**Comment by YounixM** [comment]
https://github.com/SigNoz/signoz-web/pull/983

**Comment by YounixM** [comment]
Done ✅
