### ISSUE TITLE
There is no more context in the log

### ISSUE THREAD

**Issue by laoeree** [SigNoz/signoz#6504]
Filter logs by keywords, but clicking on Context does not display the context of the log
query-service  version is 0.59.0
frontend version is 0.59.0
![image](https://github.com/user-attachments/assets/3e328da6-146d-4727-8949-6622689ec613)

**Comment by nityanandagohain** [comment]
Was it working previously  and it stopped working now ?

**Comment by laoeree** [comment]
> 它之前能正常工作，但现在却停止工作了？

No, it's the default version of Docker pulled from the official website, and you can update all the images to the latest version later. The official website's 0.56.0 and exporter 0.111.5 have this issue
