### ISSUE TITLE
Migrate dependency graph mv from signoz_index_v2 to signoz_index_v3

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#6511]

**Comment by nityanandagohain** [comment]
Any idea where we use the DependencyGraphTables ? I didn't see them being used in query service apart from the TTL API.

**Comment by srikanthccv** [comment]
The service map is powered by dependency_graph_minutes_v2

**Comment by srikanthccv** [comment]
The service map won't work for new users.

**Comment by srikanthccv** [comment]
Yes, the `dependency_graph_minutes` is old and not used anymore. Just update the query for  `dependency_graph_minutes_v2_*mv` tables.
