### ISSUE TITLE
Pipelines - Export configuration

### ISSUE THREAD

**Issue by marcoberri** [SigNoz/signoz#6528]
## Describe the solution you'd like

is it possible to have the export functionality for pipelines configurations (json format or other)? It would be very convenient when I run tests on the local installation and then bring it back to the remote platform.
thanks

#### *Thank you* for your feature request – we love each and every one!

**Comment by srikanthccv** [comment]
Duplicate of https://github.com/SigNoz/signoz/issues/4119
