### ISSUE TITLE
[Dashboard Request] 

### ISSUE THREAD

**Issue by Rjoel768** [SigNoz/signoz#6534]
## Expected Dashboard Sections and Panels

(Can be tweaked (add or remove panels/sections) according to available metrics)

## 📋 Notes

Please review the [CONTRIBUTING.md](https://github.com/SigNoz/dashboards/blob/main/CONTRIBUTING.md) for guidelines on dashboard structure, naming conventions, and how to submit a pull request.

**Comment by srikanthccv** [comment]
Please add more detail and don't spam repo.

**Comment by makeavish** [comment]
Closing it as invalid, reopen with more details
