### ISSUE TITLE
Replace the `Get started` CTA with `New source`

### ISSUE THREAD

**Issue by GeekBoySupreme** [SigNoz/signoz#6535]
We currently have the `Get Started` button as the only CTA to connect a data source. 
`Get started` is a misnomer for users who are have already been using SigNoz for a while. We should replace that with a `New source` CTA. And use [this icon](https://lucide.dev/icons/package-plus) there instead of the rocket.

<img width="753" alt="image" src="https://github.com/user-attachments/assets/b6b19bb8-cd2c-4f36-a165-5642c04603b5">

**Comment by YounixM** [comment]
@GeekBoySupreme : In what all areas do we want to change this >?

SideNav ?

**Comment by GeekBoySupreme** [comment]
Onboarding page does not have this button, right? Could you send me a screenshot on if it does?

But I just had the sidebar in mind.
