### ISSUE TITLE
Typo in Messaging Queues

### ISSUE THREAD

**Issue by GeekBoySupreme** [SigNoz/signoz#6538]
Typo in messaging queue consumer metrics - it should be `Offset`
<img width="645" alt="image" src="https://github.com/user-attachments/assets/70d4a655-ec39-4bad-baeb-638ac8d97a10">

**Comment by pranay01** [comment]
@SagarRajput-7 can we fix this?

**Comment by SagarRajput-7** [comment]
> @SagarRajput-7 can we fix this?

Fixed here - https://github.com/SigNoz/signoz/pull/6557
