### ISSUE TITLE
Responsive dropdown for quick filters

### ISSUE THREAD

**Issue by Calm-Rock** [SigNoz/signoz#6572]
## Bug description

The dropdown should expand even if I click on the extended row.

## Expected behavior

See the video attached

## How to reproduce

1. Click on any dropdown in the Quick Filters section of the Logs Explorer
2. It doesn't expand the dropdown when 

## Version information 
* **Signoz version**: Cloud

## Additional context

Please find a quick video explanation of the same - https://www.loom.com/share/f9a95d8254d547f9911a24a9eab9f0ce?sid=59c1c126-299b-431f-9cb5-ea6ec3abb96d

**Comment by vikrantgupta25** [comment]
This is done!
