### ISSUE TITLE
Update docs with instructions on how to ingest & visualise Kubernetes infra metrics in SigNoz

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#663]
[This doc](https://signoz.io/docs/tutorial/kubernetes-infra-metrics/) details out steps for getting k8s infra metrics in SigNoz. However couple of use cases are missing.

1. What it SigNoz is running in a separate k8s cluster and a user wants to send metrics from another k8s cluster to SigNoz?
2. Above doc mentions steps to get aggregate k8s metrics. How can users also get metrics about each node in the kubernetes cluster? We should add those steps also in the docs.

**Comment by prashant-shahi** [comment]
related #717

**Comment by prashant-shahi** [comment]
Completed: https://signoz.io/docs/tutorial/kubernetes-infra-metrics
