### ISSUE TITLE
Inconsistent Refresh button behaviour on metrics page

### ISSUE THREAD

**Issue by chickoocoutinho** [SigNoz/signoz#664]
## Bug description

When you change the DateTime to "Custom", the refresh button disappears but it doesn't reappear when you set it back to "Last x mins/days" option.
[https://signoz-community.slack.com/files/U02SREP0F3K/F030W996KT8/2022-02-01_16-06-10.mkv](url)

## Expected behavior
Refresh button must be present when the timeline is not set to "Custom"

## How to reproduce

1. Go to `/application` page and in the top right corner, change the timeline to "Custom"
2. Change the timeline back to "Last x mins"
3. Refresh button does not appear

## Version information 
* **Signoz Version v0.5.4**:
* **Chrome Version 97.0.4692.99**:

**Comment by chickoocoutinho** [comment]
Can I take this issue up?

**Comment by pranay01** [comment]
sure @chickoocoutinho but please discuss with @palash-signoz also once - as data time filter component can get tricky - and Palash has worked on many edge cases of it

**Comment by chickoocoutinho** [comment]
@palash-signoz  

The `refreshButtonHidden` state is toggled on button clicks and dropdown change. I was thinking of using an `useEffect` and directly linking it to `selectedTimeInterval` which properly toggles between Custom and others.

I've tested it out and it does not interfere with functionality since the "Refresh" button is hidden only when 
`selectedTimeInterval === "custom"`

**Comment by palash-signoz** [comment]
> @palash-signoz
> 
> The `refreshButtonHidden` state is toggled on button clicks and dropdown change. I was thinking of using an `useEffect` and directly linking it to `selectedTimeInterval` which properly toggles between Custom and others.
> 
> I've tested it out and it does not interfere with functionality since the "Refresh" button is hidden only when `selectedTimeInterval === "custom"`

Possibly we can turn it back on when ```selectedTimeInterval !== "custom"```
