### ISSUE TITLE
RPS and Application have a different time axis than Error Graph when 1 day is selected 

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#665]
Expected Behavior - All charts in the metrics chart should have same time period as time axis, so that it is consistent for users

Refer to loom video for more details:

https://www.loom.com/share/d510613c52e84c87a79d436e1852c7c4

**Comment by pranay01** [comment]
@srikanthccv It seems this issue still persists, any idea why?

**Comment by srikanthccv** [comment]
@pranay01 I am not aware of this bug. I will look into it. The other PR which solved the dashboards issue solved a different problem.

**Comment by srikanthccv** [comment]
This should no longer be the issue with uplot
