### ISSUE TITLE
Dashboard action buttons [Save, Apply, Discard] is in a blind spot

### ISSUE THREAD

**Issue by polyglothacker** [SigNoz/signoz#688]
## Bug description
The new dashboard action buttons are in the top right which is really in the user's blindspot after he has added the metrics. It is better positioned in the right bottom corner (just below the "Time Preference" section).

It took me help to figure out where the Save button is - also the color contrast doesn't help - it should be more prominent, especially in the black theme.

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## How to reproduce

1. Just try adding a new dashboard
2. 
3.

## Version information 
* **Signoz version**:
* **Browser version**:
* **Your OS and version**:

**Comment by polyglothacker** [comment]
![signoz3](https://user-images.githubusercontent.com/97145793/153026505-10760d33-5919-46a8-b59a-0f32aa179166.jpg)

**Comment by pranay01** [comment]
thanks @polyglothacker for opening the issue. We will look into it

**Comment by SoniaisMad** [comment]
@pranay01 Can you assign me this one ?

**Comment by pranay01** [comment]
Sure @SoniaisMad Assigned it to you. Will share the design with you before you get started on this

**Comment by SoniaisMad** [comment]
Thanks :) 
I'll wait for the design to start then

**Comment by makeavish** [comment]
New design improves this
