### ISSUE TITLE
Blocking Save dialog which feels unresponsive in retention metrics settings

### ISSUE THREAD

**Issue by polyglothacker** [SigNoz/signoz#690]
## Bug description

When saving retention metrics it looks like the process is allocating space for saving the data serially when OK is clicked on the dialog as it blocks for a noticeable period and you feel the application is unresponsive. 

## Expected behavior

Instead the space creation for data should happen asynchronously and the dialog should return immediately, or at least show a spinning wheel feedback.

## How to reproduce

1. Settings->General
2. Add say 10 days for Metrics and 10 days for Traces 
3. Click Save

## Version information 
* **Signoz version**:  Latest

* **Browser version**: Firefox
* **Your OS and version**: Debian Linux

#### *Thank you* for your bug report – we love squashing them!
![signoz4](https://user-images.githubusercontent.com/97145793/153052954-f4b51d12-23b4-4d43-9e03-ed124fa3deb9.jpg)

**Comment by pranay01** [comment]
Thanks for raising the issue @polyglothacker It seems its a firefox specific issue where the spinning wheel near Ok button is not being shown.

I tested this in chrome - and there is a spinning wheel which appears on the Ok button which gives user some feedback on this

https://www.loom.com/share/5616d5257afb4383bca987de97dbf777

**Comment by ankitnayan** [comment]
apart from fixing spinner we should make the call async and non-blocking -> https://github.com/SigNoz/signoz/issues/710

**Comment by pranay01** [comment]
the firefox specific issue is fixed now, https://github.com/SigNoz/signoz/issues/710 tracks the async approach
