### ISSUE TITLE
Cache bug in frontend (v0.6.0)

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#697]
## Bug description

On chromium browsers when a user opens signoz app then the dashboard or trace or anyother page doesn’t load, but when you do cmd+shift+R the page loads fine.

## Version information 
* **Signoz version**: v0.6.0
* **Browser version**: Brave Version 1.35.100 Chromium: 98.0.4758.87 (Official Build) (arm64)](https://brave.com/latest/)
* **Your OS and version**: MacOS 12.2 ARM64

**Comment by pranay01** [comment]
@makeavish Does this happen only for a repeat user ( someone who has opened SigNoz in the same browser earlier) or also for a new user ( who has never opened SigNoz in the same browser)?

**Comment by makeavish** [comment]
Happens only for old user.
