### ISSUE TITLE
Parse error in PromQL causes a dead panel

### ISSUE THREAD

**Issue by polyglothacker** [SigNoz/signoz#700]
## Bug description

In PromQL query I mistakenly added two queries one after another like below
`mongodb_ss_opcounters{legacy_op_type="query"} mongodb_ss_opcounters{legacy_op_type="getmore"}`

Then I saved and the panel went dead with a parse error (no interaction buttons - cant delete as well)

*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior
Parse error should come to user when he tries to save and prevent him from saving instead of causing a dead panel - which cant be deleted !

## How to reproduce

1. Add a panel
2. In PromQL enter an invalid query or two valid queries one after another
3. Save

## Version information 
* **Signoz version**: Latest
* **Browser version**: Firefox
* **Your OS and version**: Debian (Antix) bullseye
![signoz_5](https://user-images.githubusercontent.com/97145793/153345514-0340d893-44c0-4522-aba3-44b3c3f79427.jpg)

**Comment by polyglothacker** [comment]
The screenshot shows how the panel looks like after the save - you can see all the interaction options have disappeared on RHS top.

**Comment by polyglothacker** [comment]
There is a way to resurrect the panel - by dragging and dropping "time series" or "value" widgests into it - but still the issue is that the validation should happen before the user tries to save and not after causing a dead panel.

**Comment by palash-signoz** [comment]
Hi @polyglothacker 

In the Panel, there is an option that can help to edit and delete

<img width="133" alt="Screenshot 2022-02-10 at 11 40 29 AM" src="https://user-images.githubusercontent.com/88981777/153348375-eab5f0d8-a58f-48a5-addf-0d5ed27efccc.png">

**Comment by palash-signoz** [comment]
Closing the issue for now. re-open if you find this is not working

**Comment by polyglothacker** [comment]
I guess you missed the point - the screenshot shows the `full panel` and due to the parser error it is not rendering correctly - the edit/delete/maximize options *are missing*.

**Comment by polyglothacker** [comment]
![signoz6](https://user-images.githubusercontent.com/97145793/153381946-23491873-e1f3-400c-85fc-46918fefd851.jpg)
The bigger picture (literally) should make it clear  I hope. See the 2nd from top panel on the left.

**Comment by polyglothacker** [comment]
Please mark this as important as today while evaluating signoz I ended up creating 3 "dead panels" and there is no way I can get rid of them - they are cluttering the UI. Thanks for the great work!

**Comment by pranay01** [comment]
Reopen this issue. I am able to reproduce this in v0.7.1

Please see attached loom video 

cc @palash-signoz 

https://www.loom.com/share/2917691b59484830b625c0617ab71a84

**Comment by palash-signoz** [comment]
@pranay01 can you please try https://github.com/SigNoz/signoz/pull/840
