### ISSUE TITLE
Ability to Clone an Alert

### ISSUE THREAD

**Issue by polyglothacker** [SigNoz/signoz#708]
## Is your feature request related to a problem? No

When creating a bunch of similar alerts it would be quite useful if one alert can be created and then cloned multiple times to create the rest of them.

## Describe the solution you'd like
Under `Actions` under `Alerts` for each alert - also add a `Clone` action which will copy the alert data to a new alert and then take the user immediately to Editing the cloned alert.

**Comment by palashgdev** [comment]
yeah sure @learning-dev please go ahead
