### ISSUE TITLE
Make setting retention async

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#710]
## Is your feature request related to a problem?

Currently, setting retention can take a long time if a lot of data points has to be modified. Clickhouse does this async at background.

## Describe the solution you'd like
SigNoz's backend and frontend should not wait and block the UI. Rather it should say, request has been submitted and the UI should reflect wheneven it is done.

We can also show status of applied retention if that has been successfully done by clickhouse or it is still in progress.

**Comment by pranay01** [comment]
fixed by https://github.com/SigNoz/signoz/pull/1173

**Comment by makeavish** [comment]
Fixed with https://github.com/SigNoz/signoz/pull/1173 and https://github.com/SigNoz/signoz/pull/1195
