### ISSUE TITLE
Trace graph is misaligned

### ISSUE THREAD

**Issue by jze2** [SigNoz/signoz#715]
## Bug description

![obrazek](https://user-images.githubusercontent.com/86746389/153616987-b3e12c50-2956-4570-883c-7350f4362f94.png)

## Expected behavior
I expect the right edge of the first orange bar to be aligned with the right edge of the last orange bar in the image (what is happening in the red rectangle I drew?).

## How to reproduce

1.
2.
3.

## Version information 
* **Signoz version**: 0.6.0
* **Browser version**: Firefox 96.0
* **Your OS and version**: Xubuntu 20.04

**Comment by pranay01** [comment]
hi @jze2 Thanks for opening the issue. As of now the top flamegraph is not very accurate for complex traces. The bottom panel which shows the gantt chart view should be more accurate.

We are working on an improved trace flamegraph design which you can track in this issue https://github.com/SigNoz/signoz/issues/624

**Comment by ankitnayan** [comment]
@jze2 Is it possible to return the API response on this page? Would help in replicating the flamegraph and check sanity. Also, works if you can DM me/Pranay on slack as Pranay mentioned or you can mask some data and provide it. Would be really helpful to debug.

**Comment by ankitnayan** [comment]
@jze2 I have tried explaining in this loom video. 
https://www.loom.com/share/cc77e607302e41ec9e68d2e4f06a37aa

**Comment by pranay01** [comment]
fixed by #764  - Updated trace detail page design
