### ISSUE TITLE
[Docs] PromQL Queries to build k8s infrastructure dashboards

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#717]
Currently users need to build their own PromQL queries to show data in SigNoz dashboard

One can take inspirations from:
https://grafana.com/grafana/dashboards/315
https://grafana.com/grafana/dashboards/6417

SigNoz's docs for metrics are available at https://signoz.io/docs/tutorial/kubernetes-infra-metrics/#list-of-metrics-from-kubernetes-receiver

**Comment by prashant-shahi** [comment]
I had created a set of PromQL queries for the same.
However, since there is no varying k8s metrics, there were flat graphs.
Also, it would be more convenient with import/export feature - can be tracked here #730

**Comment by pranay01** [comment]
@prashant-shahi I think this is done now, right?

**Comment by prashant-shahi** [comment]
@pranay01 yes, it is done. And dashboard addition could be found in docs here: https://signoz.io/docs/tutorial/kubernetes-infra-metrics/

Closing the issue.
