### ISSUE TITLE
Very slow dashboard for K8S metrics

### ISSUE THREAD

**Issue by polyglothacker** [SigNoz/signoz#721]
## In what situation are you experiencing subpar performance?

Plotting K8s metrics which return a lot of data across multiple containers/pods

For my stage environment the following metrics as timeseries take a lot of time to preview/load  (See attached pic)

```
k8s_container_cpu_limit
k8s_container_cpu_request
k8s_container_memory_limit
k8s_container_memory_request
k8s_container_restarts
```

The worst performer is `k8s_container_memory_request` which is always the last to load.
The entire dashboard takes slightly more than 1-1.5 minute to load on average.

The bigger problem is how slow the frontend is when these metrics are added - the moment I type the metric, the preview freezes, cursor freezes and typing becomes very slow to impossible. It takes anything from 20 - 30 sec for the preview graph to appear and UI to become responsive.

## How to reproduce

1. Configure K8S infra metrics for a system with many nodes and containers
2. Add the above metrics in panels
3. Preview and save plus load all becomes very slow.

## Your Environment

- [X ] Linux
- [ ] Mac
- [ ] Windows

Please provide details of OS version etc.
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

```
K8S info

$ kubectl get nodes | wc -l
39

$ kubectl get pods -n signoz-infra-metrics  | wc -l
40
```

4G RAM and 4 core vCPU on the signoz server. Only signoz is running here.

## Additional context

Browser - Firefox/97.0 

![signoz_large_metrics](https://user-images.githubusercontent.com/97145793/153748531-455cfbaa-88e1-4008-81c4-5e5f3a9d619c.jpg)

**Comment by pranay01** [comment]
@prashant-shahi Is this issue fixed now

**Comment by ankitnayan** [comment]
https://www.loom.com/share/595d9c6e5497465fad2f5cd73498eb19

**Comment by ankitnayan** [comment]
@srikanthccv please investigate this. Will this issue be automatically fixed when below issues are fixed?

1. https://github.com/SigNoz/signoz/issues/1865
2. https://github.com/SigNoz/signoz/issues/1872

**Comment by srikanthccv** [comment]
When this was created there were several reasons why it was slow 1. PromQL 2. Raw data 3. Inefficient ui render library and more. Many things have improved since then except the handling of too many series in a result which will be addressed https://github.com/SigNoz/signoz/issues/5761. The dashboards shared here should work well https://github.com/SigNoz/dashboards/tree/main/k8s-infra-metrics
