### ISSUE TITLE
Feat(UI): Sorting Params in Aggregates API

### ISSUE THREAD

**Issue by palash-signoz** [SigNoz/signoz#726]
## Is your feature request related to a problem?

*Please describe.*
in getFilteredSpans/aggregates API there should be params with sort=desc/asc which will sort the data accordingly 

which will solve #718

**Comment by makeavish** [comment]
Have to add one more param to the API and update the DB query accordingly.

**Comment by makeavish** [comment]
We don't need to update aggregates API, also created new issue for backend: https://github.com/SigNoz/signoz/issues/732

**Comment by makeavish** [comment]
Apparently the DESC/ASC support already exists in getFilteredSpans API: https://github.com/SigNoz/signoz/blob/05c79b71190decb76bee79e535ef3251090a0cd7/pkg/query-service/app/clickhouseReader/reader.go#L1714

Example curl: 
```
curl --location --request POST 'localhost:8080/api/v1/getFilteredSpans' \
--header 'Content-Type: application/json' \
--data-raw '{
    "start":"1640294231000000000",
    "end": "1648533522000000000",
    "httpCode": ["200", "304"],
    "exclude": ["httpCode"],
    "groupBy": "httpCode",
    "limit": 10,
    "offset": 10,
    "order": "descending"
}'
```
@palash-signoz Please update the API request on frontend.
cc: @pranshuchittora @ankitnayan

**Comment by palash-signoz** [comment]
Solves via https://github.com/SigNoz/signoz/pull/718
