### ISSUE TITLE
MySql logs are not captured in Database Calls tab

### ISSUE THREAD

**Issue by ganny26** [SigNoz/signoz#728]
## Bug description

From node js application after adding auto instrument to tracer file, captured db logs metrics not getting populated in Database Calls tab

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  
<img width="1558" alt="image" src="https://user-images.githubusercontent.com/11629190/154070918-388125e4-5f06-441f-baa2-d78132c60474.png">
<img width="1570" alt="image" src="https://user-images.githubusercontent.com/11629190/154071138-87df964d-26e9-4214-aba0-552acce6bded.png">

## Expected behavior
Database calls metrics must appear in dashboard

## How to reproduce

1.clone this repo https://github.com/ganny26/opentelemetry-nodejs-distributed-tracing
2.run npm user
3.curl --location --request GET 'http://localhost:8081/user/2'

## Version information 
* **Signoz version**:
* **Browser version**:
* **Your OS and version**:

**Comment by pranay01** [comment]
More discussion on this here - https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1644931782858929?thread_ts=1644680048.871169&cid=C01HWQ1R0BC

**Comment by srikanthccv** [comment]
This is an issue from our collector span metrics writer exporter infrequently dropping the data because of tcp I/O timeout. There is a retry mechanism in place to avoid the dropping but it could be possible that the retry is also not successful in very rare scenarios. We are looking into this. If you don't see any data at all for an application that is under constant workload, please share us the logs of collector component and get in touch with us on slack directly to help us get more contextual debug info.

**Comment by srikanthccv** [comment]
@ankitnayan it has been observed that some instrumentation libraries and people who use manual instrumentation don't set the span kind to client and such operations are not considered to generate span metrics. We can be less restrictive about span kind and include the SpanKind.Internal as well. What are your thoughts?

**Comment by pranay01** [comment]
Related : https://github.com/SigNoz/signoz.io/issues/341

**Comment by ankitnayan** [comment]
@srikanthccv we can proceed with logic
```
 span.kind != SERVER
```

seems ok?

**Comment by srikanthccv** [comment]
Sounds good to me 👍 .

**Comment by AnirudhaGohokar** [comment]
> 

I can now see mongodb call trace details after changing mongodb driver version from 3.1.0 to 4.5.0 for my NodeJS application . Maybe we should update the documentation.
