### ISSUE TITLE
Feat(Backend): Add support for DESC/ASC param for getFilteredSpans API

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#732]
## Is your feature request related to a problem?

Related to this issue: https://github.com/SigNoz/signoz/issues/716

## Describe the solution you'd like

Add support for DESC/ASC param for getFilteredSpans API in query service

**Comment by makeavish** [comment]
Loom video to understand context: https://www.loom.com/share/64314df4036d4a5db9dd4407428f5ffd

**Comment by Doxify** [comment]
I'd like to tackle this issue if its still available!

**Comment by Doxify** [comment]
> Sure, assigning this to you. Let me know if you need more context.

For sure! I'll do some research today after work and I'll reach out with my questions.

**Comment by makeavish** [comment]
@Doxify Looks like you have been busy.
Should I pick this task?

**Comment by Doxify** [comment]
> @Doxify Looks like you have been busy.
> Should I pick this task?

Yeah -- sorry about this.

**Comment by makeavish** [comment]
No issues, you can other task whenever you are free. 
Thanks 😄

**Comment by makeavish** [comment]
Apparently the DESC/ASC support already exists in getFilteredSpans API: https://github.com/SigNoz/signoz/blob/05c79b71190decb76bee79e535ef3251090a0cd7/pkg/query-service/app/clickhouseReader/reader.go#L1714

Example curl: 
```
curl --location --request POST 'localhost:8080/api/v1/getFilteredSpans' \
--header 'Content-Type: application/json' \
--data-raw '{
    "start":"1640294231000000000",
    "end": "1648533522000000000",
    "httpCode": ["200", "304"],
    "exclude": ["httpCode"],
    "groupBy": "httpCode",
    "limit": 10,
    "offset": 10,
    "order": "descending"
}'
```
