### ISSUE TITLE
query-service getOutboundIP crashes from behind firewall

### ISSUE THREAD

**Issue by viljart** [SigNoz/signoz#734]
https://github.com/SigNoz/signoz/blob/5aa46c7e96e7c1acf853fb97da00180f36b881a7/pkg/query-service/telemetry/telemetry.go#L62

is this IP resolution absolutely needed!?

**Comment by pranay01** [comment]
@makeavish Can you take a look at this. This shouldn't be crashing

**Comment by makeavish** [comment]
Acknowledged the issue.
Will create a PR soon.

**Comment by makeavish** [comment]
Here's the fix PR: https://github.com/SigNoz/signoz/pull/750

**Comment by pranay01** [comment]
fixed by #750
