### ISSUE TITLE
Page with List of active Alert channels should not have time filter 

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#735]
## Bug description

Page with List of active Alert channels should not have time filter on top right corner

*If this affects the front-end, screenshots would be of great help.*  

![Open source Observability platform SigNoz 2022-02-17 at 4 53 55 PM](https://user-images.githubusercontent.com/504541/154471823-596109c5-8f25-4716-9d24-b7fd6dda1c7d.jpg)

## Expected behavior

There is no need/use of time filter being present in a page where list of active alert channels are displayed

## How to reproduce

1. Open SigNoz dashboard
2. Go to settings page
3. Click Alert Channels tab

## Version information 
* **Signoz version**: v0.6.1
* **Browser version**: Version 98.0.4758.102 (Official Build) (arm64)
* **Your OS and version**: macOS Moneterey

**Comment by not-so-rabh** [comment]
@pranay01 I would like to work on this!

**Comment by pranay01** [comment]
Sure @not-so-rabh - assigned to you. feel free to ask any questions you may have

**Comment by vg18gupta** [comment]
@pranay01  If this is not yet picked, I would like to work on this.

**Comment by palashgdev** [comment]
Sure @vg18gupta please go ahead

**Comment by sf-pchakraborty** [comment]
@palashgdev Looks like this is already fixed. Can you please close this?

**Comment by AdityaPatadiya** [comment]
Hello @pranay01, Can you assign this issue to me?
