### ISSUE TITLE
Otel Collector uses up significant amount of swap memory

### ISSUE THREAD

**Issue by runoono** [SigNoz/signoz#736]
## In what situation are you experiencing subpar performance?

*Please describe.*

## How to reproduce

1. During prolonged runtime otel collectors will use a lot of swap and will continue until the OOME kicks in and kills the collector or until the user kills them 

## Your Environment

- [x] Linux (Ubuntu 20.04 64 bit)
- [ ] Mac
- [ ] Windows

![image](https://user-images.githubusercontent.com/16387918/154472972-a909415f-05cc-4611-bc99-829652740a9a.png)

**Comment by runoono** [comment]
turns out my machine didn't have swap limit support enabled. You should be able to see if your machine has it by doing `docker info` if you get something along the lines of: 
`INFO[0781] GET /v1.21/info                              
Containers: 0
Images: 0
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.1 LTS (containerized)
CPUs: 2
Total Memory: 3.664 GiB
Name: lenovo
ID: A3ZV:2EVK:U5QB:O7CG:PEDL:SANK:X74X:QNLC:VOTK:GFDR:S24T:C5KT
WARNING: No swap limit support`
(This is a [sample output](https://unix.stackexchange.com/questions/342735/docker-warning-no-swap-limit-support) from another machine since I fixed the issue for mine)
you need to enable swap limitting for cgroups in your kernel parameters. Just add `cgroup_enable=memory swapaccount=1` to your `GRUB_CMDLINE_LINUX=` or `GRUB_CMDLINE_LINUX_DEFAULT=` in `/etc/default/grub` and run `sudo update-grub` and reboot. my swap usage hasn't gone above 600 mb ever since
![image](https://user-images.githubusercontent.com/16387918/154473782-a32ecf38-0fe9-4ec0-8d50-bcffbf5ce466.png)

**Comment by pranay01** [comment]
hey @runoono thanks for opening the issue and also adding the solution. Will confirm it from our end also and add in the docs.
