### ISSUE TITLE
Footer takes significant space on the page and does not add much value.

### ISSUE THREAD

**Issue by pranshuchittora** [SigNoz/signoz#738]
## Description
The footer on the FE takes valuable space and does not add much value.

<img width="1440" alt="Screenshot 2022-02-18 at 16 34 07" src="https://user-images.githubusercontent.com/32242596/154671257-53a7ad95-4ef2-42cf-965b-753cbf6609be.png">

We can remove this and place the copyright SigNoz Inc on some other page or show the footer only on home/login/signup page

**Comment by udasitharani** [comment]
I would like to pick this one too

**Comment by pranay01** [comment]
hey @udasitharani Let's start with this one. Assigning to you

**Comment by udasitharani** [comment]
Awesome! Thanks

**Comment by udasitharani** [comment]
So I am a bit confused on the home and login pages.
1. Not sure what page is the home page. If it is the metrics page, I (having a knack for UX) suggest we remove the footer from home page too.
2. I couldn't find any login page.

Hence, removing the footer from all the pages except the signup page for now.
Let me know if we would want to retain the footer on any other page.

**Comment by palash-signoz** [comment]
> So I am a bit confused on the home and login pages.
> 
> 1. Not sure what page is the home page. If it is the metrics page, I (having a knack for UX) suggest we remove the footer from home page too.
> 2. I couldn't find any login page.
> 
> Hence, removing the footer from all the pages except the signup page for now. Let me know if we would want to retain the footer on any other page.

@pranshuchittora @pranay01 can you please help here in which pages do we need to remove footer as @udasitharani is seems confused here

**Comment by pranay01** [comment]
@udasitharani Yeah - this should be fine to keep it only in signup page, and removing from other pages

This PR seems fine from a functionality perspective @palash-signoz
