### ISSUE TITLE
Move the theme change toggle to better place.

### ISSUE THREAD

**Issue by pranshuchittora** [SigNoz/signoz#739]
## Description 
1. The theme change toggle's placement is incorrect as it is being placed at the most important place i.e. top left, ideally it should be place in the top right as it's not the highlight of the product.

<img width="385" alt="Screenshot 2022-02-18 at 16 39 12" src="https://user-images.githubusercontent.com/32242596/154672117-1e221f43-b394-4d53-a54c-e1fd571d70aa.png">

2. There's no indication about what the toggle does, which makes not a good UX. We can replace it with something intuitive and self descriptive. 👇🏼 

<img width="195" alt="Screenshot 2022-02-18 at 16 43 32" src="https://user-images.githubusercontent.com/32242596/154672247-96da03ef-2070-4fa6-b013-1e81f9c5ca8a.png">

**Comment by udasitharani** [comment]
I would like to work on this.

**Comment by palash-signoz** [comment]
@udasitharani sure go for it

**Comment by pranay01** [comment]
@udasitharani This would also need some UX input. 

We were thinking of use what docusaurus uses on its main page https://docusaurus.io/

![Screenshot 2022-02-25 at 12 13 35 AM](https://user-images.githubusercontent.com/504541/155587384-9a2b9f7c-db09-449d-b4c6-308ff301c215.png)

Though, I not sure on the location it should be put at - we can put at top right corner as it has date time filter and I think theme toggle filter there would be distracting. 

Other location is above slack support button - but that also seems not very optimal
![Screenshot 2022-02-25 at 12 19 46 AM](https://user-images.githubusercontent.com/504541/155588486-9e6092a4-79f6-4fa2-939f-bf95b13f53f9.png)

Any better position for this?

**Comment by pranay01** [comment]
this is fixed with https://github.com/SigNoz/signoz/releases/tag/v0.8.0
