### ISSUE TITLE
Outdated Query Service README

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#740]
The [README.md](https://github.com/SigNoz/signoz/blob/develop/pkg/query-service/README.md) file docs in query-service is outdated.
Have to be updated by following this doc: https://github.com/SigNoz/signoz/blob/develop/CONTRIBUTING.md#contribute-to-query-service

**Comment by axaysagathiya** [comment]
had a talk with the [udasitharani](https://github.com/udasitharani). he allowed me to raise a PR.
@makeavish can you please review my PR.
