### ISSUE TITLE
Upgrade to clickhouse versions v2

### ISSUE THREAD

**Issue by itzikiusa** [SigNoz/signoz#751]
Hi, 
can clickhouse client be upgraded to V2?
both collector and query service

in some tests i did, it improves ingestion rate drastically (400%)
and also select query are improved(mainly if large data is being extracted, around 200%)

also, go version upgrade?
and a lot of dependencies having old versions......

Thanks!

**Comment by makeavish** [comment]
Hey @itzikiusa, thanks for the suggestions!
We have already have clickhouse-v2 upgrade PR ready for collector (https://github.com/SigNoz/opentelemetry-collector-contrib/pull/9). 
Haven't started on migration for query-service though.
Would be great if you can create PR to upgrade clickhouse version for query service and also share stats on query improvement (if you have).

**Comment by itzikiusa** [comment]
@makeavish 
i'm working with different version then original(using clickhouse MV and different web framework, also removed druid support)

**Comment by makeavish** [comment]
[v0.8.0](https://github.com/SigNoz/signoz/releases/tag/v0.8.0) uses clickhouse v2 with native client.
