### ISSUE TITLE
Issue with query-service service not starting

### ISSUE THREAD

**Issue by yadav6554** [SigNoz/signoz#757]
## Bug description
Attached screen shot of query-service not being started :
Error:
2022-02-23T13:13:42.269Z INFO clickhouseReader/reader.go:559 SELECT id, updated_at, data FROM rules
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xa2d328]

## How to reproduce

1. Followed this https://signoz.io/docs/install/docker/?utm_source=blog&utm_medium=opentelemetry_tomcat
Post install.sh the query-service doesn't come up
## Version information 
Docker Desktop 4.5.0 (74594) 
* **Signoz version**: latest
* **Browser version**: latest
* **Your OS and version**: macOs Monteray 12.1

**Comment by yadav6554** [comment]
Retried everything and it works fine now. Apologies for the inconvenience caused.

**Comment by pranay01** [comment]
cool - no issues :)
