### ISSUE TITLE
Too many decimal points in duration time variable

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#773]
There is no need for 3 decimal points in duration filter here and in other places where duration is shown. We can follow a rule of max three digits for any `duration` including the decimal places. So, if it's `1000ms` it can be shown as `1s`.
<img width="274" alt="Screenshot 2022-02-25 at 8 38 30 PM" src="https://user-images.githubusercontent.com/83692067/155738532-de9fc5c9-7c51-486e-a978-64ff5c6c5cff.png">

Ideally it should be shown like this
<img width="371" alt="Screenshot 2022-02-25 at 9 13 49 PM" src="https://user-images.githubusercontent.com/83692067/155744443-627143ae-9b7d-408c-8078-a5be328fd1e0.png">

**Comment by makeavish** [comment]
This has improved with new explorer page
