### ISSUE TITLE
Clicking on any drop down refreshes graph

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#775]
Clicking on the dropdown of any filter headings like `Status`, `Service Name`, `Operation`, etc. refreshes the graph which does not seem ideal.

The graphs should only be refreshed if I have selected or unselected a filter.

<img width="282" alt="Screenshot 2022-02-25 at 9 24 56 PM" src="https://user-images.githubusercontent.com/83692067/155746091-d6bbc7ee-810e-4caf-87bd-72b561157c5e.png">

**Comment by palashgdev** [comment]
@ankit01-oss this is intentional right if we are updating section in left ?

**Comment by makeavish** [comment]
But if we update sections then it is instantaneously updated. Why do we need to reload when we minimize or expand sections? @palashgdev

**Comment by palashgdev** [comment]
@makeavish api only ask to send the relevant data only.... probably that's the reason

**Comment by palashgdev** [comment]
if we add the filter relevant data won't be fetched

**Comment by makeavish** [comment]
@palashgdev The API call is not changed when collapsing the serviceName or anyother filter category.
So their should not be any API call made.

**Comment by makeavish** [comment]
This has improved with new explorer page in latest version
