### ISSUE TITLE
`AM-PM` should be mentioned in time filter on time filter

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#780]
## Bug description
There is no `a.m-p.m` in timestamps of time filter. This might confuse a user. Also, as we are having that in all other places, it would be consistent.

<img width="406" alt="Screenshot 2022-02-26 at 10 37 57 AM" src="https://user-images.githubusercontent.com/83692067/155830088-bfef5d70-18d7-4782-81c3-69ac6d8258b1.png">

## How to reproduce

1. Go to metrics tab
2. Choose a timestamp on a graph and click on view traces
3. The time filter on traces tab will show timestamps with no filter.

## Version information 
* **v0.6.2**
* **Google chrome**:
* **Your CPU Architecture**(ARM/Intel): ARM

**Comment by palashgdev** [comment]
that would be mis leading to the user as everywhere we are showing in 24 hr format

**Comment by pranay01** [comment]
I don't think we should show AM/PM. We should use 24 hr format everywhere
