### ISSUE TITLE
`Refresh` button disappears after applying custom timestamps

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#781]
## Bug description

The `refresh` button disappears after using custom timestamps and clicking on `apply`

<img width="257" alt="Screenshot 2022-02-26 at 10 45 38 AM" src="https://user-images.githubusercontent.com/83692067/155830219-120f7e33-2f56-42f9-9cb6-6ed3ecb76019.png">

<img width="365" alt="Screenshot 2022-02-26 at 10 48 39 AM" src="https://user-images.githubusercontent.com/83692067/155830283-8277d3e2-d8ae-4758-8fdd-77252d8fbfa2.png">

## How to reproduce

1. Apply custom timestamp
2. Click on `apply`

## Version information 
* **Signoz version**: v.0.6.2
* **Browser version**: Chrome
* **Your OS and version**: MacOS
* **Your CPU Architecture**(ARM/Intel): ARM

**Comment by pranay01** [comment]
this is as expected, as in custom time period - specific time period in past is chosen. So need to refresh it
