### ISSUE TITLE
Duration in input boxes doesnot update while changing the filters back

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#783]
## Bug description
The value input box of duration does not show updated data when the filters are changed.

Notice the data inputs:
`Min` = 0.019 ms
`Max` = 1450.837 ms

Status filters selected
`ok` and `error`
<img width="270" alt="Screenshot 2022-02-26 at 11 40 42 AM" src="https://user-images.githubusercontent.com/83692067/155831972-0c1320b2-607a-40fb-a40f-b521640cc16f.png">

Notice the data inputs:
`Min` = 22.621 ms
`Max` = 42.833 ms

Status filters selected
Only `error`

<img width="279" alt="Screenshot 2022-02-26 at 11 40 58 AM" src="https://user-images.githubusercontent.com/83692067/155832014-7551c3a6-f176-40d4-91ab-ee16e96c66a3.png">

Notice the data inputs does not get updated after selecting `ok` back:
`Min` = 22.621 ms
`Max` = 42.833 ms

Status filters selected
`ok` and `error`

<img width="280" alt="Screenshot 2022-02-26 at 11 41 13 AM" src="https://user-images.githubusercontent.com/83692067/155832046-6fdc2f8d-29e6-41fc-a25d-70d01db39abb.png">

## Version information 
* **Signoz version**: v0.6.2
* **Browser version**: chrome
* **Your OS and version**: macos
* **Your CPU Architecture**(ARM/Intel): ARM

**Comment by makeavish** [comment]
This has improved with new explorer page in latest version
