### ISSUE TITLE
Using the dropdown for filter headings reselects the checkboxes

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#784]
## Bug description
Using the dropdown for filter headings reselects the checkboxes, while other checkboxes remain same. But number are according to the state of all selected checkboxes. Please check the screenshots below for more clarity:

### State 1
All checkboxes are selected under `Status` and `Service Name`
<img width="277" alt="Screenshot 2022-02-26 at 12 02 37 PM" src="https://user-images.githubusercontent.com/83692067/155832537-b0bd255b-2301-414c-9766-7bdd4720d5f6.png">

### State 2
Under `Status` only `error` is selected. This updates the list of services to only `redis`

<img width="271" alt="Screenshot 2022-02-26 at 12 02 55 PM" src="https://user-images.githubusercontent.com/83692067/155832543-96ddedff-98e5-43d1-b549-b334a6dcd217.png">

### State 3
Minimize the `Status` dropdown

<img width="278" alt="Screenshot 2022-02-26 at 12 03 17 PM" src="https://user-images.githubusercontent.com/83692067/155832550-c5941415-d9e2-4b19-8935-f83af1d0976e.png">

### State 4
When the dropdown is unfurled, `ok` gets selected too, while `Service` shows only `redis`

<img width="272" alt="Screenshot 2022-02-26 at 12 03 35 PM" src="https://user-images.githubusercontent.com/83692067/155832561-1e3dcbdb-08ed-4541-9698-de6444f71e40.png">

## Version information 
* **Signoz version**: v0.6.2
* **Browser version**: chrome
* **Your OS and version**: macos
* **Your CPU Architecture**(ARM/Intel): arm

**Comment by makeavish** [comment]
This has improved with new explorer page in latest version
