### ISSUE TITLE
The number of span counts on a combination of filters does not match

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#785]
As you can see from the screenshot:
Number of spans under `Operation` for `SQL Select` = 250
while the number of spans under `Status` and `Service` shows 278
<img width="1238" alt="Screenshot 2022-02-26 at 12 24 31 PM" src="https://user-images.githubusercontent.com/83692067/155833287-fc94765b-975a-4ea1-895a-0c31eab215cf.png">

## Version information 
* **Signoz version**: v0.6.2
* **Browser version**: chrome
* **Your OS and version**: macos
* **Your CPU Architecture**(ARM/Intel): arm

**Comment by makeavish** [comment]
This issue is because of exclude filter.
Spans with empty operation name are also being counted.

**Comment by makeavish** [comment]
This has improved with new explorer page in latest version
