### ISSUE TITLE
Duration in `ns` is not user-friendly to read

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#786]
We can use seconds or ms for better readability.

Taken from the `traces-filter` page after selecting `Sum(duration in ns)`
<img width="965" alt="Screenshot 2022-02-26 at 12 40 25 PM" src="https://user-images.githubusercontent.com/83692067/155833799-39d391b4-ce98-472b-acb4-3fc1398d32ea.png">

## Version information 
* **Signoz version**: v0.6.2
* **Browser version**: chrome
* **Your OS and version**: macos
* **Your CPU Architecture**(ARM/Intel): arm

**Comment by pranay01** [comment]
this is fixed with https://github.com/SigNoz/signoz/pull/1081
