### ISSUE TITLE
Unintuitive to user if they can scroll to access more legends

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#787]
While I deselected all legends for filter combination of `Count` by `Operation`, there was still one line-graph left. Took me some time to figure out that the legends can be scrolled down.

<img width="955" alt="Screenshot 2022-02-26 at 12 46 03 PM" src="https://user-images.githubusercontent.com/83692067/155833993-81ad40f6-8639-4828-b23e-31cd72973ae2.png">

## Version information 
* **Signoz version**: v0.6.2
* **Browser version**: chrome
* **Your OS and version**: chrome
* **Your CPU Architecture**(ARM/Intel): arm

**Comment by makeavish** [comment]
I faced similar issue when trying to group by http. It was not intuitive that I can scroll on legends.

![image](https://user-images.githubusercontent.com/9512100/157446097-528335d7-7952-4bfe-9ea8-bc4ffa6fdaae.png)

**Comment by prashant-shahi** [comment]
Slack thread: https://signoz-team.slack.com/archives/C02BEBF6KM2/p1671006518976559

**Comment by csudani7** [comment]
@ankitnayan 
- What should be the ideal output of this issue?

1. Do we needs to show scrollbar?
2. Add Height auto?
3. Some shadow effect towards below?

**Comment by pranay01** [comment]
@csudani7 One suggestion would be to reduce the size of the legend dot. Currently its larger than the text. I think we can even reduce the size of the text a bit ( may by 2 px). What is the defaut number of rows which we show today for  legends?


I am not too inclined to show a scroll bar, as that would make the chart panels clunky.

Can we add some indication of showing that there are more legends? One possible route is to show a clickable `More` if there are more legends than what can be shown in the alloted space. We can unfurl more legends if user clicks more

![legend-scrolling](https://user-images.githubusercontent.com/504541/211893734-d154bef4-1f25-431e-b73d-fb9a8ce743d8.png)


Are there any more ways to indicate presence of more legends, may be a shadow  with a small arrow to expand? Would love suggestions here which are not too complex to implement

**Comment by csudani7** [comment]
> @csudani7 One suggestion would be to reduce the size of the legend dot. Currently its larger than the text. I think we can even reduce the size of the text a bit ( may by 2 px). What is the defaut number of rows which we show today for legends?
> 
> I am not too inclined to show a scroll bar, as that would make the chart panels clunky.
> 
> Can we add some indication of showing that there are more legends? One possible route is to show a clickable `More` if there are more legends than what can be shown in the alloted space. We can unfurl more legends if user clicks `More` - Though I am not sure how much effort will this have in implementation
> 
> ![legend-scrolling](https://user-images.githubusercontent.com/504541/211893734-d154bef4-1f25-431e-b73d-fb9a8ce743d8.png)
> 
> Are there any more ways to indicate presence of more legends, may be a shadow with a small arrow to expand? Would love suggestions here which are not too complex to implement
> 
> May be show a small down arrow which is clickable and on clicking this scroll opens up displaying all the present labels
> 
> ![Group 321](https://user-images.githubusercontent.com/504541/211895395-ad7d7c77-fc81-4ebb-9c15-46870e32d812.png)

@pranay01 

1. Yes, we can reduce size of font & legend dot. ( Still it will not resolve our issue)
2. **More...** - This idea seems good for me. But we needs figure out re-work around.
