### ISSUE TITLE
Y-axis label updates to a different scale when no legends are selected

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#788]
The y-axis label updates to a completely different scale when the `GET` method is deselected. This happens in all cases where no legend is selected. I think the label should be maintained.

<img width="969" alt="Screenshot 2022-02-26 at 12 54 59 PM" src="https://user-images.githubusercontent.com/83692067/155834253-09688c7e-b0e6-4971-b27c-ef46707ebb72.png">

<img width="967" alt="Screenshot 2022-02-26 at 12 55 16 PM" src="https://user-images.githubusercontent.com/83692067/155834265-24955170-4aaa-4e31-a81c-bb9977a2c340.png">

## How to reproduce

1.
2.
3.

## Version information 
* **Signoz version**:
* **Browser version**:
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel):

**Comment by pranshuchittora** [comment]
We have attached the relevant time units to each graph type. So looks like it is fixed.
![Screenshot 2022-06-14 at 11 43 55](https://user-images.githubusercontent.com/32242596/173506140-1388e7f4-230e-4d5b-8a22-8ddbe10496e6.png)
