### ISSUE TITLE
Random dead panel issue

### ISSUE THREAD

**Issue by polyglothacker** [SigNoz/signoz#792]
## Bug description

Created a panel using valid PromQL (don't recall the query - but this was Mongo related). Saved the panel and it rendered well.
However after some time (as in a few reloads) the panel stopped working with a random error (see attached). Now I can't remove or edit the panel.

Running from branch main, commit id: 3302a84ab579c12bc2e2443d8e0e69a1851a4fec

## How to reproduce

This is kind of random but I think this is related to issue #700 .

## Version information 
* **Signoz version**: commit id 3302a84ab579c12bc2e2443d8e0e69a1851a4fec
* **Browser version**: Firefox
* **Your OS and version**: Debian bullseye
* **Your CPU Architecture**(ARM/Intel):  amd64

## Additional context
![signoz10](https://user-images.githubusercontent.com/97145793/155925557-d4df5daa-dac3-409e-9452-6ccff2de95b9.jpg)

**Comment by ankitnayan** [comment]
@pranay01 can this be reproduced now?

**Comment by pranay01** [comment]
@palash-signoz not able to reproduce this exact case - but I am able to reproduce the dead panel issue which may be related

https://github.com/SigNoz/signoz/issues/700#issuecomment-1065099085
