### ISSUE TITLE
Move docs to this repo

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#81]
Currently, the website and documentation of SigNoz are hosted in private repos. We should plan to shift documentation to this public repo so that other contributors building and testing different integrations, deployment methods, and changes to docs can be democratically and publically updated.

We use Docusaurus for documentation and will post the steps to shift soon.

**Comment by pranay01** [comment]
@ankitnayan I think it would be better to keep the docs and website repo - separate from the SigNoz code repo

**Comment by ankitnayan** [comment]
Yes @pranay01, separate repo makes more sense.

**Comment by lalitkale** [comment]
@ankitnayan @pranay01 we could keep as folder as well in the main repo. What do you think?

**Comment by pranay01** [comment]
Moved docs to a separate repo as it a completely different website with separate deployment instructions - https://github.com/SigNoz/signoz.io
