### ISSUE TITLE
feat: Enable S3 storage for Clickhouse

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#812]
Enabling S3 storage for ClickHouse will enable users to set up long term data retention in S3 without need to worrying about disk usage when running SigNoz

**Comment by ankitnayan** [comment]
https://github.com/SigNoz/signoz/pull/837

**Comment by pranay01** [comment]
Discussion on adding s3 storage backend from jaeger community - https://github.com/jaegertracing/jaeger/issues/638#issuecomment-820213986

**Comment by jkowall** [comment]
Also on OpenSearch this is ongoing work as well. I can link issues if you want too @pranay01
