### ISSUE TITLE
Header in `Top Endpoint` section overflows in browser with reduced width

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#832]
## Bug description

Header in `Top Endpoint` section overflows in browser with reduced width

## Expected behavior

Header shouldn't overflow

## How to reproduce

1. Go to SigNoz dashboard metrics page with reduced browser window width
2. Open any application
3. Top Endpoint panel header appears overflowing

## Version information 
* **Signoz version**: v0.7.1
* **Browser version**: Version 98.0.4758.109 (Official Build) (arm64)
* **Your OS and version**: macOS 12.1
* **Your CPU Architecture**(ARM/Intel): ARM

## Additional context
![Screenshot 2022-03-08 at 12 02 17 AM](https://user-images.githubusercontent.com/504541/157095952-469aa84b-699f-4688-b68a-310eefbbaf80.png)

**Comment by pranshuchittora** [comment]
Did a quick fix, made the table scrollable horizontally with that made we are not squashing the table contents hence making it more readable.

https://user-images.githubusercontent.com/32242596/159633297-04b33d67-8ea1-4d69-b36d-f4ec88dd1a4b.mov
