### ISSUE TITLE
Add list of available instrumentations to the Add Instrumentation page

### ISSUE THREAD

**Issue by pranshuchittora** [SigNoz/signoz#853]
## Description
Currently the add instrumentation page provides a link to the signoz docs for adding instrumentations. This link is external and kinda breaks the user's flow, in order to improve the UX it would be great if we provide more details on the available instrumentations on the dashboard itself. 

Something like this 
![Screenshot 2022-03-14 at 15 23 20](https://user-images.githubusercontent.com/32242596/158149400-6471b933-2d2f-4984-ae37-f8b737b7458a.png)

> This is just a wireframe, we can put the language's logo or event segregate it into languages and frameworks.

**Comment by zaid2130** [comment]
Can I work on it? Instead of giving the external docs link, we can give the instrumentation steps in the application as well.

**Comment by pranay01** [comment]
This is implemented with v0.11.1

![Screenshot 2022-09-14 at 1 26 37 PM](https://user-images.githubusercontent.com/504541/190095565-a4a03322-372c-4686-b9fc-b8ad8ee8ff82.png)
