### ISSUE TITLE
Add "IS NOT NULL" operator in tag filtering in trace page

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#86]
Currently, to filter spans by tags there are 2 operators:
- EQUALS
- CONTAINS

An operator with the capability to check for `IS NOT NULL` values will be useful in getting all those spans which have a value of the tag. The value of `IS NOT NULL` operator that is passed in the API call would be `isnotnull`

**Comment by nishit-prasad** [comment]
Hello! I am new and would like to contribute here if this is not taken?

Currently, I am following the docs to understand and setup my environment.

**Comment by pranay01** [comment]
@nishit-prasad Sure. Assigning this to you.

You can join our [slack community](https://join.slack.com/t/signoz-community/shared_invite/zt-lrjknbbp-J_mI13rlw8pGF4EWBnorJA) and ask questions if you need any help in getting set up

**Comment by nishit-prasad** [comment]
Thank you! Appreciate it!

**Comment by pranay01** [comment]
This would potentially be useful even in new trace filter design

**Comment by pranay01** [comment]
@nishit-prasad are you still interested in working on this or I should unassign?

**Comment by makeavish** [comment]
This is similar to `EXISTS` and  `NOT EXISTS`
