### ISSUE TITLE
Too many datapoints in the graph of trace-filter page when duration is selected as 1 week

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#863]
It makes it difficult to read data points from the graph. We can make relevant aggregates to show in the graph. From the user's perspective, it should be easy to make takeaways about a week's performance from the graph. And generally the point would be to figure out any outliers.

<img width="938" alt="Screenshot 2022-03-16 at 7 01 25 PM" src="https://user-images.githubusercontent.com/83692067/158600987-8c693824-722e-483c-a4f8-aa461942a4ed.png">

## Version information 
* **Signoz version**:v0.71 with latest commits
* **Browser version**:
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel):

**Comment by makeavish** [comment]
This is fixed in latest version:
<img width="932" alt="Screenshot 2022-11-16 at 21 43 49" src="https://user-images.githubusercontent.com/9512100/202234005-ca6c8ef7-7cc4-4fa9-b418-7239af883235.png">
