### ISSUE TITLE
The dropdown filter level not synced with Y-axis labels

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#864]
The dropdown filter for the graph named `Function` has label set to `Sum(duration in ns)` while we show Y-axis duration in `min`. I think we should remove units from the labels in the dropdown.

<img width="935" alt="Screenshot 2022-03-16 at 7 04 12 PM" src="https://user-images.githubusercontent.com/83692067/158601544-4c3407b5-7f7b-4f97-8a80-1e5aba0047aa.png">

## Version information 
* **Signoz version**: v0.7.1 with latest commits
* **Browser version**:
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel):

**Comment by pranshuchittora** [comment]
This is the expected behaviour, because if nano second data point is too big therefore we are converting it to relevant units like ms, s, min, hr ....


cc @ankitnayan can you pls take a look at this.
