### ISSUE TITLE
Add "Span Kind" filter in top panel of span filtering

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#87]
Suggesting to add "**Span Kind**" filter in top panel of span filtering aside of `Latency Filter` in the below screenshot.
![Screenshot 2021-05-06 at 6 09 45 PM](https://user-images.githubusercontent.com/12460410/117299512-42901b80-ae96-11eb-857d-f005d424339e.png)

The permissible values of `Span Kind` would be:

1. SERVER which shall internally transform to `kind=2` in the API call 
2. CLIENT which shall internally transform to `kind=3` in the API call

**Comment by reachtokish** [comment]
Can I take this if no one is working on it?

**Comment by reachtokish** [comment]
I have started working on this and have a doubt. Will the `kind` be part of the initial `/spans` api call?

**Comment by pranay01** [comment]
@ankitnayan Should be able to answer this

**Comment by ankitnayan** [comment]
> I have started working on this and have a doubt. Will the kind be part of the initial /spans api call?

@reachtokish This needs to be done for 2 APIs:

1. `/spans` api
2. `/spans/aggregates` API
