### ISSUE TITLE
Add Status field from OpenTelemetry for Error Processing

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#88]
Currently Error Processing field is done by:
- Presence of tag `error:true` 
- `http.status_code` tag with value `>500`

Need to add another logic:
Span contains a field `Status` which works for all sorts of client & server requests.

Suggesting, testing of conditions to check whether the present 2 conditions are needed or can be done alone by `Status` field in Span.

**Comment by makeavish** [comment]
This is solved in latest version.
