### ISSUE TITLE
[Traces] Filter based on custom tags as part of openTelemetry property otel.resource.attributes

### ISSUE THREAD

**Issue by ikumaran29** [SigNoz/signoz#880]
## Bug description

This need not be a bug as per Signoz - but as per OpenTelemetry options - this needs to fixed.
My usecase is more like, I will have UAT and Prod Teams monitoring and tracing their clusters. All of them will use same SigNoz server. Also, I wanted UAT and Prod Team to add a tag - and identify their resources. Ensure ProdTeam can access only prod resources and not UAT resources. 

For that, in Jaeger, I add -D**otel.resource.attributes**=service.name=my-service,**my.tag=PROD**

Based on this my.tag - I differentiate them - and restrict access - in Jaeger filters. But in Signoz filter, I need a way to filter based on my custom attribute/tag.

## Expected behavior

When I provide my custom tag in resource attributes at instrumentation level - I should be able to use the same in traces filter.

## How to reproduce

1. During instrument - add -D**otel.resource.attributes**=service.name=my-service,**my.tag=PROD**
2. Now, after this agent pushes traces to collector - now, navigate to "traces" page
3. try to filter based on my.tag - currently not having possibilites.

## Version information 
* **Signoz version**: To be implemented 
* **Browser version**: n/a
* **Your OS and version**: n/a
* **Your CPU Architecture**(ARM/Intel): n/a

## Additional context
N/a

**Comment by pranay01** [comment]
Thanks for opening this issue @ikumaran29 We will be taking this up soon
