### ISSUE TITLE
Pass resource attributes to signoz UI

### ISSUE THREAD

**Issue by hardik-epifi** [SigNoz/signoz#881]
## Is your feature request related to a problem?
Use case :
We have 4 non prod environments and one common cluster of otel collector and signoz backend to receive data from all these 4 enviornments. We should be able to view traces from one env at a time.
We may want to pass service names from application code which is more business specific.

*Please describe.*
Hi I am using below method to get the trace provider :
```
func getTraceProvider(svcName string, server string) (*sdkTrace.TracerProvider, error) {
	env, _ := cfg.GetEnvironment()
	provider := sdkTrace.NewTracerProvider(
		sdkTrace.WithResource(sdkResource.NewWithAttributes(
			semconv.SchemaURL,
			semconv.DeploymentEnvironmentKey.String(env),
			semconv.ServiceNameKey.String(svcName),
			semconv.ServiceNamespaceKey.String(server),
		)),
	)
	otel.SetTracerProvider(provider)
	otel.SetTextMapPropagator(propagation.TraceContext{})
	return provider, nil
}

```
However I do not see DeploymentEnvironmentKey, SchemaURL, etc on signoz dashboard anywhere. I verified with std out exporter and these values are being passed.

## Describe the solution you'd like
Pass resource attributes to signoz UI and addtionally provide filtering support on some keys if possible

## Describe alternatives you've considered
Use AWS XRAY meanwhile

**Comment by makeavish** [comment]
[v0.8.0](https://github.com/SigNoz/signoz/releases/tag/v0.8.0) is released with this feature.
