### ISSUE TITLE
convert setTTL API to async

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#902]
setTTL API is a long duration operation that can take over a minute depending on the size of clickhouse DB, so it should be converted to non blocking async API

**Comment by LEO1612D** [comment]
Can you give me some more details on this, i can help.

**Comment by makeavish** [comment]
@LEO1612D setTTL api has to converted to async API. There are multiple ways to do that. I am describing one such way below.
So frontend would make a POST setTTL request and then use GET setTTL API to check if POST setTTL request was successful or not. We can use SQLlite to store the information on POST setTTL request status.

**Comment by ankitnayan** [comment]
> @LEO1612D setTTL api has to converted to async API. There are multiple ways to do that. I am describing one such way below. So frontend would make a POST setTTL request and then use GET setTTL API to check if POST setTTL request was successful or not. We can use SQLlite to store the information on POST setTTL request status.

We can start with checking if clickhouse provides any status on progress when a TTL is set. Else, we can send a POST request from frontend and return `change of ttl is requested and will be set soon` and store it in the sqlite db, something what @makeavish said and we can change the `getTTL` api to return an extra field `status` depending on whether the ttl extracted from clickhouse table schema matches with the entry at db. If it matches then the `status` field in getTTL api can be set as pending and accordingly the frontend can show the message at the settings page.

**Comment by makeavish** [comment]
Fixed with https://github.com/SigNoz/signoz/pull/1173 and https://github.com/SigNoz/signoz/pull/1195
