### ISSUE TITLE
Service Map misbehaves when there are no services

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#910]
## Bug description

Service Map gets stuck on loader when there are no services.

Screenshot:
<img width="1232" alt="screenshot_2022-03-24_at_08 42 08" src="https://user-images.githubusercontent.com/9512100/159974071-c8a1b1ef-8e51-45d3-88b7-69fe20999997.png">

## Expected behavior

Show there are no services when the backend returns an empty array for ServiceMapDependencies API.

## Version information 
* **Signoz version**: 0.7.3

**Comment by palash-signoz** [comment]
close https://github.com/SigNoz/signoz/pull/934
