### ISSUE TITLE
Bug (FE): UI Layout is behaving weirdly on changing the theme.

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#917]
1. UI Layout is behaving weirdly on changing the theme.
2. The footer of the popup is grey even in light mode.

https://user-images.githubusercontent.com/32242596/160103777-5a31940d-9957-46c9-8bb1-1225ca7633bd.mov

IMO this is not related to this, we can address this via another PR

_Originally posted by @pranshuchittora in https://github.com/SigNoz/signoz/issues/916#issuecomment-1078882255_

**Comment by makeavish** [comment]
This is not reproducible in latest version.
Closing it.
