### ISSUE TITLE
Support removal of TTL once set

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/signoz#937]
## Bug description

At the start of a new SigNoz cluster, get TTL API returns `-1` that indicates TTL is not set.
However, once a value is set for TTL. It cannot be unset.
Setting it to `0` makes the SigNoz data _almost_ always unavailable.

## Expected behaviour

Users should be able to unset TTL. It can be either done upon `-1`/`0` duration using the same Set TTL API handler or, we can have a new API handler with the `DELETE` method to achieve the same.

## How to reproduce

- At the start of a new SigNoz, we can see that no TTL is set.
```console
$ curl "localhost:3301/api/v1/settings/ttl"
{"metrics_ttl_duration_hrs":-1,"traces_ttl_duration_hrs":-1}
```

- Now, let's set TTL to any duration
```
$ curl -XPOST "localhost:3301/api/v1/settings/ttl?type=traces;duration=2h"
{"message":"move ttl has been successfully set up"}
```
Now, we are unable to unset any TTL.

## Version information 
* **Signoz version**: `v0.7.4`

## Additional context
Nope.

**Comment by srikanthccv** [comment]
+1 for a new handler with `DELETE`.

**Comment by pranshuchittora** [comment]
I recommend going ahead with `-1` for unsetting the TTL
