### ISSUE TITLE
 fix: cold storage changes request should be reject if the time period is same as before

### ISSUE THREAD

**Issue by pranshuchittora** [SigNoz/signoz#938]
An extension of this https://github.com/SigNoz/signoz/pull/837
Say user sends the request from the FE with the same TTL for any of the field (Traces,Metrics - Total and S3) then the BE should not try running the respective query, it must reject the changes for that field and only run the changes for the changed field.

The BE should not through an error on the API call, it should avoid running the query for the unchanged fields.

**Comment by srikanthccv** [comment]
@pranshuchittora Why make api request when there is no change in the input value?

**Comment by makeavish** [comment]
I think we should close this issue as it should only be a validation on FE.
@srikanthccv @pranshuchittora

**Comment by prashant-shahi** [comment]
@makeavish This should be handled in the backend as well.

As seen in the testbed, where TTL was set but query-service restarted. Which caused a scenario which looked like it was taking forever to setting TTL, while in reality the ClickHouse TTL was already set to the requested duration.

/cc @ankitnayan

**Comment by srikanthccv** [comment]
@prashant-shahi isn't that a different issue?

**Comment by srikanthccv** [comment]
I think the update request payload should only contain the fields that changed. Even if everything is sent I do not think the query-service should reject it. It will just honor the new data and tries to update TTL to new values.

**Comment by srikanthccv** [comment]
This is not needed
