### ISSUE TITLE
Backend should validate TTL values

### ISSUE THREAD

**Issue by pranshuchittora** [SigNoz/signoz#939]
1. Should be in relevant time unit (hr)
2. Should no allow decimal values
3. What happens when someone set the TTL to 0 (Data will never be retained)

**Comment by srikanthccv** [comment]
>Should be in relevant time unit (hr)

Valid time units are "ns", "us" , "ms", "s", "m", "h". So one could send something like "10h", "5m" etc.. Any other duration with unknown units is rejected with error.

> Should no allow decimal values

May be we should for first decimal place? If user wanted to set something like 50 hours and 30 min they could send "50h30m" as ttl.

> What happens when someone set the TTL to 0 (Data will never be retained)

This shouldn't be allowed and may be we should also come up some lower bound for ttl.
