### ISSUE TITLE
Unable to create a new channel webho

### ISSUE THREAD

**Issue by ikumaran29** [SigNoz/signoz#942]
## Bug description
When trying to add a webhook channel - I am getting below error:
error: "Error in getting 2xx response in API call to alertmanager(POST http://signoz-alertmanager:9093/api/v1/routes)\n%!(EXTRA string=404 Not Found)"

Note: In existing helm (0.7.1 - chart version 0.0.10), values.yaml - I updated the versions alone to 0.7.4. Do we have latest helm - incase, I am missing.
![image](https://user-images.githubusercontent.com/85488479/161299000-d7872e18-151d-4ed8-b7ab-08b77352be9e.png)

## Expected behavior
Should be able to create webhooks.

## How to reproduce

1. Login to Signoz
2. Navigate to settings.
3. In Channels tab, create a new channel. 

## Version information 
* **Signoz version**: 0.7.4
* **Browser version**: Chrome/FF - latest
* **Your OS and version**: Win11
* **Your CPU Architecture**(ARM/Intel): AMD

## Additional context
When logged in to my minikube - seems the url itself is invalid. I can curl the alertmanager url - but not with relative path /api/v1/routes/

In screenshot - I curled within my minikube - and seems baseurl for alertmanager was fine - but not with api/v1/routes
![image](https://user-images.githubusercontent.com/85488479/161298905-a93583f7-880a-415f-b55f-1ee7bce3fde2.png)

**Comment by prashant-shahi** [comment]
Hey @ikumaran29!

Thanks for raising this issue.

There had been few changes introduced in the recent patch release around alerts and `alertmanager`.

There is newer version of `alertmanger`: `signoz/alertmanager:0.6.0`.
In that we have changes in the CLI flags as well. You can refer the changes in [this commit](https://github.com/signoz/signoz/commit/1002ab553eed39b580d22f88d1c06b76757ea987).

We will be creating a new chart release to fix this soon.
Meanwhile, you can roll back to either `v0.7.3` or earlier versions.

**Comment by prashant-shahi** [comment]
@ikumaran29 SigNoz chart `0.0.11` is released which supports signoz `0.7.4` and alertmanager `0.6.0`.
To upgrade, you can refer here: https://signoz.io/docs/operate/kubernetes/#upgrade

Feel free to re-open the issue, if the issue persists after upgrading.
