### ISSUE TITLE
Highlight error spans

### ISSUE THREAD

**Issue by ZQiannnn** [SigNoz/signoz#943]
Background Color RED if the span has tag error:true or http.status_code:5xx
It's still not working on 0.7.4

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/19886406/161381178-5a918d5e-cb1b-4471-870a-61f711946a55.png">

<img width="609" alt="image" src="https://user-images.githubusercontent.com/19886406/161381185-e039f3f8-5dc2-4872-89c1-c4a05e97d844.png">

**Comment by palash-signoz** [comment]
@pranshuchittora
