### ISSUE TITLE
Filters For Dashboards

### ISSUE THREAD

**Issue by bhaswanth88** [SigNoz/signoz#951]
## Is your feature request related to a problem?

Currently all created dashboards can be seen in list view, but when there are many dashboards, especially for our case where we create a new dashboard for every host, it is hard to look for specific ones.

## Describe the solution you'd like

As tags are already part of dashboard, an option to filter by tags   (with eq or not eq) conditions would be really great.

for example: I want to see all dashboards with labels "prod" and "db" so that i will get dashboards of all nodes running databases. 

or  all db nodes other than prod.

It is also good to introduce saving of filter criteria which can be used later for easier searching. 

reference: Gitlab issue filter

<img width="1152" alt="Screenshot 2022-04-04 at 6 57 08 PM" src="https://user-images.githubusercontent.com/60409/161554649-ec191629-742f-4a17-8fb7-754aebf180e0.png">

#### *Thank you* for your feature request – we love each and every one!

**Comment by ankitnayan** [comment]
@pranshuchittora we can have `title`, `description` and `tag` based filtering in dashboards

**Comment by pranshuchittora** [comment]
Shipping via https://github.com/SigNoz/signoz/pull/1005 🎊
