### ISSUE TITLE
Multiple calls to getTagFilters API

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#974]
## In what situation are you experiencing subpar performance?

When a user tries to select tagKey then getTagFilters and getTagValues API is called but getTagFilters API is redundant and negatively affecting the performance.

![image](https://user-images.githubusercontent.com/9512100/162299576-4e8c2e64-d5b9-4697-ac4f-71d3cffe98a0.png)

**Comment by palash-signoz** [comment]
Blocked by #995
