### ISSUE TITLE
Add grpc status code to traces view

### ISSUE THREAD

**Issue by hardik-epifi** [SigNoz/signoz#975]
Currently signoz supports only http status code.
Services running on grpc want grpc status code so we can filter and view traces appropriately.

![image](https://user-images.githubusercontent.com/61773955/162386470-fe36c168-8dbc-413f-8e1c-bd148e3d7ccf.png)

Jaegar supports grpc status code by default.
![image](https://user-images.githubusercontent.com/61773955/162386539-fbf68f1a-aa64-4bed-b967-8d46af30bcbd.png)

Slack thread : https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1649400943185369

**Comment by ankitnayan** [comment]
@hardik-epifi  would highlighting the span as erroneous suffice? I don't think mixing http status codes and grpc status codes will be a good idea. Or should we?
We can also add another column for grpc status codes but I think it will be overkill to show 2 columns for status codes.

**Comment by hardik-epifi** [comment]
> 

Can we not populate grpc status code and http status code in same column based on rpc.system = grpc
Also highlighting as erroneous would definitely add value to someone just seeing how the system is performing but it comes with the nuance that some status codes like NotFound, InvalidArgument are not really errors. We can allow users to filter on status codes they want or they want to exclude

**Comment by ankitnayan** [comment]
right @hardik-epifi , I was also of the opinion that NotFound, InvalidArgument are not really errors. But I have seen companies using that as errors too and want to include them in error percentage.

Adding status code in the column should be handled. BTW right now, you should be able to filter out the status codes too, right? It should be available in the tags filtering at the top bar of trace filter page?

**Comment by makeavish** [comment]
[v0.8.0](https://github.com/SigNoz/signoz/releases/tag/v0.8.0) fixes this
