### ISSUE TITLE
bug: sometimes filtering traces based on service name behaves weirdly 

### ISSUE THREAD

**Issue by pranshuchittora** [SigNoz/signoz#978]
## Bug description
Sometimes Filtering doesn't work as expected. Not happens every-time but it is noticeable. 

https://user-images.githubusercontent.com/32242596/162443013-a5514368-ddd0-4855-9d11-9e847eecec40.mov

**Comment by makeavish** [comment]
@pranshuchittora Can you please check API response from network tab on developer console?
If the API response is correct then tag this issue as frontend or else tag this as backend issue.

**Comment by makeavish** [comment]
Not reproducible in latest versions.
Closing it.
